actions/runner-images

images/win/scripts/ImageHelpers/ChocoHelpers.ps1

There are a lot of logs regarding the packages download process, we can get rid of it using the choco `--no-progress` flag to improve readability.
https://github.com/actions/virtual-environments-internal/issues/2109

[Windows] Add --no-progress flag to choco install

---

images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Initialize-VM.ps1
images/win/scripts/Installers/Install-Vsix.ps1
images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1
images/win/scripts/Tests/Vsix.Tests.ps1
images/win/toolsets/toolset-2019.json

There is a 429 error during vsix packages downloading due to the limitation for unauthorized marketplace users. We have implemented retry logic for it but, unfortunately, it doesn't help all the time. The marketplace support team suggested using direct CDN links, which can be retrieved from an extension webpage.
This PR adds logic to parse the marketplace extension page and get the name, id, CDN URI, and filename of the extension. The software report was also improved to output all the extensions from the toolset.
https://github.com/actions/virtual-environments/issues/3074

[Windows] Install vsix extensions using CDN endpoint

---

images/linux/scripts/installers/java-tools.sh
images/win/scripts/Installers/Install-JavaTools.ps1

Maven 3.8.1 was released recently it would be great if we could update it to be the new default as part of the Java setup.
Fixes #3246

Updated maven from 3.6.3 to 3.8.1

---

images/win/scripts/Installers/Install-Haskell.ps1

The haskell installation broke the flow.
It was due to versioning wasn't sorted correct thus different machines had different version outcome.
One VM showed version 9 as the newest version, another VM only got version 8 and another VM only showed version 7 even though version 9 and version 8 was retrieved from Chocolatey.
When it tested on version against version 9, it tested against a variable which wasn't defined.

Haskell - Fixed version checking

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1

VS2017 has a separate SSDT installation, which includes 3 extensions that should be mentioned in the docs.
https://github.com/actions/virtual-environments/issues/3074

[Windows] Return VS2017 SSDT extensions to the readme

---

images/linux/scripts/base/limits.sh

Increases the Linux stack space from kernel default of `8192KB` to `16384KB`.

[Ubuntu] Increase Linux stack space to 16384KB

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/installers/haskell.sh

Improvement
Remove PPA repo from the apt/sources.list
https://github.com/actions/virtual-environments/issues/2951#issuecomment-819658892

Remove PPA repo of ghc

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/installers/php.sh

We need to rework php installation to remove custom PPA after successful installation.

Rework php installation

---

images/macos/provision/assets/select-xamarin-sdk-v2.sh

It is a new script that allows choosing a version for any Xamarin frameworks. 
Now you should run the script with params, e.g.: select-xamarin-sdk-v2 --mono=6.2 --android=10.0 --ios=9.2 --mac=16.2. 
You also can combine a few params that u need, not all of them, e.g.: select-xamarin-sdk-v2 --android=10.0 --mac=16.2.

select-xamarin-sdk-v2

---

README.md

We are in the process of Ubuntu 16.04 deprecation and retirement. In this PR I am removing Ubuntu 16.04 from our README.md file as we stepped into the deprecation stage.

Removed Ubuntu 16.04 from README.md

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/installers/azure-cli.sh

Improvement
Remove PPA repo from the apt/sources.list
https://github.com/actions/virtual-environments/issues/2951#issuecomment-819658892

Remove apt sources used to install azure-cli only

---

images/macos/provision/configuration/add-certificate.swift
images/macos/provision/configuration/configure-machine.sh
images/macos/templates/macOS-11.0.json

Starting from Big Sur 11.3 certificate installation requires user interaction, however it can be bypassed by using SecItemAdd method.
https://stackoverflow.com/questions/65699160/electron-import-x509-cert-to-local-keychain-macos-the-authorization-was-deni
Xcode command-line tools need to be installed to use `swiftc` hence the clt installation was moved before the configure-machine script.
https://github.com/actions/virtual-environments-internal/issues/2115

[macOS] Install Apple certificate for Big Sur via swift binary

---

images/linux/scripts/installers/ruby.sh

It turned out that updated gems can cause issues during other gem installations like Fastlane or puppet. It's better to avoid updating gems that come along with ruby. Customers can update specific gems in runtime if needed. 
https://github.com/actions/virtual-environments/issues/3307
https://github.com/actions/virtual-environments/issues/3310

[Ubuntu] Avoid updating gems

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

CMake 3.18.1 is the default version for Android Studio 4.2.0(Android Gradle Plugin version 4.2.0)
https://github.com/actions/virtual-environments/issues/3321

[Ubuntu] Add Cmake 3.18.1 for Android

---

images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

CMake 3.18.1 is the default version for Android Studio 4.2.0(Android Gradle Plugin version 4.2.0)
https://github.com/actions/virtual-environments/issues/3321

[macOS] Add Cmake 3.18.1 for Android

---

images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

CMake 3.18.1 is the default version for Android Studio 4.2.0(Android Gradle Plugin version 4.2.0)
https://github.com/actions/virtual-environments/issues/3321

[Windows] Add Cmake 3.18.1 for Android

---

images/linux/scripts/base/limits.sh

In the https://github.com/actions/virtual-environments/pull/3260 PR, we have configured limits in the `/etc/security/limits.conf` file.The file `limits.conf` is intentionally ignored by systemd in that case we should update `DefaultLimitSTACK` limits in the `/etc/systemd/system.conf`.
man 5 systemd-system.conf
`These settings control various default resource limits for units. See setrlimit(2) for details. The resource limit is possible to specify in two formats, value to set soft and hard limits to the same value, or soft:hard to set both limits individually (e.g. DefaultLimitAS=4G:16G).`
Before:
```
ulimit -s [8192]
ulimit -Hs [unlimited]
```
After:
```
ulimit -s [16384]
ulimit -Hs [unlimited]
```
https://github.com/actions/virtual-environments/issues/3257

[Ubuntu] Set DefaultLimitSTACK=16384 limit

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/installers/php.sh

This PR https://github.com/actions/virtual-environments/pull/3272 introduced a lot of issues for customers since it's not obvious that some of the packages depend on `ppa:ondrej/php`:
https://github.com/actions/virtual-environments/issues/3317
https://github.com/actions/virtual-environments/issues/3335
https://github.com/actions/virtual-environments/issues/3339
We need to revert the changes until we have implemented a better strategy to remove this ppa.

[Ubuntu] Revert "Rework php installation"

---

images/linux/scripts/installers/python.sh

Ubuntu 20 build fails with:
`ln: failed to create symbolic link '/usr/bin/pip': File exists`
There is no need to create pip3 -> pip symlink anymore since pip executable is now included in the python3-pip package.
https://github.com/actions/virtual-environments-internal/issues/2157

[Ubuntu] Remove pip symlink creation

---

images/macos/provision/core/gcc.sh
images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/Common.Tests.ps1
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

This PR adds GCC 11 and reworks the installation script to use the toolset file. As an addition, gfortran symlink will now be deleted if only it exists.
https://github.com/actions/virtual-environments/issues/3359
https://github.com/actions/virtual-environments-internal/issues/2153

[macOS] Add GCC 11

---

images/win/post-generation/Dotnet.ps1

It turned out that any tool using an old embedded NuGet version creates an empty nuget.config file in the user's home directory. For example that happens during any Powershell module installation.
To prevent the issue .NET team suggested invoking `dotnet nuget list source` command to create the default nuget.config containing the nuget.org source:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<packageSources>
<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
</packageSources>
</configuration>
```
https://github.com/actions/virtual-environments/issues/3038

[Windows] Create default nuget.config in the user's home directory

---

images/linux/toolsets/toolset-2004.json

Clang 9 will be removed from Ubuntu 20.04 images in favor of Clang 12, also the default one will be set to Clang 11
https://github.com/actions/virtual-environments/issues/3235

[Ubuntu20] Remove clang 9 and set clang 11 as the default one

---

images/win/scripts/Tests/Haskell.Tests.ps1

On a rare occasion, `choco search` doesn't return GHC version 9 at all thus the latest GHC version on the image will be downgraded. I've created an issue in the choco repository — https://github.com/chocolatey/choco/issues/2271 but we need to check the default version explicitly until it's fixed.
https://github.com/actions/virtual-environments/issues/3223

[Windows] Add a test to make sure GHC version 9.* is the default one

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/base/apt.sh
images/macos/provision/assets/select-xamarin-sdk-v2.sh

It is an improvement that allows installing an apt-fast library and doesn't use apt-get package. It helps to avoid problems with installing and failing downloading packages.
Just for Linux.
https://github.com/actions/virtual-environments-internal/issues/2071

Rework apt-fast installation to get rid of apt repo

---

images/win/scripts/Installers/Install-Msys2.ps1

Clang package missed libxml2 dependency, which leads to the error:
```
testadm2@VS19Msys2 MINGW64 ~
C:/msys64/mingw64/bin/clang.exe: error while loading shared libraries: libLLVM.dll: cannot open shared object file: No such file or directory
```
There is an issue in the msys2 repo: https://github.com/msys2/MINGW-packages/issues/8658
This PR adds explicit installation of libxml2. These changes can be safely removed When the initial issue is fixed.
https://github.com/actions/virtual-environments-internal/issues/2172

Add msys libxml2 package installation

---

images/linux/scripts/installers/php.sh

Improvement
This PR adds `imagick`, `pcov` and `sodium` PHP extensions on Ubuntu.
imagick on all supported PHP versions, sodium on PHP 7.0 and 7.1 and pcov on PHP 7.1 and newer.
**Note:** `PCOV` is disabled, as `Xdebug` is enabled by default. These two extensions should not be enabled at the same time.
Ref: https://github.com/krakjoe/pcov#interoperability

[Ubuntu] Add PHP extensions: imagick, pcov and sodium

---

images/win/scripts/Installers/Install-Haskell.ps1

Currently, the sort doesn't work properly since it sorts strings, not the version and as a result version 8.8 > 8.10.
This PR fixes it by sorting the version before grouping them.
https://github.com/actions/virtual-environments/issues/3223

[Windows] Fix pre-cached GHC list

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/helpers/SoftwareReport.Helpers.psm1
images/linux/scripts/installers/mono.sh

Improvement
Remove download.mono-project.com repo from the apt/sources.list
https://github.com/actions/virtual-environments/issues/2951#issuecomment-819658892

Rework Mono installation to avoid using apt repos on Ubuntu images

---

images/macos/provision/core/rubygem.sh

Looks like these Fastlane changes — https://github.com/fastlane/fastlane/pull/18186, which are included in version 2.184, change authorization method and broke [AppStoreRelease Azure DevOps task
](https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks/AppStoreRelease)
We need to avoid 2.184 installation until the issue is fixed in the task repo:
https://github.com/microsoft/app-store-vsts-extension/issues/244
https://github.com/actions/virtual-environments-internal/issues/2202

[macOS] Temporary hardcoding fastlane 2.183.2

---

images/macos/helpers/Tests.Helpers.psm1

In Pester version 5 `Add-AssertionOperator` was renamed to `Add-ShouldOperator`, and even though `Add-AssertionOperator` is not yet deprecated (it's an alias for `Add-ShouldOperator` now), it's better to follow the new syntax to avoid mixing up the stuff from version 4 and 5.
https://github.com/actions/virtual-environments-internal/issues/2175

[macOS] Change Add-AssertionOperator to Add-ShouldOperator

---

images/linux/scripts/helpers/Tests.Helpers.psm1

In Pester version 5 `Add-AssertionOperator` was renamed to `Add-ShouldOperator`, and even though `Add-AssertionOperator` is not yet deprecated (it's an alias for `Add-ShouldOperator` now), it's better to follow the new syntax to avoid mixing up the stuff from version 4 and 5.
https://github.com/actions/virtual-environments-internal/issues/2175

[Ubuntu] Change Add-AssertionOperator to Add-ShouldOperator

---

images/win/scripts/ImageHelpers/TestsHelpers.ps1

In Pester version 5 `Add-AssertionOperator` was renamed to `Add-ShouldOperator`, and even though `Add-AssertionOperator` is not yet deprecated (it's an alias for `Add-ShouldOperator` now), it's better to follow the new syntax to avoid mixing up the stuff from version 4 and 5.
https://github.com/actions/virtual-environments-internal/issues/2175

[Windows] Change Add-AssertionOperator to Add-ShouldOperator

---

images/macos/provision/core/rubygem.sh

It turned out that Fastlane 2.184.0 comes with the xcode-install utility hence we need to uninstall the new version before installing the 2.183.2 one.
https://github.com/actions/virtual-environments-internal/issues/2202

[macOS] Temporary hardcoding fastlane 2.183.2 rev2

---

images/win/scripts/Installers/Install-Haskell.ps1

Judging by this @HUMBERP comment in the original choco issue https://github.com/chocolatey/choco/issues/2271 — OData query returns correct results when choco search doesn't.
This PR switches the installation to use OData for versions retrieving. 
As an addition, the calculation of 3 latest major-minor versions is changed to work both in Powershell 5 and 7 as the current approach works in Powershell 5 only due to the difference in `Group-Object` sort between the versions.
https://github.com/actions/virtual-environments/issues/3434

[Windows] Switch to use OData query instead of choco search for ghc installation

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

This reverts commit 3ebf601284cae6a4406b7ea1ad08cd593a4d619b.
Bug fix
It is a not good idea to add experimental toolchain to the image, as the addition/modification of standard C/C++ headers and libraries can have wide-ranging (and often undesired) consequences across the whole system.
#3376

Revert "[ubuntu] Add GCC 11 (#3291)"

---

images/macos/helpers/Tests.Helpers.psm1
images/macos/provision/core/rubygem.sh
images/macos/software-report/SoftwareReport.Xcode.psm1
images/macos/tests/RubyGem.Tests.ps1
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

This PR change RubyGems installation to use the toolset and as an addition:
- Fastlane installation was reverted to the latest version since there is no ETA for the task to be fixed and users can setup another Fastlane version in runtime
- Conditions for 10.13 were removed as it's deprecated
- Nomad-cli version output was fixed to show the real version instead of the RubyGems version
- Nomad-ipa renamed to Nomad shenzhen CLI as it's the real name
- Xctool was returned to Big Sur
https://github.com/actions/virtual-environments-internal/issues/2202

[macOS] Refactor rubygems installation to use the toolset

---

images/macos/provision/core/mongodb.sh

Mongodb homebrew formula was updated recently https://github.com/mongodb/homebrew-brew/pull/110 and currently points to version 5.0rc. We need to announce such a major version change before providing it to customers.
https://github.com/actions/virtual-environments-internal/issues/2249

[macOS] Stick to mongodb 4.4

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/installers/erlang.sh

Recently the wrong binary was uploaded to the S3 rebar3 bucket — 3.13.1 instead of 3.16.1, which caused issues with erlang compatibility. The root cause is that the 3.13.3 release is marked as the latest in GH rebar3 repo:
Today the issue was fixed on the rebar3 side — the S3 bucket contains 3.16.1 now, but it's better to use the GH releases page to get the latest version anyway to avoid such issues in the future.
https://github.com/actions/virtual-environments-internal/issues/2246

[Ubuntu] Change rebar installation to use GitHub releases

---

images/win/scripts/Installers/Install-Msys2.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/windows2016.json
images/win/windows2019.json

This is the first PR with msys2 installation refactoring, the second one will contain test changes.
Currently, we don't test the tools installed by msys thus we don't know that something is not working until canary tests are performed against the image — the latest example https://github.com/msys2/MINGW-packages/issues/8658. 
The toolset file contains executables that come along with each package and these executables will be tested with Pester later.
https://github.com/actions/virtual-environments-internal/issues/2175

[Windows] Refactor Msys2 installation to use toolset part 1

---

README.md
docs/macos-11-onboarding.md
images/win/scripts/Installers/Install-Haskell.ps1

Adding a guide for macOS 11 onboarding when it became available for new customers.
[Rendered version](https://github.com/AlenaSviridenko/virtual-environments/blob/add-macos-11-onboarding-guide/docs/macos-11-onboarding.md)

Add macOS 11 onboarding guide

---

images/linux/scripts/installers/oras-cli.sh

ORAS repository has been moved to a new org called `oras-project`. This PR update the script to fix the next error:
```
==> azure-arm: Provisioning with shell script: C:\agent\_work\6\s\images\linux/scripts/installers/oras-cli.sh
==> azure-arm: jq: error (at <stdin>:5): Cannot iterate over null (null)
```

Update ORAS URL

---

images/macos/software-report/SoftwareReport.Java.psm1

There is no postfix for the default java version at the moment:
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
This PR fixes the root cause — we need to compare the value of env:JAVA_HOME, not the whole object.
https://github.com/actions/virtual-environments-internal/issues/2264

[macOS] Fix default java postfix in the software readme

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

In scope of this pull request we add a note to the docs about that `CONDA` is not added to the `PATH`.

[Windows] Add note about Conda

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/installers/php.sh

Use phpdismod to disable th pcov PHP extension
https://github.com/actions/virtual-environments/issues/3470

Clean way to disable the pcov PHP Extension

---

images/win/scripts/Installers/Install-NodeLts.ps1

Yarn installation fails with connection reset issues due to HTTP protocol. Updating it to HTTPS will make it more secure.

fix(windows): update npm registry to https

---

images/linux/scripts/installers/clang.sh

The libomp package provides the OpenMP runtime for Clang. Only one
version of libomp may be installed at a time:
```
$ dpkg -s libomp5-12 | grep Conflicts
Conflicts: libomp-x.y
```
The clang.sh installer script installs clang versions in the order that
they are listed in the configuration file. When clang is installed, APT
also installs the matching version of libomp, which removes the
previously installed version of libomp. This means that the image ends
up with libomp for the last version (currently 12), which is not
necessarily the same as the default version (currently 11).
As a result, even though libomp is installed, `clang -fopenmp` doesn't
work out of the box because the installed version of libomp does not
match the default clang binary.
Fix this by installing the default version …

[Ubuntu] Install default version of Clang last

---

README.md

It appeared to be not clear what "current enterprises" means. So I added an explanation for that.

Add explanation for current enterprises

---

images/macos/software-report/SoftwareReport.Toolcache.psm1
images/macos/templates/macOS-11.json
images/macos/tests/Toolcache.Tests.ps1
images/macos/toolsets/toolset-11.json

PyPy 7.3.5 (Python 2.7 and 3.7) works on Big Sur without any issues, we can safely add it to the image
https://github.com/actions/virtual-environments-internal/issues/2282

[macOS] Add PyPy to Big Sur image

---

images/win/scripts/Installers/Install-Swig.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/win/scripts/Tests/Tools.Tests.ps1
images/win/windows2016.json
images/win/windows2019.json

PR with swig 4.0.2 installation. Powershell script tests have been added, also packages are installed through the chocolatey package manager.
https://github.com/actions/virtual-environments/issues/3342

[Windows] Adding Swig

---

images/win/scripts/Tests/Haskell.Tests.ps1

Recent Haskell versions are installed into `$env:ChocolateyToolsLocation` instead of `$env:ChocolateyInstall\lib.` Recent version 8.10.5 is also installed in the new directory, but our test checks that directory only for version 9.
This PR:
- changes the test to avoid sticking a version to the exact path
- removes `Default GHC version is 9` test since we don't need it anymore after switching to use OData query for versions retrieval
https://github.com/actions/virtual-environments-internal/issues/2284

[Windows] Fix Haskell path in the pester tests

---

images/macos/helpers/SoftwareReport.Helpers.psm1
images/macos/provision/core/audiodevice.sh
images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/templates/macOS-11.json
images/macos/tests/System.Tests.ps1

There is no audio device available on macOS Big Sur images, however, we have one on Catalina.
Unfortunately, there is no easy way to install Soundflower on Big Sur as it requires user interaction but we can use blackhole to get the same result.
This PR:
- Adds blackhole installation on Big Sur along with the other audio tools already available on Catalina
- Adds a software report function to retrieve brew package version by its path since neither `sox` nor `switchaudio-osx` doesn't have version output flags
- Adds `sox` and `switchaudio-osx` to the docs
https://github.com/actions/virtual-environments/issues/3526

[macOS] Add audio device and utilities for Big Sur

---

docs/create-image-and-azure-resources.md

Improvement
In order to make it clear, need to add information that scripts should be executed with sudo privileges.
https://github.com/actions/virtual-environments/issues/3478
- [+] Documentation is updated (if applicable)

post-generation scripts should be executed with sudo permissions.

---

images/macos/toolsets/toolset-11.json

We would like to provide images with the latest stable Xcode as the default one thus need to switch the version from 12.4 to 12.5.
https://github.com/actions/virtual-environments/issues/3522

[macOS] Switch the default Xcode version from 12.4 to 12.5 for macOS Big Sur

---

images/win/scripts/Installers/Install-WindowsUpdates.ps1

[KB5003638](https://support.microsoft.com/en-us/topic/june-8-2021-kb5003638-os-build-14393-4467-d9dfce91-b425-483a-8280-f54d7005b231) causes the virtual machine to hang on shutdown step.
We need to skip this update for now to fix the image generation.
https://github.com/actions/virtual-environments-internal/issues/2287

[Windows] Don't install KB5003638 update for windows server 2016 as it breaks the VM

---

images/linux/scripts/installers/dotnetcore-sdk.sh

Improvement
The .NET versions maintenance strategy will be changed on Ubuntu images. Currently, we install all available and supported versions of .NET SDK (2.1.x, 3.1.x, 5.0.x). This approach will be changed in favor of installing the latest patch version for every feature version

installing the latest patch version for every feature version

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/installers/clang.sh

Improvement
Users need ability to install llvm related software in their workflows.
Currently the llvm.sh script adds the repos directly to /etc/apt/sources.list and provision scripts clean it up.
In order to use the the llvm component user should have info about the apt repository to install them from.
In order to make clear the same APT repo should be used for all LLVM components i combined clang and clang-format
entries into one labeled "LLVM components"
sample Readme output https://github.visualstudio.com/virtual-environments/_build/results?buildId=110833&view=logs&j=50448a2f-9550-51a0-b6c4-5ec64224dd81&t=e0a57dbd-49e7-534b-a8b5-3033d3291897
```
- LLVM components: Clang 10.0.0, 11.0.0, 12.0.1, Clang-format 10.0.0, 11.0.0, 12.0.1 (apt source: deb http://apt.llvm.org/focal/ …
```

Keep llvm apt repo

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

5.9.0 is the latest minor update before the major update 6.0.
This version includes some crucial fixes regarding the bicep.
https://github.com/actions/virtual-environments/issues/3558

[Ubuntu] Change azure ps module from 5.7.0 to 5.9.0

---

images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

5.9.0 is the latest minor update before the major update 6.0.
This version includes some crucial fixes regarding the bicep.
https://github.com/actions/virtual-environments/issues/3558

[macOS] Upgrade azure powershell from 5.7.0 to 5.9.0

---

images/win/scripts/ImageHelpers/TestsHelpers.ps1
images/win/scripts/Installers/Install-Msys2.ps1
images/win/scripts/Tests/MSYS2.Tests.ps1
images/win/windows2016.json
images/win/windows2019.json

There are no tests for the tools installed by msys2 thus we don't know that something is not working until canary tests are performed against the image.
This PR:
- Adds a new set of tests that check all the main binaries provided with installed msys2 and mingw packages.
- Main msys2 packages are tested — bash, tar, make
- Mingw packages have their on Describe for both architectures
- Get rid of elevated user SYSTEM as msys2 is perfectly installed without it and bash from msys has an issue when run under system user
- Adds `ShouldReturnZeroExitCodeWithParam` function to avoid hardcoding the exact param for each tool since some tools have `version` flag and some have `-version` or `--version`. The parameter `version` can be changed to `help` or any other if needed —  `"$ExecName" | Should …

[Windows] Improve Pester tests coverage for MSYS2

---

images/win/scripts/Installers/Install-WindowsUpdates.ps1

Reverts actions/virtual-environments#3557 as the issue seems to be fixed

Revert "[Windows] Don't install KB5003638 update for windows server 2016 as it breaks the VM"

---

images/macos/toolsets/toolset-11.json

[Xcode 12.5.1 has been released](https://developer.apple.com/news/releases/?id=06212021), we need to replace 12.5 in favor of the new version.
n\a

[macOS] Add xcode 12.5.1 to Big Sur

---

docs/software-and-images-guidelines.md

Adding clarification to the Xcode support policy

Clarify Xcode support policy

---

images/macos/toolsets/toolset-11.json

It turned out we can't remove 12.5 in favor of 12.5.1 at the moment. This PR adds Xcode 12.5 back.
n\a

[macOS] Return xcode 12.5 to Big Sur

---

images/macos/toolsets/toolset-11.json

Big Sur is mostly requested for building with the latest Xcode 12.5, which provides new Swift 5.4 features and other fixes. So we'd like to keep Xcode 11.7 for old emulators and 2 latest stable Xcode versions
https://github.com/actions/virtual-environments/issues/3555

[macOS] Remove Xcode 12.2&12.3 from Big Sur

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/tests/Tools.Tests.ps1

Exclude for Ubuntu16 was forgotten in the PR https://github.com/actions/virtual-environments/pull/3639 thus the image generation for Ubuntu 16 is broken.
n\a

[Ubuntu] Remove bicep from software docs and tests for ubuntu 16

---

images/win/scripts/Installers/Install-Msys2.ps1
images/win/scripts/Tests/MSYS2.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

Improve MSYS2 installation on Windows 2016/2019

Improve MSYS2 installation

---

images/macos/provision/core/android-toolsets.sh
images/macos/provision/core/xamarin-android-ndk.sh
images/macos/software-report/SoftwareReport.Android.psm1
images/macos/tests/Android.Tests.ps1
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

SDK Tools package is deprecated and no longer receiving updates. We need to switch to command-line tools instead
https://developer.android.com/studio/releases/sdk-tools
A few notes:
- The hardcoded values for licenses were removed as we accept them during the installation anyway
- Redundant step, which is supposed to prevent some warnings, was removed as it does nothing in the current configuration
- Old `SDK-tools` will also be available on the image as they are installed as a part of `build-tools` packages.
- A test added to make sure both "old" and "new" sdkmanagers are available
https://github.com/actions/virtual-environments/issues/3638
https://github.com/actions/virtual-environments-internal/issues/2340

[macOS] Switch android tools installation to use cmdline-tools' sdkmanager

---

images/linux/scripts/SoftwareReport/SoftwareReport.Android.psm1
images/linux/scripts/helpers/Common.Helpers.psm1
images/linux/scripts/installers/android.sh
images/linux/scripts/tests/Android.Tests.ps1
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

SDK Tools package is deprecated and no longer receiving updates. We need to switch to command-line tools instead
https://developer.android.com/studio/releases/sdk-tools
A few notes:
- Old `SDK-tools` will also be available on the image as they are installed as a part of `build-tools` packages.
- `Patcher;v4` is installed as a part of `extras;google;m2repository` so we don't need additional installation.
- A test added to make sure both "old" and "new" sdkmanagers are available
https://github.com/actions/virtual-environments/issues/3638

[Ubuntu] Switch android tools installation to use sdkmanager from command-line tools

---

images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

6.1.0 is the latest available version of Azure PowerShell module.

[macOS] Upgrade Azure PowerShell from 5.9.0 to 6.1.0

---

images/win/scripts/SoftwareReport/SoftwareReport.Android.psm1

It turned out that we have a system image that comes along with the Android SDK package for visual studio 2017. This component also matches to "Google APIs" condition thus the readme provides extra data about available google apis:
This PR fixes the condition to retrieve only google-api addons.
https://github.com/actions/virtual-environments-internal/issues/2432

[Windows] Fix android-apis output in the software docs

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1

There is an error during the software report generator related to the zip version of azmodules
```
==> vhd: Sort-Object: C:\image\SoftwareReport\SoftwareReport.Common.psm1:233
==> vhd: Line |
==> vhd:  233 |  …      $group = $_.group | Sort-Object {[Version]$_.Name.Split('_')[1]}
==> vhd:      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:      | Cannot convert value "1.0.0.zip" to type "System.Version". Error: "Input string was not in a correct
==> vhd:      | format."
```
This PR removes the zip extension so that the sorting can be done without errors.
https://github.com/actions/virtual-environments-internal/issues/2436

[Windows] Fix image generation error related to zipped az modules

---

images/macos/provision/core/android-toolsets.sh
images/macos/software-report/SoftwareReport.Android.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/Android.Tests.ps1

Intel HAXM installation doesn't work on macOS Big Sur — neither `/dev/HAX` is created nor `com.intel.kext.intelhaxm` is loaded.
According to the official documentation, the Android Emulator uses the built-in Hypervisor.Framework by default, and falls back to using Intel HAXM only if Hypervisor.Framework fails to initialize, thus we can skip the installation of HAXM at all at least for Big Sur.
This PR also:
- Changes the HAXM test to check not the installation script but the loaded kext
- Adds Intel HAXM version to the software docs
https://github.com/actions/virtual-environments-internal/issues/2390

[macOS] Skip Intel HAXM installation on Big Sur

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/installers/pipx-packages.sh
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Update `ansible-base` 2.10(only exists for version 2.10 and in Ansible 3) to `ansible-core` 2.11[(roadmap](https://docs.ansible.com/ansible-core/devel/roadmap/ROADMAP_2_11.html), [changelog](https://github.com/ansible/ansible/blob/stable-2.11/changelogs/CHANGELOG-v2.11.rst#release-summary)).
https://github.com/actions/virtual-environments/issues/3708

[Ubuntu] Update ansible-base to ansible-core

---

images/linux/scripts/installers/nodejs.sh

Runner user doesn't have required permissions to install npm global modules on Ubuntu images without sudo, this PR fix it.

[Ubuntu] Fix npm global modules installation

---

images.CI/linux-and-win/azure-pipelines/ubuntu1604.yml

Ubuntu16 is in the deprecation process, we don't need to build it daily.
https://github.com/actions/virtual-environments/issues/3287

[Ubuntu] Disable schedule builds for Ubuntu16

---

images/linux/scripts/installers/aws.sh
images/linux/ubuntu1804.json

Image generation for Ubuntu 18 is broken because Aws-cli V1 dropped python 2.7 support starting from version 1.20
https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#1200
```
==> azure-arm: Unsupported Python version detected: Python 2.7
==> azure-arm: To continue using this installer you must use Python 3.6 or later.
==> azure-arm: For more information see the following blog post: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/
==> azure-arm:
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
```
This PR switches V1 installation to use python3.
https://github.com/actions/virtual-environments-internal/issues/2456

[Ubuntu] Use python3 to install aws-cli V1

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Android `platform-tools` are installed along with any version of `build-tools` and this, sometimes, causes issues when the simultaneous installation of `build-tools` and `platform-tools` runs — as a result, two `platform-tools` installations exist on the image.  
This PR removes additional `platform-tools` installation as they are installed with the `build-tools` anyway.
https://github.com/actions/virtual-environments-internal/issues/2441

[Ubuntu] Remove platform-tools from toolset

---

images/macos/provision/configuration/configure-machine.sh

App Nap is an energy feature  that causes inactive applications to go into a paused state, helping to reduce power usage. Applications should not go to sleep.

[macOS] Disable App Nap System Wide

---

images/linux/scripts/installers/Install-Toolset.ps1

it was broken in #3701
It can be seen here: https://github.visualstudio.com/virtual-environments/_build/results?buildId=113761&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043&l=19972
```
azure-arm: Successfully installed pip-21.1.3
azure-arm: Create complete file
==> azure-arm: /bin/chown: cannot access '/opt/hostedtoolcache/@{name=Python; url=https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json; platform=linux; platform_version=18.04; arch=x64; versions=System.Object[]}': No such file or directory
azure-arm: Installing node 10.* x64...
azure-arm: Download node-10.24.1-linux-x64.tar.gz
```

[Ubuntu] Correct variable to print only tool name

---

images/linux/scripts/installers/yq.sh

It turned out that installation to /usr/local/bin can break some workflows as well as installation from PPAs such as https://launchpad.net/~rmescandon/+archive/ubuntu/yq/+packages because yq is usually installed in `/usr/bin`, but we have it in the `/usr/local/bin`that is later in the `$PATH` thus overrides yq from the `/usr/bin.`
https://github.com/actions/virtual-environments/pull/3646#pullrequestreview-711489340
https://github.com/actions/virtual-environments-internal/issues/2472

[Ubuntu] Install yq to /usr/bin

---

images/macos/provision/core/xcode.ps1

There is an exception when we try to reverse 1 element array:
`MethodException: Cannot find an overload for "Reverse" and the argument count: "1"`
This PR fixes it by reversing arrays with more than 1 element.
n\a

[macOS] Fix xcode installation script if there is only one Xcode version to install

---

images/win/scripts/Installers/Install-Rust.ps1

cargo-audit package 0.15.0 is broken so we have to temporarily stick to 0.14.1
https://docs.rs/crate/cargo-audit/0.15.0
https://github.com/actions/virtual-environments-internal/issues/2508
https://github.com/actions/virtual-environments/issues/3817

[windows] Install cargo-audit 0.14.1 as 0.15.0 is broken

---

images/win/scripts/Installers/Install-Rust.ps1

The previous PR https://github.com/actions/virtual-environments/pull/3822 was not helped, need to install cargo-audit separately.
https://github.com/actions/virtual-environments-internal/issues/2508
https://github.com/actions/virtual-environments/issues/3817

[windows] Install cargo-audit 0.14.1 as 0.15.0 is broken (fix)

---

images/macos/provision/core/rust.sh

cargo-audit package 0.15.0 is broken so we have to temporarily stick to 0.14.1
https://docs.rs/crate/cargo-audit/0.15.0
https://github.com/actions/virtual-environments-internal/issues/2508
https://github.com/actions/virtual-environments/issues/3817

[macOS] Install cargo-audit 0.14.1 as 0.15.0 is broken

---

images/linux/scripts/installers/rust.sh

cargo-audit package 0.15.0 is broken so we have to temporarily stick to 0.14.1
https://docs.rs/crate/cargo-audit/0.15.0
https://github.com/actions/virtual-environments-internal/issues/2508
https://github.com/actions/virtual-environments/issues/3817

[Ubuntu] Install cargo-audit 0.14.1 as 0.15.0 is broken

---

images/win/scripts/Installers/Install-Msys2.ps1
images/win/scripts/Installers/Install-Rust.ps1

Installation msys2 failed with:
```
vhd: :: Import PGP key 5F944B027F7FE2091985AA2EFA11531AA0AA7F57? [Y/n]
vhd: :: Synchronizing package databases...
==> vhd: error: mingw32: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: mingw64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: ucrt64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: clang64: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
==> vhd: error: msys: signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is unknown trust
```
Use …

[Windows] Use default msys2 installer

---

images/linux/scripts/installers/graalvm.sh

GraalVM got downgraded https://github.com/actions/virtual-environments/pull/3829/files#diff-6be9f9ce03ba57ca01e4ae937d5c2bb04893520fdf391ea87eb46acbc43ecdc5R123 because we get the latest release by URL https://api.github.com/repos/graalvm/graalvm-ce-builds/releases/latest and the latest release happened for 21.0.0.2.
In scope of this PR we are changing the logic of installing the latest version.

[Ubuntu] Fix GraalVM installation

---

images/linux/scripts/installers/oc.sh

The `openshift-client-linux.tar.gz` archive contains kubectl binary which replace the pervious one installed in the `images\linux\scripts\installers\kubernetes-tools.sh` script.
```
:~$ tar -ztf /tmp/oc.tar.gz
README.md
oc
kubectl
:~$ md5sum /usr/local/bin/oc
8a636bbf530bd2cf8bd2cfbe58d6cd38  /usr/local/bin/oc
:~$ md5sum /usr/local/bin/kubectl
8a636bbf530bd2cf8bd2cfbe58d6cd38  /usr/local/bin/kubectl
```

[Ubuntu] Expand oc only

---

images/win/scripts/Installers/Install-Msys2.ps1
images/win/scripts/Installers/Install-WDK.ps1
images/win/scripts/Installers/Install-Wix.ps1
images/win/scripts/Installers/Update-DotnetTLS.ps1
images/win/scripts/Installers/Update-ImageData.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1

This PR brings minor improvements to Windows image generation:
1) Make sure that `MSYS2` installation works correctly if no mingw, msys packages are specified in toolset
2) `Install-WDK.ps1` and `Install-Wix.ps1`  should fail on different platforms because they are not compatible with them
3) Don't run TLS tests in scope of `images/win/scripts/Installers/Update-DotnetTLS.ps1` because changes are not applied immediately
4) Exclude `Cached Docker images` section from docs if no containers are cached

[Windows] Implement minor improvements, rev 2

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/installers/clang.sh

Previously clang 12 installation used a custom PPA as the packages source because default Ubuntu repos did not contain appropriate packages. They are available now and installation script rework to use default repos instead of PPA.

[Ubuntu] Reworked clang installation to use default Ubuntu repo

---

images/win/post-generation/VSConfiguration.ps1
images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/VisualStudioHelpers.ps1
images/win/scripts/Installers/Install-VS.ps1
images/win/scripts/Installers/Install-WinAppDriver.ps1
images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1
images/win/scripts/Tests/VisualStudio.Tests.ps1
images/win/scripts/Tests/Vsix.Tests.ps1
images/win/scripts/Tests/WinAppDriver.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/windows2016.json
images/win/windows2019.json

1) Set channel via toolset (`release` or `pre`)
2) Invoke `Get-VSSetupInstance` with flags `-Prerelease -All` everywhere to find VS properly
3) Switch `vswhere` using to `Get-VSSetupInstance` because of better handling of preview

[Windows] Improve Visual Studio installation scripts to support Preview versions

---

images/linux/scripts/helpers/install.sh

According to the [bash manual](http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Functions) the `function` keyword is not really mandatory, other functions defined in the file have no this keyword as well.
- [n/a ] Related issue / work item is attached
- [n/a ] Tests are written (if applicable)
- [n/a ] Documentation is updated (if applicable)
- [n/a ] Changes are tested and related VM images are successfully generated

[Linux] install.sh: make the IsPackageInstalled function definition consistent

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

Prevents markdown to interpret it as strike-through style when 2 or more tilde operators appear
example:
https://github.com/actions/virtual-environments/blob/b56230f3423cc8fa24bae454cacf7e841b22fb6b/images/linux/Ubuntu2004-README.md#L305
| Name                   | Version                           |
| ---------------------- | --------------------------------- |
| fonts-noto-color-emoji | 0~20200916-1~ubuntu20.04.1        |
n/a

[ubuntu] fix: escape tilde operator in package version

---

images/linux/scripts/installers/homebrew.sh

The new behavior has been introduced in  https://github.com/Homebrew/brew/pull/11789 PR . After eval statement has been completed, the `brew shellenv` checks HOMEBREW_SHELLENV_PREFIX env and returns empty.
https://github.com/actions/virtual-environments-internal/issues/2601

[Ubuntu] Add HOMEBREW_SHELLENV_PREFIX env

---

images/linux/scripts/base/apt.sh
images/linux/scripts/tests/Apt.Tests.ps1
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

`aria2` is already installed as part of https://github.com/actions/virtual-environments/blob/133db654885e1796cc158ab04f9217826294857a/images/linux/scripts/base/apt.sh#L29
This change will add `aria2` to list of apt packages in generated README the same way `jq` is already done

[Ubuntu] fix: add aria2 to toolset

---

images/macos/software-report/SoftwareReport.Common.psm1

We should use the same name style in macOS doc for Kotlin which we use in Windows and Ubuntu docs.

[macOS] doc: rename kotlin to Kotlin

---

images/macos/provision/configuration/configure-tccdb-macos11.sh

We store these values on the base images, but in the future, we're going to add them during the image generation. This is the full set of permissions for macOS Big Sur.
https://github.com/actions/virtual-environments-internal/issues/2491

[macOS] Add configure-tccdb-macos11 script

---

images/linux/scripts/installers/erlang.sh
images/linux/scripts/installers/nvm.sh

Sometimes bash ignores `set -e` option for subshells commands and will continue to invoke the next script. We should move invoke_tests call to the bottom of a script not to override the last exit code.
https://github.visualstudio.com/virtual-environments/_build/results?buildId=115326&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043
Before:
```
==> azure-arm: Exception: /imagegeneration/helpers/Tests.Helpers.psm1:41
==> azure-arm: Line |
==> azure-arm:   41 |          throw "Test run has failed"
==> azure-arm:      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:      | Test run has failed
==> azure-arm: 
==> azure-arm: Provisioning with shell script: C:\agent\_work\6\s\images\linux/scripts/installers/firefox.sh
```
After:
```
==> azure-arm: …
```

[Ubuntu] scripts: move invoke_tests at the bottom

---

images/macos/provision/configuration/preimagedata.sh

Environment and links contain macos-11.5 term. It is invalid and all links are broken due to that.
The correct environment should be macos-11.
https://github.com/actions/virtual-environments/issues/3953

[macOS 11] fix for invalid link to release and software report

---

images/win/scripts/Installers/Install-JavaTools.ps1

Currently we install specific version of Maven on Windows images. In scope of this PR we are removing exact Maven version to install in favor to install latest available version.

[Windows] Remove exact Maven version to install

---

images/linux/scripts/installers/homebrew.sh

Remove double quotes around env vars.
Before:
```
HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew
```
Expected:
```
HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew
```
https://github.com/actions/virtual-environments/issues/3981

[Ubuntu] homebrew: remove double quotes around env vars

---

images/win/post-generation/Dotnet.ps1
images/win/scripts/Tests/ChocoPackages.Tests.ps1

Remove NuGet.Config if exists.
https://docs.chocolatey.org/en-us/choco/release-notes
Fix - Prevent creation of empty nuget.config in user appdata folder - see #2233

[Windows] postdotnet: delete nuget.conf if exists

---

images/win/scripts/Tests/ChocoPackages.Tests.ps1

Remove validation Nuget.Config test and move to canary.

[Windows] pester: remove Nuget.Config test

---

images/macos/provision/core/dotnet.sh

Currently, we install all available and supported versions of .NET SDK. In scope of this PR, we change this approach in favor of installing the latest patch version for every feature version.

[macOS] Change .NET SDK pre-installation policy

---

images/win/scripts/Installers/Install-DotnetSDK.ps1

Currently, we install all available and supported versions of .NET SDK. In scope of this PR, we change this approach in favor of installing the latest patch version for every feature version.

[Windows] Change .NET SDK pre-installation policy

---

images/win/scripts/Installers/Install-WDK.ps1
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Need more recent Windows SDK to compile against new GraphicsCaptureAccess class. Also updated WDK because of the comment that they need to be on the same version.
Verified correct version of SDK, WDK, and WDK VS extension were all installed to a generated VM. My application compiles successfully.
I more or less did the same things as the previous upgrade to 19041: #935
Someone opened issue #3641 a couple months ago, and it was closed, but I'm hoping this is fine since the PR is similar to the previous one.

Update windows-2019 image to use 20348 SDK & WDK

---

images/win/scripts/Installers/Install-Edge.ps1

Edge browser is already pre-installed on Windows Server 2022 that's why msi installation fails with exit code 1603.
https://github.com/actions/virtual-environments-internal/issues/2689

[Windows] edge: skip edge installation for windows-2022

---

images/macos/provision/configuration/configure-machine.sh
images/macos/provision/core/safari.sh
images/macos/templates/macOS-10.13.json
images/macos/templates/macOS-10.14.json
images/macos/templates/macOS-10.15.json
images/macos/templates/macOS-11.json
images/macos/tests/Browsers.Tests.ps1

Previously, we had `Allow Remote Automation` option activate on our base image from which we generate images. We would like to move this step to image generation to avoid code debt.

[macOS] Activate "Allow Remote Automation" Safari option during image generation

---

docs/software-and-images-guidelines.md

We don't mention docker images in our software guidelines, which is confusing. This PR adds a line about them.
https://github.com/actions/virtual-environments-internal/issues/2691

Add docker images to the list of tools in software guidelines

---

images/win/windows2019.json

Add extra reboot command before running the `Install-WindowsUpdates.ps1` script.
https://github.com/actions/virtual-environments/issues/4026

[Windows] winpacker: add extra reboot step

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

We should include WSLv1 section in Windows Server 2022 doc file.

[Windows] doc: add wsl info section for win22

---

images/macos/provision/core/node.sh
images/macos/tests/Node.Tests.ps1
images/macos/toolsets/toolset-10.13.json
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

Currently we install global `npm` modules in `node.sh`. In scope of this pull request we move global `npm` packages to the toolset.

[macOS] Move global npm packages to toolsets

---

images/win/scripts/Installers/Install-JavaTools.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Java.psm1
images/win/scripts/Tests/Java.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

- sets JAVA_HOME_8_X64 to use Adoptium jdk
- sets JAVA_HOME_11_x64 to use Adoptium jdk
- sets JAVA_HOME_13_X64 to use Adopt jdk (Adoptium is not available here at all)

[Windows] Add adoptium to javatools installer

---

images/macos/provision/core/powershell.sh
images/macos/tests/BasicTools.Tests.ps1
images/macos/tests/Powershell.Tests.ps1
images/macos/tests/Python.Tests.ps1
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

The `azure-cli` package pulls python3.9 as a dependency from within the `powershell.sh` installer, which is being called before the actual python installer.  In our `python.sh` script we are installing both python2 from the upstream `.pkg` file and python3 from brew. python2 installation overrides the previously created `/usr/local/bin/2to3` symlink to its own internal path -`/Library/Frameworks/Python.framework/Versions/2.7/bin/2to3`, in the meantime python3 installation attempt is being ignored (as well as the `brew link --overwrite python@3.` call) as it had already been installed by azure cli. To prevent this azure-cli installation has been moved from `powershell.sh` to `commonutils.sh` to fix the installation order.
Apart from that:
- A test has been written to make sure that `2to3` …

[MacOS] fix python installation order

---

images/win/scripts/Installers/Install-Haskell.ps1

See https://github.com/actions/virtual-environments/pull/4016 for discussion and reasoning.
This just adds ghcup the binary to the installation. It still uses chocolatey for installation. I leave it open for discussion whether chocolatey or ghcup should be used. However, there have been some reports of chocolatey issues: https://github.com/haskell/actions/issues/70#issuecomment-913100373
I can't comment on the nature of them. I believe chocolatey is quite robust. It lacks a little bit behind in adding new GHC versions, but not significantly.
The main (or maybe only) difference between ghcup and chocolatey is the shimgen wrapper they use for emulating symlinks to `ghc.exe`:
1. Chocolatey uses a proprietary shimgen: https://github.com/chocolatey/shimgen#why-is-shimgen-closed-source
2. ghcup …

Install ghcup on windows

---

images/linux/scripts/installers/rust.sh

The issue has been fixed - https://github.com/rustsec/rustsec/issues/429
https://docs.rs/crate/cargo-audit/0.15.2 - the last successful build

Revert "[Ubuntu] Install cargo-audit 0.14.1 as 0.15.0 is broken"

---

images/win/scripts/Installers/Install-Rust.ps1

The issue has been fixed - https://github.com/rustsec/rustsec/issues/429
https://docs.rs/crate/cargo-audit/0.15.2 - the last successful build

Revert "[Windows] Install cargo-audit 0.14.1 as 0.15.0 is broken"

---

images/macos/provision/core/rust.sh

The issue has been fixed - https://github.com/rustsec/rustsec/issues/429
https://docs.rs/crate/cargo-audit/0.15.2 - the last successful build

Revert "[macOS] Install cargo-audit 0.14.1 as 0.15.0 is broken"

---

images/win/toolsets/toolset-2022.json

This PR adds Microsoft.VisualStudio.Component.VC.Tools.ARM and Microsoft.VisualStudio.Component.VC.Tools.ARM64 components to VisualStudio of Windows 2022 image.

[Windows] Add Microsoft.VisualStudio.Component.VC.Tools.ARM and Microsoft.VisualStudio.Component.VC.Tools.ARM64 components to Win 2022

---

images/macos/provision/core/android-toolsets.sh
images/macos/software-report/SoftwareReport.Android.psm1
images/macos/tests/Android.Tests.ps1
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

In scope of this PR we have added Android NDK r23 to macOS images and leave the current LTS version (r21) as default.
Also, we've reworked the `android.ndk` toolset section:
- The `android.ndk.versions` field  is a manually sorted list of all versions that will be installed on the image
- The `android.ndk.lts` field has been renamed to `android.ndk.default`. It will allow us, if necessary, to set a non-LTS NDK version as default.
- The `android.ndk.latest` field has been removed and its value will be taken from the end of `android.ndk.versions` list

[macOS] Add Android NDK r23

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

This PR removes alpine:3.11 docker image from the list of pre-cached images on Ubuntu 18.04 and 20.04 VMs

[Ubuntu] Remove alpine:3.11 docker image from Ubuntu 18.04 and 20.04

---

images/macos/provision/core/xcode.ps1
images/macos/toolsets/toolset-11.json

It turned out Xcode 13 RC doesn't contain macOS-12 SDK so we decided to keep Xcode 13 beta version on the images for now.
This PR introduces the following changes:
- Location of the Xcode 13 is `/Applications/Xcode_13.0.app`. The `/Applications/Xcode_13.0.0.app` symlink will be created for this version.
- Location of the Xcode 13 beta is `/Applications/Xcode_13.0_beta.app`. There are no symlinks for this version.

[macOS] Install Xcode 13 beta along with 13 stable

---

images/macos/provision/core/haskell.sh

Freeing up disk space on macOS by removing docs and profiling libs of GHC. 
This PR is based on [Improve haskell ghcup #4016](https://github.com/actions/virtual-environments/pull/4016)

[macOS] Improve haskell setup

---

images/linux/scripts/SoftwareReport/SoftwareReport.Android.psm1
images/linux/scripts/installers/android.sh
images/linux/scripts/tests/Android.Tests.ps1
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

In scope of this PR we have added Android NDK r23 to Ubuntu images and leave the current LTS version (r21) as default.
Also, we've reworked the `android.ndk` toolset section:
- The `android.ndk.versions` field is a manually sorted list of all versions that will be installed on the image
- The `android.ndk.lts` field has been renamed to `android.ndk.default`. It will allow us, if necessary, to set a non-LTS NDK version as default.
- The `android.ndk.latest` field has been removed and its value will be taken from the end of `android.ndk.versions` list

[Ubuntu] Add android NDK r23

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1

Improving output for "Install-Binary" and "Start-DownloadWithRetry" functions with additional measuring and logging of installing and downloading durations.
https://github.visualstudio.com/virtual-environments/_build/results?buildId=116599&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043&l=5552

Measure and output installing and downloading durations

---

docs/software-and-images-guidelines.md

Currently, Android NDK policy is to install 1 latest and 1 LTS version of Android NDK. We have reconsidered the policy. The images will contain two LTS versions and one non-LTS version.

Update Android NDK policy in the Software and image guidelines

---

images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/BasicTools.Tests.ps1
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

This PR adds SBT tool to MacOS 10.14, 10.15 and 11 images.

[MacOS] Add SBT to MacOS 10.14, 10.15 and 11

---

images/macos/provision/core/openjdk.sh
images/macos/software-report/SoftwareReport.Java.psm1
images/macos/tests/Java.Tests.ps1
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

Another round of Adoptium (Temurin-Hotspot) addition. The script attempts to emulate the same behaviour as the Windows installer has (taking into account all the limitations bash has). Toolset parsing is a little bit flaky as our `get_toolset_value` function does not have the `--arg` passed (for obvious reason) to use `jq` output in the loops (suggestions are welcome!).
* Pester tests have been updated to make sure all Adopt's versions can be found in the paths we expect them to be installed to
* Some Adopt's versions have been hardcoded (they only belong to MacOS 10.x and only to Adopt, no surprise is going to happen)
* Adopt's versions `8` and `11` are using Adoptium's downloading links already (they got redirected once used), as per discussion it was considered ok as there are no …

[MacOS] Add Adoptium to Java installer

---

images/macos/provision/core/haskell.sh

Starting with ghcup 0.1.17 we can query the basedir easier.
n\a
- [n\a ] Documentation is updated (if applicable)

[macOS] Simpify ghcup code to use "ghcup whereis basedir"

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/Tests/Tools.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

This adds Clang, LLD, compiler-rt, various LLVM tools
Install time is ~ 3.5 minutes
I've manually tested windows 2016/2019 and 2022 images generated. 
https://github.com/actions/virtual-environments/issues/2530

Add LLVM via choco

---

images/linux/scripts/installers/aliyun-cli.sh

Current approach returns 2 entries:
```
https://github.com/aliyun/aliyun-cli/releases/download/v3.0.93/aliyun-cli-linux-3.0.93-amd64.tgz
https://github.com/aliyun/aliyun-cli/releases/download/v3.0.93/aliyun-cli-linux-3.0.93-arm64.tgz
```
We should use only `amd64` version.

[Ubuntu] Fix Aliyun-cli installation

---

images/win/scripts/ImageHelpers/PathHelpers.ps1

PathHelpers: removing interaction with system registry and hardcoded registry paths. Working with system environment variables instead.
Also changing functions order for better readability to following:
- Get-SystemVariable
- Set-SystemVariable
- Get-MachinePath
- Set-MachinePath
- Test-MachinePath
- Add-MachinePathItem
https://github.visualstudio.com/virtual-environments/_build/results?buildId=116836

PathHelpers: Dealing with hardcoded registry paths and optimizing code

---

images/macos/provision/core/openssl.sh
images/macos/software-report/SoftwareReport.Common.psm1

In our `openssl.sh` we [install](https://github.com/actions/virtual-environments/blob/b7f276c003aea42575b52247bdb2183e355fca2f/images/macos/provision/core/openssl.sh#L4) both the latest openssl version and 1.1.x. Starting from the last week latest openssl is 3.0, so in fact we are now installing two separate openssl versions which is ok per se. In our software report we are checking the openssl path based on the existence of the `/usr/local/opt/openssl` directory, but as soon as we have v3 installed there are the following directories
* /usr/local/opt/openssl@1.1
* /usr/local/opt/openssl@3
* /usr/local/opt/openssl
as a result the `/usr/local/opt/openssl` directory contains exactly the same files as `/usr/local/opt/openssl@3` does (I believe it has previously had files identical to the …

[MacOS] Do not install latest OpenSSL

---

images/win/scripts/Installers/Install-VCRedist.ps1
images/win/scripts/Tests/Tools.Tests.ps1
images/win/windows2016.json
images/win/windows2019.json
images/win/windows2022.json

Sometime logs for Windows Server 2019 do not contain all info:
```
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\agent\_work\4\s\images\win/scripts/Installers/Install-VCRedist.ps1
vhd: Downloading vcredist_x86.exe...
vhd: Downloading package from: https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe to path C:\Users\packer\AppData\Local\Temp\vcredist_x86.exe .
==> vhd: Provisioning with powershell script: C:\agent\_work\4\s\images\win/scripts/Installers/Install-Docker.ps1
```
- Add check_registry param
- Add vcredist test for Windows Server 2016/2019
- Remove Install-VCRedist.ps1 for Windows Server 2022

[Windows] win: add vcredist 2010 test

---

images/linux/scripts/installers/docker-compose.sh

Temporary stick docker-compose to 1.29.2 until `moby-compose` package is released with docker-compose v2.
https://github.com/actions/virtual-environments/issues/4163

[Ubuntu] set docker-compose v1

---

images/linux/scripts/installers/java-tools.sh

Currently the latest tag is 3.8.3, but there is no available binaries for this release. We should get the latest available maven version from the maven.apache.org site.
https://github.com/actions/virtual-environments/issues/4172

[Ubuntu] java: do not use the github tag release

---

images/win/windows2019.json

Occurrence, only for Windows Server 2019, after installing windows updates the process is still in progress and packer can't detect properly this status, that's why we have a chance to get:
1. Error:
`==> vhd: A system shutdown is in progress. Error: 0x8007045b
`
2. Skip software installation
```
==> vhd: Provisioning with powershell script: C:\agent\_work\3\s\images\win/scripts/Installers/Install-VCRedist.ps1
vhd: Downloading vcredist_x86.exe...
vhd: Downloading package from: https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe to path C:\Users\packer\AppData\Local\Temp\vcredist_x86.exe .
vhd: Package downloaded successfully in 0.45 seconds
vhd: Starting Install vcredist_x86.exe...
==> vhd: Provisioning with powershell script: …
```

[Windows] packer: add pause after windows update

---

images/linux/scripts/installers/java-tools.sh

Reverts actions/virtual-environments#4182
Binaries 3.8.2 have been removed without updating links to download the latest version - https://maven.apache.org/download.cgi

Revert "[Ubuntu] java: do not use the github tag release"

---

images/win/post-generation/VSConfiguration.ps1
images/win/scripts/Installers/Install-VS.ps1

The Visual Studio Experimental Instance initialization needs to happen in the user where the GA workflow will run (`runneradmin`), not on the `installer` user which is currently the case due to https://github.com/actions/virtual-environments/blob/c161416ac88327a4362f4fb8b3413fea4fe9289b/images/win/windows2022.json#L165.
See my previous pull request https://github.com/actions/virtual-environments/pull/4143 why this is needed.

Initialize Visual Studio Experimental Instance on the correct user

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

[BuildKit](https://github.com/moby/buildkit) is probably the most used build engine for Docker images via our [docker/build-push-action](https://github.com/docker/build-push-action/) GitHub Action.
Whenever a build is triggered, the latest [BuildKit image](https://hub.docker.com/r/moby/buildkit) is pulled from Docker Hub and we think it would be more efficient for GitHub to have it preloaded.
cc @chrispat @justincormack @chris-crone @tonistiigi

[Ubuntu] docker: add buildkit image

---

images/win/scripts/Installers/Install-VS.ps1

Image generation process has been starting to fail at the `Install-VS.ps1` script with `Set-Content : Could not find a part of the path 'C:\Common7\IDE\Extensions\MachineState.json'` error,  after regression was included in  https://github.com/actions/virtual-environments/pull/4223 PR. We should revert $vsInstallRoot statement to fix the issue.

[Windows] vs: revert $vsInstallRoot

---

images/win/scripts/Installers/Install-AzureCli.ps1

The latest azure-cli is not available via msi package, it can be installed using python only https://github.com/Azure/azure-cli/issues/19811
This PR changes the way we get the version as the latest release does not always include msi package.
n\a

[Windows] Install the latest available azure-cli msi package

---

images/win/scripts/Installers/Install-Selenium.ps1

`Selenium` was recently updated to 4.* version that can contain some breaking changes. We decided to pin its version to `3.141.59` for some time.

[Windows] Pin Selenium to 3.141.59 version

---

images/win/scripts/Installers/Install-NodeLts.ps1
images/win/scripts/Tests/Node.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

This PR changes way of Node.js install to use default version from toolset instead of LTS. 
https://github.com/actions/virtual-environments-internal/issues/2890
- [Windows2022](https://github.visualstudio.com/virtual-environments/_build/results?buildId=118470&view=results)

[Windows] Rework NodeJS install

---

images/linux/scripts/installers/nodejs.sh
images/linux/scripts/tests/Node.Tests.ps1
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

This PR changes way of Node.js install to use default version from toolset instead of LTS. 
https://github.com/actions/virtual-environments-internal/issues/2890
- [Ubuntu2004](https://github.visualstudio.com/virtual-environments/_build/results?buildId=118471&view=results)

[Linux] Rework NodeJS install

---

images/linux/scripts/installers/vcpkg.sh

Latest commit in master does not build, pick the previous one which builds fine. Also fixed the symlink,
`/usr/local/bin -> /usr/local/bin/vcpkg` (`bin` must remain a directory).

[Ubuntu] build vcpkg from specific commit

---

images/linux/scripts/installers/android.sh

In scope of this PR we are adding `ANDROID_NDK_LATEST_HOME` env variable on Ubuntu18 as well.

[Ubuntu] Add ANDROID_NDK_LATEST_HOME env variable

---

images/macos/provision/core/vcpkg.sh

Latest commit in master does not build, pick the previous one which builds fine. Also fixed the symlink,
`/usr/local/bin -> /usr/local/bin/vcpkg` (`bin` must remain a directory).

[macOS] install vcpkg from specific commit

---

images/win/scripts/Installers/Install-Docker.ps1

Docker service doesn't start properly after reboot with error:
`fatal: open C:\ProgramData\docker\panic.log: Access is denied.
`
https://github.com/actions/virtual-environments-internal/issues/2920

[Windows] Docker service does not start on Windows Server 2016-2022

---

images/win/post-generation/Choco.ps1

Currently a choco dummy call performed as a post-generation step might elicit unwanted upgrade (if available).
This, in turn leads to unwanted consequences like bringing the `cpack` command alias back into our images.
To prevent this a dummy call must be done for the currently installed version only.

[Windows] make choco dummy call for currently installed version

---

images/win/scripts/Installers/Install-Docker.ps1

Pin Docker EE to 20.10.7 version due to panic.log ReadOnly attribute file regression in Docker EE 20.10.8.
[actions/virtual-environments-internal#2920](https://github.com/actions/virtual-environments-internal/issues/2920)

[Windows] Pin Docker EE to 20.10.7 version

---

images/macos/software-report/SoftwareReport.Common.psm1

This pull request fixes the `Get-AzureCLIVersion` function as it returns incorrect `azure-cli` version by now.
Whenever the `az -v` command reports a message about the update possibility, the output is going to be incorrect as the `Take-OutputPart` function returns the rightmost part of the string (which is the asterisk character when update is possible).
The `Make-Output Port` function call was replaced with processing output the command `az version` using PowerShell tools to reflect a correct version.

[MacOS] Fix software report for azure-cli

---

images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json

All pre-cached Go versions less than 1.15 will be removed from all operating systems.

[MacOS] Go versions less than 1.15 should be removed until November, 8

---

images/win/scripts/Installers/Configure-Antivirus.ps1

SenseCE.exe and MsSense.exe which are part of Windows Defender Advanced Threat Protection can scan system during image generation process and causes files lock( `==> vhd: Move-Item : Access to the path 'C:\Users\packer\AppData\Local\Temp\rubyinstaller-2.4.10-1-x64' is denied.`).
```
Name        : SenseCE.exe
vhd: CommandLine : "C:\Program Files\Windows Defender Advanced Threat Protection\Classification\SenseCE.exe" "1624"
vhd:               "2ec11e40-f8f5-4d82-8e24-9621b82273bd" "1800" "60" 
vhd: MsSense.exe pid: 5024 \<unable to open process>
vhd:    48: File  (RW-)   C:\Windows\System32
vhd:    7C: Section       \BaseNamedObjects\__ComCatalogCache__
vhd:    8C: Section       \BaseNamedObjects\__ComCatalogCache__
vhd:   134: File  (R-D)   C:\Program Files\Windows Defender Advanced Threat …
```

[Windows] Set Microsoft Defender Antivirus to passive mode

---

helpers/GenerateResourcesAndImage.ps1

Improvement
Allow a passthrough option via GenerateResourcesAndImage that works with Azure storage account instances that have restricted PublicBlobAccess that do not have defaults set in conjunction with the Azure policy.
Related policy and blog description: https://azsec.azurewebsites.net/2020/08/24/everything-you-need-to-know-about-allowblobpublicaccess-on-storage-account/
- [ x] Related issue / work item is attached
- [ x] Tests are written (if applicable)
- [ x] Documentation is updated (if applicable)
- [ x] Changes are tested and related VM images are successfully generated

Optional passthrough of AllowBlobPublicAccess

---

images/macos/provision/core/vcpkg.sh

The issue is fixed, we can revert the change now.

Revert "[macOS] install vcpkg from specific commit"

---

images/win/toolsets/toolset-2022.json

Visual Studio 2022 has been released and we need to change the channel from `pre` to `release`.
n\a

[Windows] Change channel from pre to release for VS22

---

images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

Xcode beta 13 was preserved on the image due to a lack of macOS 12 SDK in the stable Xcode 13 version. Since Xcode 13.1 contains the necessary SDK we can get rid of Xcode 13 beta from the image.
The default Xcode will be also set to 13.1 because we would like to provide images with the latest stable updates as default ones.
This PR also removes Xcode 13 from macOS-12 as macOS-12 SDK is not supported in this version.
https://github.com/actions/virtual-environments/issues/4355

[macOS] Remove Xcode 13 beta & set Xcode 13.1 as default

---

images/macos/provision/core/commonutils.sh
images/macos/provision/core/llvm.sh
images/macos/templates/macOS-10.15.json
images/macos/templates/macOS-11.json
images/macos/templates/macOS-11.pkr.hcl
images/macos/tests/BasicTools.Tests.ps1
images/macos/tests/LLVM.Tests.ps1
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

Pinned the latest llvm version. The real problem I have faced is our current `clang --version` call in the test suite.
Currently `"$(brew --prefix llvm)/bin/clang --version" | Should -ReturnZeroExitCode` will be expanded to the
`/usr/local/opt/llvm/bin/clang --version` string, i.e. only brew prefix is going to be expanded but no real clang invocation happen. Suggestions on how to improve the test are welcome.
Also moved llvm to its own installer for consistency as this does not belong to `commonutils.sh` now (nor to its toolset section).

[macOS] move llvm to toolset

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/installers/nodejs.sh

This PR corrects source of n tool according to [official documentation](https://github.com/tj/n) and adds gathering of n version to Software Report.
https://github.com/actions/virtual-environments-internal/issues/2890
- [Ubuntu 1804](https://github.visualstudio.com/virtual-environments/_build/results?buildId=118902&view=results)
- [Ubuntu 2004](https://github.visualstudio.com/virtual-environments/_build/results?buildId=118901&view=results)

[Ubuntu] Change source of n tool to official

---

images/win/scripts/ImageHelpers/ChocoHelpers.ps1
images/win/scripts/Installers/Install-NodeLts.ps1

We have the [Get-LatestChocoPackageVersion](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/ImageHelpers/ChocoHelpers.ps1#L47) function now so the installation script can be simplified.
n\a

[Windows] Use Get-LatestChocoPackageVersion to get nodejs version to install

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/Tests/Miniconda.Tests.ps1
images/win/windows2022.json

Miniconda is not installed on the image but is required for some ADO users.
https://github.com/actions/virtual-environments/issues/4450

[windows] Add miniconda to windows 2022 image

---

images/macos/provision/core/vcpkg.sh

The vcpkg versioning features rely on retrieving information from its git repository history. This means users need a deep clone to access earlier versions and baselines.
See https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#builtin-baseline for one of the user-facing points that requires specifying a git commit id from the history
https://github.com/actions/virtual-environments/pull/4272

[macOS] Perform a full clone of vcpkg instead of depth=1

---

images/win/scripts/Installers/Install-MongoDB.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Starting with MongoDB 5.0, MongoDB is released as two different release series:
- Major Releases
- Rapid Releases
**Major Releases are made available approximately once a year, and generally mark the introduction of new features and improvements. Major Releases are appropriate for all MongoDB deployments.
Rapid Releases are designed for use with MongoDB Atlas, and are not generally supported for use in an on-premise capacity.**
We have to pin the version to the latest Major 5.0 release.
https://github.com/actions/virtual-environments/discussions/4481

[Windows] Pin mongodb to 5.0

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Starting with MongoDB 5.0, MongoDB is released as two different release series:
- Major Releases
- Rapid Releases
**Major Releases are made available approximately once a year, and generally mark the introduction of new features and improvements. Major Releases are appropriate for all MongoDB deployments.
Rapid Releases are designed for use with MongoDB Atlas, and are not generally supported for use in an on-premise capacity.**
We have to pin the version to the latest Major 5.0 release.
https://github.com/actions/virtual-environments/discussions/4481

[Ubuntu] Pin mongodb version to 5.0

---

images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

Starting with MongoDB 5.0, MongoDB is released as two different release series:
- Major Releases
- Rapid Releases
**Major Releases are made available approximately once a year, and generally mark the introduction of new features and improvements. Major Releases are appropriate for all MongoDB deployments.
Rapid Releases are designed for use with MongoDB Atlas, and are not generally supported for use in an on-premise capacity.**
We have to pin the version to the latest Major 5.0 release.
https://github.com/actions/virtual-environments/discussions/4481

[macOS] Pin mongodb version to 5.0

---

images/win/toolsets/toolset-2022.json

`wasm.tools` is an optional component from `.NET WebAssembly build tools` workload, which is required for some customers' builds. Installation time in runtime is about 5 minutes so it's worth baking the component into the image.
https://github.com/actions/virtual-environments/issues/4479

[Windows] Add wasm.tools component to VS2022

---

images/win/scripts/Installers/Install-LLVM.ps1
images/win/scripts/Tests/LLVM.Tests.ps1
images/win/scripts/Tests/Tools.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/windows2016.json
images/win/windows2019.json

Pinned latest llvm version using the recently added `Get-LatestChocoPackageVersion` function.
I also propose we dropping the `clang++ --version` check in tests as `clang++` calls are literally equal to the `clang -x` and `clang -lstdc++` ones (i.e. binary is in fact the same but installed a little bit differently).

[Windows] move llvm to toolset

---

images/linux/scripts/installers/java-tools.sh
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

As was discussed at the standup.  
Lets add maven back to toolset as we have experienced multiple problems as github versions and apache foundation mirror versions are out of sync too frequently.

[Ubuntu] add maven back to toolset

---

images/linux/scripts/installers/post-deployment.sh

In scope of this PR, we set chmod 777 on the following known directories:
- `/opt`
- `/usr/share`
- `/home`
The purpose of this PR is bringing some Provisioner legacy scripts to public repo. We already invoke these commands during deployment so we just move it to image-generation stage since they don't depend on user.

[Ubuntu] Chmod known directories

---

images/macos/provision/core/postgresql.sh
images/macos/tests/Databases.Tests.ps1
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

We need to move PostgreSQL along with some other tools to the toolset on all OSes to make versions control more granular.

[MacOS] Pin PostgreSQL version installed in the toolset

---

images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Install-WindowsUpdates.ps1
images/win/scripts/Tests/WindowsFeatures.Tests.ps1
images/win/windows2019.json

It turned out Windows updates are not installed during the image generation, only accepted:
- Add test to validate failed updates except Windows Defender
- Move installation script at the end as for other distros
https://github.com/actions/virtual-environments-internal/issues/2943

[Windows] Add test to validate windows updates installation

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1

- DEPRECATION NOTICE - choco version command is deprecated and will be removed in version 1.0.0.
- Do not use regex get version of choco

[Windows] softwarereport: do not use regex to get version of choco

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

The version got updated without preserving 3.8.3 (who knows why), blocks our ubuntu images generation.

[Ubuntu] Update maven to 3.8.4

---

images/linux/scripts/installers/php.sh

Looks like php version in the PPA repo got updated and now we are lacking proper libcre2 version which blocks our builds, I guess it gonna be fixed eventually but lets workaround it for now.
https://github.com/actions/virtual-environments/pull/4551

[Ubuntu] install libpcre2-8-0 for PHP compat

---

.github/workflows/linter.yml

This PR updates the CI linter workflow to only run if a JSON of MD file is changed. This saves CI time on PRs that only have changes to other file types.
Also updates [github/super-linter](https://github.com/github/super-linter) to version 4.

CI: Run linter only on changes of JSON and MD files

---

images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
images.CI/macos/anka/Service.Helpers.psm1

By default beta seed is enabled after a new clean vm has been created. We should install software updates only from stable channel.
Before:
```
[*] Fetching Software Updates ready to install on 'clean_macos_11_300gb' VM:
* Label: Device Support Update- 
Title: Device Support Update, Version:  , Size: 191029K, Recommended: YES, 
* Label: Safari15.1BigSurAuto-15.1
Title: Safari, Version: 15.1, Size: 118254K, Recommended: YES, 
* Label: macOS Big Sur 11.6.2-20G306
Title: macOS Big Sur 11.6.2, Version: 11.6.2, Size: 2548664K, Recommended: YES, Action: restart
```
After:
```
* Label: Device Support Update- 
Title: Device Support Update, Version:  , Size: 191029K, Recommended: YES, 
* Label: Safari15.1BigSurAuto-15.1
Title: Safari, Version: 15.1, Size: 118254K, Recommended: YES,
``` …

Anka disable beta seed

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/Tests/Tools.Tests.ps1
images/win/windows2022.json

Adds [sbt](https://github.com/sbt/sbt) to the Windows 2022 image. It's already installed for the Windows Server 2016 and 2019 images, and this PR adds it also to the 2022 image.

[Windows] Add sbt to Windows 2022 image

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/win/scripts/Tests/Tools.Tests.ps1

This PR adds information about installed Service Fabric SDK version to Software Report. 
https://github.com/actions/virtual-environments/issues/4546
- [Windows 2019](https://github.visualstudio.com/virtual-environments/_build/results?buildId=119560&view=results)
- [Windows 2022](https://github.visualstudio.com/virtual-environments/_build/results?buildId=119561&view=results)

[Windows] Add Service Fabric SDK to Software Report

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Node.js 16 has moved to Active LTS status and is ready for general use. We would like to provide images with the latest stable updates as default ones.

[Ubuntu] set default nodeJS version to 16

---

images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Node.js 16 has moved to Active LTS status and is ready for general use. We would like to provide images with the latest stable updates as default ones.

[Windows] set default nodeJS version to 16

---

images/macos/tests/Node.Tests.ps1
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

Node.js 16 has moved to Active LTS status and is ready for general use. We would like to provide images with the latest stable updates as default ones.

[macOS] set default nodeJS version to 16

---

images/macos/software-report/SoftwareReport.Generator.ps1

This pull request is fixing markdown in the software report. Removed double empty line after utilities list.  Added 
an empty string before the blok "Rust Tools".

[macOS] Fix markdown in the software report

---

images/win/scripts/ImageHelpers/ChocoHelpers.ps1

Bug: Get-LatestChocoPackageVersion -TargetVersion '14.1' -PackageName "nodejs"  - returning "14.18.1" instead of 14.1.0
Filtering out query result to version like or equal target one.

[Windows] Fix Get-LatestChocoPackageVersion

---

images/win/scripts/Installers/Install-MysqlCli.ps1
images/win/scripts/Tests/Databases.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

v8.0.27 is buggy as described in the related issue, we must downgrade it, and I think stay with the release version pinned in the toolset as God knows what bugs Oracle will ship with another new version of mysql.

[Windows] pin mysql release version in toolset

---

images/linux/scripts/installers/git.sh

The pull request updates git-lfs to version 3 as we are no longer blocked by the canary test suite, the successful canary pipeline can be found here: https://buildcanary.visualstudio.com/PipelineCanary/_build/results?buildId=1931732&view=logs&j=887754d4-d00e-5c30-0c89-40a8bc57d50d .

[Ubuntu] Update the version Git-lfs

---

images/win/toolsets/toolset-2022.json

This PR adds Gulp CLI global npm package to Windows 2022
https://github.com/actions/virtual-environments/issues/4577
- [Windows2022](https://github.visualstudio.com/virtual-environments/_build/results?buildId=119716&view=results)

[Windows] Add gulp-cli global npm package

---

images/win/scripts/Installers/Install-Wix.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1
images/win/scripts/Tests/Wix.Tests.ps1
images/win/windows2022.json

This PR adds WiX Toolset to Windows 2022 image.
https://github.com/actions/virtual-environments/issues/4419
- [Windows 2016](https://github.visualstudio.com/virtual-environments/_build/results?buildId=119788&view=results)
- [Windows 2019](https://github.visualstudio.com/virtual-environments/_build/results?buildId=119787&view=results)
- [Windows 2022](https://github.visualstudio.com/virtual-environments/_build/results?buildId=119786&view=results)

[Windows] Add WiX tool for Windows 2022

---

images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

php-8.1 is considered  [stable](https://www.php.net/ChangeLog-8.php#8.1.0) we must upgrade too, as composer now requires 8.1 strictly

[macOS] upgrade php version to 8.1

---

images/win/scripts/Installers/Install-Zstd.ps1

Sometimes customers have an issue with Access is denied during image generation after invoking Extract-7Zip, as a workaround is using a function with retries.
https://github.com/actions/virtual-environments/issues/4277#issuecomment-981732230

[Windows] zstd: Invoke Move-Item with retry

---

images/macos/helpers/Xcode.Installer.psm1
images/macos/provision/core/xcode.ps1

Improvement
Renaming Xcode directory to include version name destroys Launch Services database and prevents command `open` to work with .app bundles.

Rebuilding Launch Services database

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Wait-WindowsUpdatesForInstall.ps1
images/win/windows2019.json
images/win/windows2022.json

Some updates (e.g. `2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Microsoft server operating system version 21H2 for x64 (KB5007293)` )  are still in progress state during tests validation. We should wait for installation to complete.
```
PS > Get-WindowsUpdatesHistory
Status     Title
------     -----
Successful Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.353.1825.0)
Successful Windows Malicious Software Removal Tool x64 - v5.95 (KB890830)
Successful 2021-11 Cumulative Update for Microsoft server operating system version 21H2 for x64-based Systems (KB500...
InProgress 2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Microsoft server operating system ve...
```
Waiting ~10 minutes to finish:
```
PS > …
```

[Windows] Add pause after Windows Update

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Helpers.psm1

This pull request is fixing markdown in the software report. Removed double empty line after utilities list. Added separating empty lines in places where it is necessary.

[Windows] Fix markdown in the software report

---

images/win/scripts/Installers/Install-MysqlCli.ps1
images/win/scripts/Tests/Databases.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

This PR corrects MySQL installation script to add ability use Major.Minor version (and automatically determine the latest Build) or stick to specified Major.Minor.Build in case of some issues with the latest version. 
https://github.com/actions/virtual-environments-internal/issues/3031

[Windows] Improve MySQL install

---

images/win/windows2022.json

We should add a pause after installation windows features due to prevent skip running scripts after reboot.
Unexpected[run during reboot]:
```
==> vhd: Provisioning with powershell script: C:\agent\_work\12\s\images\win/scripts/Installers/Install-Docker.ps1
vhd: Install-Package Docker
==> vhd: Provisioning with powershell script: C:\agent\_work\12\s\images\win/scripts/Installers/Install-PowershellCore.ps1
vhd: VERBOSE: About to download package from
```
Expected:
```
==> vhd: A system shutdown is in progress.(1115)
vhd: pkrvm9lsr8en0xg restarted.
vhd: False
vhd: True
vhd: False
vhd: pkrvm9lsr8en0xg restarted.
vhd: False
vhd: True
vhd: False
vhd: pkrvm9lsr8en0xg restarted.
vhd: False
vhd: True
vhd: False
vhd: pkrvm9lsr8en0xg restarted.
vhd: False
vhd: False
vhd: False
==> vhd: Machine …
```

[Windows] Add pause after installation windows features

---

images/win/toolsets/toolset-2022.json

This adds the `Microsoft.VisualStudio.Component.VC.Llvm.Clang` component to Visual Studio 2022.
Currently the Clang compiler is not functional in Visual Studio 2022, because the following directory is missing:
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\lib\clang\12.0.0
```
The directory comes from this component, so adding it should fix the problem.
Hopefully the existing tests for the VS 2022 image are sufficient.

[Windows] Add Llvm.Clang component to VS 2022

---

images.CI/macos/anka/Service.Helpers.psm1

Unable to fetch full installer:
```
% /usr/sbin/softwareupdate --fetch-full-installer --full-installer-version 11.6.1
Scanning for 11.6.1 installer
Install failed with error: Update not found
```
Clear `LastRecommendedMajorOSBundleIdentifier` property:
```
[*] The 'DownloadLatestVersion' flag is set. Latest macOS version is '11.6.1' now
[*] Removing '/Applications/Install macOS Big Sur.app' installation app before downloading the new one
[*] Requested macOS '11.6.1' version installer found, fetching it from Apple Software Update
[*] Installer successfully downloaded to '/Applications/Install macOS Big Sur.app'
```

[Anka] Clear LastRecommendedMajorOSBundleIdentifier property

---

images/macos/tests/WebServers.Tests.ps1

Previously the command `brew services list` returned stopped status for a service even if the service was never stopped. Current behavior returns `none` status for a service.
```
~ runner$ brew services start httpd
==> Successfully started `httpd` (label: homebrew.mxcl.httpd)
~ runner$ brew services list
Name    Status  User   File
httpd   started runner ~/Library/LaunchAgents/homebrew.mxcl.httpd.plist
php     none
unbound none
~ runner$ brew services stop httpd
Stopping `httpd`... (might take a while)
==> Successfully stopped `httpd` (label: homebrew.mxcl.httpd)
~ runner$ brew services list
Name    Status  User File
httpd   none
php     none
unbound none
```

[macos] pester: Replace service status stopped to none

---

images/linux/scripts/SoftwareReport/SoftwareReport.Databases.psm1
images/linux/scripts/installers/mysql.sh
images/linux/scripts/tests/Databases.Tests.ps1

As has been discussed with @MaksimZhukov and @miketimofeev lets downgrade mysql on ubuntu to 8.0.26 as 8.0.27 is buggy. As there is no an older version in Oracle's PPA repo there was a need to install all the dependencies step by step utilizing the `dpkg -i` command (the order in the `mysql_debs` array matters). No toolset and other flexible solutions were considered yet as the future of this solution is uncertain and will likely be changed.

[Ubuntu] Downgrade mysql to 8.0.26

---

images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/templates/macOS-12.json
images/macos/tests/Common.Tests.ps1
images/macos/tests/RubyGem.Tests.ps1
images/macos/toolsets/toolset-12.json

Adding GCC version 11 to MacOS 12. And removing Nomad shenzhen CLI since it's in the list of software to deprecate: https://github.com/actions/virtual-environments-internal/issues/2647

[MacOS] Add GCC and remove Nomad from MacOS 12 image

---

images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Install-Kotlin.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

This PR corrects Kotlin installation script to use Get-GitHubPackageDownloadUrl function which allow to use any version to get correct download url (Major, Major.Minor, Major.Minor.Build or "latest" to get correct highest release instead of latest GitHub release url that led us to downgrade).
https://github.com/actions/virtual-environments-internal/issues/3034

[Windows] Update Kotlin install

---

images/linux/scripts/installers/mysql.sh
images/linux/scripts/tests/Databases.Tests.ps1

Recent mysql downgrade changes brought mysql 8.x to ubuntu 18.04 too, while it works, this update is unwanted and we must keep repository-provided 5.7.x

[Ubuntu] do not install mysql 8.x on 18.04

---

images/linux/Ubuntu1804-README.md

Ubuntu image is rolled back due to issues with Code QL

Revert "Ubuntu 18.04 (20211208 update)"

---

images/linux/scripts/installers/kotlin.sh

Fetching all kotlin releases and sorting out just latest version instead of direct fetching latest which is not.

[Ubuntu] Fixing kotlin latest release retrieval

---

images/linux/scripts/installers/codeql-bundle.sh
images/win/scripts/Installers/Install-CodeQLBundle.ps1

As github/codeql-action by default uses the bundle from the toolcache,
make sure that that is considered stable.
On Dec 7, we published a broken pre-release into `main` of `github/codeql-action`, which then unfortunately was picked up by the image build and deployed on Dec 9, breaking certain code-scanning workflows.

CodeQL: Pull the bundle from codeql-action@v1 rather than main.

---

images/linux/scripts/SoftwareReport/SoftwareReport.Databases.psm1

mysql-5.7.x was added back to ubuntu 18.04 but `mysqld --version` output differs from a repository and non-repository version of mysql, so for clear software report we must do a version-dependent report generation. (5.7.x reports `5.7.36-0ubuntu0.18.04.1` and we do not need ubuntu postfix as a tail).

[Ubuntu]  fix software report for mysql

---

images/win/scripts/Installers/Install-Haskell.ps1
images/win/scripts/Tests/Haskell.Tests.ps1

The [bootstrap-haskell.ps1](https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/master/scripts/bootstrap/bootstrap-haskell.ps1) script uses
`[System.EnvironmentVariableTarget]::User` instead of
`[System.EnvironmentVariableTarget]::Machine`, so it appears
ghcup env vars and PATH update never make it. Do these manually
for now.
@newhoggy
https://github.com/haskell/actions/issues/70#issuecomment-927078557
----
Can't really say if this works as expected, hence the newly added tests. I tried to be as conservative as possible, so not changing default cabal config directory.

Expose ghcup binary to PATH on windows

---

images/linux/scripts/installers/nodejs.sh

Since the migration to npm 8 is finished now, there's no need for this piece of code any more. So let's get rid of it! 🎉

[Ubuntu] remove `--unsafe-perm` code for netlify-cli

---

images/macos/software-report/SoftwareReport.Generator.ps1

Bug fixing: software report.
The nested arrays with the `gcc` and` fortran` versions in the language and runtime list have been expanded by removing the commas in the array literal because otherwise they are treated as a single element.
Test reports: https://github.com/vsafonkin/test-repo/runs/4482460272?check_suite_focus=true
Probably, we have to do it for all array literals in software report generation.

[macOS] Fix software report: gcc and fortran versions

---

images/win/windows2022.json

Sometimes container feature is not enabled. The provisioner should wait it before invoking Install-Docker.ps1 script.
```
vhd: WARNING: A restart is required to enable the containers feature. Please restart your machine.
vhd:
vhd: Name                           Version          Source           Summary
vhd: ----                           -------          ------           -------
vhd: Docker                         20.10.7          DockerDefault    Contains Docker EE for use with Windows Server.
==> vhd: Start-Service : Failed to start service 'Docker Engine (docker)'
```.
https://github.com/actions/virtual-environments-internal/issues/3096

[Windows] Wait Containers installation feature

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Install-Vsix.ps1
images/win/toolsets/toolset-2022.json

This PR adds  extension "Installer projects" to Visual Studio 2022 on Windows-2022

[Windows] Add installer projects to VS on Windows-2022

---

images/linux/scripts/helpers/mysql-service-helper.sh
images/linux/scripts/installers/mysql.sh
images/linux/scripts/tests/Databases.Tests.ps1

The pull request restores the old `/etc/init.d/mysql` script on Ubuntu 20.04 to keep backward compatibility with the sysVinit files structure.
Oracle-provided deb packages do not have these files shipped as this only is the Canonical-specific policy they have been following since 2014 to make systemd migration as flawless as possible (the init script was taken from their repo and tested manually).

[Ubuntu] install mysql init script for sysVinit compatibility

---

images/linux/scripts/helpers/mysql-service-helper.sh

There were no plans to change shebang initially, as we wanted to keep a vanilla mysql init script taken from ubuntu (this script is only used for the mysqld service and not being called directly during images generation that is why we left it as it was).
As we now have a test which checks that the `/etc/init.d/mysql` start/stop procedure was successful let's fix the shebang to silence the linter and see what happens.

[Ubuntu] enable -e bash mode in mysql helper

---

images/win/toolsets/toolset-2022.json

Add the UWP C++ tools for ARM64 to the Visual Studio installation. These tools are present on windows-2019; this PR adds them to windows-2022.

[Windows] Add UWP VC++ ARM64 component

---

images/linux/scripts/installers/cleanup.sh

Some files are left after the image generation in the `/root/.cache` and can be safely deleted.
n\a

[Ubuntu] Cleanup /root/.cache directory

---

images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

The original discussion started [here](https://github.com/actions/python-versions/pull/128). zlib is quite popular and widely used compression/decompression library and lots of tools/utilities/language bindings rely on it, it is worth having zlib explicitly installed in our images to ease further development.

[macOS] install zlib

---

images/linux/scripts/installers/mysql.sh

In the images generation process mysql-0.27 is being installed first (and the packages dependency tree is saved in apt package index), then it is being overwritten with the deb packages in the `mysql.sh` script, which makes apt guess the dependency tree even though some mysql dependencies are not listed (apt simply remembers the dependency order, no matter for which version and supplies needed missing packages automatically).
This may lead to a random failure if a customer builds their own image and exclude a script that does install mysql beforehand the actual `mysql.sh` script. To prevent this the core dependencies must be listed explicitly in the installer.

[Ubuntu] list mysql-core dependencies explicitly

---

images/linux/scripts/base/snap.sh
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

Canonical has informed us that GitHub actions generates too much traffic on their snapd servers, investigation has reveled that we inherit snap from the Azure Ubuntu images where snapd auto refresh is enabled (default settings) which causes lots of traffic on the reimage by automatically pulling all possible updates (if any). There is no way to disable auto refresh effectively but unregister snapd or mask the snapd systemd service. The most elegant solution is to put auto refresh on 60 days hold (maximum is 90 now) and calculate the deadline date as the date of an image generation + 60 days.

[Ubuntu] put snapd auto refresh on hold

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1

The rust environment is not properly initialized that's why the software section is blank:
```
- Cargo 
- Rust 
- Rustdoc 
- Rustup 1.24.3
```
https://github.com/actions/virtual-environments-internal/issues/3138

[Windows] Initialize rust environment to get software report

---

images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

This pull request unblocks python3.10 generation by adding missing X libraries into the image. libxext and libxft are needed as dependencies of libtk (which in turn is being used on the python building and testing stages for the `tkinter` and `turtle` python modules).
For the software report I preserved the original libraries naming with the capital 'X'.

[macOS] install X libraries

---

images/linux/scripts/installers/java-tools.sh
images/linux/scripts/installers/php.sh

apt-fast is kind of hack on top of the normal apt to speed up downloading by using either axel or aria2 downloading manager.
It is currently used by only `php.sh` and `java-tools.sh` installers and rationale behind its usage these days is unclear (we are using fast enough mirrors not to use an additional layer for packages management).
I have discussed it with @miketimofeev and we have come to conclusion it might be removed. 
EDIT: lets just stop using it but keep installed

[Ubuntu] Do not use apt-fast

---

images/macos/provision/core/powershell.sh

Currently, we install `powershell` using brew, which [brings OpenSSL 3.0*](https://github.visualstudio.com/virtual-environments/_build/results?buildId=120506&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=7f6ff0d4-adc5-5557-eba3-0604338bbbf7#:~:text=Pouring%20openssl%403%2D%2D3.0.1.big_sur.bottle.tar.gz) in the process. To avoid such situation, we need to rework current approach of `powershell` installation.

[macOS] Rework PowerShell installation

---

README.md

Ubuntu image READMEs were renamed in https://github.com/actions/virtual-environments/commit/986530d6bb268502c6c29cf7d8c3b1b0b3095bbe (#4974), but these links to them were not updated resulting in broken links.
#4974

Updated broken links to Ubuntu READMEs.

---

images/win/scripts/SoftwareReport/SoftwareReport.Android.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Helpers.psm1

If any function doesn't exist or provide incorrect results the script won't stop and create a readme.
- Displays the error message and stops executing(ErrorActionPreference)
- Don't display the progress bar(ProgressPreference)
- NormalView: Consists of a description of the error and the name of the object involved in the error.
- Enable strict mode, PowerShell generates a terminating error when the content of an expression, script, or script block violates basic best-practice coding rules.
- Validate software with blank versions
- Validate blank rows in table
https://github.com/actions/virtual-environments-internal/issues/3128

[Windows] Stop SoftwareReport script if error

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/Tests/ChocoPackages.Tests.ps1
images/win/toolsets/toolset-2022.json

We haven't included Perl at the beginning but it seems we need to reconsider the decision given the fact that we are going to migrate windows-latest to win2022 soon.
https://github.com/actions/virtual-environments/issues/4804

[Windows] Add Perl to windows-2022

---

images/macos/provision/configuration/configure-machine.sh

VoiceOver is a screen reader system application that provides auditory descriptions of elements help you easily navigate your screen with keyboard or gestures.
This PR enables voiceover during the image generation by creating a special file (only works if SIP is disabled).
https://github.com/actions/virtual-environments/issues/4770

[macOS] Enable voiceover if SIP is disabled

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/Tests/Tools.Tests.ps1
images/win/windows2022.json

It turned out that Service Fabric SDK is available for windows-2022, just not mentioned in the official docs yet. This PR adds SF SDK installation and also Web Platform Installer installation as WPI is a recommended way to install SF SDK.
https://github.com/actions/virtual-environments/issues/4546

[Windows] Add Service Fabric SDK to windows 2022

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/helpers/Common.Helpers.psm1
images/linux/scripts/helpers/SoftwareReport.Helpers.psm1
images/linux/scripts/helpers/Tests.Helpers.psm1
images/linux/scripts/tests/Databases.Tests.ps1
images/linux/scripts/tests/Java.Tests.ps1

Provide more verbosity during software report generation:
- Add ValidateExitCode parameter(expect exit code is 0)
- NormalView: Consists of a description of the error and the name of the object involved in the error.
- Enable strict mode, PowerShell generates a terminating error when the content of an expression, script, or script block violates basic best-practice coding rules.
- Validate software with blank versions
- Validate blank rows in table
https://github.com/actions/virtual-environments-internal/issues/3132

[Ubuntu] Add verbosity during software report generation

---

images/linux/scripts/base/snap.sh

We change snapd settings during the images generation process but there is no guarantee that snapd daemon (and its unix socket) is alive by the time the `snapd.sh` script is being run as we do not manage the snapd systemd unit explicitly (it is provided by the azure images themselves). Prior snapd restart must do the trick and bring the daemon/unix socket back before changes are made.

[Ubuntu] restart snapd during images generation

---

images/macos/provision/core/rubygem.sh

The root cause of issues with `cocoapods` in software report is the updated version (`3.3.3`) of `RubyGems`. We need to downgrade it to `3.2.33` version until the issue is resolved.

[macOS] Downgrade RubyGems version to 3.2.33

---

images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

The following error can be observed in the logs:
```Provisioning with shell script: C:\agent\_work\6\s\images\linux/scripts/base/snap.sh
==> azure-arm: Failed to restart snapd.socket: Transaction for snapd.socket/restart is destructive (systemd-networkd.service has 'stop' job queued, but 'start' is included in transaction).
==> azure-arm: See system logs and 'systemctl status snapd.socket' for details.
```
Which means that the snapd restarting process is happening at the same time with the systemd-networkd stopping process which in turn causes systemd conflict, putting the `snap.sh` call above must mitigate the actual negative impact.

[Ubuntu] put snap.sh upper environment cleanup

---

images/macos/provision/configuration/configure-machine.sh

VoiceOver is a screen reader system application that provides auditory descriptions of elements help you easily navigate your screen with keyboard or gestures.
This PR extends the work of #4805 for enabling applescript control of voiceover by setting the required defaults for the key `SCREnableAppleScript` in `com.apple.VoiceOver4/default`.
Fixes #4770

[macOS] Enable voiceover applescript defaults

---

images/win/toolsets/toolset-2019.json

Adding following components to windows 2019:
- "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM"
- "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM64"

[Windows] Add VC v141 ATL ARM/64 components to windows 2019

---

images/macos/templates/macOS-11.pkr.hcl

We should pass  `build_id` variable as an argument to the ImageName parameter instead of `UUID=${build.PackerRunUUID}` value.

[macOS] Pass build_id as an argument to ImageName

---

images/linux/scripts/SoftwareReport/SoftwareReport.Java.psm1
images/linux/scripts/installers/java-tools.sh
images/linux/scripts/tests/Java.Tests.ps1
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

As Adoptium has finally [released](https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available) the deb packages we must add the Eclipse Temurin distribution into our images as it is highly desired successor of deprecated Adopt OpenJDK. The installer itself uses lots of ideas taken from the appropriate macOS java installation. As a result we have:
* `JAVA_HOME` (and default java symlinks) is is set to Eclipse Temurin 8
* `JAVA_HOME_8_X64` is set to Eclipse Temurin 8
* `JAVA_HOME_11_X64` is set to Eclipse Temurin 11
* `JAVA_HOME_12_X64` is set to Adopt OpenJDK 12 (the only version of adopt remaining in the environment, available only on Ubuntu 18.04)
* `JAVA_HOME_17_X64` is set to Eclipse Temurin 17
Apart from that:
- Adopt OpenJDK 12 calls have been hardcoded both in the …

[Ubuntu] Add Eclipse Temurin (Adoptium) to Java installer

---

images/linux/scripts/installers/configure-environment.sh

In some workflows, we can observe traffic to cdn.fwupd.org and motd.ubuntu.com. It's not related to security issue due to installed and enabled by default on Ubuntu Server 18.04/20.04.
1. motd.ubuntu.com - https://ubuntu.com/legal/motd [motd-news.timer]
> This legal notice tells you about the information we collect using MOTD — Message of the Day. “motd-news” is a package that makes a call periodically to Canonical servers to get updated news for support and informational purposes. An example of an MOTD is shown at the end of this notice. As part of sending the message information is also collected by Canonical as set out below. 
2. cdn.fwupd.org - Update the message of the day (MOTD) on device and metadata changes [fwupd-refresh.timer]
Disable motd updates:
-  /etc/default/motd-news
- …

[Ubuntu] Disable motd updates metadata

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/installers/dotnetcore-sdk.sh
images/linux/scripts/tests/DotnetSDK.Tests.ps1
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/win/scripts/Installers/Install-DotnetSDK.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/Tests/DotnetSDK.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

- Add support to add dotnet tools to the toolset.
- Add new section under dotnet.
- Add installer for dotnet tools.
- Add tests for dotnet tools.
- Add installed dotnet tools to software report.
- Closes #4818

Add install of dotnet tools

---

images/linux/toolsets/toolset-2004.json

Accidentally we switched java default version from 11 to 8 in [this](https://github.com/actions/virtual-environments/pull/4868/files) pull request, lets get it back as expected.

[Ubuntu] Switch java default back to 11 on 20.04

---

images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

This PR contains updates of Xcode to  13.2.1 on the macOS 11

[MacOS] Update Xcode to 13.2.1 on macOS 11

---

images/macos/provision/core/nvm.sh
images/macos/provision/core/powershell.sh
images/macos/provision/core/ruby.sh
images/macos/provision/core/stack.sh
images/macos/provision/core/swiftlint.sh
images/macos/templates/macOS-10.15.json
images/macos/templates/macOS-11.json
images/macos/templates/macOS-12.json

For unauthenticated requests, the rate limit allows for up to 60 requests per hour thus we sometimes face this limitation and the build fails on API requests. Authenticated requests have a 5000 limit but we need to use a token. If no token is provided the standard limit of 60 requests will be used.
https://github.com/actions/virtual-environments-internal/issues/3222

[macOS] Allow using GitHub PAT to enlarge api requests limit

---

images/win/windows2016.json

Wait For Windows Server 2016 Updates installation:
```
vhd: Describing Windows Updates
vhd:   [+] WindowsUpdateDone.txt should exist 4ms (2ms|2ms)
vhd:   [-] 2021-01 Update for Windows Server 2016 for x64-based Systems (KB4589210) 177ms (175ms|2ms)
vhd:    Expected collection 'Successful' to contain 'InProgress', but it was not found.
vhd:    at $Status | Should -BeIn $expect, C:\image\Tests\WindowsFeatures.Tests.ps1:78
vhd:    at <ScriptBlock>, C:\image\Tests\WindowsFeatures.Tests.ps1:78
vhd:   [-] 2022-01 Cumulative Update for .NET Framework 4.8 for Windows Server 2016 for x64 (KB5008877) 4ms (3ms|1ms)
vhd:    Expected collection 'Successful' to contain 'InProgress', but it was not found.
vhd:    at $Status | Should -BeIn $expect, C:\image\Tests\WindowsFeatures.Tests.ps1:78
vhd:    at …
```

[Windows] Wait for Windows Updates

---

images/win/scripts/Tests/Tools.Tests.ps1

It was forgotten to skip the test for windows 2016 in the https://github.com/actions/virtual-environments/pull/4893
https://github.com/actions/virtual-environments/issues/4881

[Windows] Skip oledb test for windows2016

---

images/macos/provision/core/commonutils.sh
images/macos/provision/core/python.sh

tcl/tk installation paths are different on macOS 11 and 10.15, given that our hosted toolcache python binaries are compiled on 10.15 and then are used on 11 customers are unable to import the python tk module as python is looking for 10.15 specific path being run on 11.
We have discussed the long term solution with @dmitry-shibanov and @MaksimZhukov and decided to apply symlinks as a temporary solution.

[macOS] create tcl/tk symlinks for cached python

---

images/macos/provision/core/swiftlint.sh

There is an issue with swiftlint 0.46.1 installer that should be fixed in the next swiftlint version https://github.com/realm/SwiftLint/issues/3815. Hardcoding 0.46.0 for now
https://github.com/actions/virtual-environments-internal/issues/3263

[macOS] Hardcode swiftlint 0.46.0

---

images/macos/provision/core/swiftlint.sh

Reverts actions/virtual-environments#4953 as the package is fixed in the new SwiftLint release https://github.com/realm/SwiftLint/releases/tag/0.46.2

Revert "[macOS] Hardcode swiftlint 0.46.0"

---

images/macos/provision/core/swiftlint.sh

There is an issue with the .pkg file that is not yet fixed https://github.com/realm/SwiftLint/issues/3815#issuecomment-1024019219
It's safer to use the portable archive distribution as it contains only one binary and the license file.
https://github.com/actions/virtual-environments-internal/issues/3263

[macOS] Change swiftlint installation method to portable distribution

---

images/macos/provision/core/miniconda.sh

Making miniconda accessible by anyone so customers do not hit permission denied error if no setup-miniconda used (the action itself also chmods the installation directory recursively).

[macOS] change miniconda directory permissions

---

images/macos/provision/core/miniconda.sh

the order of mode calling is wrong now.

[macOS] fix operands order on miniconda

---

images/win/toolsets/toolset-2022.json

Add Visual Studio 2022  `Microsoft.VisualStudio.Component.DslTools` component on Windows Server 2022.
https://github.com/actions/virtual-environments/issues/4946

[Windows] Add DslTools Component

---

images/win/scripts/Tests/ChocoPackages.Tests.ps1
images/win/toolsets/toolset-2022.json

Given the high demand for InnoSetup on windows-2022 image and tool popularity we decided to add it to the image.
https://github.com/actions/virtual-environments/issues/5006

[Windows] Add InnoSetup to windows-2022

---

images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

While the workaround described in the attached issue works perfectly well, the actual symlinks creation happens much earlier than we have the Tcl/Tk package installed, as a result we are having broken symlinks created, to avoid this we need to install the tcl/tk package right in the place of the symlinks creation.

[macOS] install tcl-tk explicitly

---

images/macos/provision/core/nvm.sh
images/macos/provision/core/ruby.sh

This is an addition to https://github.com/actions/virtual-environments/pull/4923 to make auth optional for Ruby and Nvm installation scripts, all the other github API calls are covered with the helper.
https://github.com/actions/virtual-environments-internal/issues/3139

[macOS] Make auth optional for nvm and ruby scripts

---

images/macos/provision/configuration/configure-tccdb-macos11.sh

Currently, Microsoft Defender for macOS can't be installed on Hosted Images because of multiple modal approval windows that will block installation.
We would like to pre-approve permission access for `com.microsoft.wdav` app.
This PR adds a few more entries to `/Library/Application Support/com.apple.TCC/TCC.db` file via sqlite3:
```
kTCCServiceSystemPolicyAllFiles|com.microsoft.wdav.epsext|0|2|4|1||||UNUSED|||1643970979
kTCCServiceSystemPolicyAllFiles|com.microsoft.wdav|0|2|4|1|NULL|NULL|NULL|'UNUSED'|NULL|0|1643970979
```
```
sqlite > PRAGMA table_info(access)
0|service|TEXT|1||1
1|client|TEXT|1||2
2|client_type|INTEGER|1||3
3|auth_value|INTEGER|1||0
4|auth_reason|INTEGER|1||0
5|auth_version|INTEGER|1||0
6|csreq|BLOB|0||0
7|policy_id|INTEGER|0||0 …
```

[macOS] Update TCC.db to bypass Microsoft Defender installation

---

images/macos/templates/macOS-11.pkr.hcl

In scope of the https://github.com/actions/virtual-environments/pull/4959 PR we added GraalVM also we should add this script into the Anka template.

[macOS] Add GraalVM into Anka template

---

images/win/scripts/Installers/Install-VS.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1
images/win/scripts/Tests/VisualStudio.Tests.ps1

This PR adds Visual Studio component "Windows10SDK.17763" to Windows 2022 image.
https://github.com/actions/virtual-environments/issues/4825

[Windows] Add Windows10SDK.17763 to Win22

---

images/macos/provision/configuration/configure-machine.sh
images/macos/tests/System.Tests.ps1

Add [Developer ID - G2 (Expiring 09/17/2031 00:00:00 UTC)](https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer) certificate to the macOS images. 
https://github.com/actions/virtual-environments/issues/5037

[macOS] Add DeveloperIDG2CA.cer certificate

---

images/macos/provision/core/powershell.sh
images/macos/provision/core/stack.sh
images/macos/provision/core/swiftlint.sh
images/macos/provision/utils/utils.sh

Let's combine two variables (`REPO_NAME` and `REPO_OWNER`) into one (`REPO_ORG`) as it was done [for helper on Ubuntu](https://github.com/actions/virtual-environments/pull/4947/commits/5da9040f295b1e391a9d07ae37d94c3357b6416b).

[macOS] Update get_github_package_download_url helper

---

images/macos/provision/core/open_windows_check.sh
images/macos/templates/macOS-10.15.json
images/macos/templates/macOS-11.json
images/macos/templates/macOS-11.pkr.hcl
images/macos/templates/macOS-12.json
images/macos/tests/System.Tests.ps1

Sometimes we forget to close some windows during macOS updates on the images. In scope of this PR we have implemented a pester test that check if there are any open windows on the image at the beginning and in the end of the image generation.
https://github.com/actions/virtual-environments-internal/issues/3348

[macOS] Add test to check opened windows

---

images/win/toolsets/toolset-2022.json

Adds missing ARM/ARM64 libraries to windows-2022 image.
Fixes #5056

[Windows] Add ARM/ARM64 libraries to windows-2022 (#5056)

---

images/win/scripts/Installers/Install-Edge.ps1

Webdriver win64 for version 98.0.1108.51 doesn't exist thus all windows builds are broken. Temporary hardcode98.0.1108.50 installation.
https://github.com/actions/virtual-environments/issues/5066

[Windows] Set condition to install 98.0.1108.50 instead of 98.0.1108.51

---

images.CI/macos/move-vm.ps1

It turned out that builds didn't fail even though there was an error moving the VM to the cold storage. We need to add exit 1 to each error case.
n\a

[macOS] Add exit 1 to each error case in move-vm script

---

images/win/scripts/Installers/Install-AndroidSDK.ps1
images/win/scripts/Tests/Android.Tests.ps1

We do not install the rc version of build-tools thus we should not install the correspondent platform preview versions, which names start with a letter instead of a number. For example, the `android-Tiramisu` platform will be `android-33` once the version is released.
We have previously done the same for macOS https://github.com/actions/virtual-environments/pull/4372
https://github.com/actions/virtual-environments-internal/issues/3410

[Windows] Skip preview versions of android sdk platforms installation

---

images/macos/provision/core/open_windows_check.sh

Run osascript with retry to bypass -600 error.
```
==> veertu-anka-vm-clone.template: Provisioning with shell script: ./provision/core/open_windows_check.sh
==> veertu-anka-vm-clone.template: 40:52: execution error: Application isn’t running. (-600)
veertu-anka-vm-clone.template: Found opened window:
veertu-anka-vm-clone.template: [Warning] window Notification Center of application process NotificationCenter
```
https://github.com/actions/virtual-environments-internal/issues/3393

[macOS] Run osascript with retry

---

helpers/CreateAzureVMFromPackerTemplate.ps1

Error calling variables into last step of Azure VM creation. 
ResourceGroupName: The term 'ResourceGroupName' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Bug fixing
We get an error into the last step of creation of a VM Creation in Azure. Not retriving variables values because calls are incorrect. We should use $ResourceGroupName or ${ResourceGroupName} or $($ResourceGroupName) instead bad calling $(ResourceGroupName)

FIX: Write-Host Incorrect calls to variables.

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/macos/software-report/SoftwareReport.Common.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Helpers.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

We output not the full version in the image readme's that can confuse customers.
Also unifying function "Get-GitVersion" on all OS.

[All OS] Output full version of git to software report

---

images/win/scripts/Tests/Haskell.Tests.ps1

```
2022-02-22T00:34:39.3388641Z  vhd:   [-] cabal config was modified and exists 166ms (164ms|2ms)
2022-02-22T00:34:39.3399886Z  vhd:    Expected path 'C:\cabal' to exist, but it did not exist.
2022-02-22T00:34:39.3400920Z  vhd:    at $env:CABAL_DIR | Should -Exist, C:\image\Tests\Haskell.Tests.ps1:53
2022-02-22T00:34:39.3405661Z  vhd:    at <ScriptBlock>, C:\image\Tests\Haskell.Tests.ps1:53
```
https://gitlab.haskell.org/haskell/ghcup-hs/-/commit/2c583bcae9e333693b9bd8fc353bb0dcb2af71df - Fix NoAdjustCabalConfig on windows
Fix:
- Add test to check cabal folder
https://github.com/actions/virtual-environments/issues/5119

[Windows] Update cabal pester test

---

images/macos/provision/bootstrap-provisioner/change_password
images/macos/provision/bootstrap-provisioner/kcpassword.py
images/macos/provision/configuration/autologin.sh
images/macos/provision/configuration/configure-hostname.sh
images/macos/templates/macOS-10.15.json
images/macos/templates/macOS-11.json
images/macos/templates/macOS-11.pkr.hcl
images/macos/templates/macOS-12.json

https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes
Fix:
- Install Xcode Command Line Developer Tools(python3 is a part of the package)
- Migrating python 2 scripts to python 3
https://github.com/actions/virtual-environments/issues/5101

[macOS] Migrating python 2 scripts to python 3

---

images/win/windows2022.json

It looks like windows-2022 images are stuck sometimes on the Installing modules step for quite a long time (> 5min) during the first boot. Using `sysprep mode:VM` seems to solve the issue https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep-command-line-options?view=windows-11#modevm
https://github.com/actions/virtual-environments-internal/issues/3403

[Windows] Use mode:vm in sysprep to skip modules installation during the first boot

---

images/macos/provision/configuration/configure-machine.sh
images/macos/provision/configuration/finalize-vm.sh
images/macos/provision/core/python.sh
images/macos/provision/utils/utils.sh

During image generation we install python 2.7 package using installer due to use `anka run` transport after installing we get an open Finder window.
```
veertu-anka-vm-clone.template:   [-] Opened windows not found 7.36s (7.35s|2ms)
veertu-anka-vm-clone.template:    Expected $null or empty, but got window Python 2.7 of application process Finder.
veertu-anka-vm-clone.template:    at $openWindows.Split(",").Trim() | Where-Object { $_ -notmatch "NotificationCenter" } | Should -BeNullOrEmpty, /Users/<sensitive>/image-generation/tests/System.Tests.ps1:54
veertu-anka-vm-clone.template:    at <ScriptBlock>, /Users/<sensitive>/image-generation/tests/System.Tests.ps1:54
```
https://github.com/actions/virtual-environments-internal/issues/3412

[macOS] Anka close Python 2.7 window

---

images/linux/scripts/installers/java-tools.sh

The 'actions/setup-java' task can't resolve a java version from the toolcache if semver(release file, property SEMANTIC_VERSION) of java is not valid. For e.g.:
semver can only consist of three elements but in our case it contains  four elements - `11.0.14.1+1`  .
https://github.com/actions/virtual-environments-internal/issues/3434

[Ubuntu] Convert non valid java semver

---

images/win/scripts/Installers/Install-Rust.ps1

Currently when rust is installed on windows, it only includes the default target (`x86_64-pc-windows-msvc`). This change adds the equivalent i686 target so that 32-bit binaries may be built out of the box. Unfortunately 32-bit windows is still extremely common, so many (most?) projects that want to test and ship windows artifacts will need both 32-bit and 64-bit support.

[windows] When installing Rust, add the i686 target to enable building 32-bit binaries

---

images.CI/macos/anka/Service.Helpers.psm1
images/macos/provision/bootstrap-provisioner/setAutoLogin.sh

In scope of this https://github.com/actions/virtual-environments/pull/5115 we have migrated some scripts from python 2 -> 3, but python is part of the xcode tools which are not available on the clean image, that's why we decided to add bash script.
Fix
- Add setup autologin bash script
https://github.com/actions/virtual-environments-internal/issues/3449

[Anka] Add setup autologin bash script

---

images/win/scripts/Installers/Install-KubernetesTools.ps1

This fixes a bug that was causing the kubernetes tools download to fail since the match was finding two lines (one with chksum, the other with binaries).

Fix match regex in Kubernetes tools downloads.

---

images/linux/Ubuntu2004-Readme.md

This reverts commit 12fa229b4a3eebb871ed90ef2c45c897a4fd728d. The image was rolled back due to error reports.

Revert "Updating readme file for ubuntu20 version 20220306.1"

---

images/macos/provision/bootstrap-provisioner/kcpassword.py

In scope of https://github.com/actions/virtual-environments/pull/5115, we switched `kcpassword` script to use Python 3 instead of Python 2 because Python 2 was removed from macOS 12.
After that, kcpassword started to produce incorrect results. See https://github.com/actions/virtual-environments/issues/5231 for details.
`chr` function was changed in Python 3 and don't produce char by number anymore.
More details can be found in https://python-future.org/compatible_idioms.html#chr
- I have removed converting to string completely and convert to byte array instead
- Writing byte array directly to file
I have compared all test cases reported in https://github.com/actions/virtual-environments/issues/5231 and after my changes script product correct result for both Python 2 & 3

[macOS] Fix kcpassword compatibility issue with Python 3

---

images/win/scripts/Installers/Install-Chrome.ps1

Instead of the Google Chrome online installer, this change, uses the standalone (offline) version.
- Fixes #5203

[Windows] Use Chrome standalone installer (#5203)

---

images/macos/macos-12-Readme.md

Currently, macOS 12 is available in private preview. Let's put its docs to repo

Add docs for macOS 12 private preview

---

images/win/scripts/Installers/Install-AliyunCli.ps1

The latest alyuin-cli release is broken (the upstream has only released the source code but no appropriate versions for Windows/Linux), given that we were determining the version to download from the archive name, it is now all broken.
The most simple way to bypass it is to hardcode the working version's url straight in the installer for the time being.

[Windows] hardcode alyuin-cli version

---

images/linux/scripts/installers/google-chrome.sh

We have two issues related to chromium:
1. Base Position which is four digits (1060) for the latest version of Chrome 99.0.4844.82 instead of the usual six — https://omahaproxy.appspot.com/deps.json?version=99.0.4844.82
To fix that the previous release can be taken — 961656
2. Sometimes google lists hash instead of revision number and it breaks the logic of the script. We need to apply additional filtration to fix that.
https://github.com/actions/virtual-environments/issues/5256

[Ubuntu] Fix issues with chromium release version and apply pattern to the release version

---

images/win/scripts/Installers/Install-Choco.ps1

Choco does not ship CPack anymore. `Remove-Item` fails with the latest Choco release:
```
Remove-Item : Cannot find path 'C:\ProgramData\chocolatey\bin\cpack.exe' because it does not exist.
```
- https://github.com/chocolatey/choco/issues/89

[Windows] CPack command alias is not part of Choco anymore

---

images/win/scripts/Installers/Install-LLVM.ps1
images/win/toolsets/toolset-2022.json
images/win/windows2022.json

Currently, llvm version from the toolset is ignored because we should pass the params separately.
This PR also sticks windows 2022 llvm to version 13.
https://github.com/actions/virtual-environments/issues/5285

Install llvm version correctly

---

images/macos/provision/bootstrap-provisioner/setAutoLogin.sh

Fix /etc/kcpasswd generation script on Bash.
```
Example 1
~$ bash ./setAutoLogin.sh test "wVI=" | base64
Ct8bHtK83eqjuR8=
Example 2
~$ bash ./setAutoLogin.sh test "}_R#" | base64
ANYAANK83eqjuR8=
Example 3
~$ bash ./setAutoLogin.sh test 0000000000 | base64
TbliE+KM7dqTiR8=
Example 4
~$ bash ./setAutoLogin.sh test "111111111111" | base64
TLhjEuON7NuSiC5MiVIj0rzd6qO5Hw==
```
https://github.com/actions/virtual-environments/issues/5231

Fix setAutoLogin.sh script

---

images/macos/provision/bootstrap-provisioner/kcpassword.py
images/macos/provision/bootstrap-provisioner/setAutoLogin.sh

If the password is less than 11 characters, the current  script pads it to 11 bytes, XOR'ed and it works fine. With exactly 11 bytes, no null is added and this caused the autologin to fail.
E.g.:
_Current password: a1234567890_
https://github.com/actions/virtual-environments/issues/5231

[macOS] fix kcpassword issue for passwords exactly 11 bytes long

---

images/win/scripts/Installers/Install-CodeQLBundle.ps1

We're now using the `v2` branch as the main release branch for CodeQL, so that's the best place to get an up to date bundle version from to put into the toolcache.

Use `v2` branch to get CodeQL bundle

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1

The composer version output format has been changed, e.g. from `Composer version 2.2.9 2022-03-15 22:13:37` to `Composer 2.3.1 2022-03-30 15:41:28`.
https://github.com/actions/virtual-environments/discussions/5310

[Windows] Fix composer output version

---

images/win/toolsets/toolset-2022.json

There was a bug in the mysql preventing us from updating the version from 8.0.26 — https://bugs.mysql.com/bug.php?id=105288
The bug is now fixed and we can install the latest version.
https://github.com/actions/virtual-environments/issues/4799

[Windows] Install latest 8.0.* mysql version for windows 2022

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/installers/php.sh
images/linux/scripts/tests/Common.Tests.ps1

https://github.com/composer/composer/issues/10340 - **Composer 2.3 increased the required PHP version to >=7.2.5 and thus stop supporting PHP 5.3.2 - 7.2.4.**
We should use composer LTS version for Ubuntu Server 18.
https://github.com/actions/virtual-environments-internal/issues/3521
https://github.com/actions/virtual-environments-internal/issues/3520

[Ubuntu] Tight composer version to 2.2.9 for Ubuntu Server 18

---

.github/ISSUE_TEMPLATE/announcement.yml
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/tool-request.yml

Windows-2016 is deprecated so we can remove it from the templates. macOS-12 is in private preview and more people will have access soon so we have to add it to the templates.
n\a

Add macOS-12, remove win-16 in the issue templates

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

The output format compose version has been changed: https://github.com/composer/composer/commit/03b7882ac231d19e9373ed33a8e71d7bb5b280c1, [which is a custom format](https://github.com/composer/composer/blob/03b7882ac231d19e9373ed33a8e71d7bb5b280c1/src/Composer/Console/Application.php#L565-L570).

[Ubuntu] Fix composer version

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1

Bug fixing
Although https://github.com/actions/virtual-environments/commit/137c29497d4b02e00551c45bc94e469bc90f12c0 fixed the previous issue, they've done something: 
Previously: 
- They used [parent::getLongVersion](https://github.com/composer/composer/blob/af3e67e7458f4da460ecb394e724413e78d2169e/src/Composer/Console/Application.php#L570), which is: [`sprintf('%s <info>%s</info>', $this->getName(), $this->getVersion())`](https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Console/Application.php#L451), which indeed yields "Composer 2.3.3"
Now:
- They committed https://github.com/composer/composer/commit/03b7882ac231d19e9373ed33a8e71d7bb5b280c1, [which is a custom format](https://github.com/composer/composer/blob/03b7882ac231d19e9373ed33a8e71d7bb5b280c1/src/Composer/Console/ …

Fixed Composer "empty" version

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Add version output in docs file:
- automake
- autoconf
- litbool
https://github.com/actions/virtual-environments/issues/5360

[Ubuntu] Add automake autoconf libtool output version

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Update default go version to 1.17 since it is most popular
#5208

Update default Go version to 1.16 or higher

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

Currently we use openssl version which doesn't provide info about security updates:
Ubuntu Server 20.04 - `OpenSSL 1.1.1f 31 Mar 2020`  -> `OpenSSL 1.1.1f-1ubuntu2.12` - https://launchpad.net/ubuntu/+source/openssl/1.1.1f-1ubuntu2.12
Ubuntu Server 18.04 - `OpenSSL 1.1.1 11 Sep 2018`  -> `OpenSSL 1.1.1-1ubuntu2.1~18.04.15` https://launchpad.net/ubuntu/+source/openssl/1.1.1f-1ubuntu2.12
https://github.com/actions/virtual-environments-internal/issues/3569

[Ubuntu] Use OpenSSL package version in output

---

helpers/GenerateResourcesAndImage.ps1

If resource group name is long then the script will generate storage account name that's longer than 24 characters.
This change will limit the generated storageaccountname to 24 characters.
[Document about limits](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#:~:text=Storage%20account%20names%20must%20be,must%20be%20unique%20within%20Azure.)

Limit storageaccount name length to 24 characters

---

images/linux/scripts/installers/php.sh
images/linux/scripts/tests/Common.Tests.ps1

In scope of this https://github.com/actions/virtual-environments/pull/5390 PR we have removed  php-7.1 which is unsupported by php composer 2.3 and above.

[Ubuntu] Remove hard-coded composer version

---

images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json

- Install Az module latest version for macOS 10.15, 11 like we do for macOS-12
https://github.com/actions/virtual-environments-internal/issues/3531

[macOS] Install Az module latest version

---

images/linux/scripts/installers/google-chrome.sh

Implement a logic to retrieve the previous Chromium release if the revision that corresponds to the latest Chrome version matches an old Chromium release
https://github.com/actions/virtual-environments/issues/5256

[Ubuntu] Pull previous version of Chromium if revision is 4 digits long

---

images/macos/provision/core/git.sh

Due to the issue with the https://github.com/actions/checkout we have to temporarily stick git version to 2.35.1 https://github.com/actions/checkout/issues/760
https://github.com/actions/virtual-environments-internal/issues/3617

[macOS] Install git 2.35.1 for macOS

---

images/win/scripts/Installers/Install-Git.ps1

Due to the issue with the https://github.com/actions/checkout we have to temporarily stick git version to 2.35.1 https://github.com/actions/checkout/issues/760
https://github.com/actions/virtual-environments-internal/issues/3617

[Windows] Stick to git 2.35.1

---

images/linux/scripts/installers/git.sh

Due to the recent security changes in git actions\checkout task is experiencing issues https://github.com/actions/checkout/issues/760. The workaround is to set `git config --global --add safe.directory "*"` setting. This PR adds this setting in `/etc/skel` as the user is different between image generation VM and VM in production.
https://github.com/actions/virtual-environments-internal/issues/3617

[Ubuntu] Add safe directory setting to git config

---

images/macos/templates/macOS-10.15.json
images/macos/templates/macOS-11.json
images/macos/templates/macOS-11.pkr.hcl
images/macos/templates/macOS-12.json

There is a rare bug when installing homebrew on macOS Monterey — when calling `if [[ -z "${HOMEBREW_ON_LINUX-}" ]] && ! output="$(/usr/bin/xcrun clang 2>&1)" && [[ "${output}" == *"license"* ]]
` from the https://github.com/Homebrew/install/blob/master/install.sh script macOS gatekeeper is stuck verifying clang.
This PR moves homebrew installation right after Xcode tools one, which seems to help. Also, we don't need sudo to install the Xcode command-line tools.
[[macOS] Investigate an opened window on Monterey after the image update #3469](https://github.com/actions/virtual-environments-internal/issues/3469)

[macOS] Move homebrew installation after xcode_clt

---

images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

R version output changed from 
```
R scripting front-end version 4.1.3 (2022-03-10)
```
to
```
Rscript (R) version 4.2.0 (2022-04-22)
```
Thus we need to change the software report according to the changes.
https://github.com/actions/virtual-environments/issues/5435

[Windows] Change pattern for Rscript output

---

images/linux/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1
images/linux/toolsets/toolset-2204.json

As we now have python generated for 22.04 lets add it back to the toolcache.

[Ubuntu] Add python toolcache to 22.04

---

images.CI/linux-and-win/create-release.ps1

We should set up Tls12 as the default one to prevent an error  - `The underlying connection was closed: An unexpected error occurred on a send.`

[CI] Set TLS12

---

images/linux/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1
images/linux/toolsets/toolset-2204.json

I am in touch with @eregon and he has generated 3.1 for 22.04, 2.7/3.0 is pending as there is strong openssl-1.x dependency.

[Ubuntu] Add Ruby 3.1 to 22.04 toolcache

---

.github/ISSUE_TEMPLATE/announcement.yml
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/tool-request.yml

We need to add Ubuntu22 as the image is now available in GitHub.
n\a

Add ubuntu 22 to issue templates

---

images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/BasicTools.Tests.ps1
images/macos/toolsets/toolset-12.json

SwiftFormat is a code library and command-line tool for reformatting Swift code on macOS or Linux.
https://github.com/actions/virtual-environments/issues/5494

[macOS] Add SwiftFormat for macOS 12

---

images/linux/scripts/installers/powershellcore.sh

Could not download http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
https://github.com/actions/virtual-environments-internal/issues/3696

[Ubuntu] Update libssl for Ubuntu22

---

images/win/scripts/Installers/Install-JavaTools.ps1

Unable to download [cobertura-2.1.1-bin.zip](https://downloads.sourceforge.net/project/cobertura/cobertura/2.1.1/cobertura-2.1.1-bin.zip) archive due to broken link.
https://github.com/actions/virtual-environments-internal/issues/3701

[Windows] Update cobertura link

---

images/win/scripts/Installers/Install-Docker.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/win/scripts/Tests/Docker.Tests.ps1

[Announcing Compose V2 General Availability](https://www.docker.com/blog/announcing-compose-v2-general-availability/#:~:text=April%2026%2C%202022%20marks%20the,developer%20default%20on%20Docker%20Desktop.)
**When is Compose V2 GA and what does it mean?**
_April 26, 2022 marks the GA of Docker Compose V2. Starting today, Compose V2 is the standard across all documentation, and Compose V2 will become the developer default on Docker Desktop._
**What’ll happen to Compose V1?**
_We’ve now marked Compose V1 as deprecated. Only high-priority security patches and critical bug fixes_
How to use?
v1:
```
PS > docker-compose version --short
1.29.2
```
v2:
```
PS > docker compose version --short
2.5.0
```
https://github.com/actions/virtual-environments/issues/4657

[Windows] Add docker-compose v2

---

helpers/GenerateResourcesAndImage.ps1

We should remove ADServicePrincipal and ADApplication principals if `AzureClientId` is not set after the script completed.
https://github.com/actions/virtual-environments/issues/5472

[Generation] Cleanup AD principal resources

---

images/linux/scripts/installers/git.sh
images/macos/provision/configuration/configure-ssh.sh
images/win/scripts/Installers/Install-Git.ps1

GitHub has `ecdsa` and `ed25519` host keys, they should be present in the known hosts as well:
- https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
The new keys have been usable since Nov 16, 2021:
- https://github.blog/2021-09-01-improving-git-protocol-security-github/
n/a

Add `ecdsa` & `ed25519` GitHub host keys

---

images/linux/scripts/installers/preimagedata.sh

Previously we have to add new ubuntu versions manually, which is not convenient and produces extra code. This PR moves hardcoded parts to variables thus we don't need to take care of this file when a new Ubuntu version is released.
https://github.com/actions/virtual-environments-internal/issues/3760

[Ubuntu] Make software and release URLs using variables instead of hardcode

---

docs/create-image-and-azure-resources.md
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json
images/linux/ubuntu2204.pkr.hcl
images/win/windows2016.json
images/win/windows2019.json
images/win/windows2022.json

We have to be able to set `client_secret` or `client_cert_path` during image generation as a packer option to authenticate in Azure with using a service principal - https://www.packer.io/plugins/builders/azure/arm
https://github.com/actions/virtual-environments-internal/issues/3762

[Packer] Add client_cert_path option

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/installers/containers.sh
images/linux/scripts/tests/Tools.Tests.ps1
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json
images/linux/ubuntu2204.pkr.hcl

Given that OpenSuse is not going to provide its repo to host podman and co. anymore lets remove these packages from Ubuntu  older than 22.04

[Ubuntu] Rework podman and tools installation

---

helpers/GenerateResourcesAndImage.ps1

Template is not in the json format anymore.

fix Ubuntu 22.04 template extension

---

images/linux/scripts/installers/packer.sh
images/linux/scripts/installers/terraform.sh

Changing the legacy API endpoint URL to the new endpoint that was announced recently:
ref. https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api
```sh
curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version
```
```sh
curl -s https://api.releases.hashicorp.com/v1/releases/terraform/latest | jq -r .version
```

[Ubuntu] Use new Hashicorp Releases API

---

helpers/GenerateResourcesAndImage.ps1
images/linux/ubuntu2204.pkr.hcl

If we run `GenerateResourcesAndImage` function we are getting an error message `Inappropriate value for attribute "allowed_inbound_ip_addresses"`.
https://github.com/actions/virtual-environments/issues/5593

[ImageGen] Fix allowed_inbound_ip_addresses error

---

images/macos/helpers/Common.Helpers.psm1
images/macos/provision/core/commonutils.sh
images/macos/provision/utils/confirm-identified-developers.scpt
images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/templates/macOS-12.json
images/macos/tests/BasicTools.Tests.ps1
images/macos/tests/Common.Tests.ps1
images/macos/toolsets/toolset-12.json

Previously we tried to add VirtualBox to macOS-11 here https://github.com/actions/virtual-environments/pull/4010 but faced an issue related to video driver conflicts and lose ability to change screen resolution.
It turned out that macOS-12 doesn't have this issue and screen resolution can be changed without any issues even though Big Sur still suffers from the same issue even on the new VirtualBox version.
https://github.com/actions/virtual-environments-internal/issues/2672

[macOS] Add virtualbox to macOS-12

---

images/linux/toolsets/toolset-2204.json

According to our [oftware guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy) we have to support 3 latest versions of Clang, which are 12, 13 and 14 for Ubuntu22.
https://github.com/actions/virtual-environments/issues/5608

[Ubuntu] Add clang 13&14 instead of 10&11, make 14 default for Ubuntu22

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/tests/Java.Tests.ps1
images/linux/ubuntu2204.pkr.hcl

Eclipse Temurin Java is now available for Ubuntu 22 so we can add java-tools installation to the image.
https://github.com/actions/virtual-environments/issues/5490

[Ubuntu] Add java tools installation to Ubuntu22

---

images/macos/toolsets/toolset-11.json

Looks like we forgot about it. Big Sur has 13.2 as well

[macOS] deprecate xcode 13.2 on Big Sur

---

helpers/GenerateResourcesAndImage.ps1

Fixes #5643 
Fixes the following error when running `GenerateResourcesAndImage` on Windows:
```
invalid value "$" for flag -on-error: expected one of ["cleanup" "abort" "ask" "run-cleanup-provisioner"]
```
Tested the fix locally.

Fix "invalid value $ for flag -on-error"

---

images/linux/scripts/installers/swift.sh
images/linux/scripts/tests/Common.Tests.ps1

This change allows SourceKitten-based tools (eg SwiftLint, Sourcery) to work out of the box on the ubuntu images.
[SourceKitten](https://github.com/jpsim/SourceKitten), a popular Swift library for interacting with SourceKit, needs to know (or be told) the location of the sourcekitd framework. SourceKitten is somewhat [ubiquitous](https://github.com/jpsim/SourceKitten#projects-built-with-sourcekitten); most Swift projects I've seen or worked on used SourceKitten in some way.
On macOS, the sourcekit framework is baked-in to the Xcode toolchain(s) and therefore its location is generally known. On Linux, the location of the sourcekit framework is wherever swift is installed, which is unknown to libraries like SourceKitten.
SourceKitten searches for the sourcekit framework in [a few …

[Ubuntu] add out-of-the-box SourceKitten support

---

images/linux/scripts/installers/android.sh
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json
images/linux/ubuntu2204.pkr.hcl

Remove Android cmdline-tools and try to parse latest version from google repository.
https://github.com/actions/virtual-environments-internal/issues/3784

[Ubuntu] Install latest Android cmdline-tools

---

images/macos/provision/core/android-toolsets.sh
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

Remove Android cmdline-tools and try to parse latest version from google repository.
https://github.com/actions/virtual-environments-internal/issues/3784

[macOS] Install latest Android cmdline-tools

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

Fix PHP8.0.x version in software report.
In version 8.0.19 version output changed to 1:8.0.19. In previous version it was 8.0.18, for example.
https://github.com/actions/virtual-environments-internal/issues/3806

Fix PHP8.0.x version in software report

---

images/linux/scripts/installers/java-tools.sh

We shouldn't add adoptopenjdk ppa to Ubuntu Server 22.04 because there are no packages for one:
```
azure-arm.build_vhd: Err:7 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb jammy Release
azure-arm.build_vhd:   404   [IP: 34.139.10.89 443]
```
https://github.com/actions/virtual-environments/issues/5656

[Ubuntu] Do not add adoptopenjdk ppa to Ubuntu Server 22.04

---

images/linux/scripts/installers/aws.sh

In aws cli v1 1.25.0 release has been dropped support for Python 3.6. We are planning to downgrade aws cli v1 from 1.25.0 to 1.24.10 version and migrate to aws cli v2 for Ubuntu Server 18.04 within a short time.
https://github.com/actions/virtual-environments-internal/issues/3807

[Ubuntu] Downgrade aws cli v1 to 1.24.10

---

.github/ISSUE_TEMPLATE/announcement.yml
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/tool-request.yml

- It is useful to have the platform filed in issue templates as sometimes there is an action available for GH Actions but no alternatives from the Azure DevOps side or the bug occurs on only one platform.
- There is no validation option for checkboxes so it can be removed.
- Some fields are usually ignored so let's set validation on them as well
n\a

Rework issue templates, add platform field, rework some points

---

images/macos/toolsets/toolset-12.json

Xcode 13.4.1 has been released https://developer.apple.com/news/releases/?id=06022022a
https://github.com/actions/virtual-environments-internal/issues/3829

[macOS] Add xcode 13.4.1 to macOS12 image

---

images/linux/scripts/installers/postgresql.sh

[Ubuntu] Remove apt-key from postgresql installer

---

images/linux/scripts/installers/r.sh

Do not use `apt-key` as this is deprecated

[Ubuntu] Remove apt-key from rlang install script

---

images/linux/scripts/installers/java-tools.sh

As `apt-key` is deprecated, installing gpg keyrings manually is the best option here.

[Ubuntu] install Temurin gpg key manually on 22.04

---

images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/templates/macOS-12.json
images/macos/tests/Common.Tests.ps1

- Install miniconda to macOS 12 as we do for macOS 10.15 and macOS 11
https://github.com/actions/virtual-environments/issues/5623

[macOS] Add miniconda to macOS 12

---

images/linux/scripts/installers/google-cloud-sdk.sh

[Ubuntu] Remove apt-key from GCP installer

---

images/macos/software-report/SoftwareReport.Generator.ps1

We have added VS for mac 2022 recently keeping VS 2019 on the images as well. However, it is not possible to use VS2019 directly without renaming the app. This PR adds a note on how to do that.
https://github.com/actions/virtual-environments/issues/5682#issuecomment-1147306237

[macOS] Add a note about VS 2019 usage

---

images/linux/scripts/base/repos.sh

The microsoft.gpg public key is part of the packages-microsoft-prod.deb package, no need to update it manually.

[Ubuntu] Remove microsoft.gpg public key

---

images/linux/scripts/installers/erlang.sh

Issue:
```
==> azure-arm: E: Failed to fetch https://binaries.erlang-solutions.com/debian/dists/focal/contrib/binary-amd64/Packages.bz2  File has unexpected size (246813 != 246791). Mirror sync in progress? [IP: 18.65.229.111 443]
==> azure-arm:    Hashes of expected file:
==> azure-arm:     - Filesize:246791 [weak]
==> azure-arm:     - SHA256:f579214f2084e5e48a75dbf11f064f64b89a3389777a4b439c26b4a969d2699b
==> azure-arm:     - SHA1:09e5daf0d42ff37e41afd8f1aed1111b92a1d9a3 [weak]
==> azure-arm:     - MD5Sum:650a796bcf40b18ba5d363026c3798ba [weak]
==> azure-arm:    Release file created at: Fri, 10 Jun 2022 10:30:52 +0000
```
https://github.com/actions/virtual-environments-internal/issues/3859

[Ubuntu] Update erlang repo

---

images/macos/software-report/SoftwareReport.Generator.ps1

Looks like we have problems with displaying the content, and it must not be a part of the Catalina SW reports, while it is.

fix SW report regarding VS for macOS

---

images/linux/scripts/helpers/install.sh

Changes:
- Add filter into the  `get_github_package_download_url` function to ignore releases without assets
- Add check if a downloadUrl is empty using a filter
https://github.com/actions/virtual-environments-internal/issues/3473

[Ubuntu] Improve github releases parser

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1

Changes:
- Add filter into theGet-GitHubPackageDownloadUrl function to ignore releases without assets
- Add check if a $versionToDownload is empty using a filter
https://github.com/actions/virtual-environments-internal/issues/3473

[Windows] Improve Get-GitHubPackageDownloadUrl function

---

images/macos/software-report/SoftwareReport.Generator.ps1

Looks like we must wrap it within a pipeline itself, otherwise while sw report is correct image diff stage is broken

[macOS] get double quotes back in sw report for VS

---

images/macos/provision/utils/utils.sh

Changes:
- Add filter into the  `get_github_package_download_url` function to ignore releases without assets
- Add check if a downloadUrl is empty using a filter
https://github.com/actions/virtual-environments-internal/issues/3473

[macOS] Improve github releases parser

---

images/macos/toolsets/toolset-12.json

Reverts actions/virtual-environments#5703 as we faced an issue with simulators with Xcode 14 on the image. We will remove the Xcode 14 until further investigation

Revert "[macOS] Add Xcode 14 to macOS 12 image"

---

images/linux/scripts/installers/aws.sh

AWS CLI v1 installer stopped working on Ubuntu18 as it now requires Python 3.7 ([changelog](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst)) while Ubuntu18 has python 3.6. V2 installer doesn't require system python to operate so can be installed on the Ubuntu18.

[Ubuntu] Install aws-cli v2 on 18.04

---

images/win/Windows2022-Readme.md
images/win/scripts/Installers/Install-Mingw64.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Previously, the GitHub virtual environments only had MinGW v8.1.0
installed. That version was released in October of 2018 and, since then,
MinGW has released versions all the way up to v11.2.0. This change
updates the MinGW version to the latest available on Chocolatey for the
Windows 2022 environment. Windows 2019 retains the current v8.1.0
version. Fixes #5530.

Update MinGW on Windows 2022

---

images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/PathHelpers.ps1
images/win/scripts/Installers/Finalize-VM.ps1

https://techcommunity.microsoft.com/t5/itops-talk-blog/wsl2-now-available-on-windows-server-2022/ba-p/3447570
WSL2 now available on Windows Server 2022 and installed  through the regular update process(Second, if you wait until June, you will get the update that is required for WSL2 to run properly on a Windows Server 2022, through the regular update process.) . We can't activate WSLv2 due to unsupported by Azure on the DSV2 spec nested virtualization.
https://github.com/actions/virtual-environments/issues/5760

[Windows] Set WSLv1 version on Windows Server 2022

---

images/macos/provision/utils/utils.sh

Fix condition:
`==> vsphere-clone: /Users/runner/utils/utils.sh: line 130: null: command not found`
https://github.com/actions/virtual-environments-internal/issues/3894

[macOS] Fix utils.sh: line 130: null: command not found

---

images/linux/scripts/installers/sqlpackage.sh

The `libssl1.1_1.1.1l-1ubuntu1.3_amd64.deb` package was updated to  libssl1.1_1.1.1l-1ubuntu1.5:
> 'http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.3_amd64.deb' is wrong - '404' or exit code is not 0 - '0'

[Ubuntu] Update openssl 1.1 on Ubuntu 22.04

---

helpers/CreateAzureVMFromPackerTemplate.ps1
images.CI/linux-and-win/cleanup.ps1

Fix:
- Creating a public IP address
WARNING: [Coming breaking change] In the coming release, the default behavior will be changed as follows when sku is Standard and zone is not provided: For zonal regions, you will get a zone-redundant IP indicated by zones:["1","2","3"]; For non-zonal regions, you will get a non zone-redundant IP indicated by zones:null.
- This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
https://github.com/actions/virtual-environments/issues/5802
https://github.com/actions/virtual-environments/issues/5799

[Scripts] Fix az cli warnings

---

images/linux/post-generation/systemd-linger.sh

`loginctl enable-linger` allows us to enable user services on a machine boot and not on a user login, which in turn allows us having user sockets activated on every machine boot prior to further communication. In practice it sets up some user-specific variables (like the dbus ones)  needed for the `systemctl --user` calls.
I have tested it on:
* mpd
* dirmngr/gpg
* emacs
* snapd (this one is extremely essential as there is snapd in our images and some packages like firefox slowly migrate to the snap-only distribution approach).
More info: https://www.freedesktop.org/software/systemd/man/loginctl.html

[Ubuntu] Enable systemd lingering

---

images/macos/tests/LLVM.Tests.ps1

After https://github.com/Homebrew/homebrew-core/commit/34db45964ce662aba85cfd830c6bd5b11e517147 commit was merged there is no anymore the `/usr/local/opt/llvm` symlink.
Before:
```
lrwxr-xr-x  1 runner  admin  23 Jun 22 16:15 /usr/local/opt/llvm -> ../Cellar/llvm/13.0.1_1
lrwxr-xr-x  1 runner  admin  23 Jun 22 16:15 /usr/local/opt/llvm@13 -> ../Cellar/llvm/13.0.1_1
```
After:
```
lrwxr-xr-x  1 runner  admin  24 Jun 27 02:43 /usr/local/opt/llvm@13 -> ../Cellar/llvm@13/13.0.1
vsphere-clone: llvm@13 is keg-only, which means it was not symlinked into /usr/local,
vsphere-clone: because this is an alternate version of another formula.
```
https://github.com/actions/virtual-environments-internal/issues/3917

[macOS] Update Clang/LLVM test to use absolute path

---

images/macos/provision/utils/xamarin-utils.sh

The 6.12.0.182 mono version has been uploaded to dl.xamarin.com so we don't need the workaround anymore — https://dl.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-6.12.0.182.macos10.xamarin.universal.pkg
n\a

[macOS] Remove workaround for Mono download url

---

images/win/post-generation/GenerateIISExpressCertificate.ps1

We have to create a new certificate for IIS Express after invoke sysprep due to destroy personal data to generalise the machine
https://github.com/actions/virtual-environments-internal/issues/3924

[Windows] Create IIS Express Development Certificate

---

images/macos/provision/configuration/configure-machine.sh

After creating a virtual machine from the image, CPU growth immediately began to appear, this can be seen in the screenshot
After disabling SuggestionsAppLibraryEnabled, the CPU stabilized and further monitoring shows stable system operation
Spotlight tries to find apps which are not present in the simulators and cpu is overloaded to 100%

[macOS] Set properties for device set list

---

images/macos/templates/macOS-12.anka.pkr.hcl

```
==> veertu-anka-vm-clone.template: Downloading ./image-generation/output/* => ../image-output/
./image-generation/output/*: No such file or directory
```
https://github.com/actions/virtual-environments-internal/issues/3947

[Anka] Fix output file

---

images/linux/scripts/installers/erlang.sh

Use usual apt-get to grab the deptree, then install the package using `dpkg -i` to bypass mismatch, then restore broken deptree to fully bring esl-erlang on board (errors ignored on purpose, not relevant to resulting installation).

[Ubuntu] Apply esl-erlang workaround for 20.04

---

images/linux/scripts/installers/sqlpackage.sh

The new version is .6 http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb
n\a

[Ubuntu] Update link to openssl

---

images/linux/scripts/SoftwareReport/SoftwareReport.Browsers.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/installers/microsoft-edge.sh
images/linux/scripts/tests/Browsers.Tests.ps1
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json
images/linux/ubuntu2204.pkr.hcl

Add Microsoft Edge to all Ubuntu's versions

[Ubuntu] Add Microsoft Edge

---

images/linux/scripts/base/apt.sh

[StableReleaseUpdates](https://wiki.ubuntu.com/StableReleaseUpdates) will no longer appear in update-manager at the same time for all machines. Instead a subset of machines will be selected at random to receive the update first. The update will only be made available to everyone if there are no serious regressions encountered by the first set of users. There is still a testing process completed by Ubuntu developers before any users receive the update.
```
libsystemd-dev:
Installed: (none)
Candidate: 249.11-0ubuntu3
Version table:
249.11-0ubuntu3.3 1 (phased 0%)
[5](https://github.com/roasted-eggplant/alcheb-test/runs/7230018773?check_suite_focus=true#step:2:6)00 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd[6](https://github.com/roasted-eggplant/alcheb-test/runs/7230018773? …
```

[Ubuntu] Apt Always-Include-Phased-Updates

---

images/macos/provision/core/commonutils.sh

```
veertu-anka-vm-clone.template: 🍺  virtualbox was successfully installed!
==> veertu-anka-vm-clone.template: /Users/<sensitive>/utils/confirm-identified-developers.scpt:708:724: execution error: Application isn’t running. (-600)
```
Add retry warmup:
```
veertu-anka-vm-clone.template: 🍺  virtualbox was successfully installed!
==> veertu-anka-vm-clone.template: 40:83: execution error: Application isn’t running. (-600)
veertu-anka-vm-clone.template: application process Finder
veertu-anka-vm-clone.template: button 5 of window Security & Privacy of application process System Preference
```
https://github.com/actions/virtual-environments-internal/issues/3895

[Anka] Fix invoking confirm-identified-developers.scpt script

---

images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

Win32_product class isn't query optimized. Queries such as select * from Win32_Product where (name like 'Name%') require WMI to use the MSI provider to enumerate all of the installed products and then parse the full list sequentially to handle the where clause. This process also starts a consistency check of packages installed, verifying, and repairing the install.
https://github.com/actions/virtual-environments-internal/issues/3969

[Windows] Replace Win32_Product call to registry query

---

images.CI/macos/anka/Anka.Helpers.psm1

We should stop an image generation workflow if a vm is in failed status.
```
[*] Waiting for 'clean_macos_12_300gb' VM to get an IP address
[-] clean_macos_12_300gb is in failed status
```
https://github.com/actions/virtual-environments-internal/issues/3970

[Anka] Check vm in failed status

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/toolsets/toolset-2022.json

The extension is now available https://devblogs.microsoft.com/visualstudio/analysis-services-and-reporting-services-extensions-for-visual-studio-2022-are-here/
https://github.com/actions/virtual-environments-internal/issues/3974

[Windows] Add Microsoft Analysis Services Projects 2022

---

images/linux/scripts/installers/oras-cli.sh

Bugfix: This PR reverts the ORAS CLI version to 0.12.0 which prevents the login bug from occurring with GHCR
Addresses: #5906

Reverting ORAS CLI to version 0.12

---

images/linux/scripts/installers/oras-cli.sh

Reverts actions/virtual-environments#5907 as this is expected behavior https://github.com/oras-project/oras/issues/446#issuecomment-1185164710

Revert "Reverting ORAS CLI to version 0.12"

---

images/macos/provision/core/rubygem.sh

We can remove the hardcoded RubyGems version as the initial issue caused by the old CLAide package version brought by xcversion is now resolved here https://github.com/xcpretty/xcode-install/pull/454
This should help us install some other RubyGems, which can't be installed previously like this one https://github.com/actions/virtual-environments/issues/5642#issuecomment-1143357958
Previous PR for reference https://github.com/actions/virtual-environments/pull/4815
https://github.com/actions/virtual-environments-internal/issues/4001

[macOS] Remove hardcoded RubyGems version

---

images/win/toolsets/toolset-2022.json

Unable to exit VS via X or File | Exit after running `devenv /RootSuffix Exp /ResetSettings General.vssettings /Command File.Exit` - will be fixed in AS 3.0.4
https://github.com/actions/virtual-environments-internal/issues/4004

Remove ProBITools.MicrosoftAnalysisServicesModelingProjects2022

---

images/win/scripts/Installers/Install-AndroidSDK.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Android.psm1
images/win/scripts/Tests/Android.Tests.ps1
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

ndk-bundle was explicitly marked as "Obsolete" by Google and no one should be using it anymore. The current symlink creation process breaks the Android SDK package manager. More details can be found here https://github.com/actions/virtual-environments/issues/2689#issuecomment-1172129050
https://github.com/actions/virtual-environments/issues/5879

[Windows] Remove ndk-bundle

---

images/win/toolsets/toolset-2022.json

Dotfuscator comes installed with VS in the windows-2019 image, but not in the windows-2022 image. Installation time in runtime varies from 4 to 6 minutes so better have it preinstalled.
https://github.com/actions/virtual-environments/issues/5936

[Windows] Add dotfuscator component to VS2022

---

images/linux/ubuntu2204.pkr.hcl

https://www.packer.io/plugins/builders/azure/arm#azure_tags
> azure_tag ([]{name string, value string}) - Same as azure_tags but defined as a singular repeatable block containing a name and a value field. In HCL2 mode the dynamic_block will allow you to create those programatically.
https://github.com/actions/virtual-environments-internal/issues/4056

[Packer] Add azure_tag

---

images/linux/scripts/installers/sqlpackage.sh

The LibSSL 1.1 package for Ubuntu 21.10 was removed due to EOL.

[Ubuntu] Fix libssl1.1 installation

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/installers/mono.sh
images/linux/scripts/tests/Tools.Tests.ps1
images/linux/ubuntu2204.pkr.hcl

Mono maintainers confirmed that Ubuntu 20 packages will work for Ubuntu 22 and there is no ETA for native Ubuntu 22 packages so let's stick to those ones.
Also, this PR adds Nuget to the software readme as we somehow missed it before.
https://github.com/actions/virtual-environments-internal/issues/4066

[Ubuntu] Add mono package to ubuntu 22

---

images/win/scripts/Installers/Configure-Antivirus.ps1

Windows Defender marks the Configure-Antivirus.ps1 script as a virus.
https://github.com/actions/virtual-environments/discussions/5964

[Windows] Bypass Windows Defender false alarm

---

images/macos/provision/core/mongodb.sh

mongodb-community@5.0 is keg-only, which means it was not symlinked into /usr/local:
```
vsphere-clone:   [-] mongo 207ms (170ms|37ms)
vsphere-clone:    CommandNotFoundException: The term 'mongo' is not recognized as a name of a cmdlet, function, script file, or executable program.
vsphere-clone:    Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
vsphere-clone:    at <ScriptBlock>, /Users/runner/image-generation/tests/Databases.Tests.ps1:7
```
https://github.com/actions/virtual-environments-internal/issues/4089

[macOS] Create symlink for mongodb@5.0

---

README.md

Windows-2016 is retired in GitHub for a long time and soon will be retired from ADO as well.
https://github.com/actions/virtual-environments/issues/5403

Remove windows-2016 from the list of images

---

images/win/scripts/Installers/Install-AndroidSDK.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Android.psm1
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

It turned out some of the NDK-related variables are required by customers' projects ([like openssl](https://github.com/openssl/openssl/blob/master/Configurations/15-android.conf#L27)). We need to define all three variables pointed to the latest LTS NDK (default one) to stay on the safe side — ` 'ANDROID_NDK', 'ANDROID_NDK_HOME', 'ANDROID_NDK_ROOT'`
https://github.com/actions/virtual-environments/issues/5879

[Windows] Add ndk-related environment variables

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Install-Vsix.ps1

Starting from version 4.1.2 [SSIS.SqlServerIntegrationServicesProjects Visual studio extenstion](https://marketplace.visualstudio.com/items?itemName=SSIS.SqlServerIntegrationServicesProjects) is distributed via executable file rather than vsix one. This PR adds the ability to install the new extension version.
https://github.com/actions/virtual-environments-internal/issues/4104

[windows] Add exe installation of MicrosoftAnalysisServices Visual Studio extension

---

.github/workflows/merge_pull_request.yml

Given that now it is handled by the repository settings we should not do it via a workflow file, otherwise we experience an error.

Do not remove release doc refs manually

---

images/win/scripts/Installers/Install-MongoDB.ps1
images/win/scripts/Tests/Databases.Tests.ps1

Disable mongodb service by default on Windows Server 2019/2022.
https://github.com/actions/virtual-environments/issues/5949

[Windows] Disable mongodb service by default

---

images/win/scripts/Installers/Install-MongoDB.ps1

In slow environments we can get an error "Service 'MongoDB Server (MongoDB) (MongoDB)' cannot be stopped due to the following error: Cannot stop MongoDB service on computer '.'" due to delay start.
https://github.com/actions/virtual-environments-internal/issues/4159

[Windows] Wait for mongodb service running

---

images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

According to our [Software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md)
we support [3 latest minor versions of Go],
(https://endoflife.date/go) which are 1.17, 1.18 & 1.19 at the moment.

[macOS] remove go-1.16.x

---

images.CI/linux-and-win/build-image.ps1

It looks like we missed this flag on linux/windows ci as it is explicitly disabled on macOS, otherwise the log looks like we are
celebrating a new year (not yet), found it on Actions.
Example:

[Packer] Disable colored output on Ubuntu

---

images/win/scripts/Tests/Tools.Tests.ps1

Remove `vcredist_2010_x64` duplication - I would have expect a `vcredist_2010_x86` test, but it does just not exist.

[Windows] remove vcredist_2010_x64 duplicate test

---

images/win/toolsets/toolset-2019.json

- Add Microsoft.VisualStudio.Component.VC.Tools.ARM64EC component
https://github.com/actions/runner-images/issues/6069

[Windows] Add ARM64EC workload for Visual Studio 2019

---

images/macos/provision/core/python.sh

- Update default python version from 3.9 to 3.10
https://github.com/actions/runner-images-internal/issues/4188

[macOS] Update python3 to 3.10 version

---

images/win/toolsets/toolset-2022.json

Component.Xamarin VS component is optional by default for Visual Studio 2022 since version 17.3. We should add it back.
https://github.com/actions/runner-images/issues/6082

[Windows] Add Component.Xamarin for Visual Studio 2022

---

images/linux/ubuntu2004.json

Time to time we get the error `Script disconnected unexpectedly` during packer provisioner stage on Ubuntu Server 20.04 - https://github.visualstudio.com/virtual-environments/_build/results?buildId=128407&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043
```
==> azure-arm: Provisioning with shell script: C:\agent\_work\18\s\images\linux/scripts/base/apt-mock-remove.sh
==> azure-arm: Provisioning with shell script: C:\Windows\SERVIC~2\NETWOR~1\AppData\Local\Temp\packer-shell4207490466
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: 
==> azure-arm: Deleting individual resources ...
Build 'azure-arm' errored after 1 hour 24 minutes: Script disconnected unexpectedly. If you expected your script to …
```

[Ubuntu] Set max_retries to 3

---

images/linux/scripts/installers/preimagedata.sh
images/macos/provision/configuration/preimagedata.sh
images/win/scripts/Installers/Update-ImageData.ps1

Recently we changed name of our repo to 'runner-images'. This PR changes group title 'Virtual Environment' in workflow logs to 'Runner Image' to be consistent with new repo name.
https://github.com/actions/runner-images/pull/6006

[all OSs] Change title in workflow log

---

images/macos/provision/core/codeql-bundle.sh
images/macos/tests/Common.Tests.ps1

Corrections for test of CodeQL action bundle.
Previous PR  #6068

[macOS] CodeQL tests correction for macOS 11 and 12

---

images.CI/macos/select-datastore.ps1

Otherwise it fails in interactive mode with

select-datastore: make cluster parameter mandatory

---

.github/workflows/codeql-analysis.yml

Workflow update.
CodeQL actions release/v1 would be deprecated in December of this year:
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
Usage of CodeQL actions release/v2 is same:
https://github.com/github/codeql-action/blob/main/README.md
N/A

[actions] Updated github/codeql-action used version from v1 to v2

---

images/macos/toolsets/toolset-10.15.json

bats was [disabled](https://formulae.brew.sh/formula/bats)

[macOS] Remove bats formula installation

---

images/macos/software-report/SoftwareReport.Xcode.psm1
images/macos/tests/BasicTools.Tests.ps1
images/macos/toolsets/toolset-10.15.json

xctool formula has been [disabled](https://formulae.brew.sh/formula/xctool)

[macOS] Remove xctool formula installation

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/tests/Tools.Tests.ps1
images/linux/ubuntu2204.pkr.hcl

Add sqlcmd tool on Ubuntu Server 22.04.
https://github.com/actions/runner-images/issues/6126

[Ubuntu] Add sqlcmd on Ubuntu Server 22.04

---

images/macos/provision/core/gcc.sh

Not always the binary under the `/usr/bin/gfortran` exists which makes the script fall.

[macOS] always return True on gfortran check

---

images/linux/scripts/installers/configure-environment.sh

Pod errors due to "too many open files":
This may be caused by running out of [inotify](https://linux.die.net/man/7/inotify) resources. Resource limits are defined by fs.inotify.max_user_watches and fs.inotify.max_user_instances system variables. For example, in Ubuntu these default to 8192 and 128 respectively, which is not enough to create a cluster with many nodes.
https://github.com/actions/runner-images/issues/268#issuecomment-1222405650

[Ubuntu] Update  inotify resource limits

---

images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/Common.Tests.ps1

We do not install codeql on Catalina, therefore we must not include it into the software report generator, otherwise the build fails.

[macOS] Don't show CodeQl in Catalina's sw report

---

images/macos/software-report/SoftwareReport.Common.psm1

Brew outputs json as well so we can use jq rather than rely on our cut supply helper.

[macOS] Use json to parse libraries version

---

images/macos/provision/core/swiftlint.sh

Swiftling 0.49 introduces a breaking change — SwiftLint now requires Swift 5.6 or higher to build, and macOS 12
or higher to run.
https://github.com/realm/SwiftLint/releases/tag/0.49.0
https://github.com/realm/SwiftLint/issues/4131

[macOS] Install the latest Swiftlint only for macOS 12

---

images/macos/tests/Databases.Tests.ps1

The version output for postgresql has changed — we have (Homebrew) at the end of the output now so need to take not the last but the previous split part as a version in the test.
https://github.com/actions/runner-images-internal/issues/4239

[macOS] Fix PostgreSql pester test — take second split from the end

---

images/macos/provision/core/rubygem.sh

macOS images currently have broken cocoapods due to the fact that we have two different [public_suffix](https://rubygems.org/gems/public_suffix/versions/1.5.3) gem versions — 5.0.0 & 4.0.7 while cocoapods only works with version 4
https://github.com/CocoaPods/CocoaPods/blob/f65ac1881cfcc78a6740c6e6e738933d560c2a55/Gemfile.lock#L21
The error is
```
/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate cocoapods-core-1.11.3, because public_suffix-5.0.0 conflicts with public_suffix (~> 4.0) (Gem::ConflictError)
```
This PR temporarily uninstalls the newest public_suffix version and can be reverted once cocoapods adds support for public_suffix 5.*
https://github.com/actions/runner-images/issues/6149 …

[macOS] Uninstall public_suffix 5.0 gem

---

images/macos/provision/core/postgresql.sh

Postgresql formula has been updated to version 15 and as we are still installing version 14 we have to stop the versioned formula instead of the main one to avoid such a warning — `Warning: Use postgresql@14 instead of deprecated postgresql`
https://github.com/actions/runner-images-internal/issues/4243

[macOS] Stop versioned postgresql service instead of the general one

---

images/win/scripts/Installers/Install-VS.ps1
images/win/scripts/Tests/VisualStudio.Tests.ps1

Windows SDK 10.0.22621 added to Windows Server 2019.
#6137
-

[Windows] Add Windows11SDK.22621 to Win19

---

images/linux/scripts/installers/google-chrome.sh

https://omahaproxy.appspot.com/deps.json?version=105.0.5195.102 - returns very old chromium version
https://github.com/actions/runner-images-internal/issues/4273

[Ubuntu] Fix chromium revision parsing

---

images/win/scripts/Installers/Install-Vcpkg.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/Tests/Tools.Tests.ps1

Add VCPKG_ROOT variable in additional to VCPKG_INSTALLATION_ROOT + simple style fix
[#4241](https://github.com/actions/runner-images-internal/issues/4241)

[Windows] Add VCPKG_ROOT variable

---

images/macos/provision/core/vcpkg.sh
images/macos/software-report/SoftwareReport.Common.psm1

Add VCPKG_ROOT variable in additional to VCPKG_INSTALLATION_ROOT
[#4241](https://github.com/actions/runner-images-internal/issues/4241)

[macOS] Add VCPKG_ROOT variable

---

images/macos/toolsets/toolset-12.json

For development with the macOS Ventura SDK users need to continue to use Xcode 14 beta 6 so we need to have both beta and stable versions preinstalled until Ventura is out of beta (October 2022).
https://github.com/actions/runner-images-internal/issues/4311

[macOS] Add Xcode 14 beta 6 in macOS 12 toolset

---

images/linux/scripts/tests/Tools.Tests.ps1
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

Since homebrew-3.6.0 gcc@11 and glibc have become mandatory dependencies for any package, While we are installing zstd, it surely does not pull gcc, because zstd itself is required for GCC's LTO support, so there would be a circular dependency loop, as a result zstd's linkage is broken because it requires toolchain libs to present.
Also fixed a broken pester test.

[Ubuntu] install gcc@11 from brew

---

images/win/scripts/Installers/Install-Docker.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Helpers.psm1

Support for DockerMsftProvider ends at the end of September and will be fully transferred to Mirantis. The alternative is Docker CE / Moby.
This PR replaces installation of Docker EE in favor of Docker CE and also
- Changes docker-compose v2 installation to `C:\ProgramData\docker` as all the docker configs and libs are now placed there
- Changes `wincred` installation to the same directory as Docker CE executables (win\system32) as there is no more `C:\Program Files\Docker` in the path
- Adds Docker to the exclusion list in Software report blank version tester as the version doesn't match the general format — `master-dockerproject-2022-03-26`
https://github.com/actions/runner-images/issues/6181

[Windows] Replace Docker EE with Docker CE

---

images/linux/scripts/tests/Tools.Tests.ps1
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

This reverts commit d2c84c9d4c30a469ab32e88d9118914a9380a53f.
Every single linux binary relies on glibc from brew now, in the screenshot `ldd /bin/ls`

Revert "[Ubuntu] install gcc@11 from brew (#6202)"

---

.github/CODEOWNERS

Update to point to the right team for PR reviews: https://github.com/orgs/actions/teams/runner-images-team/members

Update codeowners to the right team for PR reviews

---

images/linux/scripts/installers/homebrew.sh
images/linux/scripts/tests/Tools.Tests.ps1
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

Kudos go to the whole homebrew team and especially @MikeMcQuaid for fixing all the issues :)

[Ubuntu] Install gcc@12 from brew

---

images/linux/scripts/installers/homebrew.sh

Homebrew installs both `gfortran-12` and `gfortran`. `gfortran` itself is a symlink and can be removed as we already are doing it on macOS.

[Ubuntu] remove gfortran symlink from brew

---

images/macos/toolsets/toolset-12.json

We would like to provide images with the latest stable updates as default ones.
https://github.com/actions/runner-images/issues/6225

[macOS] Set Xcode 14.0.1 as the default version

---

images/macos/tests/Browsers.Tests.ps1

Sometimes we have a situation when Chrome is already updated to a new major version but chromedriver isn't (mostly related to macOS as those are different homebrew formulas and can be updated not at the same time).
We need to fail a build in such cases rather than find it out only during the deployment.
This PR adds a Pester test that will fail the build in case of a version mismatch. Execution example:
https://github.com/actions/runner-images-internal/issues/4392

[macOS] Test Chrome and Chrome Driver major versions are the same

---

images/macos/provision/core/commonutils.sh

Sometimes `Expected $null or empty, but got window Security & Privacy of application process System Preferences.` window is still opened after reboot. As a fix we should kill System Preferences process.

[macOS] Close System Preferences window

---

images/macos/tests/Common.Tests.ps1

Colima tool excluded from Pester tests for macOS 10.15 image,
[#4393](https://github.com/actions/runner-images-internal/issues/4393)

[macOS] Add Colima exclusion to fix macOS-10.15 image

---

images/linux/scripts/tests/Browsers.Tests.ps1

Sometimes we have a situation when Chrome is already updated to a new major version but chromedriver isn't.
We need to fail a build in such cases rather than find it out only during the deployment.
This PR adds a Pester test that will fail the build in case of a version mismatch.
https://github.com/actions/runner-images-internal/issues/4392

[Ubuntu] Test Chrome and Chrome Driver major versions are the same

---

images/win/scripts/Tests/Browsers.Tests.ps1

Sometimes we have a situation when Chrome is already updated to a new major version but chromedriver isn't.
We need to fail a build in such cases rather than find it out only during the deployment.
This PR adds a Pester test that will fail the build in case of a version mismatch.
https://github.com/actions/runner-images-internal/issues/4392

[Windows] Test Chrome and Chrome Driver major versions are the same

---

images/linux/scripts/installers/haskell.sh
images/linux/scripts/tests/Haskell.Tests.ps1

See https://github.com/commercialhaskell/stack/issues/5895
Stack feature is documented here:
https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-installation-customisation
It's recommended, but probably too unexpected for CI. It means stack will not install GHC on its own, but through GHCup.
@al-cheb @mpilgrem

Don't install stack install hook

---

images/macos/provision/core/commonutils.sh

VMs suddenly crash on VirtualBox 7 due to new hypervisor(macOS host: Dropped all kernel extensions. [VirtualBox](https://www.virtualbox.org/wiki/VirtualBox) relies fully on the hypervisor and vmnet frameworks provided by Apple now. At the moment the implementation lacks "Internal Networking" functionality. This will be provided at a later date. - https://www.virtualbox.org/wiki/Changelog-7.0). We should downgrade VirtualBox to the previous version.
https://github.com/actions/runner-images-internal/issues/4449

[macOS] Tight VirtualBox version to 6.1.38

---

images/linux/toolsets/toolset-2004.json

Delete old Docker images with Alpine OS for Ubuntu 20.04:
alpine:3.12
alpine:3.13
[#4381](https://github.com/actions/runner-images-internal/issues/4381)

[Ubuntu] Delete old Alpine Docker images

---

images/linux/scripts/installers/rust.sh

https://github.com/rust-lang/cargo/issues/11249 - we should use `cargo install bindgen-cli`.
https://github.com/actions/runner-images-internal/issues/4478

[Ubuntu] Replace bindgen to bindgen-cli

---

images/macos/provision/core/rust.sh

https://github.com/rust-lang/cargo/issues/11249 - we should use `cargo install bindgen-cli`.
https://github.com/actions/runner-images-internal/issues/4478

[macOS] Replace bindgen to bindgen-cli

---

images/win/scripts/Installers/Install-Rust.ps1
images/win/scripts/Tests/Rust.Tests.ps1

Add additional Pester tests for Rust:
- cbindgen
- bindgen
Replace bindgen to bindgen-cli - https://github.com/rust-lang/cargo/issues/11249
https://github.com/actions/runner-images-internal/issues/4478

[Windows] Add cbindgen and bindgen pester test

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/installers/vcpkg.sh
images/macos/provision/core/vcpkg.sh
images/macos/software-report/SoftwareReport.Common.psm1
images/win/scripts/Installers/Install-Vcpkg.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/Tests/Tools.Tests.ps1

Revert breaking changes for VCPKG. Remove VCPKG_ROOT variable.
#6376

[all OSs]  Revert VCPKG_ROOT variable

---

images/win/windows2022.json

The latest Azure marketplace image version is broken:
```
Publisher               : MicrosoftWindowsServer
Offer                   : WindowsServer
Sku                     : 2022-datacenter
Version                 : latest
ExactVersion            : 20348.1131.221014
vhd: Activating Windows Feature 'NET-Framework-Features'...
==> vhd: Install-WindowsFeature : The request to add or remove features on the specified server failed.
==> vhd: Installation of one or more roles, role services, or features failed. Error: 0x800f0950
```
https://github.com/actions/runner-images/issues/6431

[Windows] Set Windows Server 2022 image_version

---

.github/workflows/create_github_release.yml
.github/workflows/create_pull_request.yml
.github/workflows/linter.yml
.github/workflows/merge_pull_request.yml
.github/workflows/update_github_release.yml

Signed-off-by: Austin Vazquez <macedonv@amazon.com>
Update actions/checkout from v2 to v3 to migrate off Node 12
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Update GitHub actions/checkout package to v3

---

images/linux/scripts/installers/php.sh

The third party repository for PHP will be removed from the Ubuntu 22.04 image in favor of the official Ubuntu software repository.
#6331

[Ubuntu] Remove ppa:ondrej/php for Ubuntu 22.04

---

images/win/scripts/Installers/Finalize-VM.ps1
images/win/windows2019.json
images/win/windows2022.json

The `install_user` Temp directory is never cleaned.
This user is used for Visual Studio, Kubernetes tools, and other installation. The Temp directory contains several resources, that are not useful at runtime (installer profile should not be used any time...)
I've checked here, it's appr. 7Gb we can reclaim:
https://github.com/asbiin/windows-test/actions/runs/3419158662/jobs/5692324619
Another option would be deleting the `install_user` profile entirely, which might have other consequences...

[Windows] Clean Install_user Temp directory

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Remove Nodejs 12.x in order to leave the three latest versions of Nodejs for Ubuntu
#6482

[Ubuntu] Remove Node 12 from toolcache

---

images/win/windows2022.json

Reverts actions/runner-images#6447
The issues has been fixed in `20348.1249.221105` version:
```
Publisher               : MicrosoftWindowsServer
Offer                   : WindowsServer
Sku                     : 2022-Datacenter
Version                 : latest
ExactVersion            : 20348.1249.221105
```

Revert "[Windows] Set Windows Server 2022 image_version"

---

images/macos/tests/System.Tests.ps1

`vsphere-clone: 17:18: syntax error: Expected expression, property or key form, etc. but found unknown token. (-2741)`
https://github.com/actions/runner-images-internal/issues/4589

[macOS] Remove \ escape

---

images/macos/provision/core/android-toolsets.sh

The default xml-attribute-prefix has changed in the v4.30 to `+@` to avoid naming conflicts with the default content name.

[macOS] fix yq invocation on android repo xml

---

images/win/scripts/Installers/Install-Haskell.ps1

The latest versions of Haskell distributed through Choco do not install correctly 
https://community.chocolatey.org/packages/ghc/9.4.3
#6575

[windows] Do not install latest version of GHC

---

images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

With the release of .NET 7.0, the content of our images has changed from our software support policy. Let's add .NET 6.0 as a permanent component of the build.
#6577

[Windows] Add .NET 6.0 as LTS

---

images/linux/scripts/installers/vcpkg.sh

File for ubuntu18 is also missed for ubuntu

[Ubuntu] Add one more missing file for vcpkg

---

images/win/scripts/Installers/Install-PowershellCore.ps1

The PowerShell v7.3.0 has compatibility issues and it is not an LTS version.  
The latest version of PowerShell will be changed to v7.2.7 
Example breaking change:
https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.3#psnativecommandargumentpassing
https://github.com/actions/runner-images-internal/issues/4615

[Windows] Pin PowerShell version 7.2.7

---

images/macos/provision/core/powershell.sh

The PowerShell v7.3.0 has compatibility issues and it is not an LTS version.
The latest version of PowerShell will be changed to v7.2.7
Example breaking change:
https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.3#psnativecommandargumentpassing
https://github.com/actions/runner-images-internal/issues/4615

[macOS] Pin PowerShell version 7.2.7

---

images/macos/tests/System.Tests.ps1

Light rework to avoid `bash -c $cmd` direct errors

[macOS] Rework open windows test

---

images.CI/linux-and-win/azure-pipelines/image-generation.yml

Enhancing Azure DevOps images generation pipeline template by exposing some new parameters to be possible to override.
These changes could simplify creation of custom images by organizations on their own Azure DevOps pipelines without a need to keep in sync a fork of this repository with custom pipeline/pipeline template.
In Organization specific repository on Azure DevOps could be created a pipeline which will be referring to `actions/runner-images` repository using [resources](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-repositories-repository?view=azure-pipelines) feature and will be calling `image-generation.yml` template directly.
Example pipeline:
```yaml
resources:
repositories:
- repository: RunnerImagesGitHub
type: github
name: …
```

Enhance image generation template for Linux and Windows variants

---

images/linux/scripts/SoftwareReport/SoftwareReport.Browsers.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/installers/firefox.sh
images/linux/scripts/tests/Browsers.Tests.ps1
images/linux/ubuntu2204.pkr.hcl

- Add Firefox browser to ubuntu 22.04 from PPA source.
- Update browsers test to be able to validate Firefox installation on Ubuntu 22.04
- Include Firefox on Ubuntu 22.04 in the Software Report
https://github.com/actions/runner-images-internal/issues/4573

[Ubuntu] Add Firefox for 22.04 from PPA source

---

.github/workflows/create_sbom_report.yml

Workflow for generating SNOM on published images of runners. The result will be uploaded as an attachment to the corresponding release.
[#4405](https://github.com/actions/runner-images-internal/issues/4405)

Add workflows to create SBOM and upload it to release asset

---

images/win/scripts/Installers/Install-Rust.ps1

The R project (and probably other OSS projects) are using mingw-w64 based compilers, that require the `x86_64-pc-windows-gnu` target for rust code. It would be great if we can preinstall this on the image.

Rust: add support for mingw-w64 toolchains

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

Add "libyaml-dev" library to all Ubuntu OSes to support Ruby gems
#6725

[Ubuntu] Add libyaml-dev library

---

images.CI/linux-and-win/azure-pipelines/image-generation.yml
images.CI/macos/azure-pipelines/image-generation.yml

Update images CI pipelines to publish artifact with readme and software report file

---

helpers/software-report-base/Calculate-ImagesDifference.ps1

Included changes:
- Create output folder if it doesn't exist yet
- Fix typo `ReleaseBranch` -> `ReleaseBranchName`

Minor fixes for Calculate-ImagesDifference.ps1

---

images/win/scripts/Installers/Install-PostgreSQL.ps1

Since the installation of the latest version of PostgreSQL 14 from the choco is broken, was decided to change the way of installation.
The current way parse the latest minor version from the git.postgresql.org site and download ".exe" file from a well-known source.
The installation itself happens in unattended mode.
#6802

[Windows] Update PostgreSQL way to install

---

images/macos/software-report/SoftwareReport.Generator.ps1

Fix minor typo for variable name in SoftwareReport generator

[MacOS] fix minor typo for variable name in SoftwareReport generator

---

images/linux/scripts/tests/Tools.Tests.ps1

We have to remove pester test for "kotlinc-js" since the check throws an error and locks image generation.

[Ubuntu] Remove pester test for kotlinc-js

---

images/win/scripts/Installers/Install-Haskell.ps1
images/win/scripts/Tests/Tools.Tests.ps1

We have to remove pester test for "kotlinc-js" since the check throws an error and locks image generation.
Revert commit (https://github.com/actions/runner-images/commit/b101b56) included in this PR to unblock two parallel issues (ghc and kotlin)

[Windows] Remove pester test for kotlinc-js

---

images/macos/tests/BasicTools.Tests.ps1

Remove kotlinc-js pester test to unblock the image generation

[macOS] Remove kotlinc-js pester test

---

images/linux/scripts/installers/haskell.sh

We use it during installation and add it to PATH, but then don't instruct ghcup to actually use this directory at runtime.
This leads to:
1. ghcup is in /usr/local/.ghcup/bin/
2. `ghcup install cabal latest` will actually install into ~/.ghcup/bin/
3. since ~/.ghcup/bin/ is not in PATH, but /usr/local/.ghcup/bin/ is, the new binary is not visible to the user
This issues does not exist on darwin, because there we use ~/.ghcup/bin/.
----
An alternative approach is matching the macOS install way and use the default `~/.ghcup`. Why was `/usr/local/.ghcup` chosen for linux?

[Haskell] Make sure GHCUP_INSTALL_BASE_PREFIX is set

---

images/win/scripts/Installers/Install-ServiceFabricSDK.ps1
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

As detailed in the blog post https://blogs.iis.net/iisteam/web-platform-installer-end-of-support-feed, the Web Platform Installer is now officially retired.
This PR changes the way of installing Service Fabric Runtime and SDK 
The Service Fabric components versions is added to the toolset files.
#6880

[Windows] Change the way of installing Service Fabric

---

images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

This reverts commit 9753e7301e19e29b89b0622b811bbb9b3891d02e.
Openssl-3.x breaks some azdo tasks which use openssl directly so we have to revert it.

Revert "[Windows] Update OpenSSL version to 3.x (#6837)"

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

[Ubuntu] fix ghcup version in software report

---

images/win/scripts/Installers/Install-AndroidSDK.ps1
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Newer version require Java 11 which we can't switch to default yet.

[Windows] Hardcode command line tools

---

images/macos/provision/core/android-toolsets.sh
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

Newer version require Java 11 which we can't switch to default yet.
#6960

[macOS] Hardcode command line tools

---

images/win/scripts/Installers/Install-Toolset.ps1

[Windows] set TLS12 for toolset

---

images/linux/scripts/installers/android.sh
images/linux/toolsets/toolset-1804.json

Newer cmd-tools require Java 11 which is not default on 18.04

[Ubuntu] Hardcode android cmd-tools on 18.04

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

[Ubuntu] .NET 5.x has been removed from the images

[Ubuntu] .NET 5.x has been removed

---

images/win/scripts/Installers/Install-PostgreSQL.ps1

We faced the issue where a new release tag for PostgreSQL was published, but the installer was not uploaded. To mitigate this issue the way to get the installer was updated.

[Windows] Reengineer the way of getting the installer for PostgreSQL

---

images/linux/scripts/installers/haskell.sh

This was initially meant to save space in docker containers, but breaks several use cases and runner images shouldn't have space constraints.
Also fixes: https://github.com/haskell/actions/issues/176
----
This will also have to be applied to macos.

[Haskell] Don't clean up haddock and profiling libs

---

images/macos/provision/core/haskell.sh

This was initially meant to save space in docker containers, but breaks several use cases and runner images shouldn't have space constraints.

Don't clean up haddock and profiling libs on MacOS

---

images/macos/provision/core/node.sh
images/macos/templates/macOS-11.anka.pkr.hcl
images/macos/templates/macOS-11.json
images/macos/templates/macOS-12.anka.pkr.hcl
images/macos/templates/macOS-12.json

The latest build failed with the test error:
```
version should correspond to the version in the toolset 67ms (66ms|2ms)
Expected like wildcard 'v16*' to match 'v19.6.0', but it did not match.
```
The root cause of installing node.js v19.6.0 was "mongosh" which uses this app as a dependency.
This is the first try to unblock the build

[macOS] Update templates to fix issue with node 19

---

images/linux/scripts/installers/google-chrome.sh

To unblock image generation we have to temporarily hardcode the chromium revision.

[Ubuntu] hardcode chromium revision for 110.x

---

images/linux/scripts/installers/mssql-cmd-tools.sh

This reverts commit c89bab7e421dbab8edddb75d8f5b3ad93a898aa5.
As it seems to be fixed

Revert "[Ubuntu] workaround libodbc installation (#7117)"
