actions/runner-images

README.md
First pass at explaining what OS's are offered.
=> Add section on OS's offered

images/linux/scripts/installers/1604/azpowershell.sh, images/linux/scripts/installers/1804/azpowershell.sh
Since install scripts got moved here, I had to redo the PR naturally
Old PR on the other repository before the installation script files got moved - https://github.com/microsoft/azure-pipelines-image-generation/pull/1426
=> Added Az Module 2.8.0 to installation scripts

images/macos/macos-10.15-Readme.md
Software updates:
- CMake 3.15.5
- App Center CLI 2.3.2
- NVM v13.3.0
- Android Emulator 29.2.11
- Android SDK Platform 29 v4
=> [MacCloud] GitHub 10.15 Software Updates Week 51

LICENSE
:wave: Actions team!
This PR updates the LICENSE's year from 2019 to 2020 :v:
=> LICENSE: update year

images/win/scripts/Installers/Install-WindowsUpdates.ps1
Added missing param to actually install Windows updates.
=> Add -Install to Get-WUInstall call to actually install Windows Updates.

images/linux/scripts/installers/cmake.sh
Issue:
https://github.com/actions/virtual-environments/issues/56
Fix:
Update Cmake version to  Cmake 3.15.4
=> Update CMake on Linux

images/linux/scripts/installers/1604/basic.sh, images/linux/scripts/installers/1804/basic.sh
Issue:
https://github.com/actions/virtual-environments/issues/265
Fix:
Install upx on Ubuntu 16.04/18.04
=> Add upx on Ubuntu 16.04/18.04

images/linux/scripts/installers/hosted-tool-cache.sh, images/linux/toolcache-1604.json, images/linux/toolcache-1804.json, images/linux/ubuntu1604.json, images/linux/ubuntu1804.json
- Switch toolcache to GitHub feed
- Add authorization for github feed
=> Switch Linux toolcache to GitHub package registry

images/linux/scripts/installers/kind.sh, images/win/scripts/Installers/Install-Kind.ps1
Signed-off-by: Tamal Saha <tamal@appscode.com>
=> Update to Kind v0.7.0

images/linux/scripts/installers/1604/dotnetcore-sdk.sh, images/linux/scripts/installers/1804/dotnetcore-sdk.sh
With this change, the following .NET Core components will get installed.
```
dotnet --info
.NET Core SDK (reflecting any global.json):
Version:   3.1.100
Commit:    cd82f021f4
Runtime Environment:
OS Name:     ubuntu
OS Version:  18.04
OS Platform: Linux
RID:         ubuntu.18.04-x64
Base Path:   /usr/share/dotnet/sdk/3.1.100/
Host (useful for support):
Version: 3.1.0
Commit:  65f04fb6db
.NET Core SDKs installed:
2.1.300 [/usr/share/dotnet/sdk]
2.1.301 [/usr/share/dotnet/sdk]
2.1.302 [/usr/share/dotnet/sdk]
2.1.401 [/usr/share/dotnet/sdk]
2.1.402 [/usr/share/dotnet/sdk]
2.1.403 [/usr/share/dotnet/sdk]
2.1.500 [/usr/share/dotnet/sdk]
2.1.502 [/usr/share/dotnet/sdk]
2.1.503 [/usr/share/dotnet/sdk]
2.1.504 [/usr/share/dotnet/sdk]
2.1.505 [/usr/share/dotnet/sdk]
2.1.506 …
```
=> Update linux images to include .NET Core 3.1

images/linux/scripts/installers/postgresql.sh, images/linux/ubuntu1604.json, images/linux/ubuntu1804.json
- add libpq-dev and documentation about it
- add Postgresql Client
=> Add libpq-dev to linux images

images/win/Windows2019-Readme.md, images/win/scripts/Installers/Validate-NET48.ps1
- add net core path to docs
- add net core path to doc generation
=> Add net core path to docs

images/win/scripts/Installers/Install-NodeLts.ps1, images/win/scripts/Installers/Validate-NodeLts.ps1
Install lerna npm globally
Test lerna is in path
=> Add lerna to windows images

images/linux/scripts/installers/1604/kubernetes-tools.sh, images/linux/scripts/installers/1804/kubernetes-tools.sh, images/linux/scripts/installers/nodejs.sh
Replace existing references to git.io with full links to repositories.
Internal issue: [#109](https://github.com/actions/virtual-environments-internal/issues/109)
=> Remove references to git.io

images/linux/scripts/installers/1604/dotnetcore-sdk.sh, images/linux/scripts/installers/1804/dotnetcore-sdk.sh
In scope of this PR we've fixed [this issue](https://github.com/actions/virtual-environments/issues/213)
=> Add ".dotnet/tools" to the PATH

images/linux/scripts/installers/firefox.sh, images/linux/scripts/installers/google-chrome.sh, images/linux/scripts/installers/selenium.sh, images/linux/ubuntu1604.json, images/linux/ubuntu1804.json
Add Gecko webdriver to linux images
Move selenium installation to its own script
=> Install Firefox(Gecko) webdriver to linux images

images/linux/ubuntu1604.json, images/linux/ubuntu1804.json, images/win/Windows2016-Azure.json, images/win/Windows2019-Azure.json
Add ImageOS companion to ImageVersion - https://github.com/actions/virtual-environments/issues/345
| Name  |ImageOS   |
|---|---|
| Windows 2016  |win16   | 
|  Windows Server 2019 |win19   | 
| Ubuntu 16.04  |ubuntu16   | 
| Ubuntu 18.04  |ubuntu18   |
=> Add ImageOS environment variable

images/win/scripts/Installers/Install-Firefox.ps1, images/win/scripts/Installers/Install-SeleniumWebDrivers.ps1, images/win/scripts/Installers/Validate-SeleniumWebDrivers.ps1
- install latest firefox
- install latest gecko driver for firefox
=> Install latest firefox for Windows

.github/workflows/stale.yml
Related https://xamarinhq.slack.com/archives/CSC1E3PTM/p1582100109459300
=> Updating stale.yml

images/win/scripts/ImageHelpers/InstallHelpers.ps1
FullName is missing from the variable.
=> Quick VS19 modules validation fix

images/linux/scripts/installers/1604/dotnetcore-sdk.sh, images/linux/scripts/installers/1804/dotnetcore-sdk.sh
Remove version 3.1.102 from the install list, .NET gave a heads-up that this might cause issues and they are working on a fix.
https://github.com/dotnet/aspnetcore/issues/19133
=> [Ubuntu] Disable .net SDK 3.1.102 installation

images/linux/scripts/installers/1604/dotnetcore-sdk.sh, images/linux/scripts/installers/1804/dotnetcore-sdk.sh
First PR https://github.com/actions/virtual-environments/pull/456 hasn't disabled 3.1.102 installation completely.
=> [Ubuntu] Disable .net SDK 3.1.102 installation part 2

images/win/scripts/Installers/Install-Git.ps1
Reverts actions/virtual-environments#415 due to
https://github.com/actions/virtual-environments/issues/480
=> Revert "Restore Git bash utilities to the PATH"

images/linux/scripts/installers/1604/kubernetes-tools.sh, images/linux/scripts/installers/1804/kubernetes-tools.sh
xref: https://helm.sh/docs/intro/install/#from-script
Signed-off-by: Tamal Saha <tamal@appscode.com>
=> Update to helm 3

images/win/scripts/Installers/Windows2016/Install-SSDT.ps1
This PR related to the issue #484. It update SSDT version for VS 2017 to the latest version (15.9.3).
=> Update SSDT to 15.9.3

images/macos/macos-10.15-Readme.md
- Rust 1.41.1
- Ruby 2.6.5p114
- Go 1.14
- CocoaPods 1.9.0
- NuGet 5.4.0.6315
- Vcpkg 2020.02.04
- Gradle 6.2.1
- zstd 1.4.4
- Microsoft Edge 80.0.361.62 
- MSEdgeDriver 80.0.361.62
- 3.8.2
- 8.4.7.17
- 6.6.0.166
- 13.10.0.21
- 6.10.0.21
=> macOS Catalina 10.15.3 sofware updates week 10

images/linux/scripts/installers/bazel.sh, images/win/scripts/Installers/Validate-Bazel.ps1, images/win/scripts/Installers/Validate-Mercurial.ps1
Bazelisk and Mercurial(on Windows) versions are blanked lines currently.
This PR fixes output scripts.
=> Fix bazelisk and mercurial output in readme

images/linux/scripts/installers/preimagedata.sh, images/linux/ubuntu1604.json, images/linux/ubuntu1804.json, images/win/Windows2016-Azure.json, images/win/Windows2019-Azure.json, images/win/scripts/Installers/Update-ImageData.ps1
Request info: https://github.com/actions/virtual-environments-internal/issues/208
Provide more virtual environment details in the runner. 
- The OS version
- The image version
- A link to the markdown file with image details
Default file path for imagedata.json:
| Name | Path| Packer Variable | Packer script |
|--------|------|------------------|---------------|
| Ubuntu 16.04 | /imagegeneration/imagedata.json | imagedata_file | installers/preimagedata.sh |
| Ubuntu 18.04 | /imagegeneration/imagedata.json | imagedata_file | installers/preimagedata.sh |
| Windows Server 2016 | C:\imagedata.json | imagedata_file | Installers/Update-ImageData.ps1 |
| Windows Server 2019 | C:\imagedata.json | imagedata_file | Installers/Update-ImageData.ps1 |
| macOS 10.15 | /Users/runner/imagedata.json | - | …
=> Add additional agent info

images/win/scripts/Installers/Install-Firefox.ps1, images/win/scripts/Installers/Validate-SeleniumWebDrivers.ps1
There are two more issues that were not resolved in https://github.com/actions/virtual-environments/pull/509
Changes:
- Add path creation to geckodriver installation
- Swap IEDriver and ChromeDriver versions
=> Another WebDrivers output fix for Windows

images/win/Windows2016-Azure.json, images/win/Windows2019-Azure.json, images/win/scripts/Installers/Install-Go.ps1, images/win/scripts/Installers/Validate-Go.ps1
- install latest golang version for windows
#63 
#458
=> Install latest patch versions of golang for windows

images/win/scripts/Installers/Install-Docker.ps1, images/win/scripts/Installers/Validate-Docker.ps1
- Add installation and validation of helm
Green image (deployed and tested) - https://github.visualstudio.com/virtual-environments/_build/results?buildId=62474&view=results
=> Add helm installation

images/win/scripts/Installers/Windows2019/Install-VS2019.ps1
Added Windows 10 SDK (10.0.14393.795) to Windows 2019 environment.
Issue: #451
=> Add Windows 10 SDK (10.0.14393.795) to Windows 2019 environment

images/win/Windows2016-Azure.json, images/win/Windows2019-Azure.json
See https://github.com/actions/virtual-environments/issues/579
=> Solve error with Set-ExecutionPolicy

images/linux/scripts/installers/rust.sh, images/win/scripts/Installers/Install-Rust.ps1
Close Linux and Windows part of #600.
=> rust: Use rustup's minimal profile

images.CI/credscan-exclusions.json
Added new file to ignore hardcoded passwords.
=> Added credscan file to ignore SQL Express pass

images/win/scripts/Installers/Validate-SQLExpress.ps1
seems to be a copy-paste error resulting in strange documentation
=> use the right software name

images/linux/scripts/installers/cmake.sh
The newest version of CMake adds some nice new features, but is missing on the linux environments. I've simply updated the version number in the install script.
=> Update CMake to 3.17.0 on all environments

images/linux/scripts/installers/1804/containers.sh, images/linux/ubuntu1804.json
Signed-off-by: phozzy <arthur.fayzullin@gmail.com>
A pull request for issue #320
=> Add installation of container tools

.github/ISSUE_TEMPLATE/tool-request.md
Feature Request Improvment.
Added two useful fields which help us to make a decision: add package or not.
- [+] Documentation is updated
=> Feature request: Added Tool license/Installation time.

images/win/scripts/Installers/Install-AzureModules.ps1, images/win/scripts/Installers/Validate-AzureModules.ps1
This new version contains a few new commands that 3.5.0 does not have: https://www.powershellgallery.com/packages/Az/3.8.0
=> Upgrade to Az 3.8

images/win/scripts/Installers/Validate-Rust.ps1
Update documentation. Fix formatting only. No chance in content.
=> Windows2019-Readme.md: Fix formatting of Rust-section.

images/linux/scripts/installers/validate-disk-space.sh
We can't get through 18432Mb now.
=> [Ubuntu] low free disk space limit

images/linux/scripts/installers/1804/containers.sh
A fix for documentation in #320
=> Fix documentation for containertools

images/linux/scripts/installers/cmake.sh
Bug fix: Fix minor glitch in cmake installer message text.
=> Fix minor glitch in cmake installer message

images/macos/macos-10.15-Readme.md
- Node.js v12.16.3
- NVM - Cached node versions: v12.16.3 v13.14.0
- Homebrew 2.2.14
- Curl 7.70.0
- Cmake 3.17.2
- Azure CLI 2.5.1
- AWS CLI 2.0.10
- AWS SAM CLI 0.48.0
- Google Chrome 81.0.4044.129 
- Microsoft Edge 81.0.416.68 
- MSEdgeDriver 81.0.416.68
- 2.7.18
- 3.7.7
| Version          | Build   | Path                              |
| ---------------- | ------- | --------------------------------- |
| 11.5 (beta)      | 11N605c | /Applications/Xcode_11.5_beta.app |
=> macOS software updates week19

images/win/scripts/Installers/Install-DACFx.ps1
Improvement
I have changed link for DACFx installation which is pointing to actual version.
https://github.com/actions/virtual-environments/issues/850
=> SQL Server Data-Tier Application Framework latest upgrade.

images/linux/scripts/installers/haskell.sh
Update the version of stack, as it fixes several issues related with haddock, Cabal 3, etc.
As far as I searched, there is no related issue.
I'm not on Windows, and I don't know how to use `ps1` under linux.
=> Update Haskell tool Stack

images/win/scripts/Installers/Validate-Boost.ps1
Added a special note for setting BOOST_ROOT variable since CMake requires it.
=> Update Boost documentation

images/win/Windows2016-Azure.json, images/win/Windows2019-Azure.json, images/win/scripts/Installers/Install-GitHub-CLI.ps1, images/win/scripts/Installers/Validate-GitHub-CLI.ps1
New tool
Installation size: 16.5Mb
Installation time:  5 sec
=> Install GitHub CLI on Windows images

images/linux/scripts/installers/azpowershell.sh
Added support for PowerShell Az Module 3.8.0
This allows to leverage the new APIs introduced in 3.8.0
=> Support for Az Module (3.8.0)

images/win/scripts/ImageHelpers/InstallHelpers.ps1, images/win/scripts/Installers/Install-ContainersFeature.ps1, images/win/scripts/Installers/Validate-WDK.ps1
Replace `Get-WmiObject` with `Get-CimInstance`
=> Replace use of deprecated WMI v1 cmdlets

images/linux/scripts/installers/kind.sh, images/win/scripts/Installers/Install-Kind.ps1
Remove hard-coded Kind version and use GitHub kind repo as the source to get the latest version
https://github.com/actions/virtual-environments/issues/952
=> Update kind to the latest version

images/linux/scripts/installers/haskell.sh
Refactor installation for readability
No issue, just a common sense 😀
- [N\A] Related issue / work item is attached
=> [Ubuntu] Refactor haskell install script

images/linux/scripts/helpers/install.sh, images/linux/scripts/installers/pypy.sh
Added helper function for retry to download file.
Internal issue: [#588](https://github.com/actions/virtual-environments-internal/issues/588)
=> Add download retry helper on Ubuntu

images/linux/scripts/installers/docker-compose.sh
Update to new stable version of docker-compose:
https://github.com/docker/compose/releases/tag/1.25.5
=> update docker-compose version

images/win/Windows2016-Azure.json, images/win/Windows2019-Azure.json, images/win/scripts/Installers/Install-MongoDB.ps1, images/win/scripts/Installers/Validate-MongoDB.ps1
New tool
Install MongoDB
**total size:** 930MB
**installation time:** less than a minute
https://github.com/actions/virtual-environments/issues/20
=> Install MongoDB on Windows images

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/tool-request.md, README.md
Update readme file to include Ubuntu 20.04 that was recently added to GitHub Actions and Azure DevOps
=> Add Ubuntu 20.04 to readme

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
=> Add missing array comma in SoftwareReport.Generator.ps1

images/win/scripts/Installers/Finalize-VM.ps1
=> Fix typo in comment

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1
=> Fix Get-VisualStudioExtensions function name typo

images/linux/scripts/installers/1604/basic.sh, images/linux/scripts/installers/basic.sh
Add a few linux utilities.
Size: ~ 3 Mb
Time: ~ 1 min
#986
=> Add linux utils

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
We've missed sbt in software report generator, this PR fixes it.
n\a
=> [Windows] Add sbt to software report generator

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
Improvement
Added additional column for .NET 4.8,4.72 package type.
https://github.com/actions/virtual-environments/issues/953
- [+] Documentation is updated (if applicable)
- [-] Changes are tested and related VM images are successfully generated
=> .NET: Add package type for Windows Readme.

images/win/Windows2016-Readme.md
+ Image Version: 20200614.1  
+ Rust 1.44.0  
+ PHP 7.4.7  
+ PowerShell 7.0.2  
+ Helm 3.2.3  
+ Gradle 6.5  
+ Azure CosmosDb Emulator 2.11.1.0  
+ Bazelisk 1.5.0  
+ Packer 1.6.0  
+ azcopy 10.4.3  
+ AWS CLI 2.0.22  
+ Microsoft Edge 83.0.478.45  
+ Microsoft Edge Driver 83.0.478.45  
+ | Visual Studio Enterprise 2017 | 15.9.28307.1177 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise |  
+ | Component.Xamarin                                                         | 15.9.28307.1177  |  
+ 1.1.14 2.1.300 2.1.301 2.1.302 2.1.401 2.1.402 2.1.403 2.1.500 2.1.502 2.1.503 2.1.504 2.1.505 2.1.506 2.1.507 2.1.508 2.1.509 2.1.510 2.1.511 2.1.512 2.1.513 2.1.514 2.1.515 2.1.602 2.1.603 2.1.604 2.1.605 2.1.606 2.1.607 2.1.608 2.1.609 2.1.610 2.1.611 2.1.612 2.1.700 2.1.701 …
=> [Software update] Windows Server 2016 (20200614 update) Week 25

images/linux/scripts/helpers/install.sh
Bug fixing 
Added `compressed` flag to helper.
#1066
=> Fix retry download helper function

images/win/Windows2016-Readme.md
+ Image Version: 20200621.1  
+ Rust 1.44.1  
+ PHP 7.4.7  
+ PowerShell 7.0.2  
+ Node 12.18.1  
+ NPM 6.14.5  
+ Helm 3.2.4  
+ NuGet 5.6.0.6591  
+ Gradle 6.5  
+ sbt 1.3.12  
+ Azure CosmosDb Emulator 2.11.1.0  
+ Bazel 3.3.0  
+ Bazelisk 1.5.0  
+ Packer 1.6.0  
+ azcopy 10.4.3  
+ AWS CLI 2.0.24  
+ AWS SAM CLI 0.53.0  
+ Google Chrome 83.0.4103.106  
+ Microsoft Edge 83.0.478.54  
+ Microsoft Edge Driver 83.0.478.54  
+ | 12.18.1 | x64          |  
+ | 4.2.8.0 | MongoDB     | Running       | Automatic        |  
+ | Visual Studio Enterprise 2017 | 15.9.28307.1177 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise |  
+ | Component.Xamarin                                                         | 15.9.28307.1177  |  
+ 1.1.14 2.1.300 2.1.301 2.1.302 2.1.401 2.1.402 …
=> [Software update] Windows Server 2016 (20200621 update) Week 26

images/win/Windows2019-Readme.md
+ Image Version: 20200621.1  
+ Rust 1.44.1  
+ PHP 7.4.7  
+ PowerShell 7.0.2  
+ Node 12.18.1  
+ NPM 6.14.5  
+ Helm 3.2.4  
+ NuGet 5.6.0.6591  
+ sbt 1.3.12  
+ Azure CosmosDb Emulator 2.11.1.0  
+ Bazel 3.3.0  
+ Packer 1.6.0  
+ azcopy 10.4.3  
+ AWS CLI 2.0.24  
+ AWS SAM CLI 0.53.0  
+ Google Chrome 83.0.4103.106  
+ Microsoft Edge 83.0.478.54  
+ Microsoft Edge Driver 83.0.478.54  
+ | 12.18.1 | x64          |  
+ | 4.2.8.0 | MongoDB     | Running       | Automatic        |  
+ | ----------------------------- | -------------- | -------------------------------------------------------------- |  
+ | Visual Studio Enterprise 2019 | 16.6.30204.135 | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise |  
+ | Component.Android.NDK.R16B …
=> [Software update] Windows Server 2019 (20200621 update) Week 26

images/win/Windows2019-Readme.md
+ OS Version: 10.0.17763 Build 1282  
+ Image Version: 20200630.0  
+ Java 1.8.0_252 (default)  
+ Java 11.0.7   
+ Java 13.0.2   
+ Python 3.7.8  
+ Composer 1.10.8  
+ sbt 1.3.13  
+ Bazel 3.3.1  
+ Kubectl 1.18.5  
+ Azure CLI 2.8.0  
+ AWS CLI 2.0.26  
+ Google Cloud SDK 299.0.0  
+ Google Chrome 83.0.4103.116  
+ Microsoft Edge 83.0.478.56  
+ Microsoft Edge Driver 83.0.478.58  
+ Mozilla Firefox 78.0  
+ | 3.7.8 (Default) | x64, x86     |  
+ | Version | UserName | Password | EnvironmentVariables                                                                                                                  | Path                           | ServiceName       | ServiceStatus | ServiceStartType |  
+ | ------- | -------- | -------- | …
=> [Software update] Windows Server 2019 (20200630 update) Week 27

images/win/Windows2016-Readme.md
+ OS Version: 10.0.14393 Build 3750  
+ Image Version: 20200628.0  
+ Java 1.8.0_252 (default)  
+ Java 11.0.7   
+ Java 13.0.2   
+ Composer 1.10.8  
+ Kubectl 1.18.5  
+ Azure CLI 2.8.0  
+ AWS CLI 2.0.26  
+ Google Cloud SDK 298.0.0  
+ Google Chrome 83.0.4103.116  
+ Microsoft Edge 83.0.478.56  
+ Microsoft Edge Driver 83.0.478.56  
+ | Version | UserName | Password | EnvironmentVariables                                                                                                                  | Path                           | ServiceName       | ServiceStatus | ServiceStartType |  
+ | ------- | -------- | -------- | ------------------------------------------------------------------------------------------------------------------------------------- | …
=> [Software update] Windows Server 2016 (20200628 update) Week 27

images/win/scripts/Installers/Install-AzureCli.ps1
Minor fix to remove unused temporary $Env:AZURE_EXTENSION_DIR variable
=> Minor fix to remove unused temporary $Env:AZURE_EXTENSION_DIR variable

images/linux/scripts/installers/rust.sh
- Add cargo-outdated
- Add cargo-audit
https://github.com/actions/virtual-environments/issues/1029
- [ubuntu1604](https://github.visualstudio.com/virtual-environments/_build/results?buildId=74783&view=results)
- [ubuntu1804](https://github.visualstudio.com/virtual-environments/_build/results?buildId=74784&view=results)
- [ubuntu2004](https://github.visualstudio.com/virtual-environments/_build/results?buildId=74785&view=results)
=> Add cargo packages for Linux

images/win/scripts/Installers/Install-Rust.ps1, images/win/scripts/Installers/Validate-Rust.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
- Add cargo-outdated
- Add cargo-audit
https://github.com/actions/virtual-environments/issues/1029
- [windows16](https://github.visualstudio.com/virtual-environments/_build/results?buildId=74845&view=results)
- [windows19](https://github.visualstudio.com/virtual-environments/_build/results?buildId=74844&view=results)
=> Add cargo packages for windows

images/linux/scripts/helpers/document.sh
Bug fixing
Improve back tick screening in order to produce correct markdown
=> Fix StartCode/EndCode markup

images/linux/scripts/installers/php.sh
=> Fix Readme.md generation

.github/ISSUE_TEMPLATE/tool-request.md
Adding a basic test case request for new tools to the issue template.
- [N\A] Changes are tested and related VM images are successfully generated
=> Add a request about basic test case to the issue template

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/tool-request.md, README.md, images.CI/azure-pipelines/ubuntu1604.yml, images.CI/azure-pipelines/ubuntu1804.yml, images.CI/azure-pipelines/ubuntu2004.yml, images.CI/azure-pipelines/windows2016.yml, images.CI/azure-pipelines/windows2019.yml
Switch from master to main branch
=> Switch default branch from master to main

images/linux/scripts/installers/r.sh, images/linux/ubuntu1604.json, images/linux/ubuntu1804.json, images/linux/ubuntu2004.json
- Add R language and tools
https://github.com/actions/virtual-environments/issues/1220
=> Add R tool for linux

images/linux/scripts/installers/1604/android.sh, images/linux/scripts/installers/1804/android.sh, images/linux/scripts/installers/2004/android.sh
=> Add Android SDK Build-Tools 30.0.1 to Ubuntu

images/linux/scripts/installers/aws-sam-cli.sh, images/linux/ubuntu1604.json, images/linux/ubuntu1804.json, images/linux/ubuntu2004.json
Bug fixing: build `AWS SAM CLI`  with copy of Python toolcache to aviod installation of third party packages into toolcache. 
#1202
=> Copy Python for build aws sam cli

CONTRIBUTING.md
Update documentation to include more details about contribution to Windows images
=> Update Windows contribution guide

images/linux/scripts/installers/r.sh
- fix version for R, to install latest version
https://github.com/actions/virtual-environments/issues/1220
=> Latest R version

images/linux/scripts/installers/netlify.sh, images/linux/ubuntu1604.json, images/linux/ubuntu1804.json, images/linux/ubuntu2004.json
Add `netlify-cli` to the 3 Linux images.
#1289
=> Add Netlify CLI to Linux images

images/linux/scripts/installers/1604/android.sh, images/linux/scripts/installers/1804/android.sh, images/linux/scripts/installers/2004/android.sh
Set proper permissions for whole /usr/local/lib/android folder
#1337 
- Ubuntu 1604: https://github.visualstudio.com/virtual-environments/_build/results?buildId=78163&view=results
- Ubuntu 1804: https://github.visualstudio.com/virtual-environments/_build/results?buildId=78164&view=results
- Ubuntu 2004: https://github.visualstudio.com/virtual-environments/_build/results?buildId=78162&view=results
=> Set permissions to ANDROID_HOME directory

images/linux/scripts/installers/kubernetes-tools.sh
Add `kustomize` to the 3 Linux images.
https://github.com/actions/virtual-environments/issues/1414
=> Add Kustomize to the 3 Linux images.

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/tool-request.md
- Set needs triage label using template
- Add repro steps section to bug template
=> Improve issue templates: repro steps and labels

images/win/scripts/Tests/Browsers.Tests.ps1
Get chrome path from the registry instead of hard-coded value.
https://github.com/actions/virtual-environments-internal/issues/1037
=> [Windows] Get chrome path from registry

images/win/scripts/Installers/Install-GoogleCloudSDK.ps1, images/win/scripts/Tests/Tools.Tests.ps1
=> Fix GoogleCloudSDK test name typo

images/win/scripts/Installers/Install-DACFx.ps1
Updating DacFx from 18.5 to 18.5.1
=> update dacfx to 18.5.1

images/linux/scripts/installers/kubernetes-tools.sh
New tool, Bug fixing, or Improvement?  Improvement
Install kustomize without Snap, as documented here: https://github.com/actions/virtual-environments/issues/1514
=> Install kustomize without snap

.github/workflows/create_github_release.yml, .github/workflows/create_pull_request.yml, .github/workflows/merge_pull_request.yml, .github/workflows/update_github_release.yml
- Added bot's approve step before merging software docs PR.
- Method of merging sets to `squash`
- Changed job names on workflows
Test approve: https://github.com/vsafonkin/test-repo/pull/3
Test merge with squash: https://github.com/vsafonkin/test-repo/pull/4
Internal issue: [#1093](https://github.com/actions/virtual-environments-internal/issues/1093)
=> Add approve by Actions bot to software docs PR

CONTRIBUTING.md
Updating Ubuntu contribution guide as now we have different approach for Software doc generation.
=> Update Ubuntu contribution guide

images/win/scripts/SoftwareReport/SoftwareReport.Android.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
Improve documentation for Android on Windows to present it in more convenient way.
The result: 
[Improve documentation for Android tools on Windows and MacOS](https://github.com/actions/virtual-environments-internal/issues/1073)
=> Improve documentation for Android on Windows

help/CreateImageAndAzureResources.md, helpers/GenerateResourcesAndImage.ps1
I hope you guys are merging into `main` and do not have another develop branch 🤔 ?
- Using new `Azure` ps module in `GenerateResourcesAndImage.ps1`.
- Updated the documentation to state that this module is required.
- #1633
=> using azure module in ps script, adjusted documentation

images/linux/ubuntu1604.json, images/linux/ubuntu1804.json, images/linux/ubuntu2004.json, images/win/Windows2016-Azure.json, images/win/Windows2019-Azure.json
Reformat JSON Packer files using the default JSON formatter baked into Visual Studio Code.
Allows taking advantage of automatic JSON formatting to ensure consistent formatting across all JSON files, allowing me to focus on features instead.
None
=> refactor: auto format JSON using VSC

.github/workflows/linter.yml
Improvement
The PR adds a check on pool requests JSON and Markdown files are syntactically correct.
=> Add json & md linting with github/super-linter

images/macos/provision/core/openssl.sh
- add import utils for openssl.sh on macOS
=> Add import utils for openssl.sh

images/macos/tests/Xcode.Tests.ps1
Fix Xcode test execution on MacOS images
=> Fix Xcode test execution on MacOS images

images/macos/provision/configuration/configure-machine.sh
Recently, we disabled spotlight indexing to reduce CPU usage. In scope of this PR we are reverting this change since customers started facing with the issues after that.
=> [macOS] Enable spotlight indexing

images/macos/provision/core/android-toolsets.sh, images/macos/provision/utils/utils.sh, images/macos/software-report/SoftwareReport.Android.psm1, images/macos/tests/Android.Tests.ps1, images/macos/toolsets/toolset-10.13.json, images/macos/toolsets/toolset-10.14.json, images/macos/toolsets/toolset-10.15.json, images/macos/toolsets/toolset-11.0.json
In this pull request we add logic to install android tools dynamic for macOS.
=> [macOS] Retrieve the list of Android packages for installing dynamically

.github/workflows/issue-triager.yml
Fixed label case in comparison
=> Fixed label comparison in issue-triager

images/macos/provision/utils/xcode-utils.sh
=> Update Xcode 12 to 12.0.1

images/macos/provision/core/openssl.sh, images/macos/provision/core/python.sh
Related issues:
- https://github.com/actions/virtual-environments/issues/1869
- https://github.com/actions/virtual-environments/issues/1811
Untap local formulas to prevent issues on brew update
=> Untap local formulas to fix "brew update" command

images/win/scripts/Installers/Install-VS.ps1
The issue has been fixed, we don't need this workaround anymore.
=> Revert "[windows] Temporary workaround for VS installation"

images/linux/scripts/installers/post-deployment.sh
In scope of this PR we are cleaning yarn and npm cache on Ubuntu Images. See details in related issue.
=> [Ubuntu] Clean yarn and npm cache

images/win/scripts/Installers/Finalize-VM.ps1
In scope of this PR we are cleaning yarn and npm cache. See details in related issue.
=> [Windows] Clean yarn and npm cache

.github/ISSUE_TEMPLATE/announcement.md
Adding template for announcement issues
=> Add announcement template

images/macos/provision/utils/xcode-utils.sh
The new Xcode has arrived.
https://developer.apple.com/news/releases/?id=10302020c
n\a
=> [macOS] Change Xcode 12.1 to 12.1.1 rc

images/macos/macos-10.13-Readme.md, images/macos/macos-10.14-Readme.md
Improvement
Added actual 10.13/10.14 readme files to virtual-environments repo
- [-] Related issue / work item is attached
=> Added 10.13/10.14 readme files to macos folder.

images/win/scripts/Installers/Finalize-VM.ps1
Bug fixing
MSI requires full access to C:\Windows\Temp
=> Give full access to Temp folder

images/linux/scripts/installers/powershellcore.sh
Reverts actions/virtual-environments#1965
=> Revert "[Ubuntu] Install pwsh using dotnet tool"

images/macos/provision/assets/select-xamarin-sdk.sh, images/macos/provision/core/pipx-packages.sh, images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
Improvement
Add too docker information listed in Software report the docker digest and age.
=> Print more informantion about cached Docker images on Windows

images/win/scripts/Installers/Configure-Shell.ps1, images/win/scripts/Installers/Install-Msys2.ps1, images/win/scripts/Tests/Shell.Tests.ps1
Reverts actions/virtual-environments#1937
=> Revert "[Windows] Add bash wrapper from git"

images/win/scripts/Installers/Install-WinAppDriver.ps1
winapp driver 1.2.1 has been recently released and we need to update it
https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1
n\a
=> [windows] Update winapp driver to 1.2.1

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
Windows Server 2019 [10.0.17763] supports only WSLv1. 
https://github.com/actions/virtual-environments/issues/2060
=> [Windows] Update WSLv1 version

images/win/post-generation/InternetExplorerConfiguration.ps1
Turn off IE ESC during running post-generation process.
https://github.com/actions/virtual-environments-internal/issues/1338
=> [Post-Generation] Turn off IE ESC factory script

images/linux/scripts/installers/gfortran.sh
Improvement.
gfortran-10 installation has been added to Ubuntu 18/20 image deployment.
https://github.com/actions/virtual-environments/issues/1796
=> gfortran-10 has been added

images/linux/post-generation/cleanup-logs.sh
Add cleanup-logs.sh post-generation script.
https://github.com/actions/virtual-environments-internal/issues/943
=> [Ubuntu] Add cleanup-logs.sh post-generation script

images/linux/scripts/installers/containers.sh, images/linux/scripts/installers/erlang.sh, images/linux/scripts/installers/google-chrome.sh, images/linux/scripts/installers/google-cloud-sdk.sh, images/linux/scripts/installers/java-tools.sh, images/linux/scripts/installers/postgresql.sh
In scope of this PR we are replacing http to https.
=> [Ubuntu] Replace http to https

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
Improvement
In order to make it more clear, I've added the following topics to software report for ubuntu:
https://github.com/actions/virtual-environments/issues/2134
=> [Ubuntu] Powershell Tools/Modules software report.

images/macos/provision/core/gcc.sh, images/macos/software-report/SoftwareReport.Common.psm1, images/macos/tests/Common.Tests.ps1
Add gfortran-10 and remove the default gfortran symlink from PATH.
https://github.com/actions/virtual-environments/issues/2176
=> [macOS] Add gfortran-10

help/CreateImageAndAzureResources.md
Added git to the requirements
Fixed clone location (as further is referenced to c:\ )
Fixed import of modules (current command gives error! )
=> added git, fixed clone location, fixed import of modules

README.md
Updated README with information about usage of discussions
=> Update README with "how to contact us" guide

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/linux/toolsets/toolset-1604.json, images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
Adds `pass` package
Fixes #2302 
cc. @maxim-lobanov
=> [Ubuntu] Add pass package

images/win/windows2016.json, images/win/windows2019.json
Packer started to disconnect from the generation after about 20 minutes, with old spec everything is fine, need to revert until further investigation is done.
=> Revert "[Windows] Change vm spec to Standard_D8s_v4"

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/macos/software-report/SoftwareReport.Common.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
In scope of this PR we are fixing Vcpkg version output on all images
=> Fix Vcpkg output

images/linux/scripts/installers/haskell.sh, images/linux/scripts/tests/Common.Tests.ps1
Added Pester tests for Haskell on Ubuntu.
=> [Ubuntu] Migrate tests for Haskell to Pester

README.md
Add two sections to README:
- ***What images are available for GitHub Actions and Azure DevOps?***
- ***What image version is used in my build?***
Corrected **Regular Weekly Rhythm**
=> Update readme to include more information about image availability

images/macos/software-report/SoftwareReport.Common.psm1, images/macos/software-report/SoftwareReport.Generator.ps1, images/macos/software-report/SoftwareReport.Xcode.psm1
Rework MacOS documentation to be consistent with Ubuntu and Windows tests
[Rework MacOS documentation to be consistent with Ubuntu and Windows tests #1604](https://github.com/actions/virtual-environments-internal/issues/1604)
[macOS-10.14](https://github.visualstudio.com/virtual-environments/_build/results?buildId=93586&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=0cc083f2-e4b4-5c2b-a1d7-966043ae867c), [macOS-10.15](https://github.visualstudio.com/virtual-environments/_build/results?buildId=93587&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=0cc083f2-e4b4-5c2b-a1d7-966043ae867c), [macOS-11.0](https://github.visualstudio.com/virtual-environments/_build/results?buildId=93584&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=0cc083f2-e4b4-5c2b-a1d7-966043ae867c)
=> Rework MacOS documentation

images.CI/macos/move-vm.ps1
Fixed comment with appropriate variable names.
=> Fixed a comment

images/linux/scripts/installers/java-tools.sh, images/linux/scripts/tests/Java.Tests.ps1, images/linux/toolsets/toolset-1604.json, images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
Moved the list of installed Java versions to toolset on Ubuntu
[#1635](https://github.com/actions/virtual-environments-internal/issues/1635)
=> [Ubuntu] Move the list of installed Java versions to toolset 

images/win/scripts/Installers/Install-JavaTools.ps1, images/win/scripts/Tests/Java.Tests.ps1, images/win/toolsets/toolset-2016.json, images/win/toolsets/toolset-2019.json, images/win/windows2016.json
Moved the list of installed Java versions to toolset on Windows
[#1635](https://github.com/actions/virtual-environments-internal/issues/1635)
=> [Windows] Move the list of installed Java versions to toolset

images/linux/scripts/base/apt.sh
Bug fixing / Improvement
The purge will remove any leftovers configuration files, including /etc/apt/apt.conf.d/20auto-upgrades.
=> [ubuntu] Purge unattended upgrades

images.CI/macos/move-vm.ps1
Invoke command to change specs for a vm should be invoked after shutdown operation.
=> [Image.CI] Change vm spec after shutdown

images/linux/scripts/SoftwareReport/SoftwareReport.Android.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Android.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
In scope of this PR we are sorting tool names inside each category in alphabetical order.
=> [Windows] Sort tool names in README

images/linux/scripts/SoftwareReport/SoftwareReport.Android.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
Sort tool names in Alphabetical order inside each category in README of Ubuntu
[#1665](https://github.com/actions/virtual-environments-internal/issues/1665)
=> [Ubuntu] Sort tool names in README

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
The Perl package manager
Simply detecting the version of a tool that's already present.
=> Adds detection of cpan version

images/win/Windows2019-Readme.md
=> Revert "Windows Server 2019 (20210110 update)"

images/win/Windows2016-Readme.md
=> Revert "Windows Server 2016 (20210110 update)"

images/linux/Ubuntu1604-README.md
=> Revert "Ubuntu 1604 (20210111 update)"

images/linux/Ubuntu2004-README.md
=> Revert "Ubuntu 2004 (20210111 update)"

images/linux/Ubuntu1804-README.md
=> Revert "Ubuntu 1804 (20210111 update)"

images/macos/toolsets/toolset-10.15.json, images/macos/toolsets/toolset-11.0.json
Xcode 12.4 RC released https://developer.apple.com/documentation/xcode-release-notes/xcode-12_4-rc-release-notes/
n\a
=> [macOS] Add Xcode 12.4

images/win/scripts/Installers/Install-Git.ps1
In scope of this PR we are switching Git installation to use `choco` formula. See details in related issue.
=> [Windows] Install Git using choco

images/macos/provision/core/commonutils.sh
We've faced issue related Bazel 4.0.0. Please see: https://github.com/bazelbuild/bazel/pull/12882
We've decided to hardcode the `3.7.1` version of Bazel for the macOS images less than macOS 1015.
=> [macOS] Fix Bazel issue

.github/ISSUE_TEMPLATE/bug-report.md
Updating bug report with Image Version field because we have to ask for it pretty often.
=> Add Image Version field to bug template

images/macos/provision/core/openjdk.sh
- XCode 12.4 (already added to toolset.json)
- Zulu OpenJDK 7.44.0.11
https://github.com/actions/virtual-environments-internal/issues/1755
=> [macOS] Software updates week 5 2021

.github/ISSUE_TEMPLATE/config.yml
In scope of this pull request we add `config.yml` in `ISSUE_TEMPLATE` to restrict creation of blank issues.
- config.yml: https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
=> Add config.yml to restrict creation of blank issues

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
Sort docker images by name in documentation to reduce diff noise: https://github.com/actions/virtual-environments/pull/2709/files#diff-13c32e50a93846c2ce39a041f2893dad4ddf1263edaac708ffff365379473d21R272
=> Sort docker images by name in documentation

images/macos/helpers/Xcode.Helpers.psm1, images/macos/helpers/Xcode.Installer.psm1
Improvement
Helper function for execution of `xcversion` with more than one attempt.
https://github.com/actions/virtual-environments-internal/issues/1795
=> Helper function for execution of xcversion with more than one attempt.

images/linux/ubuntu1604.json, images/linux/ubuntu1804.json, images/linux/ubuntu2004.json, images/win/windows2016.json, images/win/windows2019.json
=> Revert "[Windows, Ubuntu] Temporarily switch VM size to V2"

images.CI/macos/select-datastore.ps1
The previous approach wasn't so good as we thought — this one is much better 🤞
https://github.com/actions/virtual-environments-internal/issues/1864
=> [macOS] Improve select-datastore script rev2

images/linux/scripts/installers/preimagedata.sh, images/macos/provision/configuration/preimagedata.sh, images/win/scripts/Installers/Update-ImageData.ps1
In scope of this PR we are adding a link to the image release in logs.
=> Provide a link to the image release in logs

images/linux/scripts/installers/php.sh
Bug fixing 
This fixes php extension setup by switching to versioned packages for all extensions.
=> [Ubuntu] Fix PHP extensions

images/win/scripts/Installers/Install-Zstd.ps1
Changes:
- Update zstd to 1.4.9
- Use https://github.com/facebook/zstd releases
https://github.com/actions/virtual-environments/issues/2858
=> [Windows] Update zstd to 1.4.9

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
Documentation improvement. update oc CLI to OpenShift CLI (oc) similar to other CLIs in the Ubuntu image documentation
https://github.com/actions/virtual-environments/pull/2692
=> Update oc CLI to OpenShift CLI

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/helpers/Common.Helpers.psm1
It's useful to have this data since the issues can be related to the kernel version — https://github.com/actions/virtual-environments/issues/2848
https://github.com/actions/virtual-environments-internal/issues/1930
=> [Ubuntu] Add Linux kernel version to software report

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
We provide OpenSSL version in macOS and windows readme but not in Ubuntu one.
https://github.com/actions/virtual-environments/issues/2977
=> [Ubuntu] Add openssl to software readme

images/linux/scripts/SoftwareReport/SoftwareReport.WebServers.psm1
Improvement
I documented Mono web server
=> Update Ubuntu documentation to include mono web-server

images/macos/provision/core/openjdk.sh, images/macos/software-report/SoftwareReport.Java.psm1
In scope of this pull request we edit logic to replace '+' in java version path to '-'.
=> [macOS] Replace '+' from java version folder to '-'

images/linux/scripts/installers/pipx-packages.sh
Install ansible into an existing ansible-base Virtual Environment
Builds:
https://github.visualstudio.com/virtual-environments/_build/results?buildId=103171&view=results
https://github.visualstudio.com/virtual-environments/_build/results?buildId=103172&view=results
https://github.com/actions/virtual-environments-internal/issues/1976
=> [Ubuntu] inject ansible pkg

images/linux/scripts/SoftwareReport/SoftwareReport.Java.psm1
In scope of this PR we are sorting Java versions order in README.
=> [Ubuntu] Sort Java versions order in README

images/linux/scripts/installers/google-chrome.sh
Rework Chrome installation to avoid using apt `https://dl.google.com/linux/chrome/deb/` source.
https://github.com/actions/virtual-environments-internal/issues/1958
=> [Ubuntu] Rework Chrome installation to avoid using apt source

images/linux/scripts/installers/aws.sh
- suppress unzip messages
- use the download_with_retries helper function
e.g. build:
https://github.visualstudio.com/virtual-environments/_build/results?buildId=103242&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043
lines: 11239 -   4621(azure-arm: Archive:  awscliv2.zip) = 6618
=> [Ubuntu] suppress unzip messages in aws.sh script

images/linux/scripts/installers/Install-AzureModules.ps1
- disable verbose parameter to suppress messages
=> [Ubuntu] Disable verbose parameter in Install-AzureModules.ps1

images/linux/scripts/installers/android.sh, images/linux/scripts/installers/google-chrome.sh, images/linux/scripts/installers/java-tools.sh, images/linux/scripts/installers/packer.sh, images/linux/scripts/installers/terraform.sh
Suppress unzip messages in a packer log:
- android.sh
- google-chrome.sh
- java-tools.sh
- packer.sh
- terraform.sh
=> [Ubuntu] Suppress unzip messages in a packer log

images/linux/scripts/installers/aliyun-cli.sh, images/linux/scripts/installers/aws-sam-cli.sh, images/linux/scripts/installers/azcopy.sh, images/linux/scripts/installers/git.sh, images/linux/scripts/installers/oc.sh, images/linux/scripts/installers/oras-cli.sh, images/linux/scripts/installers/phantomjs.sh, images/linux/scripts/installers/pulumi.sh
Suppress tar verbose messages:
- aliyun-cli.sh
- aws-sam-cli.sh
- azcopy.sh
- git.sh
- oc.sh
- oras-cli.sh
- phantomjs.sh
- pulumi.sh
=> [Ubuntu] Suppress tar verbose messages

images/linux/scripts/installers/aliyun-cli.sh, images/linux/scripts/installers/android.sh, images/linux/scripts/installers/aws-sam-cli.sh, images/linux/scripts/installers/clang.sh, images/linux/scripts/installers/containers.sh, images/linux/scripts/installers/erlang.sh, images/linux/scripts/installers/firefox.sh, images/linux/scripts/installers/github-cli.sh, images/linux/scripts/installers/java-tools.sh, images/linux/scripts/installers/phantomjs.sh, images/linux/scripts/installers/selenium.sh
- suppress wget messages to use -q parameter
- replace wget to download_with_retries helper function
https://github.com/actions/virtual-environments-internal/issues/1982
=> [Ubuntu] Replace wget to download_with_retries helper function

images/linux/toolsets/toolset-1604.json, images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
Az module 5.7 is out which fixes a critical issue about nested bicep files.
https://github.com/actions/virtual-environments/issues/2867
=> [Ubuntu] Upgrade az powershell module from 5.5.0 to 5.7.0

images/linux/scripts/SoftwareReport/SoftwareReport.Browsers.psm1, images/linux/scripts/installers/google-chrome.sh, images/linux/scripts/tests/Browsers.Tests.ps1
Renamed Chromium executable to `chromium-browser`
#3133
=> [Ubuntu] Fix Chromium installation

images.CI/linux-and-win/cleanup.ps1
We should avoid showing sensitive info in the logs.
https://github.com/actions/virtual-environments-internal/issues/1908
=> Add stream redirection to hide log output in cleanup script

images.CI/linux-and-win/cleanup.ps1
Fix error output with az option --only-show-errors
https://github.com/actions/virtual-environments/pull/3140
=> Another fix for cleanup script

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/linux/scripts/installers/homebrew.sh, images/linux/scripts/tests/Tools.Tests.ps1, images/linux/toolsets/toolset-1604.json, images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
Migrate `zstd` package installation from apt source to homebrew with the latest package release.
https://github.com/actions/virtual-environments/issues/2858
=> [Ubuntu] Install zstd homebrew

images/linux/scripts/installers/google-chrome.sh
Remove:
- /etc/cron.daily/google-chrome 
- /etc/apt/sources.list.d/google-chrome.list
- /etc/apt/sources.list.d/google-chrome.list.save
=> [Ubuntu] Remove google chrome repo

images/linux/scripts/installers/java-tools.sh, images/linux/scripts/tests/Java.Tests.ps1
In scope of this PR we are fixing `GRADLE_HOME ` environment variable
=> [Ubuntu] Fix GRADLE_HOME environment variable

helpers/CreateAzureVMFromPackerTemplate.ps1
Bug (-o json) and Improvement (naming, output)
Script failed if the default az output format had been changed.
Random naming of everything, and no summary of what was created made cleanup unnecessarily hard.
- [*] Changes are tested and related VM images are successfully generated
=> Make CreateAzureVMFromPackerTemplate friendlier

.github/workflows/issue-triager.yml
Added workflow step to check for empty spammy issues and close them automatically with comment and label.
=> Add workflow step to check if issue is spammy

README.md
=> Update `macos-11.0` to `macos-11` in README

docs/create-image-and-azure-resources.md
Add section how to install Az module section.
https://github.com/actions/virtual-environments/issues/3465
=> Add install Az module section

images/macos/software-report/SoftwareReport.Common.psm1, images/macos/software-report/SoftwareReport.Generator.ps1, images/macos/tests/Common.Tests.ps1, images/macos/toolsets/toolset-10.14.json, images/macos/toolsets/toolset-10.15.json, images/macos/toolsets/toolset-11.json
PR with swig 4.0.2 installation. Script tests have been added, also packages are installed through the homebrew package manager.
https://github.com/actions/virtual-environments/issues/3342
=> [macOS] Adding Swig

images/macos/toolsets/toolset-11.json
Xcode 13.0 beta has been released recently.
n\a
=> [macOS] Add Xcode 13.0 to Big Sur image

images/win/scripts/Installers/Install-JavaTools.ps1
When you copy a protected file to a folder on the same, or a different volume, it inherits the permissions of the target directory. However, when you move a protected file to a different location on the same volume, the file retains its access permission setting as though it is an explicit permission(in our case it's TEMP dir).
Fix: 
- Expand an archive to the hostedtoolcache folder and preserve inheritance permissions for Authenticated Users group
https://github.com/actions/virtual-environments/issues/3588
=> [Windows] Fix Java_Adopt_Jdk permissions

images/win/scripts/Installers/Install-Bicep.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/win/scripts/Tests/Tools.Tests.ps1, images/win/windows2016.json, images/win/windows2019.json
PR with bicep cli installation. Powershell script tests have been added, also packages are installed through the chocolatey package manager.
#3461
=> [Windows] Adding Bicep CLI

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/linux/scripts/installers/bicep.sh, images/linux/scripts/tests/Tools.Tests.ps1, images/linux/ubuntu1604.json, images/linux/ubuntu1804.json, images/linux/ubuntu2004.json
PR with bicep cli installation for Ubuntu images. Includes changes from #3600 for Windows.
#3461
=> [Ubuntu] Adding Bicep CLI

images/linux/Ubuntu2004-README.md
Reverts actions/virtual-environments#3623 as we rolled back the image due to the customer’s issue with gradle
=> Revert "Ubuntu 2004 (20210621 update)"

images/linux/scripts/SoftwareReport/SoftwareReport.Databases.psm1, images/linux/scripts/installers/sqlpackage.sh, images/linux/scripts/tests/Tools.Tests.ps1, images/linux/ubuntu1804.json, images/linux/ubuntu2004.json
New tool
Total size (as of current version): 104 MB after installation, 39MB of download
Installation time (as of current version): a few seconds
Note:
Using the evergreen link for sqlpackge linux package per https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download
=> [Ubuntu] Add SqlPackage

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/linux/scripts/installers/yq.sh, images/linux/scripts/tests/Tools.Tests.ps1, images/linux/ubuntu1604.json, images/linux/ubuntu1804.json, images/linux/ubuntu2004.json, images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
This is a new tool, `yq`. It is a small, popular tool to query and manipulate YAML files - equivalent to `jq` on JSON.
#3645
=> Install yq

images/win/scripts/Installers/Install-MongoDB.ps1
Version 5 potentially contains breaking changes.
Need to make an announcement before upgrading to it.
https://github.com/actions/virtual-environments/issues/3749
=> [Windows] Stick mongodb version to 4.4.7

images/linux/scripts/installers/mongodb.sh
Update MongoDB to the latest 5.0 release version.
https://github.com/actions/virtual-environments/issues/3749
=> [Ubuntu] Update MongoDB to version 5

images/macos/provision/core/mongodb.sh, images/macos/tests/Databases.Tests.ps1
Update MongoDB to the latest 5.0 release version.
https://github.com/actions/virtual-environments/issues/3749
https://github.com/actions/virtual-environments-internal/issues/2483
=> [macOS] Update MongoDB to version 5

images/linux/scripts/installers/kubernetes-tools.sh
Kubectl version is changed from 1.20.x to 0.21.x beta. In scope of this PR we are fixing installation of kubectl.
=> [Ubuntu] Fix kubectl installation

images/win/scripts/Installers/Install-DotnetSDK.ps1, images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1
Fix platform conditions by adding brackets
=> [Windows] Fix platform conditions by adding brackets

README.md
Updating README file with new Ubuntu 16.04 usage terms. No new customers are accepted to this runner.
=> Change Ubuntu 16.04 usage terms

images/win/scripts/Installers/Initialize-VM.ps1
- Disable Network Location wizard
- Disable Server Manager on Logon
https://github.com/actions/virtual-environments/issues/3874
=> [Windows] Disable network discovery popup

images/win/scripts/Installers/Install-DotnetSDK.ps1, images/win/scripts/Installers/Windows2019/Install-WSL.ps1, images/win/toolsets/toolset-2019.json, images/win/windows2019.json
=> Move WSL installation to toolsets

.github/workflows/create_pull_request.yml
Added additional steps to `create_pull_request` workflow to request [virtual-environments-akvelon](https://github.com/orgs/actions/teams/virtual-environments-akvelon) as reviewers for image update pull requests.
https://github.com/actions/virtual-environments-internal/issues/2597
=> Request Akvelon team as reviewers for image update pull requests

images/linux/scripts/installers/homebrew.sh
- Remove eval statement
- Remove HOMEBREW_SHELLENV_PREFIX=''
=> [Ubuntu] Remove eval statement

images/linux/scripts/SoftwareReport/SoftwareReport.Databases.psm1
https://wiki.postgresql.org/wiki/Postgres
=> PostgreSQL not Postgre SQL

images/linux/scripts/installers/selenium.sh
Selenium downloads will move to GitHub releases - https://www.selenium.dev/blog/2021/downloads-moving-to-github-releases/
https://github.com/actions/virtual-environments/issues/3938
=> [Ubuntu] selenium: Download selenium-server-standalone.jar from GitHub releases

images/win/scripts/Installers/Install-Selenium.ps1
Selenium downloads will move to GitHub releases - https://www.selenium.dev/blog/2021/downloads-moving-to-github-releases/
#3938
=> [Windows] win/selenium: Download selenium-server-standalone.jar from GitHub

.github/workflows/create_pull_request.yml
Bug fixing: invoking script in `github-script` task is incorrect (missing commas)
=> Fix workflow step to request PR reviewers

.github/ISSUE_TEMPLATE/announcement.yml, .github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/tool-request.yml, README.md
=> Update readme with Windows Server 2022 info

images/win/toolsets/toolset-2019.json
In scope of this PR we are adding Visual Studio 2019 component - `ComponentGroup.UWP.VC.v141`
=> [Windows] Add Visual Studio component

images/win/Windows2022-Readme.md, images/win/toolsets/toolset-2022.json
=> Windowsd Server 2022: prepull docker images

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/linux/scripts/installers/haskell.sh, images/linux/scripts/tests/Haskell.Tests.ps1
See https://github.com/actions/virtual-environments/pull/4016 for discussion and reasoning
=> Use ghcup to install GHC on linux and remove docs and profiling libs

images/win/toolsets/toolset-2016.json, images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
- Update Az module to 6.4 version
https://github.com/actions/virtual-environments/issues/4057
=> [Windows] toolset: update to Az 6.4

images/linux/scripts/installers/haskell.sh
See https://github.com/actions/virtual-environments/issues/4094
@al-cheb
=> Fix unnecessary /usr/bin/ghc symlink

images/win/scripts/Installers/Install-Kotlin.ps1, images/win/scripts/Tests/ChocoPackages.Tests.ps1, images/win/scripts/Tests/Kotlin.Tests.ps1, images/win/scripts/Tests/Tools.Tests.ps1, images/win/toolsets/toolset-2016.json, images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json, images/win/windows2016.json, images/win/windows2019.json, images/win/windows2022.json
In scope of this PR we are moving the `Kotlin `installation to a separate file with reworked installation approach.
=> [Windows] Rework Kotlin installation

images/win/scripts/ImageHelpers/InstallHelpers.ps1, images/win/scripts/Installers/Install-GDK.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/win/scripts/Tests/Tools.Tests.ps1, images/win/windows2019.json
Including latest release of the **Microsoft Game Development Kit (GDK) ( June 2021 GDK Update 2 )** to the Windows OS 2019
=> [Windows OS] Include Microsoft Game Development Kit (GDK) to image

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
Update Az 6.1.0 -> 6.4.0
https://github.com/actions/virtual-environments/issues/4057
=> [Ubuntu] az: update Az 6.1.0 -> 6.4.0

images/linux/scripts/installers/haskell.sh
Starting with 0.1.17 we can query this easier.
Same for mac.
=> [Ubuntu] Simplify ghcup code

images/macos/provision/configuration/CreateCleanAnkaTemplate.ps1
In order to generate clean templates for Anka templates, it is required to use a special script. Let's add it to the repository for further use.
https://github.com/actions/virtual-environments-internal/issues/2471
=> [macOS] Anka script for clean macOS generation.

images/macos/toolsets/toolset-10.14.json, images/macos/toolsets/toolset-10.15.json, images/macos/toolsets/toolset-11.json
=> [MacOS] Add Adoptium (Temurin-Hotspot) jdk 17 LTS

images/win/scripts/Tests/Java.Tests.ps1, images/win/toolsets/toolset-2016.json, images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
It has been released
- [ n/a ] Tests are written (if applicable)
- [ n/a ] Documentation is updated (if applicable)
- [ n/a ] Changes are tested and related VM images are successfully generated
=> [Windows] Add Adoptium (Temurin-Hotspot) jdk 17 LTS

images.CI/macos/azure-pipelines/macos12.yml, images/macos/helpers/Common.Helpers.psm1, images/macos/provision/configuration/environment/bashrc, images/macos/provision/core/commonutils.sh, images/macos/provision/core/homebrew.sh, images/macos/provision/core/miniconda.sh, images/macos/provision/core/ruby.sh, images/macos/provision/core/xcode-clt.sh, images/macos/provision/utils/utils.sh, images/macos/software-report/SoftwareReport.Generator.ps1, images/macos/software-report/SoftwareReport.Xcode.psm1, images/macos/templates/macOS-12.json, images/macos/tests/Android.Tests.ps1, images/macos/tests/BasicTools.Tests.ps1, images/macos/tests/Common.Tests.ps1, images/macos/tests/PHP.Tests.ps1, images/macos/tests/RubyGem.Tests.ps1, images/macos/tests/System.Tests.ps1, images/macos/tests/XamarinNDK.Tests.ps1, images/macos/toolsets/toolset-12.json
In scope of this pull request we are preparing virtual-environments source code to support macOS 12 (Monterey).
[Build macOS 12](https://github.visualstudio.com/virtual-environments/_build/results?buildId=117005&view=results)
=> Add macOS 12 image templates

images/macos/toolsets/toolset-12.json
Sync toolset, otherwise stable images generation breaks
=> [MacOS] add Temurin-Hotspot to MacOS 12

images/win/scripts/Installers/Install-VS.ps1
We need to wait for the /ResetSettings command to complete otherwise it's not having any effect as shown below:
https://github.com/josetr/VsixTesting/runs/3697544944?check_suite_focus=true#step:4:1
https://github.com/josetr/VsixTesting/runs/3697544919?check_suite_focus=true#step:4:1
=> Fix Visual Studio Experimental Instance Initialization

images/win/toolsets/toolset-2022.json
Yet another Visual Studio Code 2022 component
=> [Windows] Add new component to VS22

images/macos/provision/core/openssl.sh
As written in the comment, let's restore old behaviour for the time being as we observe too many failures.
=> [MacOS] Restore openssl-1.1.x symlink

images/win/scripts/Installers/Install-PyPy.ps1
When you copy a protected file to a folder on the same, or a different volume, it inherits the permissions of the target directory. However, when you move a protected file to a different location on the same volume, the file retains its access permission setting as though it is an explicit permission(in our case it's TEMP dir).
Fix: 
- Expand an archive to the hostedtoolcache folder and preserve inheritance permissions for Authenticated Users group
https://github.com/actions/virtual-environments/issues/4277
=> [Windows] Fix PyPy permissions

images.CI/linux-and-win/azure-pipelines/image-generation.yml, images.CI/macos/azure-pipelines/macos12.yml
We need to test macOS-12 daily.
=> Schedule macOS-12 builds

images/win/scripts/Installers/Install-Docker.ps1
Reverts actions/virtual-environments#4397
=> Revert "[Windows] Docker service does not start on Windows Server 2016-2022"

helpers/GenerateResourcesAndImage.ps1
_Bug fix_
_Fixed typo that broke script._
_n/a_
=> Fix typo in helpers/GenerateResourcesAndImage.ps1.

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
We need to upgrade Selenium server version from 3 to 4
=> [Ubuntu] Upgrade Selenium server version from 3 to 4

images/macos/provision/core/chrome.sh, images/macos/tests/Browsers.Tests.ps1
We need to upgrade Selenium server version from 3 to 4.
=> [macOS] Upgrade Selenium server version from 3 to 4

images/win/scripts/Tests/Browsers.Tests.ps1, images/win/toolsets/toolset-2016.json, images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
We need to upgrade Selenium server version from 3 to 4.
=> [Windows] Upgrade Selenium server version from 3 to 4

images/linux/scripts/installers/postgresql.sh, images/linux/scripts/tests/Databases.Tests.ps1, images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
We need to move PostgreSQL along with some other tools to the toolset on all OSes to make versions control more granular.
=> [Ubuntu] Pin PostgreSQL version installed in the toolset

images/win/scripts/Installers/Install-Docker.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/win/scripts/Tests/Docker.Tests.ps1
It is official docker helper provided by docker team: https://github.com/docker/docker-credential-helpers
Currently, we install this tool in provisioner. This PR moves this logic to image generation code.
=> [Windows] Install Docker-wincred

images/macos/provision/core/php.sh, images/macos/tests/PHP.Tests.ps1, images/macos/toolsets/toolset-10.15.json, images/macos/toolsets/toolset-11.json, images/macos/toolsets/toolset-12.json
This pull request moves the PHP version to the toolset. Also added a check to the pester tests to make we are installing the correct version with accordance to the toolset.
=> [macOS] Add PHP to the toolset

images/linux/scripts/installers/php.sh
This reverts commit 81d68d49b3e76eef3376e14a361e0c3778119a22. Shall be fixed upstream.
=> Revert "[Ubuntu] install libpcre1-8-0 for PHP compat (#4551)"

images/win/post-generation/Choco.ps1
Issue was fixed in choco 0.11.1 - https://github.com/actions/virtual-environments/issues/3010#issuecomment-912273248
https://github.com/actions/virtual-environments-internal/issues/2992
=> [Windows] Remove Choco.ps1 post-generation script

images/win/scripts/Installers/Install-Wix.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1, images/win/scripts/Tests/Tools.Tests.ps1, images/win/scripts/Tests/Wix.Tests.ps1, images/win/windows2022.json
As has been discussed with @MaksimZhukov, @miketimofeev and @al-cheb lets revert this for now and refactor later due to net-negative impact on users.
=> Revert "Add WiX v3 to Windows 2022. (#4448)"

images/win/toolsets/toolset-2016.json, images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
This PR updates MySQL versions.
https://github.com/actions/virtual-environments-internal/issues/3031
=> [Windows] MySQL version update

images/win/toolsets/toolset-2016.json, images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
=> [Windows] upgrade php version to 8.1

helpers/GenerateResourcesAndImage.ps1
The Az.Resources PowerShell module version 5.1.0 of Azure PowerShell introduces changes to the identity-related cmdlets. The cmdlets that rely on Azure AD Graph are transitioning to Microsoft Graph. 
https://docs.microsoft.com/en-us/powershell/azure/azps-msgraph-migration-changes?view=azps-7.0.0
https://github.com/actions/virtual-environments/issues/4698
=> Update the script to support MSGraph

images.CI/macos/anka/Anka.Helpers.psm1
To prevent error like that, we have to delete an image from registry before to push the new one:
```
Invoke-AnkaCommand: There is an error during command execution: -anka: clean_macos_11_300gb:
registry uuid (94349549-4749-4263-844d-483c4aa2692b) doesn't match
```
=> [Anka] Delete image before push

images/win/toolsets/toolset-2022.json
Add `Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang` component.
https://github.com/actions/virtual-environments/issues/4716
=> [Windows] Add NativeDesktop.Llvm.Clang component

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
This PR updates the npm parcel package to v2
=> [Ubuntu] Update npm parcel package to v2

images.CI/macos/anka/Anka.Helpers.psm1, images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
Add TagName param with default value Unix timestamp(e.g. = 1639650079).
=> Add TagName param with default value Unix timestamp

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/win/toolsets/toolset-2016.json, images/win/toolsets/toolset-2019.json
This PR updates the npm parcel package to v2
=> [Windows] Update npm parcel package to v2

docs/create-image-and-azure-resources.md
The title of the section is confusing and it's actually just a note.
=> Remove the self-hosted pool mentioning from the doc

images/macos/toolsets/toolset-11.json, images/macos/toolsets/toolset-12.json
Xcode 13.2.1 has been released.
N/a
=> [macOS] Add xcode 13.2.1

helpers/GenerateResourcesAndImage.ps1
Need add option for permit to use Storage with https traffic only
#4788
=> Add EnableHttpsTrafficOnly for storage

images/win/scripts/Installers/Finalize-VM.ps1, images/win/windows2016.json, images/win/windows2019.json, images/win/windows2022.json
This PR updates Finalize-VM script to remove false-positive error messages from logs. 
https://github.com/actions/virtual-environments/issues/4662
=> [Windows] Update Finalize-VM script

images.CI/linux-and-win/azure-pipelines/ubuntu1804.yml, images.CI/linux-and-win/azure-pipelines/ubuntu2004.yml, images/linux/scripts/installers/preimagedata.sh
We have to change the names in the CI and image data as well.
Previous PRs:
https://github.com/actions/virtual-environments/pull/4795
https://github.com/actions/virtual-environments/pull/4794
=> Change capitalization for Readme name in CI ymls

docs/software-and-images-guidelines.md
The customer asked why didn't we have the latest updates for Python and Ruby on Ubuntu images. We decided to clarify this moment in the software guidelines as it's not clear for everyone that some packages might be outdated in the upstream repo.
n\a
=> Add data about Ubuntu packages to software guidelines

images/win/toolsets/toolset-2022.json
Add Net.Component.4.7.TargetingPack component on Windows Server 2022
https://github.com/actions/virtual-environments/issues/4858
=> [Windows] Add Net.Component.4.7.TargetingPack component

images/macos/toolsets/toolset-10.15.json, images/macos/toolsets/toolset-11.json
This PR updates Azure PowerShell to 7.1 version.
https://github.com/actions/virtual-environments/issues/4832
=> [macOS] Update Azure PowerShell to 7.1

images/win/scripts/Installers/Install-JavaTools.ps1
=> Fixing small typo

docs/create-image-and-azure-resources.md
Added: -AzureClientId {AADApplicationID} -AzureClientSecret {AADApplicationSecret} -AzureTenantId {AADTenantID} to the command.
=> Added AAD Service Principals to the command

docs/create-image-and-azure-resources.md
Add info about build_resource_group_name option
https://github.com/actions/virtual-environments/discussions/4543#discussioncomment-1975725
=> [Packer] Add info about build_resource_group_name option

images/win/scripts/ImageHelpers/InstallHelpers.ps1, images/win/scripts/Installers/Install-AzureCli.ps1, images/win/scripts/Installers/Install-SQLOLEDBDriver.ps1, images/win/scripts/Installers/Install-WebPlatformInstaller.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/win/scripts/Tests/Tools.Tests.ps1, images/win/windows2019.json, images/win/windows2022.json
Add SQL OLEDB Driver to win19 and win22
=> [Windows] Add SQL OLEDB Driver to win19 and win22

images/macos/toolsets/toolset-12.json
As shown on the Xcode versions page
=> [macOS] upgrade xcode to 13.3_beta1

images/linux/scripts/installers/dotnetcore-sdk.sh, images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
This PR adds .NET SDK 6.0 to Ubuntu images.
https://github.com/actions/virtual-environments/issues/4424
=> [Ubuntu] Add .NET SDK 6.0

.github/ISSUE_TEMPLATE/bug-report.yml
We would like to add a new label to sort issues easier. As an addition, we suggest filing all the questions in the discussions section.
=> Add bug report label and mention discussions

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml
Markdown is not supported in the description, so let's add an option. Rendered version:
=> Add an option to proceed to the discussions sections

images/macos/provision/core/graalvm.sh, images/macos/software-report/SoftwareReport.Common.psm1, images/macos/software-report/SoftwareReport.Generator.ps1, images/macos/templates/macOS-10.15.json, images/macos/templates/macOS-11.json, images/macos/templates/macOS-12.json, images/macos/tests/BasicTools.Tests.ps1, images/macos/tests/Common.Tests.ps1
Installing GraalVM to macOS 1015 and 11 images via homebrew referencing https://github.com/graalvm/homebrew-tap
=> [MacOS] Add GraalVM to macOS 1015 and 11 images

images/win/toolsets/toolset-2022.json
Add `Embedded and IoT development tools(Component.MDD.Linux.GCC.arm)` component.
https://github.com/actions/virtual-environments/issues/4998
=> [Windows] Add Component.MDD.Linux.GCC.arm component

images/win/toolsets/toolset-2022.json
The component is missing from VS22 although required by customers' workflows.
https://github.com/actions/virtual-environments/issues/5011
=> [Windows] Add UWP.VC.v142 VS22 component

images.CI/macos/azure-pipelines/image-generation.yml, images.CI/macos/select-datastore.ps1, images/macos/templates/macOS-10.15.json, images/macos/templates/macOS-11.json, images/macos/templates/macOS-12.json
Updating select-datastore script with cluster name based sorting.
=> Improve select-datastore with cluster based filtering

images/win/scripts/ImageHelpers/ImageHelpers.psm1, images/win/scripts/ImageHelpers/PathHelpers.ps1, images/win/scripts/Installers/Configure-Antivirus.ps1, images/win/scripts/Installers/Finalize-VM.ps1
- Disable user services 
- Disable scheduled tasks
- Update antivirus configuration
- Configure windows settings
https://github.com/actions/virtual-environments-internal/issues/3328
=> [Windows] Configure Windows settings,disable services and scheduled tasks

images/linux/scripts/SoftwareReport/SoftwareReport.Databases.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
Explain how to start PostgreSQL, as done for MySQL.
Closes #4964.
=> docs: explain how to start PostgreSQL

images/win/scripts/Installers/Install-Edge.ps1
This PR updates Install Edge logic to use the same version for Edge Driver which Edge browser already has.
https://github.com/actions/virtual-environments-internal/issues/3395
=> [Windows] Update Install Edge logic

docs/software-and-images-guidelines.md
=> Update deprecation guidance

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
Maven 3.8.4 is no longer available for download
fixes #5229
=> maven 3.8.5

images/macos/software-report/SoftwareReport.Common.psm1, images/macos/software-report/SoftwareReport.Generator.ps1, images/macos/tests/BasicTools.Tests.ps1, images/macos/toolsets/toolset-10.15.json, images/macos/toolsets/toolset-11.json, images/macos/toolsets/toolset-12.json
#Description
Add YQ tool to MacOS images
Related issue:
Fixes: https://github.com/actions/virtual-environments/issues/5144
Related issue / work item is attached
Tests are written (if applicable)
Documentation is updated (if applicable)
Changes are tested and related VM images are successfully generated
=> [MacOS] Add YQ tool to macOS images(#5144)

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json
Add Microsoft.Graph module on Ubuntu Server 18.04/20.04.
https://github.com/actions/virtual-environments/issues/5255
=> [Ubuntu] Add Microsoft.Graph module

images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
- Update Az module from 7.1.0 to 7.3.2 version
https://github.com/actions/virtual-environments/issues/5345
=> [Windows] Update Az module to 7.3.2 version

images/macos/toolsets/toolset-12.json
Xcode 13.3.1 has been released today https://developer.apple.com/news/releases/?id=04112022a
n\a
=> [macOS] Add Xcode 13.3.1

images/macos/provision/bootstrap-provisioner/setAutoLogin.sh
Fix missing then in if-elseif-else construction
=> Fix missing then

.github/workflows/codeql-analysis.yml, images/macos/provision/bootstrap-provisioner/kcpassword.py
- Add codeql workflow
- Fix kcpassword function trigger 
https://github.com/actions/virtual-environments-internal/issues/3597
=> Create codeql workflow

images/win/scripts/ImageHelpers/InstallHelpers.ps1
Sometimes we face an issue with the VS marketplace — the portal can be unavailable when making a request.
This PR adds retry logic to allow more than one try.
n\a
=> [Windows] Add retries to Get-VsixExtenstionFromMarketplace function

README.md
=> Update table with macOS 12 Public Beta info

docs/create-image-and-azure-resources.md, helpers/GenerateResourcesAndImage.ps1
Update [GenerateResourcesAndImage.ps1](https://github.com/actions/virtual-environments/blob/main/helpers/GenerateResourcesAndImage.ps1) script adding Ubuntu Server 22.04 ImageType.
=> Add Ubuntu2204 ImageType

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
Fix for `kubectl` version in software report.
https://github.com/actions/virtual-environments-internal/issues/3680#issuecomment-1117011303
=> [Ubuntu] Fix kubectl version report

images/linux/Ubuntu2204-Readme.md
We are going to provide Ubuntu 22 image soon thus need to add a readme.
https://github.com/actions/virtual-environments-internal/issues/3606
=> Add readme for Ubuntu 22 image

images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
Fix for kubectl version in software report.
https://github.com/actions/virtual-environments/issues/5489
=> [Windows] Fix kubectl version in software report

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/macos/software-report/SoftwareReport.Common.psm1
Fix GHCup version 
https://github.com/actions/virtual-environments-internal/issues/3454
=> [macOS] Fix GHCup version output

docs/create-image-and-azure-resources.md
=> Fix: typo in create-image-and-azure-resources.md

images/macos/toolsets/toolset-12.json
=> [macOS] set Xcode-13.3.1 as default

images/macos/toolsets/toolset-12.json
Xcode 13.4 RC has been released.
n\a
=> [macOS] Add Xcode 13.4 to macOS-12 image

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/linux/scripts/installers/docker-moby.sh, images/linux/scripts/tests/Tools.Tests.ps1
Amazon ECR Docker Credential Helper - https://github.com/awslabs/amazon-ecr-credential-helper
https://github.com/actions/virtual-environments/issues/5521
=> [Ubuntu] Add amazon-ecr-credential-helper

images/linux/scripts/SoftwareReport/SoftwareReport.Rust.psm1
Bug fix for cargo outdated version in software report
n/a
=> [Ubuntu] Fix cargo outdated version in report

images/linux/scripts/installers/powershellcore.sh, images/linux/scripts/installers/sqlpackage.sh
PowerShell Core v7.2.4 has been released - https://github.com/PowerShell/PowerShell/releases/tag/v7.2.4 and available for Ubuntu Server 22.04
https://github.com/actions/virtual-environments-internal/issues/3732
=> [Ubuntu] Revert powershell fix for Ubuntu 22.04

README.md
add Ubuntu 22.04 badge
Add Ubuntu-22.04 image badge to the main VE repo page #3727
=> add Ubuntu 22.04 badge readme url

images/macos/toolsets/toolset-12.json
Add appcenter-cli package on macOS 12.
https://github.com/actions/virtual-environments/issues/5569
=> [macOS] Add appcenter-cli

images/macos/software-report/SoftwareReport.Common.psm1
Bug fix for cargo audit version in software report
https://github.com/actions/virtual-environments/pull/5604
https://github.com/actions/virtual-environments/pull/5605
=> [macOS] Fix cargo audit version in software report

images/win/scripts/Tests/Tools.Tests.ps1
Before merging we need to test this fix
https://github.com/actions/virtual-environments-internal/issues/3787
=> [Windows] Image build DACFx test fix 

images/linux/scripts/SoftwareReport/SoftwareReport.Rust.psm1
The version is empty at the moment, need to fix it the same way as we did for macOS here https://github.com/actions/virtual-environments/pull/5606
n\a
=> [Ubuntu] Fix software report for cargo audit

images/win/toolsets/toolset-2016.json, images/win/toolsets/toolset-2019.json
We have an issue with the latest parcel version installation. This PR downgrades the version until we find out the root cause of the problem.
https://github.com/actions/virtual-environments/issues/5616
=> [Windows] Downgrade parcel to 2.5.0

images/linux/scripts/base/repos.sh
* Do not use apt-key
* Do not use curl
* Use wget for consistency
* Dearmor file straight from stdout
* Do not do the same action twice
=> [Ubuntu] rework Microsoft repo installation

images/linux/scripts/installers/yq.sh
- Use direct link to download latest yq version
- Remove tar using
=> [Ubuntu] Use direct link to download latest yq version

images/macos/toolsets/toolset-12.json
Xcode 14 beta has been released https://developer.apple.com/news/releases/?id=06062022h
https://github.com/actions/virtual-environments/issues/5702
=> [macOS] Add Xcode 14 to macOS 12 image

images/macos/templates/macOS-11.anka.pkr.hcl, images/macos/templates/macOS-12.anka.pkr.hcl
- Remove indentation
- Remove spaces
- Remove duplicate execute_command
- Rename scripts -> script when necessary
- Update bootstrap path
=> [Packer] Fix anka packer template

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
- Include dash version
https://github.com/actions/virtual-environments/issues/5795
=> [Ubuntu] Add dash version into documentation

images/macos/toolsets/toolset-12.json
Will be deployed next week as planned
=> [macOS] set Xcode 13.4.1 as default

images/win/scripts/Tests/LLVM.Tests.ps1, images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
- Update LLVM 13 -> 14
https://github.com/actions/virtual-environments/issues/5835
=> [Windows] Update LLVM to version 14

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json, images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
Update Az Powershell modules to version 7.5 on Windows and Linux
https://github.com/actions/virtual-environments-internal/issues/3938
=> [Windows\Linux] Update Az powershell to 7.5

images/macos/tests/LLVM.Tests.ps1, images/macos/toolsets/toolset-10.15.json, images/macos/toolsets/toolset-11.json, images/macos/toolsets/toolset-12.json
- Update LLVM 13 -> 14
https://github.com/actions/virtual-environments/issues/5835
=> [macOS] Update LLVM to version 14

images/linux/scripts/SoftwareReport/SoftwareReport.Browsers.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/installers/microsoft-edge.sh, images/linux/scripts/tests/Browsers.Tests.ps1
=> [Ubuntu] Add Microsoft Edge Web Driver

images/linux/scripts/installers/erlang.sh
Looks like the problem is gone.
=> [Ubuntu] revert esl-erlang fix

images/win/scripts/ImageHelpers/InstallHelpers.ps1, images/win/toolsets/toolset-2022.json
- Add ProBITools.MicrosoftAnalysisServicesModelingProjects2022 3.0.4
https://github.com/actions/virtual-environments-internal/issues/3974
=> [Windows] Add ProBITools.MicrosoftAnalysisServicesModelingProjects2022 3.0.4

docs/create-image-and-azure-resources.md
=> Added step for download & install git

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json
Add CMake 3.22.1 for Android
https://github.com/actions/virtual-environments/issues/5952
=> [Ubuntu] Add Cmake 3.22.1 for Android

images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
Add Cmake 3.22.1 for Android
https://github.com/actions/virtual-environments/issues/5952
=> [Windows] Add Cmake 3.22.1 for Android

images/macos/toolsets/toolset-11.json, images/macos/toolsets/toolset-12.json
Add CMake 3.22.1 for Android
https://github.com/actions/virtual-environments/issues/5952
=> [macOS] Add Cmake 3.22.1 for Android

images.CI/macos/anka/Service.Helpers.psm1
- Add check if installerPath is not empty
- Update installer pattern
=> [Anka] Fix installer pattern to support macOS beta version

images/linux/scripts/installers/android.sh, images/macos/provision/core/android-toolsets.sh, images/win/scripts/Installers/Install-AndroidSDK.ps1
There was an error in the comment, should be NDK_ROOT instead of NDK_LATEST
https://github.com/actions/virtual-environments/pull/5983#discussion_r938574872
=> [all OSs] Fix comment about NDK variables

docs/create-image-and-azure-resources.md
Replace Virtual-Environments to Runner Images
=> [Docs] Replace virtual-environments to runner images

images/macos/software-report/SoftwareReport.Common.psm1, images/macos/software-report/SoftwareReport.Generator.ps1, images/macos/tests/Common.Tests.ps1, images/macos/toolsets/toolset-11.json, images/macos/toolsets/toolset-12.json
Reverts actions/runner-images#6059 as wee need configuration to match that for Linux.
=> Revert "[macOS] Added CodeQL"

images/linux/scripts/installers/dotnetcore-sdk.sh
Otherwise installation is inconsistent. I hope this is temporarily.
=> [Ubuntu] put Microsoft repo higher for dotnet

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
=> [Ubuntu] fix Software report for OpenShift CLI

images/linux/Ubuntu2004-Readme.md
=> [Ubuntu] fix README for 20.04

images/win/toolsets/toolset-2022.json, images/win/windows2022.json
Add VS 2022 components:
- Microsoft.Net.Component.4.8.1.SDK
- Microsoft.Net.Component.4.8.1.TargetingPack
https://github.com/actions/runner-images/issues/6124
=> [Windows] Add Microsoft.Net.Component.4.8.1

images/macos/provision/core/xcode.ps1
We should install these components manually now.
=> [macOS] Install tvOS and watchOS runtime sims

.github/workflows/create_pull_request.yml
The team name has changed and we have to adjust the create pr workflow accordingly.
=> Rename team in the PR creation

images/win/scripts/Installers/Install-WDK.ps1, images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1, images/win/scripts/Tests/WDK.Tests.ps1
Install WDK.vsix on VS 2022.
https://github.com/actions/runner-images/issues/5897
=> [Windows] Install WDK.vsix on VS 2022

images/macos/provision/configuration/finalize-vm.sh
https://docs.fastlane.tools/getting-started/ios/authentication/ - The resulting session will be stored in ~/.fastlane/spaceship/[email]/cookie
=> [macOS] Remove fastlane cached cookie

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/announcement.yml, .github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/tool-request.yml
=> Rebrand templates

images/win/scripts/Installers/Finalize-VM.ps1
Enable WpnUserService_LUID service by default on Windows.
https://github.com/actions/runner-images-internal/issues/4328
=> [Windows] Enable WpnUserService

images/macos/toolsets/toolset-12.json
=> [macOS] Add Xcode 14.1 beta

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/win/scripts/Tests/ChocoPackages.Tests.ps1, images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
Add ImageMagick tool to both Windows images. 
#6207
=> [Windows] Add ImageMagick tool

images/macos/toolsets/toolset-12.json
Xcode 14.0.1 has been released https://developer.apple.com/news/releases/?id=09162022a
n/a
=> [macOS] Add Xcode 14.0.1 to macOS 12

images/win/scripts/Installers/Wait-WindowsUpdatesForInstall.ps1, images/win/scripts/Tests/WindowsFeatures.Tests.ps1
Exclude Windows Defender update checking.
https://github.com/actions/runner-images/discussions/6231
=> [Windows] Exclude Windows Defender update checking

images/linux/scripts/installers/graalvm.sh, images/linux/scripts/installers/r.sh, images/linux/scripts/installers/yq.sh
Bringing comments to installer scripts to standard. List of tools: GraalVM, R, YQ
N/A
=> [Ubuntu] Update installers comments

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/installers/homebrew.sh, images/linux/scripts/tests/Tools.Tests.ps1
So it does not conflict with the canonical-provided software and toolchain in particular.
=> [Ubuntu] do not add homebrew to $PATH

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
=> [Ubuntu] fix sw generator for homebrew

images/win/scripts/Installers/Install-Docker.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/win/scripts/Tests/Docker.Tests.ps1
- Fix docker-win-credential link
- Add docker symlink to fix issue with az acr login
https://github.com/actions/runner-images/issues/6286
=> [Windows] Add docker symlink

docs/create-image-and-azure-resources.md
3 post-generation scripts were removed and 1 was added for the Windows environment in the past 10 months or so. This is an update to the documentation to reflect those changes.
1. https://github.com/actions/runner-images/issues/3010#issuecomment-912273248
2. https://github.com/actions/runner-images/pull/4585
3. https://github.com/actions/runner-images/pull/4635
4. https://github.com/actions/runner-images/pull/5852
=> Actualizing the Windows post-generation scripts' documentation

images/macos/provision/configuration/finalize-vm.sh, images/macos/provision/core/commonutils.sh, images/macos/provision/utils/confirm-identified-developers.scpt, images/macos/software-report/SoftwareReport.Common.psm1, images/macos/software-report/SoftwareReport.Generator.ps1, images/macos/toolsets/toolset-12.json
Add Parallels Desktop extension:
1. Install Parallels
2. Approve the Parallels Kernel Extension
3. Reboot
4. Uninstall Parallels
https://github.com/actions/runner-images/issues/6105
=> [macOS] Add Parallels Desktop extension

images/linux/Ubuntu2004-Readme.md, images/linux/Ubuntu2204-Readme.md
=> [Ubuntu] fix readme files

images/win/scripts/Installers/Install-Docker.ps1
We should install latest release of Docker CE.
https://github.com/actions/runner-images/issues/6333
=> [Windows] Install latest release of Docker CE

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json
=> [Ubuntu] Document tar version

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/tests/Common.Tests.ps1, images/linux/ubuntu2204.pkr.hcl
=> [Ubuntu] Add swift to 22.04

images/win/scripts/Installers/Install-Git.ps1
There is no latest Git version in choco repo due to issues:
- https://github.com/chocolatey-community/chocolatey-packages/pull/2021#issuecomment-1283576319
- https://github.com/chocolatey-community/chocolatey-packages/issues/2007
- https://github.com/chocolatey-community/chocolatey-packages/issues/1995
https://github.com/actions/runner-images-internal/issues/4502
=> [Windows] Install git from gh

images/macos/software-report/SoftwareReport.Generator.ps1
=> [macOS] exclude Colima from Catalina's sw report

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/linux/scripts/installers/vcpkg.sh, images/macos/provision/core/vcpkg.sh, images/macos/software-report/SoftwareReport.Common.psm1, images/win/scripts/Installers/Install-Vcpkg.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/win/scripts/Tests/Tools.Tests.ps1
Reverts actions/runner-images#6449
=> Revert "[all OSs]  Revert VCPKG_ROOT variable"

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/linux/scripts/installers/vcpkg.sh, images/macos/provision/core/vcpkg.sh, images/macos/software-report/SoftwareReport.Common.psm1, images/win/scripts/Installers/Install-Vcpkg.ps1, images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1, images/win/scripts/Tests/Tools.Tests.ps1
Revert breaking changes for VCPKG. Remove VCPKG_ROOT variable.
#6376
=> [all OSs] Revert VCPKG_ROOT variable

images/macos/macos-10.15-Readme.md
=> [macOS] fix readme for 10.15

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/win/scripts/Tests/Shell.Tests.ps1
Remove unnecessary conditions for WSL.
=> [Windows] Remove Test-IsWin19 WSL condition

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json
=> [Ubuntu] add Node 18 to toolcache

images/macos/provision/configuration/environment/bashrc
This is fix for https://github.com/actions/runner-images/issues/6507
=> Add Python to $PATH

images/win/toolsets/toolset-2019.json
Reverts actions/runner-images#6540
=> Revert "[Windows] Remove Azure.Storage.AzCopy component"

images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json
=> [Ubuntu] Add .NET 7

images/linux/scripts/installers/android.sh
Syntax has changed a bit with a new version
=> [Ubuntu] fix yq invocation on android repo xml

images/linux/scripts/installers/vcpkg.sh
=> Workaround vcpkg installation

images/macos/provision/core/vcpkg.sh
vcpkg workaround
https://github.com/microsoft/vcpkg/issues/27786
=> [macos] vcpkg workaround

images/linux/scripts/installers/mongodb.sh
=> [Ubuntu] fix mongodb installation

images/linux/scripts/installers/powershellcore.sh, images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json
Pin pwsh-core version to avoid upgrades to 7.3
=> [Ubuntu] pin powershell-core version

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json
Update the PowerShell Az module version to 9.0.1 on Ubuntu
#6650
=> [Ubuntu] Update Az module version to 9.0.1

images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
Update the PowerShell Az module version to 9.0.1 on Windows
#6650
=> [Windows] Update Az module version to 9.0.1

images/win/scripts/Installers/Install-IEWebDriver.ps1
Since the IEDriverServer.exe has been moved from google storage to Selenium's Github repo, we are going to:
- Update IEDriverServer.exe to the latest version.
- Update the download source of IEDriverServer.exe 
#6656
=> [Windows] update IEDriverServer version to latest

README.md
Mention ongoing migrations in the main readme.
=> [README] Mention ongoing migrations

images/macos/toolsets/toolset-12.json
=> [macOS] Add xcode-14.2

images/linux/scripts/installers/google-chrome.sh
=> [Ubuntu] hardcode chromium revision for 108.x

images/macos/toolsets/toolset-10.15.json, images/macos/toolsets/toolset-11.json, images/macos/toolsets/toolset-12.json
=> [macOS] Update PHP to 8.2

.github/workflows/create_sbom_report.yml
Update workflow according to the latest changes. Replaced external variable imageLabel to agentSpec.
And a small code improvement.
https://github.com/actions/runner-images-internal/issues/4405
=> Update SBOM-workflow with new variable agentSpec

.github/ISSUE_TEMPLATE/announcement.yml, .github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/tool-request.yml, .github/pull_request_template.md
=> Do not include macOS-10.15 into templates

images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
=> [Windows] upgrade php version to 8.2

helpers/software-report-base/SoftwareReport.Comparer.psm1, helpers/software-report-base/SoftwareReport.Nodes.psm1, images/macos/software-report/SoftwareReport.Browsers.psm1, images/macos/software-report/SoftwareReport.Common.psm1, images/macos/software-report/SoftwareReport.Generator.ps1, images/macos/software-report/SoftwareReport.Toolcache.psm1, images/macos/software-report/SoftwareReport.Xcode.psm1
Included changes:
- `ToolNode` -> `ToolVersionNode`
- `ToolVersionsNode` -> `ToolVersionsListNode`
- `HeaderNode.AddHeaderNode` -> `HeaderNode.AddHeader`
- `HeaderNode.AddToolNode` -> `HeaderNode.AddToolVersion`
- `HeaderNode.AddToolVersionsNode` -> `HeaderNode.AddToolVersionsList`
- `HeaderNode.AddTableNode` -> `HeaderNode.AddTable`
- `HeaderNode.AddNoteNode` -> `HeaderNode.AddNote`
=> [macOS] Rename some entities in software report module

images/win/scripts/Installers/Install-MysqlCli.ps1
The MySQL archive was temporarily moved to SA to continue the release process.
=> [Windows] download MySQL from SA

.github/workflows/create_sbom_report.yml
Edits for GHA<->AzDO interaction. Artifact upload step implementation.
https://github.com/actions/runner-images-internal/issues/4405
=> Update SBOM-gen add artifact upload + bugfix

.github/workflows/create_sbom_report.yml
=> Testing of event payload

.github/workflows/create_sbom_report.yml
Reverts actions/runner-images#6786
=> Revert "Testing of event payload"

.github/workflows/create_sbom_report.yml
Change naming pattern to avoid using "/"
=> Fix use of invalid characters in artifact name

images/macos/toolsets/toolset-12.json
=> [macOS] set Xcode 14.1 as default

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1, images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/macos/software-report/SoftwareReport.Common.psm1
=> Tiny polishing macOS and Linux docs

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json
Update Az module version to 9.1.1
#6819
=> [Ubuntu] Update Az module version to 9.1.1

helpers/software-report-base/SoftwareReport.Nodes.psm1, helpers/software-report-base/tests/SoftwareReport.Difference.E2E.Tests.ps1, helpers/software-report-base/tests/SoftwareReport.Nodes.Unit.Tests.ps1
=> Small improvements for software generator module

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json
Update Az module version to 9.2.0
#6819
=> [Ubuntu] Update Az module version to 9.2.0

images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
Update the Az module version to 9.2.0
#6819
=> [Windows] Update Az module version to 9.2.0

images/win/toolsets/toolset-2019.json, images/win/toolsets/toolset-2022.json
Update OpenSSL version to 3.x
#6830
=> [Windows] Update OpenSSL version to 3.x

images/linux/scripts/installers/google-chrome.sh
This reverts commit fb484d95309e2fdb6b943ba345c0e0975de10e68.
=> Revert "[Ubuntu] hardcode chromium revision for 108.x (#6734)"

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1, images/linux/scripts/installers/homebrew.sh, images/linux/scripts/installers/zstd.sh, images/linux/scripts/tests/Tools.Tests.ps1, images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json, images/linux/ubuntu1804.json, images/linux/ubuntu2004.json, images/linux/ubuntu2204.pkr.hcl
In order to get the latest zstd version we had to change the way of getting the app.
The current approach works with the official facebook repository in GitHub.
https://github.com/actions/runner-images-internal/issues/4404
=> [Ubuntu] update zstd version

docs/create-image-and-azure-resources.md
As per https://github.com/actions/runner-images/issues/5911#issuecomment-1185231772
=> Update documentation with minimum packer version

images/linux/toolsets/toolset-1804.json, images/linux/toolsets/toolset-2004.json, images/linux/toolsets/toolset-2204.json
I had an issue creating the linux image because there is no version 3.8.6 here anymore https://downloads.apache.org/maven/maven-3/
=> update maven from 3.8.6 to 3.8.7
