actions/runner-images

- images/macos/toolsets/toolset-10.15.json
- images/macos/toolsets/toolset-11.json
- images/macos/toolsets/toolset-12.json
Update LLVM version to 15
#6803
> [macOS] Update llvm to version 15

- images/win/toolsets/toolset-2019.json
- images/win/toolsets/toolset-2022.json
Update LLVM version to 15
#6803
> [Windows] Update LLVM version to 15

- README.md
We no longer have active migrations by now
> README: no active migrations

- images/linux/scripts/helpers/Tests.Helpers.psm1
- images/macos/helpers/Tests.Helpers.psm1
- images/win/scripts/ImageHelpers/TestsHelpers.ps1
> Disable Pester test colors

- images/macos/toolsets/toolset-12.json
> [macOS] Switch defailt Xcode to 14.2

- images/win/scripts/ImageHelpers/InstallHelpers.ps1
In order to reduce failed builds the retry function was added to the "Install-VsixExtension" function.
#6899
> [Windows] Add retry to Install-VsixExtension

- images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
Update software report generator to fix Parcel version output
> [Windows] fix software report generator for Parcel

- images/linux/toolsets/toolset-1804.json
- images/linux/toolsets/toolset-2004.json
- images/linux/toolsets/toolset-2204.json
Update Az PowerShell version from 9.2.0 to 9.3.0
> [Linux] Upgrade Az powershell to 9.3.0

- images/win/toolsets/toolset-2022.json
Improvement
Android Emulator requires Hyper-V feature to be installed
> install Hyper-V feature

- README.md
Note: this is merging into branch `package_managers_table`
Was trying things out and figured I'd propose the changes on top of #6959
> Update package managers table

- LICENSE
> LiCENSE: we are in 2023!

- images/win/scripts/Installers/Install-Toolset.ps1
Add retries to toolset installation as we do on macOS
> [Windows] add retries in toolset installation

- README.md
Add table with software installed from different package managers across all the OSes.
> README: add package managers table

- images.CI/macos/anka/Anka.Helpers.psm1
- images/macos/templates/macOS-12.anka.pkr.hcl
Update the script and packer config file for macOS 12 for anka v3 compatibility
> Update the code for anka v3 compatibility

- images/macos/templates/macOS-11.anka.pkr.hcl
Update packer config for macOS-11
> Update packer config for macOS-11

- images/macos/helpers/Common.Helpers.psm1
- images/macos/provision/utils/utils.sh
Update helper scripts for future macOS 13 image generation.
> [macOS] prepare helpers for macOS 13

- images/linux/scripts/installers/sqlpackage.sh
Fix libssl version
https://github.com/actions/runner-images-internal/issues/4821
> Fix libssl version

- images/linux/toolsets/toolset-2004.json
- images/linux/toolsets/toolset-2204.json
> [Ubuntu] set node 18 as default

- images/win/toolsets/toolset-2019.json
- images/win/toolsets/toolset-2022.json
> [Windows] set node 18 as default

- images/macos/toolsets/toolset-11.json
- images/macos/toolsets/toolset-12.json
> [macOS] set node 18 as default

- images/macos/provision/core/python.sh
Due to https://github.com/Homebrew/homebrew-core/commit/ee3aa6c60fcf3481f13af14afafe4b5e95f70564 changes.
> [macOS] Update Python3 installer script

- images/linux/scripts/installers/mssql-cmd-tools.sh
Looks like there is a version conflict.
> [Ubuntu] install ODBC before Microsoft repo

- images/win/scripts/Installers/Install-Rust.ps1
Change download link due to customer request and to be closer to official [install guide](https://forge.rust-lang.org/infra/other-installation-methods.html#rustup).
#7035
> [Windows] Update Rustup download link

- images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
It has changed the format a bit
> [Ubuntu] fix PHP sotware report

- images/macos/templates/macOS-13.anka.pkr.hcl
- images/macos/toolsets/toolset-13.json
Add packer template for macOS 13
> [macOS] Add packer template for macOS 13

- images/macos/templates/macOS-13.anka.pkr.hcl
- images/macos/toolsets/toolset-13.json
> [macOS] update macOS 13 template

- images/macos/software-report/SoftwareReport.Common.psm1
- images/macos/software-report/SoftwareReport.Generator.ps1
Add pkg-config version to a software report for macOS due to latest changes
> [ macOS ] Add pkg-config to report

- images/macos/provision/configuration/finalize-vm.sh
- images/macos/provision/core/commonutils.sh
- images/macos/provision/core/ruby.sh
- images/macos/software-report/SoftwareReport.Generator.ps1
- images/macos/tests/Android.Tests.ps1
- images/macos/tests/BasicTools.Tests.ps1
- images/macos/tests/Git.Tests.ps1
- images/macos/tests/Java.Tests.ps1
- images/macos/tests/RubyGem.Tests.ps1
Update some scripts and tests in macos directory to be able to generate macOS 13 images
> [macOS] prepare repository for macOS 13

- .github/workflows/macos-generation.yml
- .github/workflows/macos11.yml
- .github/workflows/macos12.yml
- .github/workflows/ubuntu-win-generation.yml
- .github/workflows/ubuntu2004.yml
- .github/workflows/ubuntu2204.yml
- .github/workflows/windows2019.yml
- .github/workflows/windows2022.yml
In order to move "unstable" image generation from Azure pipelines to GitHub actions.
> Add GitHub actions for image generation

- images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
- images/linux/scripts/tests/Tools.Tests.ps1
- images/linux/ubuntu1804.json
It is broken for a while and does not look to be fixed.
> [Ubuntu] Do not install erlang on 18.04

- images/macos/provision/core/commonutils.sh
Otherwise we have endless loop
> [Anka] add retries

- images/win/toolsets/toolset-2022.json
Enable Hypervisor Platform optional feature in order to let android emulator accelaration
https://github.com/actions/runner-images-internal/issues/4786
> Enable Hypervisor Platform

- images/macos/templates/macOS-12.anka.pkr.hcl
> [Anka] add script to fix broken simulators name

- images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
- images/linux/scripts/installers/erlang.sh
- images/linux/scripts/tests/Tools.Tests.ps1
- images/linux/ubuntu1804.json
Workaround installation to bypass hashes mismatch.
> [Ubuntu] rework erlang installation (workaround hashes)

- images/win/scripts/Installers/Install-JavaTools.ps1
- images/win/toolsets/toolset-2019.json
- images/win/toolsets/toolset-2022.json
As we do on ubuntu, otherwise lots of workflows are broken
> [Windows] pin maven version

- images/linux/scripts/installers/google-chrome.sh
This reverts commit bbac29011e04dff6563dd7f8b44a79fa658ed281.
> Revert "[Ubuntu] hardcode chromium revision for 110.x (#7113)"

- images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
> [Ubuntu] print maven version on Ubuntu 22.04

- images.CI/linux-and-win/azure-pipelines/image-generation.yml
> Do not expose packer-log in pipelines

- images/linux/toolsets/toolset-2004.json
- images/linux/toolsets/toolset-2204.json
Add alpine 3.17 docker image
https://github.com/actions/runner-images/issues/7270
> [Ubuntu] Add alpine 3.17 docker image

- images/win/scripts/ImageHelpers/InstallHelpers.ps1
Remove stale filter that force us to miss subversions of Android platforms.
#7271
> [Windows] Update condition for Android packages filter

- images/linux/scripts/installers/haskell.sh
Update installer script for Haskell. Changes will affect Cabal version.
#7305
> [Ubuntu] Install latest but not recommended Cabal

- .github/workflows/create_sbom_report.yml
Update to use access to the Network Volumes from bash
> Update SBOM workflow to use syft with bash shell for macOS

- images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
- images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
Add systemd version to software report
https://github.com/actions/runner-images/issues/7374
> [Ubuntu] Add systemd version to software report

- .github/workflows/macos-generation.yml
- .github/workflows/macos11.yml
- .github/workflows/macos12.yml
- .github/workflows/ubuntu2004.yml
- .github/workflows/ubuntu2204.yml
- .github/workflows/windows2019.yml
- .github/workflows/windows2022.yml
- images.CI/macos/move-vm.ps1
With this PR several issues will be fixed:
- Now pipeline can be run even with empty fields ("Custom repository (owner/repo)", "Commit hash")
- Job "Move vm to cold storage and clear datastore tag" will be executed always
- In case the pipeline fails the VM name will be updated with the "failed" suffix
> Update CI actions according to demands

- images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
- images/linux/scripts/base/apt.sh
- images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
There are a couple of workarounds in code that are not needed anymore. This request removes them.
> [Windows|Ubuntu] Remove obsolete workarounds

- .gitignore
- .vscode/settings.json
Remove vscode settings file and add it to gitignore so it doesn't interfere with user configuration.
> Remove vscode settings file

- .github/workflows/macos-generation.yml
- .github/workflows/macos11.yml
According to the security team's recommendation - [thread](https://github.slack.com/archives/C1UTM9MEU/p1681810013379959), we should not use variable masking in the production. Instead, we should use repository secrets.
In this Pull Request, we are removing the variable masking and adding repo secrets to the pipeline.
> Remove variable mask, add repo secrets

- images/macos/macos-13-Readme.md
> Update macos-13-Readme.md: Remove timestamp in heading

- images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
- images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
> fix software version

- images/macos/provision/bootstrap-provisioner/installNewProvisioner.sh
As discussed internally with @mikhailkoliada, submitting changes required to build MacOS images for ARM64 runners.
It was tested with an image generated locally on a test rack and unblocked us for validating our Github workflows.
> updates for MacOS M1/arm64 runners

- images/macos/provision/core/ruby.sh
- images/macos/software-report/SoftwareReport.Generator.ps1
- images/macos/templates/macOS-13.anka.pkr.hcl
- images/macos/toolsets/toolset-13.json
> Add Ruby and Python to toolcache

- images/macos/templates/macOS-13.anka.pkr.hcl
- images/macos/tests/Common.Tests.ps1
- images/macos/tests/Databases.Tests.ps1
- images/macos/tests/Node.Tests.ps1
- images/macos/tests/OpenSSL.Tests.ps1
- images/macos/tests/PipxPackages.Tests.ps1
- images/macos/tests/Python.Tests.ps1
- images/macos/tests/System.Tests.ps1
- images/macos/tests/Toolcache.Tests.ps1
- images/macos/tests/WebServers.Tests.ps1
- images/macos/tests/Xamarin.Tests.ps1
Add RunAll-Tests.ps1 to the macOS 13 template.
Add exclusions to the test to skip them on macOS 13
> [macOS] add RunAll-Tests.ps1 to the macOS-13

- .github/workflows/macos11.yml
- .github/workflows/macos12.yml
- .github/workflows/ubuntu2004.yml
- .github/workflows/ubuntu2204.yml
- .github/workflows/windows2019.yml
- .github/workflows/windows2022.yml
Update label names for GH actions CI pipelines
> Update labels for CI pipelines (GH actions)

- images/macos/tests/Ruby.arm64.Tests.ps1
- images/macos/tests/Xcode.Tests.ps1
- images/macos/toolsets/toolset-11.json
- images/macos/toolsets/toolset-12.json
Add architecture references to toolset for consistency across MacOs scripts
> [macos] add architecture references

- .github/workflows/macos11.yml
- .github/workflows/macos12.yml
- .github/workflows/ubuntu2004.yml
- .github/workflows/ubuntu2204.yml
- .github/workflows/windows2019.yml
- .github/workflows/windows2022.yml
> Update actions labels

- images/macos/provision/configuration/preimagedata.sh
we have to fix it for Ventura due to case changes
> [macOS] fix preimage data for Ventura

- README.md
I found a broken link while reading README.md.
> Fix incorrect Homebrew link in README.md

- images/macos/provision/configuration/configure-machine.sh
- images/macos/tests/System.Tests.ps1
The script usage condition has been modified to include all versions of macOS starting from Monterey.
#7621
> [macOS] Update condition for automation mode

- README.md
This PR will update the link in the readme file.
https://github.com/actions/runner-images-internal/issues/5093
#7628
> Update azure function name

- images/linux/scripts/installers/sqlpackage.sh
> [Ubuntu] Update libssl package version

- images/macos/templates/macOS-11.anka.pkr.hcl
- images/macos/templates/macOS-12.anka.pkr.hcl
- images/macos/templates/macOS-13.anka.pkr.hcl
- images/macos/templates/macOS-13.arm64.anka.pkr.hcl
Adjust hcl2 packer templates to work with encoded string
> [macos] Adjust hcl2 packer templates with decoding

- images/win/scripts/Installers/Install-MysqlCli.ps1
This reverts temporary workaround actions/runner-images#6769.
> Revert "[Windows] download MySQL from SA (#6769)"

- images/linux/scripts/base/apt-ubuntu-archive.sh
Additional repos should be added to cloud-init templates to survive re-bundle.
Potential resolution to #7758
> [ubuntu] Add additional repos to cloud-init template

- .github/workflows/create_sbom_report.yml
Payload's `imageVersion` is in `<major_version>.<minor_version>` format.
Adjust workload for accurate comparison
> Update SBOM report workflow's version-check job

- images/linux/scripts/installers/preimagedata.sh
- images/win/scripts/Installers/Update-ImageData.ps1
Tags come in the form of `<label>/<version_major>.<version_minor>`.
Fix software and release URLs for windows and ubuntu
> Fix software and release URLs for windows and ubuntu

- images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
- Fix cargo-outdated version
- Simplification, standardisation if possible
> [Windows] Rework common tools software report script

- images/linux/scripts/installers/hhvm.sh
> [Ubuntu] do not check ssl cert for hhvm

- images/macos/helpers/Xcode.Installer.psm1
- images/macos/provision/core/homebrew.sh
- images/macos/provision/core/xcode.ps1
fix regression in Simulators runtimes intall
https://github.com/actions/runner-images-internal/issues/5218
> [macos] fix XCode simulator install behaviour

- images/win/scripts/Installers/Install-Edge.ps1
Disable Edge auto-updates to avoid possible edge/edge-driver compatibility issues and image inconsistency
> [Windows] Disable Edge auto-updates

- docs/create-image-and-azure-resources.md
`subsctiption` -> `subscription`
That's all.
> Typo fix in create-image-and-azure-resources.md

- .github/workflows/macos-generation.yml
- images.CI/macos/azure-pipelines/image-generation.yml
> [macos] Cleanup xcversion leftovers

- .github/workflows/ubuntu-win-generation.yml
> Fix minor typo in workflow file

- images/linux/scripts/installers/google-chrome.sh
According to the information on [ChromeDriver website](https://chromedriver.chromium.org/), starting with version 115 these json endpoints should be used to determine compatible versions and download urls: https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints. This PR updates script that installs Chrome and ChromeDriver to use one of these endpoints.
> [Ubuntu] Fix chromedriver download process

- .github/workflows/ubuntu-win-generation.yml
followup of https://github.com/actions/runner-images-internal/issues/5253
https://github.com/actions/runner-images-internal/issues/5253
> [ubuntu, windows] cast "run_id" to 32 bit unsigned to match BuildId

- .github/workflows/ubuntu-win-generation.yml
"run_id" does not match UInt32 restrictions, also Powershell is not good with "%" operator within pipelines
https://github.com/actions/runner-images-internal/issues/5253
> revert PR7941

- .github/workflows/macos11.yml
- .github/workflows/macos12.yml
- .github/workflows/ubuntu2004.yml
- .github/workflows/ubuntu2204.yml
- .github/workflows/windows2019.yml
- .github/workflows/windows2022.yml
Eliminate the possibility to run CI automatically.
> Remove cron job from CI

- images.CI/linux-and-win/azure-pipelines/ubuntu2004.yml
- images.CI/linux-and-win/azure-pipelines/ubuntu2204.yml
- images.CI/linux-and-win/azure-pipelines/windows2019.yml
- images.CI/linux-and-win/azure-pipelines/windows2022.yml
Revert "[WinLin] Remove schedules from Azure pipelines (#7576)"
> Revert "[WinLin] Remove schedules from Azure pipe"

- images/linux/scripts/base/apt.sh
- images/linux/scripts/helpers/install.sh
- images/linux/scripts/installers/azure-cli.sh
- images/linux/scripts/installers/cmake.sh
- images/linux/scripts/installers/codeql-bundle.sh
- images/linux/scripts/installers/docker-compose.sh
- images/linux/scripts/installers/docker-moby.sh
- images/linux/scripts/installers/git.sh
- images/linux/scripts/installers/haskell.sh
- images/linux/scripts/installers/heroku.sh
- images/linux/scripts/installers/java-tools.sh
- images/linux/scripts/installers/julia.sh
- images/linux/scripts/installers/kubernetes-tools.sh
- images/linux/scripts/installers/leiningen.sh
- images/linux/scripts/installers/microsoft-edge.sh
- images/linux/scripts/installers/miniconda.sh
- images/linux/scripts/installers/nodejs.sh
- images/linux/scripts/installers/nvm.sh
- images/linux/scripts/installers/packer.sh
- images/linux/scripts/installers/pulumi.sh
- images/linux/scripts/installers/pypy.sh
- images/linux/scripts/installers/ruby.sh
- images/linux/scripts/installers/rust.sh
- images/linux/scripts/installers/swift.sh
- images/linux/scripts/installers/terraform.sh
- images/linux/scripts/installers/zstd.sh
Set `-fsS` flags for curl to catch errors early. Also add `-L` flag to handle redirects and improve build stability.
> [Ubuntu] Set flags for curl

- images/macos/provision/configuration/configure-machine.sh
- images/macos/provision/core/codeql-bundle.sh
- images/macos/provision/core/dotnet.sh
- images/macos/provision/core/edge.sh
- images/macos/provision/core/haskell.sh
- images/macos/provision/core/miniconda.sh
- images/macos/provision/core/node.sh
- images/macos/provision/core/nvm.sh
- images/macos/provision/core/openjdk.sh
- images/macos/provision/core/powershell.sh
- images/macos/provision/core/pypy.sh
- images/macos/provision/core/ruby.sh
- images/macos/provision/core/vsmac.sh
- images/macos/provision/utils/utils.sh
Set `-fsS` flags for curl to catch errors early. Also add `-L` flag to handle redirects and improve build stability.
> [mac OS] Set flags for curl invocations

- images/macos/provision/core/xcode.ps1
- images/macos/tests/Xcode.Tests.ps1
Improve script consistency by utilizing `Get-Architecture` helper function
> [macos] Utilize Get-Architecture helper function

- images/macos/helpers/Xcode.Installer.psm1
- images/macos/toolsets/toolset-13.json
update XCode 15 to Beta 5
https://github.com/actions/runner-images/issues/7986
> Macos 13 xcode 15 beta5

- images/macos/templates/macOS-11.anka.pkr.hcl
- images/macos/templates/macOS-12.anka.pkr.hcl
- images/macos/templates/macOS-13.anka.pkr.hcl
- images/macos/templates/macOS-13.arm64.anka.pkr.hcl
unpin anka plugin version
https://github.com/actions/runner-images-internal/issues/5255
> Unpin veertu packer

- images/win/scripts/Installers/Install-MongoDB.ps1
- images/win/toolsets/toolset-2019.json
- images/win/toolsets/toolset-2022.json
Change mongodb installation from choco to .msi download due binary missing in choco repo
> [Windows] Change mongodb installation from choco to .msi download

- images/macos/provision/core/chrome.sh
Reverting pretty old rework: https://github.com/actions/runner-images/pull/1861.
[#5315](https://github.com/actions/runner-images-internal/issues/5315)
> [macOS] Install Google Chrome cask with default method

- images/linux/scripts/base/apt-ubuntu-archive.sh
- images/linux/ubuntu2004.json
Add resilience to apt `sources.list`:
1) Script execution order adjusted in `ubuntu20` template for consistency
2) `sources.list` adjusted with `apt-transport-mirror`
> [ubuntu] Update apt sources.list

- images/win/toolsets/toolset-2022.json
Add Hyper-V PowerShell module to be able to manage VMs via Powershell.
Based on https://github.com/actions/runner-images/pull/8028
> [Windows] Add Hyper-V PowerShell module

- images/win/scripts/Installers/Install-AzureCli.ps1
Change Az Cli installation to x64.
> [windows] Change Az Cli to x64

- images/win/scripts/Installers/Install-Chrome.ps1
- images/win/scripts/Tests/Browsers.Tests.ps1
Google have released Google Chrome for Testing - it's special version of Google Chrome browser with auto-updates disables and some other optimizations for testing and automation. It might worth switching to that version.
> [Windows] Install Google Chrome for Testing

- images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
- images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
- images/linux/scripts/installers/docker.sh
- images/linux/ubuntu2004.json
- images/linux/ubuntu2204.pkr.hcl
Install `docker` from official repository
> [ubuntu] Change docker to install from official repository

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
This PR adds VSCode configuration files with code formatting settings that correspond style guide developed recently.
> Configure formatting and extensions for vscode

- images/win/toolsets/toolset-2019.json
- images/win/toolsets/toolset-2022.json
Update LLVM version to 16
https://github.com/actions/runner-images/issues/8125
> [Windows] Update LLVM version to 16

- images/win/scripts/Installers/Install-Chrome.ps1
- images/win/scripts/Tests/Browsers.Tests.ps1
This reverts commit d9169bba1e28bd781128a8d8cdb28d0b182db9c6.
https://github.com/actions/runner-images/issues/8114
> Revert "Try installing Google Chrome for Testing (#7997)"

- images/macos/provision/configuration/max-files.sh
Workaround for limit applying thru SIP restrictions.
https://github.com/actions/runner-images-internal/issues/5314
> [macOS] Fix open file limits

- images/macos/toolsets/toolset-13.json
> [macos] update XCode 15 to Beta 8

- images/win/scripts/Installers/Install-DotnetSDK.ps1
this is cleanup made before adding "validate checksum" feature
> windows: cleanup DotNETSdk install script

- README.md
Old screenshot yet reflected the `actions/virtual-environments` repository which is currently rebranded as the `actions/runner-images` one.
>  README: update environment version screenshot

- images/win/scripts/Installers/Install-PowershellCore.ps1
implement checksum validation for Powershell Core
> [windows] implement checksum validation for Powershell Core

- images/win/scripts/Installers/Install-MongoDB.ps1
Fix mongoDB installation error
> [Windows] Change source for mongodb version parser

- images/win/scripts/Installers/Install-Docker.ps1
implement checksum validation for docker-wincred
> [windows] implement checksum validation for docker-wincred

- images/win/scripts/Installers/Install-OpenSSL.ps1
implement checksum validation for OpenSSL
> [windows] implement checksum validation for OpenSSL

- images.CI/linux-and-win/convert-to-vhd.ps1
Since the migration to the new agents and subscription is done, we do not need this condition anymore.
https://github.com/actions/runner-images-internal/issues/5187
> Remove OS selection condition

- images.CI/linux-and-win/azure-pipelines/image-generation.yml
Move the `Convert managed image to VHD` step below to get the software report faster.
> Move the conversion step after the software report

- images/win/scripts/Installers/Install-OpenSSL.ps1
accidently, "break" terminated script itself, not just "ForEach" loop.
https://github.com/actions/runner-images-internal/issues/5419
> [windows] fix openssl installation

- images/win/scripts/Installers/Install-AzureModules.ps1
inline documentation improvemen
> [windows] clarify Install-AzureModules description

- images/win/scripts/Installers/Install-OpenSSL.ps1
https://github.com/actions/runner-images-internal/issues/5419
> [windows] fix openssl package condition

- images/macos/provision/core/openssl.sh
- images/macos/tests/OpenSSL.Tests.ps1
* fix the prefix
* fix the smoke pester tests
* make openssl@1.1 the default yet
> [macOS] improve openssl@1.1 installation on arm64

- README.md
Switch to the new Azur Function to complete migration to the new tenant
https://github.com/actions/runner-images-internal/issues/5187
> Switch to the new Azure Function

- images/win/scripts/Installers/Install-Kotlin.ps1
Update installer script with checksum for Kotlin
> [Windows] Add checksum verification for Kotlin

- helpers/GenerateResourcesAndImage.ps1
helpers/GenerateResourcesAndImage.ps1: check for interactive mode
https://github.com/actions/runner-images/issues/8298
> helpers/GenerateResourcesAndImage.ps1: check for interactive mode

- images/macos/software-report/SoftwareReport.Xcode.psm1
> [macOS] do not list Xcode-install in sw report on OS13

- images/win/scripts/Installers/Install-Rust.ps1
implement checksum validation for rustup
> [windows] implement checksum validation for rustup

- images/win/scripts/Installers/Install-Git.ps1
Update installer script with checksum for Git
> [Windows] Add checksum verification for Git

- images/macos/provision/core/git.sh
- images/macos/software-report/SoftwareReport.Common.psm1
- images/macos/software-report/SoftwareReport.Generator.ps1
- images/macos/tests/Git.Tests.ps1
> [Mac OS] Remove hub utility

- images/win/scripts/Installers/Install-GitHub-CLI.ps1
Update installer script with checksum for GitHub CLI
> [Windows] Add checksum verification for GitHub CLI

- images/win/scripts/Installers/Install-AWS.ps1
Update installer script with checksum for AWS SAM CLI
> [Windows] Add checksum verification for AWS SAM CLI

- images/win/scripts/Installers/Install-Msys2.ps1
Update installer script with checksum for MSYS2
> [Windows] Add checksum validation for MSYS2

- images.CI/macos/azure-pipelines/image-generation.yml
Remove not used variable group
> Remove not used variable group

- images/win/scripts/Installers/Warmup-User.ps1
disable TSVCache.exe hard drives scanning
> [windows] disable TSVNCache.exe

- images/win/scripts/Installers/Install-DotnetSDK.ps1
implement DotNETSDK checksum validation
> [windows] implement DotNETSDK checksum validation

- images/macos/macos-13-arm64-Readme.md
> [macOS] add README file for M1 runner

- images/win/scripts/Installers/Install-KubernetesTools.ps1
Update installer script with checksum for Kind
> [Windows] Add checksum verification for Kind

- images/win/scripts/Installers/Install-MysqlCli.ps1
- images/win/toolsets/toolset-2019.json
- images/win/toolsets/toolset-2022.json
Change MySQL installation way from .zip to .msi for adding digital signature validation.
> [Windows] Rework MySQL installation script

- images/macos/software-report/SoftwareReport.Generator.ps1
Update software report for macOS 13 arm64.
Exclude Composer from the list for macOS 13 arm64.
> [macOS] Update software report for macOS 13 arm64

- images/win/scripts/Installers/Install-Mingw64.ps1
- images/win/toolsets/toolset-2019.json
- images/win/toolsets/toolset-2022.json
This PR changes the way we install MinGW from using choco package to manual installation. It would provide more control over updates and version selection.
> [Windows] Install mingw binaries manually

- images/win/scripts/Installers/Install-WindowsUpdates.ps1
[Windows] Exclude KB5001148 from Windows update
> [Windows] Exclude KB5001148 from windows update

- images/win/scripts/Installers/Install-NSIS.ps1
Use Chocolatey as a package manager for NSIS package
> [Windows] Install NSIS package from Chocolatey

- images/win/scripts/Installers/Install-Stack.ps1
Update installer script with checksum for Stack
> [Windows] Add checksum validation for Stack

- images/win/scripts/Installers/Install-JavaTools.ps1
Add checksum validation for Cobertura archive
> [Windows] Add checksum verification for cobertura

- images/linux/scripts/installers/azure-cli.sh
> [Ubuntu] pin az-cli to v2.52.0

- images/win/scripts/Installers/Install-Docker.ps1
Currently we don't verify whether Docker installs successfully or not. This PR introduces such verification and improves output in Install-Docker.ps1 script.
> [Windows] Exit on Docker installation failure

- images/win/scripts/Installers/Install-AzureCli.ps1
> [windows] Pin Azure CLI to 2.52.0

- images/win/scripts/Installers/Install-AzureCli.ps1
Fix code style in `Install-AzureCli.ps1`
Following https://github.com/actions/runner-images/commit/0795b9ed8be55c2c08f33647e103f70dd18d9df6
> [Windows] Fix code style in Install-AzureCli.ps1

- images/linux/scripts/installers/terraform.sh
Pin Terraform 1.5.7 until 1.6.1 is released
Ref: https://github.com/hashicorp/terraform/issues/33977
> [Ubuntu] Pin Terraform 1.5.7

- images/win/scripts/Installers/Warmup-User.ps1
revert unsuccessful warmup. 
https://github.com/actions/runner-images/issues/8164
> [windows] reverting SQL LocalDB warmup

- images/win/scripts/Installers/Install-Miniconda.ps1
implement checksum valiation for Miniconda
> [windows] implement checksum validation for Miniconda

- images/linux/scripts/installers/terraform.sh
This reverts commit 4d6ce38166b6942984d53fc83a0a71593c2d82ee.
> Revert "[Ubuntu] Pin Terraform 1.5.7 (#8504)"

- images/win/toolsets/toolset-2019.json
- images/win/toolsets/toolset-2022.json
Updating new signature thumbprint for Visual Studio installer
> [Windows] Update signature for VS installer

- images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
- images/linux/scripts/installers/terraform.sh
Exclude macOS Sonoma from software update list
> Update anka clean script

- images/linux/scripts/installers/terraform.sh
- images/macos/provision/core/openjdk.sh
- images/macos/tests/Java.Tests.ps1
> Fix Gradle test

- images/linux/scripts/installers/azure-cli.sh
- images/linux/scripts/installers/terraform.sh
Ubuntu revert azcli to the latest version
> [Ubuntu] revert azcli to the latest version

- images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
- images.CI/macos/anka/Service.Helpers.psm1
Exclude upgrade to Sonoma from macOS 13 clean images
> Exclude upgrade to Sonoma

- images/linux/scripts/installers/terraform.sh
- images/win/scripts/Installers/Install-AzureCli.ps1
Windows revert Az CLI to the latest version
> [Windows] revert Az CLI to the latest version

- images/win/toolsets/toolset-2019.json
- images/win/toolsets/toolset-2022.json
> [Windows] Add Java 21

- images/macos/software-report/SoftwareReport.Generator.ps1
- images/macos/software-report/SoftwareReport.Java.psm1
- images/macos/toolsets/toolset-13.json
Install Java 21 on MacOS arm64 image.
> [macOS] Install Java 21 on MacOS 13 arm64

- images/win/scripts/Installers/Install-AliyunCli.ps1
Update installer script with checksum for Aliyun CLI
> [Windows] Add checksum verification for Aliyun CLI

- images.CI/macos/anka/Anka.Helpers.psm1
- images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
Set static UUID to the clean image
> Set static UUID to the clean image

- images/win/scripts/Installers/Install-SQLOLEDBDriver.ps1
This PR updates MySQL OLEDB driver to 18.6.7.0 and adds signature validation
> [Windows] Update SQL OLEDB driver to 18.6.7.0

- images/linux/scripts/installers/heroku.sh
This PR change way to install heroku-cli from 'provided script' to 'apt-get'.
> [Ubuntu] Update heroku-cli installation script (apt-install)

- images/macos/provision/core/chrome.sh
- images/macos/software-report/SoftwareReport.Browsers.psm1
- images/macos/software-report/SoftwareReport.Generator.ps1
- images/macos/templates/macOS-13.arm64.anka.pkr.hcl
- images/macos/tests/Browsers.Tests.ps1
Add Chrome to MacOS 13 arm64 image.
> [macOS] Add Chrome to arm64 image

- images/linux/scripts/installers/java-tools.sh
- images/linux/scripts/tests/Java.Tests.ps1
- images/linux/toolsets/toolset-2004.json
- images/linux/toolsets/toolset-2204.json
> [Ubuntu] Add Java 21

- images/macos/provision/core/powershell.sh
we determine Powershell version on the fly, let's add retries to that machinery
> [macos] retry powershell meta download

- images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
fix VersionPattern for Clang v15
> [Ubuntu] fix VersionPattern for Clang v15

- images/macos/provision/core/pypy.sh
add retries to PyPy installation
> [macos] add retries to PyPy installation

- images/macos/provision/core/node.sh
add retries to yarn install script
> [macos] add retries to yarn install script

- images/macos/software-report/SoftwareReport.Generator.ps1
- images/macos/software-report/SoftwareReport.Toolcache.psm1
Add node.js to the software report for macOS 13 arm64
> [macOS] add node to software report macOS 13 arm64

- images/macos/provision/core/codeql-bundle.sh
add reties to CodeQL download step
> [macos] add reties to CodeQL download step

- images/win/scripts/Installers/Install-MongoDB.ps1
This PR fix error when Install-MongoDB.ps1 script tries to download `pre-release` version of MongoDB
Closes https://github.com/actions/runner-images/issues/8252
> [Windows] Add filter for upcoming version in mongodb version parser

- images/macos/provision/core/edge.sh
add retries to edge install script
> [macos] add retries to edge install script

- images/macos/provision/core/apache.sh
- images/macos/provision/core/aws.sh
- images/macos/provision/core/azcopy.sh
- images/macos/provision/core/bicep.sh
- images/macos/provision/core/homebrew.sh
- images/macos/provision/core/nginx.sh
use brew_smart_install where appropriate
> [macos] use brew_smart_install where appropriate

- images/win/scripts/Installers/Finalize-VM.ps1
disable WindowsUpdate service
https://github.com/actions/runner-images/issues/8599
> [windows] disable WindowsUpdate service

- images/macos/provision/core/xcode.ps1
- images/macos/toolsets/toolset-12.json
- images/macos/toolsets/toolset-13.json
introduce more flexible way of making a decision whether install or not install xcode runtimes
> [macos] introduce more flexible way of managind xcode runtimes

- images/macos/provision/core/homebrew.sh
- images/macos/provision/core/nvm.sh
- images/macos/provision/utils/utils.sh
download package cache as well, suppress caching output
improve brew caching approach
download package cache as well, suppress caching output
> [macos] improve brew caching approach

- images/win/scripts/Installers/Install-PyPy.ps1
> unpin PyPy checksum

- images/linux/scripts/installers/aws.sh
- images/linux/scripts/installers/kotlin.sh
- images/linux/scripts/installers/kubernetes-tools.sh
Update installer scripts with checksum for Kotlin, Minikube, AWS SAM CLI using `get_github_package_hash()`
[#5491](https://github.com/actions/runner-images-internal/issues/5491)
> [Ububntu] Add checksum validation for Kotlin, Minikube, AWS SAM CLI

- images/macos/provision/core/android-toolsets.sh
- images/macos/provision/core/commonutils.sh
- images/macos/provision/core/pypy.sh
- images/macos/provision/utils/utils.sh
- images/macos/tests/BasicTools.Tests.ps1
This PR improves errexit bash option handling for Mac OS. It introduces option state check to prevent unnecessary manipulations and fixes issue where option remains disabled after successful download.
> [MacOS] improve errexit option handling

- images/linux/scripts/installers/swift.sh
This PR adds PGP validation for swift installation
> [Ubuntu] Add PGP validation for swift

- images/macos/provision/core/commonutils.sh
- images/macos/tests/Common.Tests.ps1
This PR reverts seemingly obsolete #6391
> [MacOS] Unpin Virtualbox

- images/win/scripts/Installers/Install-Rust.ps1
Reverts actions/runner-images#8713
> Revert "[Windows] Pin bindgen cli version to avoid bug"

- images/linux/scripts/installers/rust.sh
Reverts actions/runner-images#8714
> Revert "[Ubuntu] Pin bindgen cli version to avoid bug"

- images/macos/templates/macOS-14.anka.pkr.hcl
- images/macos/toolsets/toolset-14.json
This PR adds template to generate Mac OS 14 image
> [Mac OS] Add template for Mac OS 14 image

- images/macos/provision/core/commonutils.sh
- images/macos/tests/Common.Tests.ps1
Reverts actions/runner-images#8653
> Revert "[MacOS] Unpin Virtualbox"

- images/macos/helpers/Common.Helpers.psm1
- images/macos/helpers/Xcode.Installer.psm1
- images/macos/provision/configuration/configure-tccdb-macos.sh
- images/macos/provision/configuration/preimagedata.sh
- images/macos/provision/core/commonutils.sh
- images/macos/provision/core/node.sh
- images/macos/provision/utils/utils.sh
- images/macos/software-report/SoftwareReport.Generator.ps1
- images/macos/tests/Android.Tests.ps1
- images/macos/tests/BasicTools.Tests.ps1
- images/macos/tests/Common.Tests.ps1
- images/macos/tests/Databases.Tests.ps1
- images/macos/tests/Node.Tests.ps1
- images/macos/tests/PipxPackages.Tests.ps1
- images/macos/tests/Python.Tests.ps1
- images/macos/tests/Ruby.arm64.Tests.ps1
- images/macos/tests/RubyGem.Tests.ps1
- images/macos/tests/System.Tests.ps1
- images/macos/tests/Xamarin.Tests.ps1
- images/macos/toolsets/toolset-14.json
This pull request includes a variety of changes to support the new macOS Sonoma operating system. The most important changes include adding support for Sonoma to various functions, skipping certain tests on macOS Sonoma , and modifying the software report to exclude certain tools and sections on macOS Sonoma.
> [Mac OS] Adapt code for Mac OS 14 image

- images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
- images.CI/macos/anka/Service.Helpers.psm1
- images/macos/provision/configuration/auto-software-update-arm64.exp
Fix macOS 13 arm64 software update part
https://github.com/actions/runner-images-internal/issues/5567
> Fix macOS 13 arm64 software update part

- images/macos/software-report/SoftwareReport.Generator.ps1
- images/macos/templates/macOS-13.arm64.anka.pkr.hcl
- images/macos/tests/Common.Tests.ps1
Add AWS cli to the macOS 13 arm64
> [macOS] Add AWS cli to the macOS 13 arm64

- images/macos/provision/utils/utils.sh
Make brew_smart_install verbose (take one)
> utils.sh: make brew_smart_install verbose

- images/ubuntu/toolsets/toolset-2004.json
- images/ubuntu/toolsets/toolset-2204.json
> [Ubuntu] Add dotnet 8

- images/windows/scripts/build/Install-WDK.ps1
Update Windows Driver Kit version
https://github.com/actions/runner-images/issues/8718
> [Windows] Update Windows Driver Kit version

- images/windows/templates/windows-2019.json
- images/windows/templates/windows-2022.json
Otherwise it breaks on case-sensitive fs
> [packer] fix install-powershell script name

- images/windows/scripts/build/Configure-SystemEnvironment.ps1
- images/windows/scripts/build/Configure-Toolset.ps1
- images/windows/scripts/build/Install-AndroidSDK.ps1
- images/windows/scripts/build/Install-Chrome.ps1
- images/windows/scripts/build/Install-DotnetSDK.ps1
- images/windows/scripts/build/Install-EdgeDriver.ps1
- images/windows/scripts/build/Install-Firefox.ps1
- images/windows/scripts/build/Install-Haskell.ps1
- images/windows/scripts/build/Install-IEWebDriver.ps1
- images/windows/scripts/build/Install-JavaTools.ps1
- images/windows/scripts/build/Install-Miniconda.ps1
- images/windows/scripts/build/Install-NodeJS.ps1
- images/windows/scripts/build/Install-PHP.ps1
- images/windows/scripts/build/Install-Pipx.ps1
- images/windows/scripts/build/Install-PostgreSQL.ps1
- images/windows/scripts/build/Install-Selenium.ps1
- images/windows/scripts/build/Install-Vcpkg.ps1
- images/windows/scripts/helpers/ImageHelpers.psm1
- images/windows/scripts/helpers/PathHelpers.ps1
- images/windows/scripts/helpers/test/PathHelpers.Tests.ps1
This pull request includes a series of changes to improve the setting of environment variables in various PowerShell scripts. The most important changes include replacing the use of the `setx` command with `[Environment]::SetEnvironmentVariable` to ensure correct setting of environment variables in the machine context.
> [Windows] Use common approach to set machine vars

- images/windows/scripts/build/Install-EdgeDriver.ps1
This pull request updates the expected signature thumbprint of the EdgeDriver executable.
> [Windows] Fix signature for MS Edge webdriver

- .github/workflows/create_sbom_report.yml
- Fix version check logic
- Revert pinned SYFT version for Windows (optional)
> Fix SBOM workflow logic

- images/windows/scripts/build/Install-WindowsUpdates.ps1
- images/windows/scripts/build/Install-WindowsUpdatesAfterReboot.ps1
- images/windows/scripts/helpers/ImageHelpers.psm1
- images/windows/scripts/helpers/InstallHelpers.ps1
- images/windows/scripts/tests/WindowsFeatures.Tests.ps1
This pull request introduces improvements to the retrieval and processing of Windows update statuses. It renames and updates the `Get-WindowsUpdateStates` function to improve readability and maintainability. It also updates scripts that use that helper function.
> [Windows] Update helper function that returns Windows Update states

- CONTRIBUTING.md
PR updates `Generate-SoftwareReport.ps1` ref in `CONTRIBUTING.md`
> Update report generator script name in CONTRIBUTING.md

- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
update NSIS to 3.09
https://github.com/actions/runner-images/issues/8890
> [windows] update NSIS to 3.09

- images/windows/scripts/build/Install-ActionsCache.ps1
- images/windows/scripts/build/Install-IEWebDriver.ps1
- images/windows/scripts/build/Install-Kotlin.ps1
- images/windows/scripts/build/Install-Mingw64.ps1
- images/windows/scripts/build/Install-Selenium.ps1
- images/windows/scripts/docs-gen/SoftwareReport.Browsers.psm1
- images/windows/scripts/helpers/ImageHelpers.psm1
- images/windows/scripts/helpers/InstallHelpers.ps1
- images/windows/scripts/tests/Browsers.Tests.ps1
- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
This pull request implements the new function `Resolve-GithubReleaseAssetUrl` in place of the `Get-GitHubPackageDownloadUrl` with reduced and simplified parameter set and more straightforward internal logic.
> [Windows] Reimplement function resolving GH asset

- images/ubuntu/scripts/build/configure-dpkg.sh
- images/ubuntu/scripts/build/configure-environment.sh
- images/ubuntu/scripts/build/configure-system.sh
- images/ubuntu/scripts/build/install-actions-cache.sh
- images/ubuntu/scripts/build/install-android-sdk.sh
- images/ubuntu/scripts/build/install-azure-devops-cli.sh
- images/ubuntu/scripts/build/install-firefox.sh
- images/ubuntu/scripts/build/install-google-chrome.sh
- images/ubuntu/scripts/build/install-java-tools.sh
- images/ubuntu/scripts/build/install-leiningen.sh
- images/ubuntu/scripts/build/install-microsoft-edge.sh
- images/ubuntu/scripts/build/install-miniconda.sh
- images/ubuntu/scripts/build/install-nvm.sh
- images/ubuntu/scripts/build/install-selenium.sh
- images/ubuntu/scripts/build/install-swift.sh
- images/ubuntu/scripts/build/install-vcpkg.sh
- images/ubuntu/scripts/helpers/etc-environment.sh
PR changes `/etc/environment` management approach, with helper functions being used where applicable.
> [ubuntu] Unify approach to /etc/environment

- images/windows/scripts/build/Install-AliyunCli.ps1
- images/windows/scripts/build/Install-AndroidSDK.ps1
- images/windows/scripts/build/Install-Chocolatey.ps1
- images/windows/scripts/build/Install-CloudFoundryCli.ps1
- images/windows/scripts/build/Install-DotnetSDK.ps1
- images/windows/scripts/build/Install-EdgeDriver.ps1
- images/windows/scripts/build/Install-Firefox.ps1
- images/windows/scripts/build/Install-JavaTools.ps1
- images/windows/scripts/build/Install-Kotlin.ps1
- images/windows/scripts/build/Install-KubernetesTools.ps1
- images/windows/scripts/build/Install-Msys2.ps1
- images/windows/scripts/build/Install-PyPy.ps1
- images/windows/scripts/build/Install-Rust.ps1
- images/windows/scripts/build/Install-Stack.ps1
- images/windows/scripts/helpers/ImageHelpers.psm1
- images/windows/scripts/helpers/InstallHelpers.ps1
- images/windows/scripts/helpers/VisualStudioHelpers.ps1
This pull request implements new function `Test-FileChecksum` for file checksum verification instead of the old one (`Use-ChecksumComparison`). The new function accepts the path of the file to check and includes hash computation logic. Also it introduce come other minor changes to improve readability and maintainability of the code.
> [Windows] Refactor helpers that verify hashsum and signature

- images/macos/scripts/build/Install-Toolset.ps1
- images/macos/scripts/build/install-actions-cache.sh
- images/macos/scripts/build/install-android-sdk.sh
- images/macos/scripts/build/install-aws-tools.sh
- images/macos/scripts/build/install-azcopy.sh
- images/macos/scripts/build/install-chrome.sh
- images/macos/scripts/build/install-codeql-bundle.sh
- images/macos/scripts/build/install-common-utils.sh
- images/macos/scripts/build/install-dotnet.sh
- images/macos/scripts/build/install-edge.sh
- images/macos/scripts/build/install-homebrew.sh
- images/macos/scripts/build/install-miniconda.sh
- images/macos/scripts/build/install-mono.sh
- images/macos/scripts/build/install-node.sh
- images/macos/scripts/build/install-nvm.sh
- images/macos/scripts/build/install-openjdk.sh
- images/macos/scripts/build/install-powershell.sh
- images/macos/scripts/build/install-pypy.sh
- images/macos/scripts/build/install-python.sh
- images/macos/scripts/build/install-ruby.sh
- images/macos/scripts/build/install-visualstudio.sh
- images/macos/scripts/helpers/Common.Helpers.psm1
- images/macos/scripts/helpers/Xcode.Installer.psm1
- images/macos/scripts/helpers/utils.sh
- images/macos/scripts/helpers/xamarin-utils.sh
This pull request implements simplified interface and more straightforward behavior for the download_with_retry function. The new implementation matches the the function with the same name in Windows image helpers (https://github.com/actions/runner-images/pull/8906) and the function with the same name in Ubuntu image helpers (https://github.com/actions/runner-images/pull/8912), so these changes would improve overall code consistency and maintainability.
> [Mac OS] Rewrite function download_with_retry

- .github/workflows/ci-cleanup.yml
PR updates `ci-cleanup.yml` with env variable for untrusted input
> Add PR_HEAD_REF env variable to ci-cleanup.yml

- images/ubuntu/scripts/tests/Databases.Tests.ps1
- images/ubuntu/scripts/tests/Helpers.psm1
- images/ubuntu/scripts/tests/Java.Tests.ps1
- images/ubuntu/scripts/tests/Tools.Tests.ps1
This PR:
1. Removes `Validate-ToolExist` function which is not used
2. Renames `ShouldMatchCommandOutput` to accurately match it's function
3. Some style changes
> [ubuntu] Refactor test helpers

- CONTRIBUTING.md
- docs/create-image-and-azure-resources.md
This pull request includes various documentation updates to improve clarity, consistency, and readability. It includes updates to the `create-image-and-azure-resources.md` file and the `CONTRIBUTING.md`.
> Validate and update some documentation

- images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/ubuntu/scripts/docs-gen/SoftwareReport.Android.psm1
- images/ubuntu/scripts/docs-gen/SoftwareReport.Browsers.psm1
- images/ubuntu/scripts/docs-gen/SoftwareReport.CachedTools.psm1
- images/ubuntu/scripts/docs-gen/SoftwareReport.Common.psm1
- images/ubuntu/scripts/docs-gen/SoftwareReport.Databases.psm1
- images/ubuntu/scripts/docs-gen/SoftwareReport.Helpers.psm1
- images/ubuntu/scripts/docs-gen/SoftwareReport.Java.psm1
- images/ubuntu/scripts/docs-gen/SoftwareReport.Rust.psm1
- images/ubuntu/scripts/docs-gen/SoftwareReport.Tools.psm1
- images/ubuntu/scripts/docs-gen/SoftwareReport.WebServers.psm1
This PR:
1. Removes `Restore-UserOwner` function and invokes command directly
2. Renames `Take-OutputPart` function to `Get-StringPart` with approved verb
3. Removes unused `Get-AptSourceRepository` function
4. Combines `Get-PathWithLink` and `Get-LinkTarget` to a single function for simplicity
5. Contains minor style changes
> [ubuntu] Refactor Software Report helpers

- .github/workflows/create_sbom_report.yml
Implementation of checking for the presence of a release and SBOM asset to avoid redundant pipeline launches.
> Update SBOM generation workflow

- images/ubuntu/scripts/build/install-azcopy.sh
- images/ubuntu/scripts/docs-gen/SoftwareReport.Tools.psm1
[Ubuntu] Temporary pin the AzCopy version
> [Ubuntu] Temporary pin the AzCopy version

- images/macos/scripts/build/install-azcopy.sh
- images/macos/scripts/docs-gen/SoftwareReport.Common.psm1
Temporary pin the AzCopy version
> [macOS] Temporary pin the AzCopy version

- images/ubuntu/scripts/tests/ActionArchiveCache.Tests.ps1
- images/ubuntu/scripts/tests/Android.Tests.ps1
- images/ubuntu/scripts/tests/Apt.Tests.ps1
- images/ubuntu/scripts/tests/CLI.Tools.Tests.ps1
- images/ubuntu/scripts/tests/Common.Tests.ps1
- images/ubuntu/scripts/tests/Databases.Tests.ps1
- images/ubuntu/scripts/tests/DotnetSDK.Tests.ps1
- images/ubuntu/scripts/tests/Haskell.Tests.ps1
- images/ubuntu/scripts/tests/Helpers.psm1
- images/ubuntu/scripts/tests/Java.Tests.ps1
- images/ubuntu/scripts/tests/Node.Tests.ps1
- images/ubuntu/scripts/tests/PowerShellModules.Tests.ps1
- images/ubuntu/scripts/tests/RunnerCache.Tests.ps1
- images/ubuntu/scripts/tests/Tools.Tests.ps1
- images/ubuntu/scripts/tests/Toolset.Tests.ps1
This PR:
1. Removes `Test-AndroidPackage` function. Invoke commands directly instead
2. Removes excessive `param()` for `It` blocks
3. Rework `podman networking` test
4. Minor style changes
> [ubuntu] Refactor pester tests

- images/windows/scripts/build/Install-MysqlCli.ps1
- images/windows/scripts/build/Install-NET48-devpack.ps1
- images/windows/scripts/build/Install-NET48.ps1
- images/windows/scripts/build/Install-ServiceFabricSDK.ps1
- images/windows/scripts/build/Install-VCRedist.ps1
- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
pin installer checksum where available
https://github.com/actions/runner-images-internal/issues/5489
> [windows] pin checksum where available

- images/windows/scripts/helpers/ChocoHelpers.ps1
Improving security of Windows builds.
[#5493](https://github.com/actions/runner-images-internal/issues/5493)
> [Windows] Force Chocolatey to check packages hashes

- images/windows/scripts/build/Install-EdgeDriver.ps1
New Edge Web Driver was released and file signature needs an update
> [windows] Update signature for Edge Web Driver

- images/ubuntu/scripts/build/install-ruby.sh
Small security improvement for Ubuntu images
[#5493](https://github.com/actions/runner-images-internal/issues/5493)
> [Ubuntu] Force ruby gem to check gems

- images/ubuntu/scripts/build/install-ruby.sh
Reverts actions/runner-images#9022
> Revert "[Ubuntu] Force ruby gem to check gems"

- images/macos/toolsets/toolset-13.json
- images/macos/toolsets/toolset-14.json
- Add Xcode 15.2 Beta to the macOS 13 images
- Sync macOS 14 template
> [macOS] Add Xcode 15.2 Beta

- images/macos/scripts/build/configure-tccdb-macos.sh
This PR fix TCC.db records with giving permission for screen capturing 
https://github.com/actions/runner-images/issues/8782
> [MacOS] Fix rules for screencapture 

- .github/workflows/create_sbom_report.yml
Fix naming pattern to met code style requirements
> Fix SBOM workflow first step name

- images/macos/scripts/build/install-powershell.sh
- images/macos/toolsets/toolset-11.json
- images/macos/toolsets/toolset-12.json
- images/macos/toolsets/toolset-13.json
- images/macos/toolsets/toolset-14.json
Pin pwsh version in toolset and make it iterable.
> [macOS] pin pwsh-core in toolset

- images/ubuntu/scripts/build/Configure-Toolset.ps1
- images/ubuntu/scripts/build/Install-PowerShellAzModules.ps1
- images/ubuntu/scripts/build/Install-PowerShellModules.ps1
- images/ubuntu/scripts/build/Install-Toolset.ps1
- images/ubuntu/scripts/helpers/Common.Helpers.psm1
This PR refactors PowerShell scripts used for Ubuntu builds:
1) `Get-ToolsetContent` helper function is used instead of direct commands
2) `Invoke-DownloadWithRetry` helper function is added
3) Local functions are renamed
4) Simplified conditions
5) Minor style changes
> [ubuntu] Refactor PowerShell build scripts

- images/windows/scripts/build/Install-PowershellCore.ps1
- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
Make it flexible and easier to pin
> [Windows] pin pwsh-core in toolset 

- images/ubuntu/scripts/tests/System.Tests.ps1
Update `Disk free space` test to validate needed free disk space.
- https://github.com/github/hosted-runners/issues/424
> [Ubuntu] Increase threshold in the Disk free space test

- images/windows/scripts/build/Install-EdgeDriver.ps1
This PR updates signature thumbprint for edge driver
> [Windows] Update signature for Edge driver

- images/windows/scripts/build/Install-AzureCli.ps1
- images/windows/scripts/build/Install-EdgeDriver.ps1
This PR updates signature for azure cli
https://github.com/actions/runner-images/issues/9133
> [Windows] Fix signature for azure cli

- images/ubuntu/templates/ubuntu-minimal.pkr.hcl
Add missing `INSTALLER_SCRIPT_FOLDER` environment variable for `ubuntu-minimal` packer template
> [ubuntu] Fix pwsh installation for ubuntu-minimal

- images/windows/scripts/build/Install-DACFx.ps1
- images/windows/toolsets/toolset-2019.json
Fix signature for vs and dacfx
https://github.com/actions/runner-images/issues/9140
https://github.com/actions/runner-images/issues/9142
> [Windows] Fix signature for vs and dacfx

- images/windows/scripts/helpers/InstallHelpers.ps1
- images/windows/templates/windows-2019.pkr.hcl
- images/windows/templates/windows-2022.pkr.hcl
This PR adds `IMAGE_FOLDER` environment variable to locate toolset file in `Get-ToolsetContent` helper function
> [windows] Add dynamic path for Get-ToolsetContent

- images/windows/scripts/build/Install-DockerCompose.ps1
This PR pin docker compose to version v2.23.3
https://github.com/actions/runner-images/issues/9172
> [Windows] Pin docker compose 2.23.3

- LICENSE
> Update LICENSE (Happy 2024!)

- images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/macos/scripts/tests/BasicTools.Tests.ps1
- images/macos/scripts/tests/RubyGem.Tests.ps1
- images/macos/scripts/tests/WebServers.Tests.ps1
- images/macos/templates/macOS-13.anka.pkr.hcl
- images/macos/toolsets/toolset-13.json
Get rid of unused software in macOS 13
> [macOS] Get rid of unused software in macOS 13

- images/windows/toolsets/toolset-2022.json
Update Visual Studio signature for windows-2022 image
https://github.com/actions/runner-images/issues/9188
> [Windows] Update VS signature for windows-2022

- images.CI/macos/azure-pipelines/image-generation.yml
- images.CI/macos/azure-pipelines/secondary-macos11.yml
- images.CI/macos/azure-pipelines/secondary-macos12.yml
Test secondary MacOs image generation
> Add secondary MacOs image generation pipelines

- images/macos/templates/macOS-14.anka.pkr.hcl
- images/macos/toolsets/toolset-14.json
Get rid of unused software in macOS 14
> [macOS] Get rid of unused software in macOS 14

- images/ubuntu/toolsets/toolset-2004.json
- images/ubuntu/toolsets/toolset-2204.json
This PR updates PowerShell Core on Ubuntu images to 7.4.x.
> [ubuntu] Update PowerShell Core to 7.4.x

- images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1
- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
This PR updates PowerShell Core on Windows images to 7.4.x.
> [windows] Update PowerShell Core to 7.4.x

- images/ubuntu/scripts/build/install-azcopy.sh
Revert those changes: https://github.com/actions/runner-images/pull/8982
Current release should be okay.
> [Ubuntu] Unpin AzCopy version to latest

- README.md
> README: tem remove of rollout badges

- images/macos/scripts/build/install-azcopy.sh
Revert those changes: https://github.com/actions/runner-images/pull/8979
Current release should be okay.
> [macOS] Unpin AzCopy version to latest

- images/ubuntu/scripts/tests/System.Tests.ps1
- images/ubuntu/templates/ubuntu-20.04.pkr.hcl
- images/ubuntu/templates/ubuntu-22.04.pkr.hcl
- images/ubuntu/templates/ubuntu-minimal.pkr.hcl
> [Ubuntu] reduce disks size in packer template

- .github/ISSUE_TEMPLATE/announcement.yml
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/tool-request.yml
> Add macOS 14 and macOS 14 Arm64 labels

- README.md
> Update for OS 14 Public Beta

- images/macos/macos-14-Readme.md
- images/macos/macos-14-arm64-Readme.md
> [macOS] Add OS14 READMEs

- images/windows/toolsets/toolset-2022.json
Another update for Visual Studio bootstrapper signature
> [Windows] Visual Studio 2022 signature updated

- images/ubuntu/scripts/build/install-docker.sh
- images/ubuntu/scripts/tests/Tools.Tests.ps1
- images/ubuntu/toolsets/toolset-2004.json
- images/ubuntu/toolsets/toolset-2204.json
Update installer and tests to work with the version pinning in a normal way
> [Ubuntu] Update Docker installer script

- images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/macos/scripts/docs-gen/SoftwareReport.Toolcache.psm1
- images/macos/scripts/tests/Toolcache.Tests.ps1
- images/macos/templates/macOS-14.anka.pkr.hcl
- images/macos/templates/macOS-14.arm64.anka.pkr.hcl
- images/macos/toolsets/toolset-14.json
> [macOS] Add toolcache to the macOS 14

- images/ubuntu/scripts/build/install-bazel.sh
> [ubuntu] Fix typo in install-bazel.sh

- images/ubuntu/scripts/build/install-sqlpackage.sh
In scope of this pull request, we update libssl version
> [Ubuntu] Update version of libssl

- images/windows/toolsets/toolset-2019.json
This PR updates VS signature thumbprint for windows-2019 image
https://github.com/actions/runner-images-internal/issues/5806
> [Windows] Update VS signature for windows-2019

- images/ubuntu/scripts/helpers/install.sh
This PR fixes error message redirection for some functions in install.sh helper script.
> [ubuntu] Fix error message redirection in install.sh

- README.md
> Update README.md: fix macOS-latest-large mapping in table

- images/windows/scripts/build/Configure-System.ps1
- images/windows/scripts/tests/WindowsFeatures.Tests.ps1
- images/windows/templates/windows-2019.pkr.hcl
- images/windows/templates/windows-2022.pkr.hcl
- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
Add Wireless LAN windows feature
https://github.com/actions/runner-images/issues/9305
> [Windows] Add Wireless LAN feature

- images/ubuntu/toolsets/toolset-2004.json
- images/ubuntu/toolsets/toolset-2204.json
Remove Ruby and Go old versions
- https://github.com/actions/runner-images/issues/9326
- https://github.com/actions/runner-images/issues/9327
> [Ubuntu] Remove Ruby, Go old versions

- .github/workflows/merge_pull_request.yml
> [merge-pr yaml] update to modern actions version

- .github/workflows/update_github_release.yml
> [update GitHub release yaml] switch to modern actions version

- images/ubuntu/scripts/build/install-sqlpackage.sh
This PR updates libssl1.1 on ubuntu image.
> [ubuntu] Update libssl1.1 version

- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
> [Windows] Upgrade php version to 8.3

- README.md
This PR adds Image Rollout Status badges to Readme file
> Add Image Rollout Status badges

- images/ubuntu/toolsets/toolset-2004.json
- images/ubuntu/toolsets/toolset-2204.json
> [Ubuntu] Update Az to 11.3.1

- images/macos/scripts/build/Configure-Xcode-Simulators.ps1
- images/macos/templates/macOS-13.anka.pkr.hcl
- images/macos/templates/macOS-13.arm64.anka.pkr.hcl
- images/macos/templates/macOS-14.anka.pkr.hcl
- images/macos/templates/macOS-14.arm64.anka.pkr.hcl
Add PowerShell version of Configure-Xcode-Simulators script
> [macOS] Add PowerShell version of Configure-Xcode-Simulators script

- images/macos/scripts/build/install-common-utils.sh
Newer version requires Xcode >=15.0 which is available only on OS13+
> [macOS] pin xcbeautify on OS12

- images/macos/toolsets/toolset-13.json
- images/macos/toolsets/toolset-14.json
Add XCode 15.3 to macOS 13 and macOS 14
#9459
> [macOS] add xcode 15.3 to macOS 13, 14

- images/macos/scripts/build/install-aws-tools.sh
- images/macos/scripts/build/install-common-utils.sh
- images/macos/scripts/build/install-git.sh
- images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/macos/scripts/tests/BasicTools.Tests.ps1
- images/macos/scripts/tests/Common.Tests.ps1
- images/macos/scripts/tests/Git.Tests.ps1
- images/macos/scripts/tests/Rust.Tests.ps1
- images/macos/templates/macOS-11.pkr.hcl
- images/macos/toolsets/toolset-11.json
We need to remove more software as building takes enormous amount of time due to degradation of installers
> [macOS] Delete more software from Big Sur

- .github/workflows/create_sbom_report.yml
Last release works better on Windows but consume to much resources on Ubuntu and macOS.
> Unpin SYFT tool version for Windows images

- images/windows/scripts/build/Install-Zstd.ps1
> [Windows] pin zstd to v1.5.5

- images/macos/scripts/docs-gen/SoftwareReport.Common.psm1
This PR fixes `composer` version parser for MacOS documentation
> [macos] Fix composer version parser

- images/windows/scripts/build/Install-Zstd.ps1
Reverts actions/runner-images#9570
> Revert "[Windows] pin zstd to v1.5.5"

- images/windows/scripts/build/Install-AzureCli.ps1
It happens from time to time.
https://github.com/actions/runner-images/issues/9610
> [Windows] Fix outdated Azure CLI installer signature

- images/windows/scripts/helpers/ChocoHelpers.ps1
Due to the latest changes in Chocolatey this helper should be moved from API.
More info [here](https://blog.chocolatey.org/2024/03/ccr-api-changes/).
> [Windows] Force Resolve-ChocoPackageVersion function to use CLI

- README.md
> Update README.md (OS14 latest migration)

- images/windows/toolsets/toolset-2022.json
> [Windows] Update Visual Studio 2022 signature

- images/ubuntu/scripts/helpers/Common.Helpers.psm1
- images/ubuntu/scripts/helpers/os.sh
> [Ubuntu] Add Numbat (24.04) helper functions

- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
update NSIS to 3.10
Related issue:
[#9596](https://github.com/actions/runner-images/issues/9596)
**Check list**
> update nsis version in windows images

- images/macos/toolsets/toolset-14.json
In scope of this PR, we add Xcode 15.4 Beta to macOS 14
> [macOS] Add Xcode 15.4 Beta

- images/ubuntu/scripts/build/install-heroku.sh
Fix heroku installation
https://github.com/actions/runner-images/issues/9716
> [Ubuntu] Fix heroku installation

- images/windows/scripts/build/Install-Chrome.ps1
- images/windows/scripts/tests/Browsers.Tests.ps1
Update google updater service name parser due changing its format with new version
> [Windows] Update google updater service name parser

- images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
> [Ubuntu] include Erlang only in ubuntu2004

- images/windows/scripts/build/Install-AzureCli.ps1
Updated the Latest ExpectedSignature of the AzureCli.
> 9771 Azurecli Expected signature updated

- images/ubuntu/Ubuntu2404-Readme.md
> Add Ubuntu24 initial readme

- images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/ubuntu/scripts/tests/Toolset.Tests.ps1
- images/ubuntu/templates/ubuntu-24.04.pkr.hcl
- images/ubuntu/toolsets/toolset-2404.json
Add missing toolcache packages and fix Fastlane section in software report.
> [Ubuntu] Add Go and Node to the toolcache on 24.04

- images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/ubuntu/scripts/tests/Tools.Tests.ps1
- images/ubuntu/templates/ubuntu-24.04.pkr.hcl
Revert back Bazel into Ubuntu 24.04 image
> [Ubuntu] Install Bazel and Bazelisk on Ubuntu 24.04

- images/macos/toolsets/toolset-14.json
Replace XCode 15.4 Beta with the latest release candidate.
> [macOS] Add Xcode 15.4 Release Candidate

- images/windows/toolsets/toolset-2019.json
Add missing tool to the image.
https://github.com/actions/runner-images/issues/9834
> [Windows] Add .NET SDK 8.0 to Windows-2019

- .github/ISSUE_TEMPLATE/announcement.yml
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/tool-request.yml
> [Ubuntu] Add 24.04 to templates

- README.md
> README: mark ubuntu24 as beta

- README.md
> README: use the same tag for deprecated as for beta

- helpers/GenerateResourcesAndImage.ps1
Add ubuntu 24.04 to custom images generator
> Add ubuntu 24.04 to custom image scripts generator

- images/ubuntu/toolsets/toolset-2404.json
Packages were published couple days ago
https://github.com/actions/runner-images/issues/9834
> [Ubuntu] Add .NET SDKs 6 and 7 on Ubuntu 24.04

- images/windows/scripts/build/Install-Git.ps1
- images/windows/scripts/tests/Git.Tests.ps1
Add git environment variable `GIT_CLONE_PROTECTION_ACTIVE` with the value `false` to mitigate changes in the latest release. https://github.blog/2024-05-14-securing-git-addressing-5-new-vulnerabilities/
> [Windows] Add new git environment variable

- images/macos/scripts/build/configure-machine.sh
- images/macos/scripts/tests/Git.Tests.ps1
Add git environment variable `GIT_CLONE_PROTECTION_ACTIVE` with the value `false` to mitigate changes in the latest release. https://github.blog/2024-05-14-securing-git-addressing-5-new-vulnerabilities/
> [macOS] Add new git environment variable

- images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1
Update thumbprint for cosmosdb-emulator
#9909
> [Windows] Update thumbprint for cosmosdb-emulator

- images/ubuntu/scripts/build/install-kubernetes-tools.sh
Reverts actions/runner-images#9867
https://github.com/helm/helm/issues/13040#issuecomment-2127518356
> Revert "[Ubuntu] Pin Helm 3.14.4 due to unusual release of 3.15.0"

- .github/workflows/codeql-analysis.yml
- .github/workflows/linter.yml
- .github/workflows/powershell-tests.yml
Noisy warnings and soon deprecation
> Update github/codeql-action and actions/checkout actions version

- images/windows/scripts/build/Install-AWSTools.ps1
Update signature for SessionManagerPluginSetup.exe
Closes: https://github.com/actions/runner-images/issues/9958
> [Windows] Update signature for SessionManagerPluginSetup.exe

- images/ubuntu/scripts/build/install-azure-cli.sh
> [ubuntu] Install native azure-cli on noble

- images/macos/scripts/build/configure-machine.sh
- images/macos/scripts/tests/Git.Tests.ps1
- images/ubuntu/scripts/build/install-git.sh
- images/ubuntu/scripts/tests/Tools.Tests.ps1
- images/windows/scripts/build/Install-Git.ps1
- images/windows/scripts/tests/Git.Tests.ps1
v2.45.2 of git fixes those issues with las and it is now being installed in latest builds so we are safe to revert this change starting next week's deployment.
> [All OSes] Revert gitlfs changes

- images/ubuntu/toolsets/toolset-2004.json
- images/ubuntu/toolsets/toolset-2204.json
- images/ubuntu/toolsets/toolset-2404.json
- images/windows/scripts/build/Install-DockerCompose.ps1
- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
In order to continue work started here: https://github.com/actions/runner-images/pull/9817
> [Ubuntu, Windows] Update Docker tools versions

- images/macos/toolsets/toolset-14.json
New compatible with macOS 14.5+ Xcode released.
> [macOS-14] Add Xcode 16.0 Beta 1

- .github/workflows/ubuntu2404.yml
This PR adds Actions workflow for triggering ubuntu-2404 Image build
> [ubuntu24] Add Actions build workflow

- images/ubuntu/scripts/build/configure-environment.sh
- images/ubuntu/scripts/tests/System.Tests.ps1
This reverts commit 145c80df8dab28d9850f24361dd09ff05f854606.
> Revert "[Ubuntu] disable apparmor (#10024)"

- images/ubuntu/scripts/build/install-gfortran.sh
Always install latest Fortran symlink
> [Ubuntu] always install gfrotran

- images/windows/scripts/build/Install-GoogleCloudCLI.ps1
This PR:
Updates Google CLI signature on windows
> [windows] Fix Google CLI signature for windows

- README.md
This PR updates Image Rollout Badge URLs in `README.md`
> Update Image Rollout Badge URLs

- images/ubuntu/toolsets/toolset-2004.json
- images/ubuntu/toolsets/toolset-2204.json
Add alpine 3.19 docker image for ubuntu 20 and 22.
> [Ubuntu] Add alpine 3.19 docker image

- images/windows/scripts/build/Install-AzureCli.ps1
Nightly image generation failed due to AzureCli signature, this PR will update the new Signature.
Windows-19 and Windows 2022 image generations will be successful
> [Windows] updated azure cli signature

- images/windows/scripts/build/Install-Chrome.ps1
1) Image generation failed due to visual studio cli signature, this PR will update the new Signature.
2) Windows 2019 and 2022 image generations will be successful.
> [Windows] Fix google chrome signature error for windows

- images/ubuntu/scripts/build/install-rust.sh
- images/windows/scripts/build/Install-Rust.ps1
1) Builds were failed with rust issue. 
[ Ubuntu](https://github.visualstudio.com/runner-images/_build/results?buildId=136452&view=logs&j=001f5b32-88ff-5d71-9ac8-3526ca5cebb7) and [windows ](https://github.visualstudio.com/runner-images/_build/results?buildId=136456&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f05f5d13-c61c-51fd-2a8c-71d3e56d3e3f)
2) This PR will fix the issue and helps to successful image generation.
> [Ubuntu,Windows] Fix rust issue for ubuntu and windows

- images/ubuntu/scripts/build/install-azure-cli.sh
Reverts actions/runner-images#10126
> Revert "[Ubuntu] Update Shell Script to Verify Azure CLI Availability"

- images/macos/toolsets/toolset-14.json
Xcode 16.1 Beta compatible with macOS 14 released.
> [macOS] Add Xcode 16.1 Beta for macOS14

- images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/ubuntu/scripts/tests/Tools.Tests.ps1
- images/ubuntu/templates/ubuntu-24.04.pkr.hcl
Adding kotlin in ubuntu 24.04 image
> [Ubuntu] adding kotlin in ubuntu 24.04 image

- images/macos/scripts/build/configure-system.sh
- images/macos/scripts/build/configure-tccdb-macos.sh
- images/macos/scripts/build/install-bicep.sh
- images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/macos/scripts/docs-gen/SoftwareReport.Browsers.psm1
- images/macos/scripts/docs-gen/SoftwareReport.Java.psm1
- images/macos/scripts/docs-gen/SoftwareReport.Toolcache.psm1
- images/macos/scripts/helpers/Common.Helpers.psm1
- images/macos/scripts/helpers/utils.sh
- images/macos/scripts/tests/BasicTools.Tests.ps1
- images/macos/scripts/tests/Browsers.Tests.ps1
- images/macos/scripts/tests/Common.Tests.ps1
- images/macos/scripts/tests/Databases.Tests.ps1
- images/macos/scripts/tests/Haskell.Tests.ps1
- images/macos/scripts/tests/Linters.Tests.ps1
- images/macos/scripts/tests/Node.Tests.ps1
- images/macos/scripts/tests/PHP.Tests.ps1
- images/macos/scripts/tests/PipxPackages.Tests.ps1
- images/macos/scripts/tests/Python.Tests.ps1
- images/macos/scripts/tests/RubyGem.Tests.ps1
- images/macos/scripts/tests/Rust.Tests.ps1
- images/macos/scripts/tests/System.Tests.ps1
- images/macos/scripts/tests/Toolcache.Tests.ps1
- images/macos/scripts/tests/WebServers.Tests.ps1
- images/macos/scripts/tests/Xamarin.Tests.ps1
- images/macos/scripts/tests/Xcode.Tests.ps1
- images/macos/templates/macOS-15.anka.pkr.hcl
- images/macos/templates/macOS-15.arm64.anka.pkr.hcl
- images/macos/toolsets/toolset-15.json
This code makes the following changes:
- introduce macOS-15 templates
- introduce macOS-15 related base functions
- introduce macOS-15 toolset
- update conditions to run macOS-15 builds
- fix a couple of minor bugs
What this code **does not do**? 
- These edits do not indicate that GitHub users can use the macOS-15 image. 
- These edits do not mark the beginning of a public or non-public beta of macOS-15. 
- This code is not recommended for use in building macOS-15 images.
> [macOS] Introduce macOS-15 code

- images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/ubuntu/scripts/tests/Tools.Tests.ps1
- images/ubuntu/templates/ubuntu-24.04.pkr.hcl
Added Packer tool to Ubuntu 24.04 image. 
https://github.com/actions/runner-images/issues/10445
> Add Packer tool to Ubuntu24.04 image

- images/macos/scripts/tests/System.Tests.ps1
Previously we checked for 10 GB which is MS but not GH standard
> [macOS] Update free space test condition to 14 GB

- images/macos/toolsets/toolset-15.json
As a matter of initial setup for the upcoming `beta`
> [macOS] Update initial macOS-15 Xcode setup

- images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/ubuntu/scripts/tests/Common.Tests.ps1
- images/ubuntu/templates/ubuntu-24.04.pkr.hcl
This PR adds the Swift version to the Ubuntu 24 image. This will helps users to use swift programing language with ubuntu-24.04 image.
> [Ubuntu] Add swift version to ubuntu 24 image

- images/windows/scripts/helpers/VisualStudioHelpers.ps1
- images/windows/toolsets/toolset-2019.json
This PR will fix the issue with the Visual Studio signature and updates the signature for Visual Studio on windows 2019 image.
[10591](https://github.com/actions/runner-images/issues/10591)
> [Windows] Fix visual studio  signature issue on windows 2019 image

- images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/ubuntu/scripts/tests/Browsers.Tests.ps1
- images/ubuntu/templates/ubuntu-24.04.pkr.hcl
Added Firefox to Ubuntu24.04 image.
https://github.com/actions/runner-images/issues/10374
> [Ubuntu] Added firefox to Ubuntu24.04 image

- README.md
Remove stale badge
https://github.com/actions/runner-images/issues/10636
> [doc] Change Ubuntu-24.04 status: beta -> GA

- images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
- images.CI/macos/anka/Service.Helpers.psm1
Update base image generation to work with Sequoia updates
> [macOS] Update base image generation to work with Sequoia updates

- .github/ISSUE_TEMPLATE/announcement.yml
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/tool-request.yml
- README.md
- images/macos/macos-15-Readme.md
- images/macos/macos-15-arm64-Readme.md
🚀 
- https://github.com/github/roadmap/issues/987
> [macOS] Introduce macOS-15 beta images

- images/macos/scripts/docs-gen/SoftwareReport.Xcode.psm1
Provide more info for better transparency
[#6287](https://github.com/actions/runner-images-internal/issues/6287)
> [macOS] Add Xcode symlinks to the Software Report

- images/windows/scripts/build/Install-EdgeDriver.ps1
This PR will update the signature thumbprint for the edge driver in the windows  images.
https://github.com/actions/runner-images/issues/10822
> [Windows] Signature thumbprint updated for the edgedriver

- README.md
Update documentation to reflect the new Xcode support policy
- https://github.com/actions/runner-images/issues/10703
> [doc] Update Xcode support policy

- images/macos/toolsets/toolset-15.json
Add Xcode 16.1 and 16.2 Beta 1 to macOS15
> [macOS] Add Xcode 16.1 and 16.2 Beta 1 to macOS15

- images/macos/toolsets/toolset-15.json
Add Xcode 16.2_beta_2 to macOS 15
> [macOS]Add Xcode 16.2_beta_2 to macOS 15

- images/macos/scripts/build/install-unxip.sh
- images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/macos/scripts/docs-gen/SoftwareReport.Common.psm1
- images/macos/scripts/tests/Common.Tests.ps1
- images/macos/templates/macOS-13.anka.pkr.hcl
- images/macos/templates/macOS-13.arm64.anka.pkr.hcl
- images/macos/toolsets/toolset-13.json
Add unxip for macOS13 and macOS13 arm images.
> [macOS] Add unxip for macOS13

- images/macos/scripts/build/install-openssl.sh
- images/macos/scripts/tests/OpenSSL.Tests.ps1
> Macos openssl1.1 issue

- images/macos/scripts/build/install-openssl.sh
- images/macos/scripts/tests/OpenSSL.Tests.ps1
Add openssl@1.1 using old homebrew commit
> [macOS] Add openssl@1.1 using old homebrew commit

- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
This PR adding latest Dotnet version 9.0  in Windows-2019 and windows-2022
https://github.com/actions/runner-images/issues/10964
> [Windows] Adding Dotnet latest version 9.0

- images/windows/toolsets/toolset-2022.json
Update Visual Studio signature for windows-2022 image
> [Windows] Update Visual Studio signature

- images/windows/scripts/build/Install-DACFx.ps1
This PR will fix the DACF signature issue.
> [Windows] Updated the DACF thumbprint signature.

- images/macos/scripts/tests/System.Tests.ps1
- images/macos/toolsets/toolset-15.json
- Add Xcode 15.4 on macOS-15
- Update disk space test to provide more output
> [macOS] Add Xcode 15.4 to macOS-15

- images/windows/scripts/build/Configure-ImageDataFile.ps1
- images/windows/templates/windows-2025.pkr.hcl
Fix the value of the variable "image_os" for Windows 2025
> [Windows] Fix the value of the variable "image_os" for Windows 2025

- images/windows/scripts/build/Install-EdgeDriver.ps1
> [Windows] Update EdgeDriver signature

- images/macos/scripts/build/install-common-utils.sh
- images/macos/scripts/tests/BasicTools.Tests.ps1
Add Symlink for tcl-tk8
https://github.com/actions/runner-images/issues/11074
> [macOS] Add Symlink for tcl-tk8

- .github/ISSUE_TEMPLATE/announcement.yml
- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/tool-request.yml
- README.md
- images/windows/Windows2025-Readme.md
Add Windows Server 2025 Readme and update docs
> [Windows] Introduce Windows Server 2025 beta images

- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
- Version Update addressing [CVE](https://www.cve.org/CVERecord?id=CVE-2023-23383)
- Bump Service Fabric to latest build for 9.1 version
> [Windows] Update Service Fabric Versions

- images/windows/toolsets/toolset-2025.json
Remove Visual Studio components related to 4.7.SDK
> [Windows-2025] Remove Visual Studio components related to 4.7.SDK

- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
Reverts actions/runner-images#11048
As we need to check with 1ES folks.
> Revert "[Windows] Update Service Fabric Versions"

- images/windows/toolsets/toolset-2019.json
This PR will update the Visual Studio signature for Windows 2019.
> [Windows] Update visual studio signature for windows 2019

- images/ubuntu/scripts/build/cleanup.sh
- images/ubuntu/scripts/build/install-azure-cli.sh
- images/ubuntu/scripts/build/install-azure-devops-cli.sh
Reverts actions/runner-images#11173
Reverting this as user workflows are failing due to this [issue](https://github.com/actions/runner-images/issues/11347)
> Revert "Implement az-cli warmup on ubuntu"

- images/macos/scripts/build/install-rubygems.sh
Add activesupport 7.1.5.1 to the macOS Images.
> [macOS] Add activesupport 7.1.5.1 to all images

- images/ubuntu/scripts/build/install-kubernetes-tools.sh
This PR will fix the minikube installation failure on Ubuntu by pinning the version.
https://github.com/actions/runner-images/issues/11407
> [Ubuntu] Fix minikube failure on ubuntu images

- images/ubuntu/scripts/helpers/etc-environment.sh
> [ubuntu] Update etc-environment.sh

- images/macos/scripts/build/Install-Xcode.ps1
- images/macos/scripts/helpers/Xcode.Installer.psm1
- images/macos/toolsets/Readme.md
- images/macos/toolsets/toolset-14.json
- Removed redundant variable
- Added content validation
- Updated related documentation
> [macOS] Update Xcode installer script - type optimization

- images/macos/macos-15-arm64-Readme.md
Rolling back image due to the issue: https://github.com/actions/runner-images/issues/11509
> Revert "macOS 15 arm64 (20250127) Image Update"

- images/macos/scripts/tests/Mono.Tests.ps1
Update condition for mono test case to run only for macOS13 and macOS14.
> [macOS] Update condition for mono test case

- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
This PR will update the mongodb signature thumbprint.
https://github.com/actions/runner-images/issues/11523
> [Windows 19 & 22] Updated the mongodb signature thumbprint.

- images/windows/scripts/build/Install-WSL2.ps1
This PR will update the latest WSL2 checksum.
> [Windows 2025] Updated latest WSL2 checksum.

- images/windows/scripts/build/Install-AWSTools.ps1
This PR will update the signature for AWScli SessionManagerPluginSetup.exe.
https://github.com/actions/runner-images/issues/11553
> [Windows] Update signature for AWScli SessionManagerPluginSetup.exe

- images/macos/macos-15-arm64-Readme.md
Reverts actions/runner-images#11575
> Revert "macOS 15 arm64 (20250210) Image Update"

- images/windows/scripts/build/Install-EdgeDriver.ps1
- images/windows/scripts/build/Install-WSL2.ps1
This PR will fix edgedriver signature in windows images and Wsl2 checksum in windows 2025 image.
> [Windows] Updating Edgedriver signature and Wsl2 checksum

- images.CI/linux-and-win/build-image.ps1
This pull request updates the Azure tags handler to pass the tags into the Packer.
https://github.com/actions/runner-images/issues/11606
> Update Azure tags handler

- images/macos/toolsets/toolset-15.json
Adding xcode 16.3 beta to macOS15 images
> [macOS] Adding xcode 16.3 beta to macOS15 images

- images/windows/scripts/build/Install-Git.ps1
Revert https://github.com/actions/runner-images/pull/11642
> Revert "[Windows] Pin the git version to 2.47.1".

- images/windows/scripts/build/Install-Firefox.ps1
This PR update the gecko-driver-signature for Windows images
> [Windows] Updating gecko-driver-signature

- images/windows/toolsets/toolset-2022.json
- images/windows/toolsets/toolset-2025.json
This PR will update the Visual Studio signature Thumbprint on windows images 22 and 25.
> [windows(22 & 25)] Update  Visual Studio signature Thumbprint on windows

- images/macos/macos-15-Readme.md
Reverts actions/runner-images#11682
> Revert "macOS 15 (20250226) Image Update"

- images/macos/macos-14-Readme.md
Reverts actions/runner-images#11661
> Revert "macOS 14 (20250224) Image Update"

- images/macos/macos-14-arm64-Readme.md
Reverts actions/runner-images#11671
> Revert "macOS 14 arm64 (20250225) Image Update"

- images/macos/macos-15-arm64-Readme.md
Reverts actions/runner-images#11681
> Revert "macOS 15 arm64 (20250226) Image Update"

- images/ubuntu/scripts/build/install-ninja.sh
- images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/ubuntu/scripts/docs-gen/SoftwareReport.Tools.psm1
- images/ubuntu/scripts/tests/Tools.Tests.ps1
- images/ubuntu/templates/ubuntu-20.04.pkr.hcl
- images/ubuntu/templates/ubuntu-22.04.pkr.hcl
- images/ubuntu/templates/ubuntu-24.04.pkr.hcl
Add Ninja to Ubuntu images
#11391
#11235
> [Ubuntu] Add Ninja

- images/windows/scripts/docs-gen/Generate-SoftwareReport.ps1
- images/windows/scripts/docs-gen/SoftwareReport.Tools.psm1
- images/windows/scripts/tests/ChocoPackages.Tests.ps1
- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
- images/windows/toolsets/toolset-2025.json
Add Ninja to Windows images
https://github.com/actions/runner-images/issues/11391
https://github.com/actions/runner-images/issues/11235
> [Windows] Add Ninja

- images/macos/toolsets/toolset-15.json
WatchOS and tvOS version has been updated
> [macOS] Xcode 16.3 beta 2 - WatchOS tvOS version update

- images/ubuntu/scripts/build/install-ruby.sh
This PR will fix the Ubuntu 20 failure by pinning supported ruby gems.
> [Ubuntu] Fix Ubuntu 20 failure by pinning ruby gems

- .github/workflows/create_pull_request.yml
Reverts actions/runner-images#11817
> Revert "Updating create_pull_request file"

- images/macos/macos-15-Readme.md
Reverts actions/runner-images#11788
> Revert "macOS 15 (20250312) Image Update"

- images/macos/macos-15-arm64-Readme.md
Reverts actions/runner-images#11787
> Revert "macOS 15 arm64 (20250312) Image Update"

- images/windows/toolsets/toolset-2025.json
This PR will update the **mongodb** signature thumbprint for Windows 25.
> [Windows 25]Updated the mongodb signature thumbprint.

- images/ubuntu/scripts/build/install-rust.sh
This PR fixes the rust issue for ubuntu-20 and ubuntu-22.
https://github.com/actions/runner-images/issues/11941
> [Ubuntu 20 & Ubuntu22] Fix Rust issue.

- images/windows/toolsets/toolset-2019.json
This PR will fix the visual studio signature thumbprint for Windows- 2019.
> [Windows] Update Visual Studio Signature Thumbprint for 2019

- images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1
This PR updates the checksum for the AzureCosmoDB image for Windows Images
> [Windows] update AzureCosmoDB checksum

- images/windows/scripts/build/Install-AzureCli.ps1
- images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1
This PR will update the AzureCli and AzureCosmosDbEmulator signature for windows images
> [Windows] Update AzureCli and AzureCosmosDbEmulator signature

- images/macos/scripts/docs-gen/SoftwareReport.Browsers.psm1
1. Add Mozilla Firefox details to software report file for arm64 images.
> [macOS] Add Mozilla Firefox details to software report file for arm64 images.

- .github/workflows/linter.yml
https://github.com/super-linter/super-linter/releases
> Bumped `super-linter/slim` package to `v7`

- images/windows/toolsets/toolset-2022.json
This PR will update LLVM version to `20` for windows22.
> [Windows22] Updating LLVM version to 20.

- images/windows/toolsets/toolset-2025.json
>Strawberry Perl is a perl environment for MS Windows containing all you need to run and develop perl applications. It is designed to be as close as possible to perl environment on UNIX systems.
* Update `strawberryperl` from `5.40.0.1` -> `5.40.2.2`
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases
> [Windows 2025] Update `strawberryperl` to `5.40.2.2`

- images/ubuntu/scripts/build/post-build-validation.sh
- images/ubuntu/templates/build.ubuntu-22_04.pkr.hcl
- images/ubuntu/templates/build.ubuntu-24_04.pkr.hcl
This PR validate MS Defender is not installed
> Validate MS Defender is not installed

- images/windows/scripts/build/Install-WDK.ps1
This PR will upgrade the Windows Driver Kit (WDK) to the latest version 10.1.26100.4202.
https://github.com/actions/runner-images/issues/12533
> [windows-22] Upgrade Windows Driver Kit (WDK) to latest

- images/windows/scripts/build/Install-Mercurial.ps1
This PR updates Mercurial to the latest version.
> [Windows] Updating Mercurial latest version 6.3.1

- images/macos/scripts/build/configure-tccdb-macos.sh
Cover some additional cases for Apple Script usage on macOS
> [macOS] Add more TCC entries for bash and osascript

- README.md
Updating macos-15 images pointing to macos-latest label tag.
> Update macOS labels in README.md

- images/ubuntu/scripts/build/install-cmake.sh
- images/windows/toolsets/toolset-2019.json
- images/windows/toolsets/toolset-2022.json
- images/windows/toolsets/toolset-2025.json
This PR will unpin the version for cmake tool on windows and ubuntu images
https://github.com/actions/runner-images/issues/12958
> [Windows,Ubuntu] Unpin the Cmake version

- images/macos/scripts/build/install-ruby.sh
Replacing https://github.com/actions/runner-images/pull/13051 for macOS due to how our repo processes work and some issues with the initial PR.
https://github.com/actions/runner-images/issues/13050
> [macOS] Update Ruby installer script due to #13050

- .github/workflows/check-pinned-versions.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create_pull_request.yml
- .github/workflows/linter.yml
- .github/workflows/merge_pull_request.yml
- .github/workflows/powershell-tests.yml
- .github/workflows/trigger-ubuntu-win-build.yml
- .github/workflows/validate-json-schema.yml
https://github.com/actions/checkout/releases
> Bump GitHub `actions/checkout` packages to `v5`

- .github/workflows/linter.yml
https://github.com/super-linter/super-linter/releases
> Bump `super-linter/slim` package to `v8`

- .github/workflows/linter.yml
Reverts actions/runner-images#13114
> Revert "Bump `super-linter/slim` package to `v8`"

- images/windows/scripts/build/Install-PostgreSQL.ps1
Program Files is a bit more protected directory on Windows Server 2025, and inheritance work a bit other way there.
https://github.com/actions/runner-images/issues/13040
> [Windows] Move PGDATA out of Program Files

- images/ubuntu/scripts/tests/System.Tests.ps1
- images/windows/scripts/tests/WindowsFeatures.Tests.ps1
This pull request updates disk space validation logic in both Ubuntu and Windows test scripts to improve clarity and consistency.
> [Windows,Ubuntu] Update disk space pester test
