actions/runner-images

images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

[macOS] Add pkg-config via brew for vcpkg

---

images/linux/scripts/installers/sqlpackage.sh

Remove sqlpackage fix for Ubuntu 22.04
https://github.com/actions/runner-images/issues/7147

[Ubuntu] Remove libssl dependency

---

images/macos/toolsets/toolset-12.json

Announcement(issue-7127): Xcode 13.4 will be pointing to Xcode 13.4.1 and Xcode 13.4 removed.
https://github.com/actions/runner-images/issues/7127

[macOS] point Xcode 13.4 to 13.4.1

---

images/macos/provision/utils/utils.sh

Update utils.sh for macOS. Add check for "all" type of bottle, enhance logging for hypothetical failures  with echo+jq pair.

[macOS] Update utils.sh - brew all bottles, fix echo

---

images/macos/provision/core/commonutils.sh

[macOS] do not install tcl/tk symlinks on BigSur

---

images/linux/scripts/helpers/install.sh

Use the interval value in retry function 
https://github.com/actions/runner-images/issues/7208

[Ubuntu] Use variable instead of hard coded value

---

images/linux/scripts/installers/android.sh

[ubuntu] fix cmdline-tools parser

---

images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

This reverts commit 7e014ba67ba4fccf5280394ff77663a65eb0ca84.
The latest stable maven release broke deployments to/incompatible with GitHub Packages.
Talking with support the root cause seems to be this commit.

Revert "[Ubuntu] Update Maven to 3.9.0 (#7060)"

---

images/win/scripts/Installers/Install-Docker.ps1

Choco updated version of docker-compose to v2. Pin version v1 => 1.29.*

[windows] Fix version for docker-compose v1

---

images/linux/scripts/tests/CLI.Tools.Tests.ps1

AWS session manager plugin 1.2.458.0 has introduced breaking change: output was redirected to stderr instead of stdout.
automatic test should have been updated accordingly
https://github.com/actions/runner-images/issues/7284

[ubuntu] aws session manager plugin 1.2.458.0 fix

---

images/linux/scripts/installers/java-tools.sh
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

Maven 3.8.7 available only as archived version, download links were updated.
More info here: https://maven.apache.org/download.cgi

[Ubuntu] Update Maven to 3.8.8, new download link

---

images.CI/macos/select-datastore.ps1

Small improvement for MacOS image generation. We need to ignore "vmkdump" because it is not VM folder

[macos] ignore "vmkdump" folder in VISphere

---

images/macos/helpers/Common.Helpers.psm1

Use the interval value in retry function
https://github.com/actions/runner-images/issues/7208

[macOS] Use variable instead of hard coded value

---

images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json
images/macos/toolsets/toolset-13.json

Go 1.17.x will be removed from all OSes and 1.20.x will be set as default.
Image deployment is starting on April 3 and will take 3-4 days.
As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of Go are supported.
If your builds depend on Go 1.17.x they can be broken.
https://github.com/actions/runner-images/issues/7276

[macos] remove go 1.17

---

images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Go 1.17.x will be removed from all OSes and 1.20.x will be set as default.
Image deployment is starting on April 3 and will take 3-4 days.
As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of Go are supported.
If your builds depend on Go 1.17.x they can be broken.
https://github.com/actions/runner-images/issues/7276

[windows] remove go 1.17

---

images/win/scripts/Installers/Install-OpenSSL.ps1
images/win/scripts/Tests/ChocoPackages.Tests.ps1
images/win/scripts/Tests/Tools.Tests.ps1
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json
images/win/windows2019.json
images/win/windows2022.json

Add script to install OpenSSL using executable installer rather then choco package. This is mainly to be able to select which version to install and to switch between light and full variants. The problem with choco is that light package doesn't provide up-to-date patch for OpenSSL 1.1.1 and full package doesn't have versions for OpenSSL 3.x.
Script uses repo https://github.com/slproweb/opensslhashes to get information about currently available versions of Win-OpenSSL installers, filters out installers that don't satisfy the requirements provided and selects the latest version among remaining ones.
Currently it is configured to install full variant of the version 1.1.1.

[Windows] Add script for OpenSSL installation

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/tests/Tools.Tests.ps1

Fix OpenSSL library issue for PhantomJS.
Assign env var for OpenSSL to work with deprecated request from PhantomJS.
[#4917](https://github.com/actions/runner-images-internal/issues/4917)

[Ubuntu] Temp patch for PhantomJS/libssl conflict

---

images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

Go 1.17.x will be removed from all OSes and 1.20.x will be set as default.
Image deployment is starting on April 3 and will take 3-4 days.
As of the [software support](https://github.com/actions/runner-images#software-and-image-support) policy only 3 latest versions of Go are supported.
If your builds depend on Go 1.17.x they can be broken.
https://github.com/actions/runner-images/issues/7276

[ubuntu] remove go 1.17

---

images/win/scripts/Tests/Tools.Tests.ps1

Currently test for OpenSSL only checks that OpenSSL binary exists and is executable but the version is not validated. This request changes test to ensure that the version of OpenSSL binary that is located using PATH matches the version specified in toolset.

[Windows] Validate OpenSSL version

---

.github/workflows/macos-generation.yml
.github/workflows/ubuntu-win-generation.yml

scheduled image generation uses dedicated "macos-vmware" runner not available in forks. 
thus builds should not be scheduled in forks

hide builds using dedicated runners from forks

---

images/win/scripts/Installers/Install-Ruby.ps1

Ruby 2.4 is too deep in current releases manifest.

[Windows] Add more releases per page for Ruby installer

---

images/win/scripts/Installers/Install-WindowsFeatures.ps1

According to the email from: Alexander Grest <Alexander.Grest@microsoft.com>
```
[Hyper-V hypervisor scheduler types | Microsoft Learn](https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types)
You could try to enable the root scheduler (bcdedit /set hypervisorschedulertyupe root) and see if it improves emulator launch, but please note that you lose isolation guarantees between SMT threads.
```
https://github.com/actions/runner-images-internal/issues/4786

Run bcdedit /set hypervisorschedulertyupe root

---

helpers/GenerateResourcesAndImage.ps1
images/linux/ubuntu2204.pkr.hcl

The logic is used in GenerateResourcesAndImage for setting tags is suitable for json manifests only. It causes function failure when tags are set for Ubuntu22 build. This PR is use proper way to pass tags to the build based on hcl2 manifest.

Fix failure when tags are set for Ubuntu 22 generation

---

images/win/scripts/Installers/Install-DotnetSDK.ps1

Improvement
Adds .NET environments variables that are already being added in the [Linux image](https://github.com/actions/runner-images/blob/07662e65bab775c1bf9e974047a33ab2929d1f1a/images/linux/scripts/installers/dotnetcore-sdk.sh#L87-L89).
This will remove some noise in the output and squeeze out some performance.
I started a [discussion post](https://github.com/actions/runner-images/discussions/7209), but I never received any feedback.

Add .NET environment variables to windows image 

---

images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
images.CI/macos/anka/Service.Helpers.psm1

In this PR 
Added: 
- Support macOS 13 clean image generation on the arm64 platform 
Fixed: 
- macOS 12 tried to download the major update to macOS Ventura
https://github.com/actions/runner-images-internal/issues/4941

Support ARM64 architecture

---

images/linux/scripts/helpers/install.sh

There is a bug in `download_with_retries` function: the flag `-e` remains unset after successful download. It means that shell doesn't stop script execution when any command fails after `download_with_retries` invocation. It may obscure failure on further software installation.

[Ubuntu] Enable exit on error immediately after download attempt

---

images.CI/macos/anka/Anka.Helpers.psm1

Fixing an issue in generating Anka images for MacOS arm64 images. TLS was not enabled for the Anka node, and TLS verification was failing.
MacOS Intel images generation was not impacted as Anka TLS and TLS verification were disabled. It will be enabled there too.
Error seen first in [this build](https://dev.azure.com/mseng/AzDevNext.Deploy/_build/results?buildId=19752222&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=829dae9b-42f5-5e1c-cb9a-4dfa99b6fb63&l=117):  `Invoke-AnkaCommand: There is an error during command execution: anka: SSL connect error`
Error after enabling TLS for Anka in [this build](https://dev.azure.com/mseng/AzDevNext.Deploy/_build/results?buildId=19756189&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=829dae9b-42f5-5e1c-cb9a-4dfa99b6fb63&l=116): …

Add ca cert to the command line to use TLS in DVT racks

---

.github/ISSUE_TEMPLATE/bug-report.yml

since macOS-13 is generally available, let us add to 
https://github.com/actions/runner-images-internal/issues/5030

[macos] add macOS-13 to issue template

---

images/macos/provision/core/edge.sh

Fixing failing image generation for MacOS 11 and 12
Failing builds:
[MacOS 12](https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=19853895&view=results)
[MacOS 11](https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=19863509&view=results)
New version Edge start using EdgeUpdater instead Microsoft Autoupdate from `13.0.1774.35: May 5, 2023` - https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel
Docs for disabling auto updated using EdgeUpdater - https://learn.microsoft.com/en-us/deployedge/edge-learnmore-edgeupdater-for-macos

[MacOS] Fix edge installing script

---

images/linux/scripts/tests/Browsers.Tests.ps1

Pester test for Firefox browser uses sudo command that prevents test from succeeding on live VM after provisioning. This PR fixes that test.

Test firefox without sudo

---

images/linux/scripts/installers/post-deployment.sh
images/macos/provision/configuration/finalize-vm.sh

Currently generation scripts are removed from image in one of the last stages of image generation. We need them to run Pester tests on runners provisioned in real environment.
The alternative solution would be to checkout this repo each time we want to run tests. But in may cause unexpected failures when testing previously built image after tests or toolset in repo have been updated.

Keep generation scripts in macOS and Ubuntu images

---

images/linux/ubuntu2204.pkr.hcl

Ubuntu 22 generation is broken due to invalid variable references in HCL template. This PR fixes those references.

Fix variable references in Ubuntu 22 template

---

images/macos/software-report/SoftwareReport.Generator.ps1

in image generation pipeline several "software report" files are created, including "systeminfo.txt"
that file is not used later, we can drop its generation
https://github.com/actions/runner-images-internal/issues/5013

[macos] systeminfo.txt: remove debug leftover

---

images/linux/scripts/installers/docker-moby.sh

Fix the condition in the file docker-moby.sh
Instead of "-eq" we will use "=="
"==" is for string comparisons and "-eq" is for numeric ones.
#7586

[ubuntu] fix the condition in docker-moby.sh

---

.github/workflows/macos-generation.yml
images.CI/macos/move-vm.ps1
images.CI/macos/set-vm-size.ps1

Currently `vm-move.ps1` script has off-target functionality in terms of setting VM size. It causes resizing to be performed twice in some image generation pipelines. This request separates logic of moving and resizing in two different scripts to avoid aforementioned behavior.

Separate VM resizing and moving into two different scripts

---

images/macos/provision/core/python.sh
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/tests/Python.Tests.ps1

python (and pipx) added to MacOS13
https://github.com/actions/runner-images/issues/7590

[macos] enable python3 (and pipx) on macOS13

---

docs/create-image-and-azure-resources.md
helpers/GenerateResourcesAndImage.ps1

Depending on PowerShell version, -RestrictToAgentIpAddress argument behaves differently.
Runners are using PowerShell 7.2, where double quotes should be escaped.
Documentation is updated.

Add double quote escaping and update GenerateResourcesAndImage.ps1 documentation

---

images/macos/provision/core/python.sh

Fix Python installer script to install Python2 only on macOS 11 and 12

[macOS] Fix Python2 installer condition

---

images/linux/scripts/installers/containers.sh

Ubuntu 20 image generation silently fails on execution of containers.sh script because URL for libcontainers repo key is invalid.
Failed run example: https://github.com/actions/runner-images/actions/runs/5055635815/jobs/9072092744?pr=7627
This PR fixed URL and removes `-q` flag from `wget` command to see it's execution result.

[Ubuntu] Fix url for Ubuntu 20 libcontainers repo key

---

helpers/software-report-base/SoftwareReport.Nodes.psm1
images/win/scripts/ImageHelpers/TestsHelpers.ps1

Correct typo from 'Delimeter' to 'Delimiter'.
None

Correct typo from 'Delimeter' to 'Delimiter'

---

.github/ISSUE_TEMPLATE/announcement.yml
.github/ISSUE_TEMPLATE/tool-request.yml
images/macos/toolsets/toolset-13.json

The new version of XCode have been released recently for macOS 13. This PR is to install it on our runners.

[macOS] Add XCode 14.3.1 for macOS 13

---

README.md

Add information about `-latest` migration.

README: explain -latest migration process

---

images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

The "--local-only" key was deprecated and deleted from the software report generation.

[Windows] fix software report for innosetup

---

.github/workflows/macos-generation.yml
images.CI/macos/azure-pipelines/image-generation.yml
images/macos/provision/core/xcode.ps1
images/macos/templates/macOS-11.anka.pkr.hcl
images/macos/templates/macOS-11.json
images/macos/templates/macOS-12.anka.pkr.hcl
images/macos/templates/macOS-12.json
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-13.arm64.anka.pkr.hcl

XCode installation using xcode-install and 2FA enabled AppleID requires session cookie.
Add to image-generation workflows and packer templates

[macos] add cookie based installation for Xcode

---

images.CI/macos/anka/Service.Helpers.psm1

set $IsLatest to false when specifying exact version
This is so that we take [this path](https://github.com/actions/runner-images/blob/dfdd2daf84e33e18c114a9986bab5418c381664a/images.CI/macos/anka/Service.Helpers.psm1#LL70C31-L70C31) when requesting the version from mist as currently, `IsLatest` is true by default.

set $IsLatest to false when specifying exact version

---

images.CI/linux-and-win/azure-pipelines/image-generation.yml

Prevent image generation failure when invalid remote ref exists
Example: https://dev.azure.com/github/runner-images/_build/results?buildId=132220&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=58defa89-d6ac-5420-9bcc-1b908ffd19eb

Set checkout options in image generation pipeline

---

images/macos/provision/core/codeql-bundle.sh

(Originally opened as a cross-platform PR here: #7602)
We are migrating to tagging the CodeQL bundle using semantic versions (like `codeql-bundle-v2.13.3`) rather than a date-based versions (like `codeql-bundle-20230516`). This lets us simplify how we version these bundles within the toolcache.
Previously, we used a version number like `2.13.3-20230516` to allow us to look up the version in the toolcache by either the CLI version number (2.13.3) or the bundle tag name (`codeql-bundle-20230516`).  This PR changes how we version bundles in the toolcache to take advantage of the new bundle tag name.  For bundles versioned as `codeql-bundle-v2.13.3`, we can just version the bundle in the toolcache as `2.13.3` since the bundle tag name is derivable from the CLI version number.

[macOS] CodeQL: Simplify the toolcache version number for bundles tagged using semver

---

images/win/scripts/Installers/Install-CodeQLBundle.ps1

(Originally opened as a cross-platform PR here: #7602)
We are migrating to tagging the CodeQL bundle using semantic versions (like `codeql-bundle-v2.13.3`) rather than a date-based versions (like `codeql-bundle-20230516`). This lets us simplify how we version these bundles within the toolcache.
Previously, we used a version number like `2.13.3-20230516` to allow us to look up the version in the toolcache by either the CLI version number (2.13.3) or the bundle tag name (`codeql-bundle-20230516`).  This PR changes how we version bundles in the toolcache to take advantage of the new bundle tag name.  For bundles versioned as `codeql-bundle-v2.13.3`, we can just version the bundle in the toolcache as `2.13.3` since the bundle tag name is derivable from the CLI version number.

[Windows] CodeQL: Simplify the toolcache version number for bundles tagged using semver

---

images/linux/scripts/installers/codeql-bundle.sh

(Originally opened as a cross-platform PR here: #7602)
We are migrating to tagging the CodeQL bundle using semantic versions (like `codeql-bundle-v2.13.3`) rather than a date-based versions (like `codeql-bundle-20230516`). This lets us simplify how we version these bundles within the toolcache.
Previously, we used a version number like `2.13.3-20230516` to allow us to look up the version in the toolcache by either the CLI version number (2.13.3) or the bundle tag name (`codeql-bundle-20230516`).  This PR changes how we version bundles in the toolcache to take advantage of the new bundle tag name.  For bundles versioned as `codeql-bundle-v2.13.3`, we can just version the bundle in the toolcache as `2.13.3` since the bundle tag name is derivable from the CLI version number.

[Linux] CodeQL: Simplify the toolcache version number for bundles tagged using semver

---

docs/create-image-and-azure-resources.md

Update GenerateResourcesAndImage documentation, so Warning is displayed before the action.

Update GenerateResourcesAndImage documentation

---

images/linux/scripts/helpers/Common.Helpers.psm1
images/macos/software-report/SoftwareReport.Android.psm1
images/win/scripts/ImageHelpers/InstallHelpers.ps1

Pester test for Android SDK may fail if new version of any package was released after image had been created. This PR enables packages list caching so we always get the same result.

Cache Android SDK packages list

---

images/macos/toolsets/toolset-13.json

add pkg-config to MacOS 13 images
https://github.com/actions/runner-images/issues/7632

Macos 13 pkg config

---

.github/workflows/create_sbom_report.yml

SBOM report generation is failing when executing `syft`.
Add `sudo` to override

[macos] Add sudo to SBOM generation

---

images/macos/software-report/SoftwareReport.Generator.ps1

Add pkg-config to the software report
Previously was deleted by mistake - https://github.com/actions/runner-images/commit/c6c271672676f9d02828e6262d4126d6860700b3#diff-d7d6fd7f830c5bd0d43cf8aebeb9f2e32574fddac321eff8419f4aafb043f70a

[macOS] Add pkg-config to the software report

---

images/linux/toolsets/toolset-2004.json

Remove .Net 3.1 from images.
#7667

[Ubuntu] Remove .Net 3.1 as its EOL

---

.github/workflows/ci-cleanup.yml

Assigning multiple CI labels to one pull request causes many skipped runs to be created. This job cleans them.

Add CI job to remove skipped CI runs

---

images/macos/helpers/Xcode.Installer.psm1
images/macos/provision/core/xcode.ps1
images/macos/tests/Xcode.Tests.ps1

Additional simulator runtimes were installed by default with XCode until version 14, so we have switch in our repo that enables simulators installation for XCode 14.*. As version 15 have released and it behaves the same we have to fix this switch to run installation for new XCode as well.

Fix XCode simulators installation

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1

Reverting the rustfmt version output to its previous state. [Example](https://github.com/actions/runner-images/pull/7843/commits/819a32b679df2546059d45103a2c49924a262a59#:~:text=Rustfmt%201.5.2%2D-,stable,-Member).

[Windows] Rm "-stable" part  from rustfmt version

---

.github/workflows/macos-generation.yml
images.CI/macos/azure-pipelines/image-generation.yml
images/macos/helpers/Xcode.Installer.psm1
images/macos/provision/core/xcode.ps1
images/macos/templates/macOS-11.anka.pkr.hcl
images/macos/templates/macOS-11.json
images/macos/templates/macOS-12.anka.pkr.hcl
images/macos/templates/macOS-12.json
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json
images/macos/toolsets/toolset-13.json

xcversion does not work anymore, we are switching to storing XCode installers in intermediate Azure storage
https://github.com/actions/runner-images-internal/issues/5204

[macos] refactor XCode installation approach

---

.github/workflows/macos-generation.yml

XCode installers now are downloaded from intermediate storage account, it is required to add appropriate parameters to github generation pipeline as well 
https://github.com/actions/runner-images-internal/issues/5204

[macos] propagate XCode install variables to github image generation

---

images/macos/provision/core/xcode.ps1

temporarily skip installing XCode-15 simulators
https://github.com/actions/runner-images-internal/issues/5219

[macos] temporarily disable simulators on XCode-15

---

images/macos/provision/core/powershell.sh

Add additional `chown`  command to PowerShell installation script for fixing permission issue during pipeline/workflow
https://github.com/actions/runner-images-internal/issues/5217

[MacOS] Change directory owner root => runner for .cache and .config in arm64

---

images.CI/macos/azure-pipelines/image-generation.yml

Test results generation was removed a long time ago: https://github.com/actions/runner-images/pull/2261. We don't need this command anymore.

[mac OS] Don't try to copy test results to artifacts directory

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

Includes APT vital packages such as `curl`, `gcc` and `jq` in software report. Was there any reason to move them out of the report or is this an unexpected side-effect?
N/A.

[ubuntu] include apt vital pkgs in software report

---

images/macos/helpers/Xcode.Installer.psm1

let us switch to `Start-DownloadWithRetry` instead of `Invoke-WebRequest` to allow retries during download of XCode installer
https://github.com/actions/runner-images-internal/issues/5222

[macos] download XCode installer with retries

---

images/macos/provision/bootstrap-provisioner/installNewProvisioner.sh

During the process of downloading the provisioner installer, potentially vulnerable data got into the log. There won't be any more.

[macOS] Remove sensitive data from a download log

---

.github/workflows/ubuntu-win-generation.yml

run_number is unique per workflow, several workflows may use the same number. It breaks VM deployment convention. let us switch to unique run_id 
https://github.com/actions/runner-images-internal/issues/5253

use unique run_id instead of repeative run_number for VM releases

---

images/macos/provision/utils/utils.sh

There is a problem with `get_github_package_download_url` function: any errors that may occur when fetching release list from GitHub API are ignored and it may cause odd errors during further script execution. This PR adds flags '-f' and '-S' to curl invocation to force script to output error information and stop.

[mac OS] Stop processing when unable to download release list from GitHub

---

images/linux/scripts/installers/google-chrome.sh

Currently omahaproxy portal returns incorrect revision for chromium so we have to hardcode it temporarily

[Ubuntu] Temporarily hardcode chromium revision

---

images/linux/scripts/installers/google-chrome.sh

Following https://github.com/actions/runner-images/pull/7940, install latest ChromeDriver patch that matches current Chrome build. This is to address possible issue where image generation may fail when ChromeDriver and Chrome patch numbers differ.

[Ubuntu] Install latest chromedriver for current build

---

.github/workflows/create_sbom_report.yml

With latest `v0.85.0` release of `syft`, SBOM workflow fails to complete successfully on Windows.
Temporarily pin `syft` to `v0.84.1`

[windows] Temporarily pin syft version for SBOM report

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Install-Chrome.ps1

According to the information on [ChromeDriver website](https://chromedriver.chromium.org/), starting with version 115 these json endpoints should be used to determine compatible versions and download urls: https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints. This PR updates script that installs Chrome and ChromeDriver to use one of these endpoints.

[Windows] Fix chromedriver download process

---

images/linux/scripts/installers/configure-environment.sh
images/linux/ubuntu2204.pkr.hcl

Azure's latest Ubuntu 22.04 image is lacking a kernel fix https://github.com/torvalds/linux/commit/6e250dcbff1d3ce347b8294e4ec6da96a2cecdb5.
GitHub Actions' `ubuntu-22.04` image is built upon Azure's base image. Without the fix, when customers' workflows upload large-size artifacts to remote servers and remote server fell behind in responding with ACK TCP packets, the delayed ACK packets are counted as INVALID because they are out of the TCP window, leading to the client kernel panic and responding with RST. This results in the intermittent connection reset symptom that has been reported by multiple customers[^1][^2][^3][^4].
> With permission, a more detailed analysis/history can be seen [here](https://github.com/github/c2c-actions-support/issues/2441#issuecomment-1610588448).
Until the …

Enable `nf_conntrack_tcp_be_liberal` for Ubuntu 22.04 until kernel update

---

helpers/GenerateResourcesAndImage.ps1

Those organisations that have applied this built-in (Microsoft authored) Azure Policy [Storage accounts should have the specified minimum TLS version](https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2Ffe83a0eb-a853-422d-aac2-1bffd182c5d0) are unable to use these build tools due to the requisite storage account command not passing in a minimum TLS version.
```powershell
GenerateResourcesAndImage: /agent/_work/1/s/UpdateRunnerImage.ps1:66
Line |
66 |  GenerateResourcesAndImage -SubscriptionId ${env:SUBSCRIPTIONID} `
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Resource 'itcgiocstprunnerwin2022r' was disallowed by policy. Policy
| identifiers: …
```

specify min tls for supporting stg acct - to support MS policy

---

images/macos/provision/core/swiftlint.sh

Revert PR https://github.com/actions/runner-images/pull/2296 and install swiftlint from Homebrew again since Mojave and High Sierra have been deprecated yet.

[macOS] Install swiftlint from Homebrew

---

.github/workflows/ubuntu-win-generation.yml

try to switch to "run_id" again, because "run_number" is not unique
https://github.com/actions/runner-images-internal/issues/5253

second attempt to switch to run_id for release number generation

---

images/linux/scripts/installers/google-chrome.sh

Currently [omahaproxy page](https://omahaproxy.appspot.com/) is used to get information about available Chrome revisions, but it was retired in April 2023 and doesn't work good now. Recently Google created [new page](https://googlechromelabs.github.io/chrome-for-testing/) and json endpoints that have all the information we need. This PR is to switch to the new endpoints.

[Ubuntu] Use new official endpoints to get Chromium revision

---

images/macos/provision/core/chrome.sh
images/macos/software-report/SoftwareReport.Browsers.psm1
images/macos/tests/Browsers.Tests.ps1

With the new [ChromeDriver release process](https://groups.google.com/g/chromedriver-users/c/qVPTFXnedw0) it's advised to use Google Chrome for Testing for automation and development instead of a "classic" Google Chrome. Furthermore on mac OS new ChromeDriver [can only work with Google Chrome for Testing](https://bugs.chromium.org/p/chromium/issues/detail?id=1466427). This PR is to install both ChromeDriver and Google Chrome for Testing from the official site to ensure versions match and compatibility.

[mac OS] Install Google Chrome for Testing

---

images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

The latest version of Android cmdline tools are build for Java 17 that is not default in both Ubuntu 20.04 and Ubuntu 22.04. It causes installation script failure. This PR pins package version to workaround that failure.

[Ubuntu] Pin Android cmdline-tools version

---

images/win/scripts/Installers/Install-Edge.ps1

Edge is currently installed on base Windows Server 2019 VMs - there is no need to install it from Choco.

[Windows] Update Edge installer to install only webdriver

---

images/macos/provision/core/xcode.ps1
images/macos/tests/Xcode.Tests.ps1

enable XCode-15.0.0-Beta2 + simulators.
https://github.com/actions/runner-images-internal/issues/5219

[macos] enable simulators for XCode-15

---

images/linux/scripts/SoftwareReport/SoftwareReport.Java.psm1
images/linux/scripts/installers/java-tools.sh
images/linux/scripts/tests/Java.Tests.ps1
images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

Recently Adoptium team started brownouts for AdoptOpenJDK and it breaks image generation process. This PR remove AdoptOpenJDK references from images.

[Ubuntu] Remove AdoptOpenJDK

---

images/win/scripts/Installers/Install-MysqlCli.ps1

mimic to browser behaviour by speciifying "Accept: text/html" when determining current mysql version
https://github.com/actions/runner-images/issues/8004

[win] specify accept header when downloading mysql meta

---

images/win/scripts/Installers/Install-JavaTools.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Java.psm1
images/win/scripts/Tests/Java.Tests.ps1
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Recently Adoptium team started brownouts for AdoptOpenJDK and it breaks image generation process. This PR remove AdoptOpenJDK references from images.
Request for mac OS: #8025
Request for Ubuntu: #8022

[Windows] Remove AdoptOpenJDK

---

images/macos/provision/core/openjdk.sh
images/macos/software-report/SoftwareReport.Java.psm1
images/macos/tests/Java.Tests.ps1
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json
images/macos/toolsets/toolset-13.json

Recently Adoptium team started brownouts for AdoptOpenJDK and it breaks image generation process. This PR remove AdoptOpenJDK references from images.
Request for Ubuntu: #8022
Request for Windows: #8026

[mac OS] Remove AdoptOpenJDK

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1

As Python 2.7 has been removed from Ubuntu we don't require to separate items for Python version in software report. This PR removes one of that items.

[Ubuntu] Remove duplicated line with Python version from report

---

images/linux/scripts/installers/miniconda.sh

In 2018 repo.continuum.io was replaced with repo.anaconda.com (https://github.com/conda/conda/issues/6886). Recently old repo have been finally shut down and it causes image generation to fail. This updates repo URL in Miniconda installation script.
Related requests: [mac OS](https://github.com/actions/runner-images/pull/8042), [Windows](https://github.com/actions/runner-images/pull/8041)

[Linux] Update miniconda download link

---

images/macos/provision/core/miniconda.sh

In 2018 repo.continuum.io was replaced with repo.anaconda.com (https://github.com/conda/conda/issues/6886). Recently old repo have been finally shut down and it causes image generation to fail. This updates repo URL in Miniconda installation script.
Related requests: [Ubuntu](https://github.com/actions/runner-images/pull/8043), [Windows](https://github.com/actions/runner-images/pull/8041)

[mac OS] Update miniconda download link

---

images/win/scripts/Installers/Install-Miniconda.ps1

In 2018 repo.continuum.io was replaced with repo.anaconda.com (https://github.com/conda/conda/issues/6886). Recently old repo have been finally shut down and it causes image generation to fail. This updates repo URL in Miniconda installation script.
Related requests: [mac OS](https://github.com/actions/runner-images/pull/8042), [Ubuntu](https://github.com/actions/runner-images/pull/8043)

[Windows] Update miniconda download link

---

images/macos/helpers/Common.Helpers.psm1
images/macos/helpers/Xcode.Installer.psm1
images/macos/toolsets/toolset-12.json
images/macos/toolsets/toolset-13.json

small improvement, use "unxip" utility from Homebrew if available
https://github.com/actions/runner-images-internal/issues/5272

[macos] use unxip if available for XCode unpacking

---

helpers/GenerateResourcesAndImage.ps1

Extra escaping is required for quotes in PS5 when passing arguments to external commands.\

Fix issue where tags json is wrong in PS5

---

images/macos/provision/configuration/configure-machine.sh

we are fine with that API usage, no need to see warnings every time

[macos] suppress swiftc warnings regarding deprecated API

---

docs/create-image-and-azure-resources.md
helpers/GenerateResourcesAndImage.ps1

The main purpose of this PR is to rewrite helper script for image generation to use az CLI util instead of Powershell module.
Other improvements:
- Prepare parameters first and run packer template validation prior to logging to Azure in order to catch errors early;
- Validate existence of Storage Account in order to reuse it in case where Resource Group is being kept;
- Add flag to silently continue execution if Resource Group exists already;
- Add verbose output;
- Increase default interval to wait for AD propagation to 120 seconds to meet AD SLA and use progress bar to track progress;
- Add missing newline after git commit information;
- Update doc string;
- Cleanup code and apply common styling.

Rewrite helper script for image generation

---

images/macos/helpers/Xcode.Installer.psm1

XCode license acceptance: limit execution timeouts just for macos-13
https://github.com/actions/runner-images-internal/issues/5319

use "license accept timeout" only on MacOS-13

---

images/linux/scripts/tests/Tools.Tests.ps1

`kubectl` was updated to 1.28 and version output has been changed.
Adjust version handling in Pester test

[ubuntu] Adjust kubectl version handling

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Install-Vsix.ps1
images/win/scripts/Installers/Install-WDK.ps1

We shall attempt using VSIX installer from the VS installer and not the VS itself as recommended by the team. The installer from the VS references the installer from the VS installer in anyway.
Closes: https://github.com/actions/runner-images/issues/8069

[Windows] use VsixInstaller from the installer

---

images/win/scripts/Tests/Tools.Tests.ps1

Kubernetes v1.28 have been released recently.
It removes --short flag from `kubectl version` command so build will start failing as soon as choco package `kubernetes-cli` is updated to the latest version (that usually happens in a couple of days after official release). In order to prevent Windows image builds from failing, I request to remove this flag in Kubernetes Tools tests.
More information: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#deprecation

[Windows] Remove deprecated kubectl flag

---

images/linux/scripts/installers/aliyun-cli.sh
images/linux/toolsets/toolset-2004.json

With latest updates, `aliyun` is failing on `ubuntu20` with `GLIBC_2.32` and `GLIBC_2.34` issues.
Pinning version to `3.0.174`

[ubuntu20] Pin aliyun to 3.0.174

---

images/linux/scripts/tests/Tools.Tests.ps1

Currently commands to test k8s tools in Ubuntu image differ from the same commands in mac OS and Windows. This PR updates tests for Ubuntu to make them work the same way as in other operation systems.

[Ubuntu] Make k8s tools tests consistent across OS

---

images/linux/scripts/installers/mysql.sh

Looks like we do not need it anymore

[Ubuntu] do not source os-release during mysql installation

---

images/macos/provision/bootstrap-provisioner/installNewProvisioner.sh

Reverts actions/runner-images#7934 due to https://github.com/github/maccloud/issues/2615#issuecomment-1683933670

Revert "[macOS] Remove sensitive data from a download log"

---

images/macos/provision/core/xcode.ps1

yet another attempt to improve XCode installation robustness
https://github.com/actions/runner-images-internal/issues/5339

[macos] move license accept out of parallel ForEach

---

images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
images.CI/macos/anka/Service.Helpers.psm1

/usr/sbin/softwareupdate appears not very stable last time. let's try mist-cli 
https://github.com/actions/runner-images-internal/issues/5340

[macos] use mist-cli for downloading OS distribution when generating anka clean vm

---

helpers/software-report-base/SoftwareReport.Nodes.psm1
helpers/software-report-base/tests/SoftwareReport.Nodes.Unit.Tests.ps1

We should report broken nodes to reduce the debug time

report Tool nodes with null or empty versions

---

images.CI/macos/anka/Anka.Helpers.psm1
images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
images.CI/macos/anka/Service.Helpers.psm1

check external command status in Invoke-SSHPassCommand (used for anka pipelines)
https://github.com/actions/runner-images-internal/issues/5356

[macos] check exit code in Invoke-SSHPassCommand

---

images/macos/toolsets/toolset-13.json

make 14.3.1 default, remove Xcode 14.3

[macOS] remove Xcode 14.3, default to 14.3.1

---

images/macos/provision/core/node.sh

We do not install any npm packages from within toolset on OS13 (yet)

[macOS] do not iterate over npm packages on Ventura

---

images/linux/toolsets/toolset-2004.json
images/linux/toolsets/toolset-2204.json

Pigz is a parallel implementation of gzip for modern multi-processor and multi-core machines. Previously we had this utility on runners as a dependency for docker, but now we don't. This PR adds `pigz` to the list of packages to install.

[Ubuntu] Add pigz utility

---

images/macos/provision/core/android-toolsets.sh
images/macos/software-report/SoftwareReport.Android.psm1
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json
images/macos/toolsets/toolset-13.json

drop deprecated Hardware_Accelerated_Execution_Manager
https://github.com/actions/runner-images-internal/issues/5373

macos: drop Hardware_Accelerated_Execution_Manager

---

images/linux/scripts/installers/containers.sh
images/linux/scripts/tests/Tools.Tests.ps1

podman networking smoke test
regression caught by customer
https://github.com/actions/runner-images/issues/7753

[ubuntu] add testcase for podman networking

---

images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/toolsets/toolset-13.json

macos-13: retirement of VS for Mac
https://github.com/actions/runner-images/discussions/8212

[macos] macos 13: retire VS Mac

---

images/macos/provision/configuration/finalize-vm.sh

As yarn is available on OS13 images now, we must cleanup its cache as well.

[macOS 13] cleanup yarn cache

---

images.CI/linux-and-win/convert-to-vhd.ps1

Due to migration, we have found that currently used agents handle AZ CLI commands differently. 
This change mitigates it.
https://github.com/actions/runner-images-internal/issues/5385

Fix CI for runners with PowerShell 7

---

images/macos/helpers/Xcode.Installer.psm1
images/macos/provision/core/xcode.ps1
images/macos/toolsets/toolset-13.json

add visionOS runtime
https://github.com/actions/runner-images/issues/8144

[macos] introduce additional runtimes for XCode

---

images/win/scripts/Installers/Install-AzureModules.ps1
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

for custom PowerShell modules kept in C:\Modules (required by some ADO tasks) unify installation method - use Powershell Gallery for all cases. Powershell Gallery is trusted source, integrity is checked during installation

[windows] switch to Powershell Gallery when preparing Azure modules

---

images/macos/helpers/Xcode.Installer.psm1
images/macos/provision/core/xcode.ps1

it is cleanup. idea of using "xcpretty" worked bad with pipefail on powershell.
while we are looking for better pipefail handling, let's temporarily suppress output

[macos] suppress xcodebuild output 

---

images/macos/tests/Xamarin.Tests.ps1

Add exclusion for macOS 13 to the Xamarin test
https://github.com/actions/runner-images-internal/issues/5401

[macos] Add exclusion for macOS 13 to the Xamarin test

---

images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/BasicTools.Tests.ps1
images/macos/toolsets/toolset-13.json

Remove Vagrant from macOS 13 due to no local "providers" being installed.
We do not install a "virtual box" on macOS 13.
https://github.com/actions/runner-images-internal/issues/5401

[macos] remove vagrant from macos 13

---

images/macos/toolsets/toolset-13.json

1. Update XCode 15 to Release Candidate 1
2. Remove visionOS, no SDKs for RC1 and could not be installed with `xcodebuild`

[macos] Add Xcode15 RC1

---

images/win/scripts/Installers/Configure-Antivirus.ps1

let's disable windows defender task by "Set-MpPreference -ScanScheduleDay 8" (otherwise defender creates deleted tasks)
https://github.com/actions/runner-images/issues/8164

[windows] disabling windows defender scheduled task

---

images/win/toolsets/toolset-2022.json

Updating version mingw from  to 12.2.0.03042023 to 11.2.0.07112021 for windows-22
https://github.com/actions/runner-images/issues/8266

[Windows] Update version mingw to 12.2

---

images.CI/macos/anka/Service.Helpers.psm1

According to [mist-cli](https://github.com/ninxsoft/mist-cli#examples), `mist list firmware` should be used for Apple Silicon Macs. PR fixes cases when there are different arm and intel version available by mist.

Adjust MacOs13 arm64 base image generation script

---

images/macos/provision/core/xcode.ps1

[macOS] drop spaceship env variables from Xcode.ps1

---

images/macos/templates/macOS-13.arm64.anka.pkr.hcl

We need to pin version here as well to avoid backward compatibility issues

[macOS] pin openssl@1.1.1 in arm64 image

---

images/macos/provision/core/openssl.sh

These are for intel, could be ignored for M1 for now

[macOS] do not install intel related symlinks on arm64 openssl

---

images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/InstallHelpers.ps1

Fix typo in Use-ChecksumComparison function name (the second 'С' is Cyrillic letter).

Fix typo in function name

---

images.CI/macos/anka/CreateCleanAnkaTemplate.ps1

This is an enhancement to add a boolean flag that workflows can use to specify whether or not to push to the Anka registry after a clean image has been generated. This helps separate the build and push stages from each other for easier testing.

add $PushToRegistry flag to control when to run anka registry push

---

.vscode/settings.json

This PR adds some settings for VSCode:
- Insert newline to the end of each file and trim redundant newlines
- Ignore [SC2096](https://www.shellcheck.net/wiki/SC2096) as we use complex shebang for mac OS scripts
- Ignore [SC1090](https://www.shellcheck.net/wiki/SC1090) to allow using non-constant sources
- Re-enable [SC1091](https://www.shellcheck.net/wiki/SC1091) as correct file path may be defined using special comment
- Add `-x` flag to allow shellcheck accessing arbitrary files

Update vscode configuration

---

docs/create-image-and-azure-resources.md

It looks like current version of image generation manual is quite confusing as the section describing helper script has title 'Automated image generation' while helper script have been designed mainly for manual generation. This PR changes titles and updates text so the purpose of helper script becomes more clear. Also it adds explicit recommendation to invoke packer directly when building images in an automated workflow.
Also this PR update manual structure and adds table of contents.

Update manual to clarify helper script purpose

---

images/macos/toolsets/toolset-13.json

This gem is being sunset, lets not install it on macOS starting with 13

[macOS] do not install xcode-install gem on Ventura

---

images/win/scripts/Installers/Install-Git.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/win/scripts/Tests/CLI.Tools.Tests.ps1

[Windows] Remove hub utility

---

images/win/scripts/Tests/Tools.Tests.ps1

improve OpenSSL test coverage
https://github.com/actions/runner-images-internal/issues/5419

[windows] missing openssl pester tests

---

images/win/scripts/Installers/Finalize-VM.ps1

StorSvc service wakes up in 700-800 sec and scans all files, which affects runner a lot. Let us try to disable it

[windows] disable StorSvc for runners

---

images/win/scripts/Installers/Install-PyPy.ps1

implementing checksums for PyPy

[windows] implement PyPy checksum validation

---

images/win/scripts/Installers/Install-AzureDevOpsCli.ps1

as Jesse Houwing has found "az devops" warms up during first run which takes ~40 sec.
warm up is done by running "az devops <subsystem> --help" with config redirected to persistent "C:\" location, also keyring installation requires "fake" login
original PR: https://github.com/actions/runner-images/pull/8294
warming up "az devops" first invocation.
due to security reasons we cannot accept original PR: https://github.com/actions/runner-images/pull/8294
https://github.com/actions/runner-images/issues/8296

[windows] warmup "az devops" for the first run

---

images/win/scripts/Installers/Install-PyPy.ps1

Temporary patch for PyPy installation script. The checksum for the required file is not published on the pypy.org website.

[Windows] Patch for missing PyPy3.9-7.3.13 SHA

---

images/macos/helpers/Xcode.Installer.psm1

Current implementation requires `XCODE_INSTALL_SAS` to be manually suffixed with `?` symbol.
Change allows copying SAS token without symbol additions

[macos] Adjust Xcode storage Uri

---

images/win/scripts/Installers/Install-JavaTools.ps1

Update installer script with checksum for JDKs

[Windows] Add checksum validation for JDKs

---

images/macos/provision/core/commonutils.sh

Exclude virtualbox from macOS 13 arm64

[macOS] Exclude virtualbox from macOS 13 arm64

---

images/macos/provision/core/openjdk.sh
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/tests/Java.Tests.ps1
images/macos/tests/Xamarin.Tests.ps1
images/macos/toolsets/toolset-13.json

Add Java to the macOS 13 arm64
https://github.com/actions/runner-images-internal/issues/5447

[macOS] Add Java to the macOS 13 arm64

---

images/win/scripts/Installers/Install-Haskell.ps1

Currently we use bootstrap script to install Haskell on Windows. But we can't validate that it's legit and safe. Since we only use that script to download ghcup utility, we can get rid of it. This PR replaces bootstrapper invocation with simple commands that create required directories and download binary directly.
Manual reference: https://www.haskell.org/ghcup/install/#manual-installation

[Windows] Simplify ghcup installation

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Install-IEWebDriver.ps1
images/win/scripts/Installers/Install-Selenium.ps1

This PR updates Selenium installation scripts to use `Get-GitHubPackageDownloadUrl` function in order to improve readability.

[Windows] Use function to get selenium asset url

---

images/win/scripts/Installers/Install-AzureDevOpsCli.ps1

cleanup. no functional change. non needed output was suppressed

[windows] actually suppress output of "az devops login"

---

images/macos/provision/configuration/preimagedata.sh

Fix Software and Release URLs in `preimagedata.sh` for macOS 13 arm64 images.

[macos13] Fix preimagedata for arm64

---

images/macos/provision/core/rubygem.sh

`activesupport 7.1.0` gem (`cocoapods` dependency) has bug https://github.com/CocoaPods/CocoaPods/issues/12081, which prevents `cocoapods` installation. Implement workaround until new release
1. `public_suffix` workaround is obsolete and removed
2. `activesupport` temporarily pinned to `7.0.8`

[macos] Add activesupport gem workaround for cocoapods

---

images/linux/scripts/installers/Install-Toolset.ps1

Currently we unarchive toolset assets to `INSTALLER_SCRIPT_FOLDER` and those assets remain in final image. We don't need them so this PR changes destination for tar command to `/tmp`. As a result we free 2.6 GB on image disk.

[Ubuntu] Change destination for toolcache assets

---

images/win/scripts/Installers/Install-VCRedist.ps1

Fix code style in `Install-VCRedist.ps1` for windows

[windows] Fix code style in Install-VCRedist.ps1

---

images/win/scripts/Installers/Warmup-User.ps1

ignore rare error which happens on copying locked files in prepared user profile
==> azure-arm.image: Copy-Item : The process cannot access the file
==> azure-arm.image: 'C:\Users\packer\AppData\Local\Microsoft\VisualStudio\16.0_14229d81\privateregistry.bin.LOG2' because it is being used
==> azure-arm.image: by another process.

[windows] ignore error on copying user profile warmup

---

images/linux/scripts/installers/action-archive-cache.sh
images/linux/scripts/tests/ActionArchiveCache.Tests.ps1
images/linux/ubuntu2004.json
images/linux/ubuntu2204.pkr.hcl

New tool
Fetching latest release from https://github.com/actions/action-versions
The latest release contain all tar.gz or zip of all versions of the top 5 used first-party actions (ex: `actions/checkout`).
With these cached on the hosted runner image, the hosted runner won't need to reach out to codeload to download those same assets over and over again.
The asset is about 120MB for both Windows and non-Windows, the download and unzip normally is less than 10s.
Since the assets is an archive of other archive, we only need to unzip the outer layer, after unzip the total size on disk are pretty much the same.
https://github.com/github/actions-broker/issues/17

Download actions/action-versions latest release on Linux and set ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE

---

images/win/scripts/Installers/Install-ActionArchiveCache.ps1
images/win/scripts/Installers/Update-ImageData.ps1
images/win/scripts/Tests/ActionArchiveCache.Tests.ps1
images/win/windows2019.json
images/win/windows2022.json

New tool
Fetching latest release from https://github.com/actions/action-versions
The latest release contain all tar.gz or zip of all versions of the top 5 used first-party actions (ex: `actions/checkout`).
With these cached on the hosted runner image, the hosted runner won't need to reach out to codeload to download those same assets over and over again.
The asset is about 120MB for both Windows and non-Windows, the download and unzip normally is less than 10s.
Since the assets is an archive of other archive, we only need to unzip the outer layer, after unzip the total size on disk are pretty much the same.
https://github.com/github/actions-broker/issues/17

Download actions/action-versions latest release on Windows and set ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE

---

images/macos/provision/configuration/environment/bashrc
images/macos/provision/core/action-archive-cache.sh
images/macos/templates/macOS-11.json
images/macos/templates/macOS-12.anka.pkr.hcl
images/macos/templates/macOS-12.json
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/tests/ActionArchiveCache.Tests.ps1

New tool
Fetching latest release from https://github.com/actions/action-versions
The latest release contain all tar.gz or zip of all versions of the top 5 used first-party actions (ex: `actions/checkout`).
With these cached on the hosted runner image, the hosted runner won't need to reach out to codeload to download those same assets over and over again.
The asset is about 120MB for both Windows and non-Windows, the download and unzip normally is less than 10s.
Since the assets is an archive of other archive, we only need to unzip the outer layer, after unzip the total size on disk are pretty much the same.
https://github.com/github/actions-broker/issues/17

Download actions/action-versions latest release on macOS and set ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE

---

images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

Update toolsets for MacOS 11 and 12 according to changes introduced by https://github.com/actions/runner-images/commit/60963fb52e25c7e731d0c7a16290c03bdf3feb15

[macOS] Fix java info in toolsets

---

images/macos/provision/core/rubygem.sh

Make cocoapods' `activesupport` gem workaround more resilient to version changes. `activesupport 7.1.1` still not working with cocoapods

[macos] Adjust activesupport ruby gem version pinning

---

images/macos/provision/core/dotnet.sh

use special helper for downloading DotNETSDK installer

[macos] add retries when installing DotNETSDK

---

images/linux/scripts/installers/firefox.sh

Add Mozillateam PPA manually because automated process fails often due to some issues on Launchpad server.

[Ubuntu] Add Mozilla PPA manually

---

images/macos/provision/core/android-toolsets.sh
images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json
images/macos/toolsets/toolset-13.json

this is a preparation for future enabling android sdk on macos-13 arm64
https://github.com/actions/runner-images/issues/8515

[macos] move android "cmdline-tools" to toolset

---

images/linux/scripts/helpers/install.sh

Adding following functions to work with packages hashes:
`get_github_package_hash()` will be used to get package hash from GitHub release body, possible to use with direct release link or with just `repo_owner` and `repo_name` pair.
`use_checksum_comparison()` will be used to compare known checksum with the package hash
https://github.com/actions/runner-images-internal/issues/5491

[Ubuntu] Add helpers to work with checksums

---

images/macos/provision/core/codeql-bundle.sh
images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/Common.Tests.ps1

Previously, we cached two versions since we prioritized hitting the toolcache over landing new releases quicker. However after experimenting with this, we have decided to prioritize getting new releases into customers' hands more quickly.

[macOS] Cache only the latest version of CodeQL

---

images/macos/provision/core/android-toolsets.sh

introduce toolset possibility to install Android SDK Tools
https://github.com/actions/runner-images/issues/8515

[macos] introduce toolset possibility to install Android SDK Tools

---

images/win/scripts/Installers/Install-JavaTools.ps1

This PR changes directory name that is Java 21 installed to. Currently it has '.LTS' suffix and this difference causes issues.

[Windows] Fix Java 21 location

---

images/macos/provision/core/edge.sh

Edge Updater configuration fails on Mac OS 13 with the following error:
```
chown: /Library/Managed Preferences/com.microsoft.EdgeUpdater.plist: No such file or directory
```
It seems like on Mac OS 13 installation script executes in different directory so relative paths doesn't work as expected. This PR fixes those paths.

[Mac OS] Fix Edge Updater configuration steps

---

images/macos/toolsets/toolset-13.json

enable android cmdtools on macos-13 arm64
https://github.com/actions/runner-images/issues/8515

[macos] enable android cmdtools on macos-13 arm64

---

images/macos/provision/utils/utils.sh

sometimes "brew install" fails due to network timeout, let's use "brew --cache" with retries to make it more robust

[macos] add retries to "brew install"

---

images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Strawberry Perl bundles a lot of software that breaks other packages when appears in PATH. This PR pin it's version to avoid unexpected updates.
CI builds: [Windows 2019](https://github.com/actions/runner-images-ci/actions/runs/6589026134), [Windows 2022](https://github.com/actions/runner-images-ci/actions/runs/6589026141)

[Windows] Rollback and pin Strawberry Perl

---

images/linux/scripts/helpers/install.sh
images/linux/scripts/installers/aliyun-cli.sh
images/linux/scripts/installers/cmake.sh
images/linux/scripts/installers/docker.sh

Add new helper `get_hash_from_remote_file()`
Update installer scripts with checksum for Aliyun CLI, CMake, Docker Compose v2 using `get_hash_from_remote_file()`
[#5491](https://github.com/actions/runner-images-internal/issues/5491)

[Ubuntu] Add checksum validation for Aliyun CLI, CMake, Docker Compose v2

---

images/macos/provision/core/chrome.sh
images/macos/provision/core/miniconda.sh
images/macos/provision/core/openjdk.sh
images/macos/provision/utils/utils.sh
images/win/scripts/Installers/Install-PyPy.ps1

simplify "brew_smart_install" helper

[macos] simplify "brew_smart_install" helper

---

images/macos/provision/core/commonutils.sh

This PR fixes broken retry logic for AppleScript that confirms identity for 'Parallels International GmbH'

[Mac OS] Fix logic for retrying AppleScript execution

---

images/linux/scripts/installers/sqlpackage.sh

Installer script `sqlpackage` requires libssl1.1 dependency. There was hardcoded version `libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb` which is no more available at repository <http://security.ubuntu.com/ubuntu/pool/main/o/openssl> and because of that the build of ubuntu22 image is failing.
This PR fixes this issue to specify version `libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb`, which is available at the repository.
#8681

Build of ubuntu22 image fails due to mismatch libssl1.1  version

---

images.CI/macos/azure-pipelines/image-generation.yml

Need to increase the timeout for macOS 11 builds

[macOS] increase timeout for the macOS ci

---

helpers/GenerateResourcesAndImage.ps1

Double quotes in command arguments should be escaped when running on PowerShell 7.0-7.2. It's especially important for us because Ubuntu runners still have PowerShell 7.2 installed.
This PR adds additional check for PowerShell version in order to handle double quotes correctly. See also this PR: #7613

Escape quotes when running in PowerShell 7.0-7.2

---

images/linux/scripts/installers/kotlin.sh
images/win/scripts/Installers/Install-Kotlin.ps1

The [latest release notes](https://github.com/JetBrains/kotlin/releases/tag/v1.9.20) for Kotlin v1.9.20 includes multiple lines that contain the search string "kotlin-compiler", one of which is not the line that contains the checksum. This tweaks the search string to only look for the filename ending in `.zip`, where the checksum should be present.

fix: checksum search for Kotlin

---

images/linux/scripts/installers/rust.sh

Latest bindgen release has a bug. We should temporary pin previous release.
https://github.com/actions/runner-images/issues/8710

[Ubuntu] Pin bindgen cli version to avoid bug

---

images/linux/scripts/helpers/install.sh
images/linux/scripts/installers/docker-compose.sh
images/linux/scripts/installers/docker.sh
images/linux/scripts/installers/github-cli.sh
images/linux/scripts/installers/kubernetes-tools.sh
images/linux/scripts/installers/oras-cli.sh
images/linux/scripts/installers/pulumi.sh
images/linux/scripts/installers/yq.sh
images/linux/scripts/installers/zstd.sh

- Add double space check to the `get_hash_from_remote_file()` function
- Fix some typos from previous PRs
- Add checksums for Docker Compose v1, amazon-ecr-credential-helper, GitHub CLI, Kind, ORAS CLI, Pulumi, yq, zstd
https://github.com/actions/runner-images-internal/issues/5491

[Ubuntu] Add more checksum validations

---

images/win/scripts/Installers/Install-Rust.ps1

Latest bindgen release has a bug. We should temporary pin previous release.
https://github.com/actions/runner-images/issues/8710

[Windows] Pin bindgen cli version to avoid bug

---

images.CI/macos/anka/CreateCleanAnkaTemplate.ps1

This PR disables VNC initialization for Mac OS 14 images to be able to start testing base images generation.

[Mac OS] Temporary disable VNC for Mac OS 14

---

images/linux/toolsets/toolset-2204.json

The GCC 13 toolchain is missing gfortran-13.
This seems to be a recurring theme:
- https://github.com/actions/runner-images/pull/2103
- https://github.com/actions/runner-images/pull/6736

Add gfortran-13 to ubuntu:22.04

---

images/linux/scripts/installers/git-lfs.sh
images/linux/scripts/installers/git.sh
images/linux/scripts/tests/Tools.Tests.ps1
images/linux/ubuntu2004.json
images/linux/ubuntu2204.pkr.hcl
images/linux/ubuntuminimal.pkr.hcl

for better observability of integrity validation let us split install script into two

[ubuntu] split git and git-lfs into separate install scripts

---

images/linux/scripts/tests/Android.Tests.ps1
images/win/toolsets/toolset-2019.json
images/win/toolsets/toolset-2022.json

Android SDK Patch applier v4 not found in M2 Repository.
https://github.com/actions/runner-images/issues/8737

[Windows] Remove Android SDK Patch applier v4

---

images/macos/provision/core/openjdk.sh

This pull request removes the 'LTS' suffix from the version if it is present to avoid issues with cached Java.

[Mac OS] Remove 'LTS' suffix from OpenJDK version

---

images/win/scripts/Installers/Install-Docker-Compose.ps1
images/win/scripts/Installers/Install-Docker-WinCred.ps1
images/win/scripts/Installers/Install-Docker.ps1
images/win/scripts/Tests/Docker.Tests.ps1
images/win/windows2019.json
images/win/windows2022.json

the idea is to end with 1 script per 1 component for better observability

[windows] split docker install into 3 scripts

---

images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/tests/Android.Tests.ps1

add android SDK to SW report on Ventura ARM64

[macos] add android SDK to SW report on Ventura ARM64

---

images.CI/macos/anka/Service.Helpers.psm1

This pull request modifies `Get-AvailableIPSWVersions` function to return Mac OS Build ID instead of version. It also adds `--compatible` flag to the `mist list firmware` command.

[Mac OS] Update Anka Helpers to build Mac OS 14 ARM image

---

images.CI/macos/anka/Service.Helpers.psm1

This pull request adds a condition for MacOS Sonoma in the `Get-MacOSIPSWInstaller` function.

[Mac OS] Add missing MacOS Sonoma condition

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Finalize-VM.ps1

This PR:
1) Switches to `Stop-SvcWithErrHandling` and `Set-SvcWithErrHandling` functions in `Finalize-VM.ps1`.
2) Adds `StopOnError` parameter to `Set-SvcWithErrHandling` function.
3) Adjusts `Stop-SvcWithErrHandling` and `Set-SvcWithErrHandling` functions to style guide.

[Windows] Adjust services handling in Finalize-VM and helpers

---

images/win/scripts/Installers/Install-MysqlCli.ps1

For those of us building an image from this repo in AWS, the `Invoke-WebRequest` call to https://dev.mysql.com/downloads/mysql/8.0.html has been failing for awhile with a 403 Forbidden, even with the `Accept` header that was added back in #8009. The protection/filtering they have on that page from their CDN provider seems to have greater restrictions on requests coming from EC2 IPs. This issue is easily replicated in the free tier of AWS.
We tested setting various combinations of headers and cookies, including this version which works with pwsh but not PowerShell 5.1 (can't customize the `Connection` header in 5.1)
```
Invoke-RestMethod -Uri "https://dev.mysql.com/downloads/mysql/8.0.html" -Headers @{
'Accept'='text/html';
'Accept-Encoding'='gzip';
'Connection'='keep-alive'; …
```

[Windows] Set user agent header to get mysql patch version

---

images/macos/provision/core/rust.sh
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-14.anka.pkr.hcl
images/macos/tests/Haskell.Tests.ps1
images/macos/tests/Rust.Tests.ps1

Remove Haskell and Cargo packages from macOS 13 and macOS 14 images

[macOS] Remove Haskell and Cargo packages

---

images/macos/provision/core/haskell.sh

With brew deprecation on macos-11, `ghc` and `cabal-install` are installed by brew as dependency of `yq` when building from source. Links cause conflicts with `ghc` from `ghcup`. This PR unlinks brew packages

[macos11] Unlink brew ghc and cabal-install

---

images/macos/tests/Common.Tests.ps1

Exclude macOS 13 and 14 from the "Stack" test.
https://github.com/actions/runner-images-internal/issues/5585

[macOS] Exclude macOS 13 and 14 from "Stack" test.

---

images/macos/provision/core/commonutils.sh
images/macos/provision/core/haskell.sh
images/macos/toolsets/toolset-11.json

- Updating YQ installation for macOS Big Sur due to this OS deprecation in Homebrew.
- Reverting previous YQ related changes
[#5587](https://github.com/actions/runner-images-internal/issues/5587)

[macOS] Reconsider YQ installation on macOS 11

---

helpers/GenerateResourcesAndImage.ps1

PR fixes incorrect packer template names for ubuntu in GenerateResourcesAndImage.ps1

[ubuntu] Fix template names in GenerateResourcesAndImage.ps1

---

images/ubuntu/templates/ubuntu-20.04.json
images/ubuntu/templates/ubuntu-22.04.pkr.hcl

PR fixes download location for Software Report and Readme on ubuntu

[ubuntu] Fix software report download directory

---

images/ubuntu/scripts/build/phantomjs.sh
images/ubuntu/scripts/build/sqlpackage.sh

Add pre-checked SHA256 hashes for some pinned packages.
[#5491](https://github.com/actions/runner-images-internal/issues/5491)

[Ubuntu] Pin SHA256 for PhantomJS and libssl1.1

---

images/macos/scripts/docs-gen/SoftwareReport.Generator.ps1

Exclude "Stack" from software report

[macOS] Exclude "Stack" from software report for macOS 13 and 14

---

images/macos/scripts/docs-gen/SoftwareReport.Common.psm1
images/macos/scripts/docs-gen/SoftwareReport.Generator.ps1
images/macos/toolsets/toolset-12.json
images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json

Adding xcodes and xcbeautify to all images except macOS Big Sur.
#8827

[macOS] Add xcodes and xcbeautify to macOS images

---

helpers/GenerateResourcesAndImage.ps1

This pull request fixes issue where `Get-PackerTemplatePath` fails in PowerShell 5.1 because of the different behavior of the `Join-Path` cmdlet.

Fix issue where GetPackerTemplatePath fails in PS5

---

images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json

This PR remove Ubuntu:16.04 & Ubuntu:18.04 docker images from runner-images
https://github.com/actions/runner-images/issues/8776

[Ubuntu] Remove Ubuntu:16.04 & Ubuntu:18.04 docker images

---

images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json

Remove Nodejs 14.x  from ubuntu images
https://github.com/actions/runner-images/issues/8779

[Ubuntu] Remove Nodejs 14.x 

---

images/windows/scripts/tests/Haskell.Tests.ps1
images/windows/scripts/tests/Helpers.psm1
images/windows/scripts/tests/Java.Tests.ps1
images/windows/scripts/tests/MSYS2.Tests.ps1
images/windows/scripts/tests/Toolset.Tests.ps1

This pull request includes various changes to improve the functionality, clarity, readability, and usability of the Windows image test helpers. Main changes:
- remove the `Get-CommandResult` function as it's trivial and used too little;
- remove the `ShouldReturnZeroExitCodeWithParam` assertion as it's behavior is unobvious while we don't really need it;
- rename the `MatchCommandOutput` assertion to `OutputTextMatchingRegex`, to better match Pester framework logic;
- add documentation for all test helpers.

[Windows] Update test helpers

---

images/ubuntu/scripts/build/install-container-tools.sh
images/ubuntu/scripts/helpers/install.sh

PR changes `echo -e` to `printf` as a tool more suited for escape sequences handling

[ubuntu] Change echo to printf for escape sequences

---

images/ubuntu/scripts/docs-gen/SoftwareReport.Common.psm1
images/ubuntu/scripts/docs-gen/SoftwareReport.Helpers.psm1
images/ubuntu/scripts/helpers/Common.Helpers.psm1
images/ubuntu/scripts/tests/Android.Tests.ps1
images/ubuntu/scripts/tests/Java.Tests.ps1

This PR adjusts `Common.Helpers.psm1`:
1. Move `Get-OSVersionShort`, `Get-OSVersionFull`, `Get-KernelVersion` functions to `SoftwareReport.Helpers.psm1` - functions are only used in report generation
2. Move `Get-AndroidPackages` function to `Android.Tests.ps1` - function is not used anywhere else
3. Remove `Get-EnvironmentVariable` function - use `[System.Environment]::GetEnvironmentVariable()` directly instead as it is self-explanatory on its own
4. Rename `Validate-AndroidPackage` function to `Test-AndroidPackage` - approved verb
5. Add descriptions of complex functions

[ubuntu] Refactor Common.Helpers

---

images/windows/scripts/build/Install-AWSTools.ps1
images/windows/scripts/build/Install-Git.ps1
images/windows/scripts/build/Install-Kotlin.ps1
images/windows/scripts/helpers/ImageHelpers.psm1
images/windows/scripts/helpers/InstallHelpers.ps1

This pull request includes changes to improve the scripts used to fetch data using Github API:
- Implements the `Get-GithubReleasesByVersion` function that retrieves GitHub releases for a specified repository based on version. Also the function caches the results to improve performance and reduce the number of API calls.
- Updates the `Resolve-GithubReleaseAssetUrl` function to use the new function to work with Github API.
- Implements the function that gets hash from Github release body from scratch, utilizing the new function to work with Github API and implementing simplified interface.
Also this request adds some documentation scripts and removes the `Get-WinVersion` function.

[Windows] Update functions that get urls and hashes from Github

---

helpers/GenerateResourcesAndImage.ps1
images.CI/linux-and-win/cleanup.ps1

Currently the powershell script doesn't support a Service principal which secret contains an hyphen "-".
If someone tries to run the `GenerateResourcesAndImage` script will receive the same error that is exposed [here](https://github.com/Azure/azure-cli/issues/7054).
To fix this I applied the suggestion described in Microsoft documentation [here](https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#use-hyphen-characters-in-parameters).
https://github.com/actions/runner-images/issues/8928

Fix AzureClientSecret parameter not supporting hyphens

---

images/ubuntu/scripts/docs-gen/SoftwareReport.Android.psm1
images/ubuntu/scripts/helpers/Common.Helpers.psm1
images/ubuntu/scripts/helpers/install.sh
images/ubuntu/scripts/tests/Android.Tests.ps1

This PR simplifies toolset management:
1. Remove `Get-ToolsetValue` PowerShell function - it is barely used and easily substituted by `Get-ToolsetContent` function
2. Remove `get_toolset_path` bash function and use value directly

[ubuntu] Refactor Toolset functions

---

images/ubuntu/scripts/build/install-actions-cache.sh
images/ubuntu/scripts/build/install-aliyun-cli.sh
images/ubuntu/scripts/build/install-cmake.sh
images/ubuntu/scripts/build/install-docker.sh
images/ubuntu/scripts/build/install-firefox.sh
images/ubuntu/scripts/build/install-github-cli.sh
images/ubuntu/scripts/build/install-kotlin.sh
images/ubuntu/scripts/build/install-kubernetes-tools.sh
images/ubuntu/scripts/build/install-oras-cli.sh
images/ubuntu/scripts/build/install-runner-package.sh
images/ubuntu/scripts/build/install-sbt.sh
images/ubuntu/scripts/build/install-selenium.sh
images/ubuntu/scripts/helpers/install.sh

This pull request implements `resolve_github_release_asset_url` function in place of the `get_github_package_download_url` with enhanced functionality, matching it's windows equivalent.

[ubuntu] Refactor GitHub package download URL function

---

images.CI/macos/anka/CreateCleanAnkaTemplate.ps1

fix clean image generation CI by skipping Sinima updates for Monterey

[macos] skip Sonoma updates for Monterey

---

images/ubuntu/scripts/build/install-android-sdk.sh
images/ubuntu/scripts/helpers/install.sh

This PR:
1. Remove `verlte` function - used only once, compare directly instead
2. Rename `filter_components_by_version` to `add_filtered_instalaltion_components`
3. Remove irrelevant workaround and minor style changes

[ubuntu] Refactor android sdk build script

---

images/windows/scripts/build/Install-Selenium.ps1
images/windows/scripts/helpers/InstallHelpers.ps1

This way function will work for GitHub releases with multiple asset versions. Will only work with simple number series of no more than ten in a row.
Currently it's only SeleniumHQ/selenium. Example: 
- https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-dotnet-strongnamed-4.16.0.zip
- https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-dotnet-strongnamed-4.16.1.zip

[Windows] Update Resolve-GithubReleaseAssetUrl function

---

.github/workflows/create_sbom_report.yml

Quick fix for https://github.com/actions/runner-images/pull/8975

Update release variable to use ID instead of branch in SBOM workflow

---

images/macos/scripts/docs-gen/SoftwareReport.Common.psm1
images/ubuntu/scripts/docs-gen/SoftwareReport.Tools.psm1

Update the Packer version output.
Get rid of `Packer v` in `Packer v1.10.0` output.

[Ubuntu] Update the Packer version output

---

images/ubuntu/templates/ubuntu-20.04.pkr.hcl
images/ubuntu/templates/ubuntu-22.04.pkr.hcl
images/ubuntu/templates/ubuntu-minimal.pkr.hcl
images/windows/templates/windows-2019.pkr.hcl
images/windows/templates/windows-2022.pkr.hcl

Azure plugin v2.0+ for packer contains breaking changes, which affects pipelines. Pin version to `1.4.5`

Pin Azure plugin version in packer templates

---

images/windows/scripts/build/Install-Miniconda.ps1

fix Miniconda checksum extraction
https://github.com/actions/runner-images/issues/9017

[windows] fix extracting checksum for Miniconda installer

---

images/macos/scripts/build/install-mono.sh
images/macos/scripts/build/install-python.sh
images/macos/scripts/helpers/utils.sh
images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json

This PR pin SHA256 checksums for `Mono Framework`, `NUnit console`, `Python 2`
https://github.com/actions/runner-images-internal/issues/5490

[MacOS] Pin SHA256 for macos packages

---

images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
images.CI/macos/anka/Service.Helpers.psm1

- Updating the scheme for working with macOS updates - now there are no attempts to install or check an update to a new version of the OS.
- Added an error handler for launching with attempts - before that it crashed in some cases.

Fix macOS CI - clean images updates

---

images/ubuntu/scripts/build/install-actions-cache.sh
images/ubuntu/scripts/build/install-aliyun-cli.sh
images/ubuntu/scripts/build/install-aws-tools.sh
images/ubuntu/scripts/build/install-cmake.sh
images/ubuntu/scripts/build/install-docker.sh
images/ubuntu/scripts/build/install-github-cli.sh
images/ubuntu/scripts/build/install-kotlin.sh
images/ubuntu/scripts/build/install-kubernetes-tools.sh
images/ubuntu/scripts/build/install-oras-cli.sh
images/ubuntu/scripts/build/install-pulumi.sh
images/ubuntu/scripts/build/install-runner-package.sh
images/ubuntu/scripts/build/install-selenium.sh
images/ubuntu/scripts/build/install-yq.sh
images/ubuntu/scripts/build/install-zstd.sh
images/ubuntu/scripts/helpers/install.sh

This PR:
1) Adds `get_github_releases_by_version()` function
2) Reworks `resolve_github_release_asset_url()` function
3) Renames `get_github_package_hash()` function to `get_checksum_from_github_release()` and reworks it
4) Renames `get_hash_from_remote_file()` function to `get_checksum_from_url()` and reworks it

[ubuntu] Refactor functions for GitHub assets and hashes

---

.github/ISSUE_TEMPLATE/announcement.yml
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/tool-request.yml

Let's now distinguish Apple Silicon runners in template for better reports granularity

[macOS] distinguish Arm64/M1 in the template

---

images/ubuntu/scripts/build/install-container-tools.sh
images/ubuntu/scripts/build/install-heroku.sh
images/ubuntu/scripts/build/install-hhvm.sh
images/ubuntu/scripts/build/install-mongodb.sh
images/ubuntu/scripts/build/install-mono.sh

Since `apt-key` is deprecated, use `gpg`

[ubuntu] Remove apt-key from build scripts

---

images/ubuntu/scripts/build/install-android-sdk.sh
images/ubuntu/scripts/docs-gen/SoftwareReport.Android.psm1
images/ubuntu/scripts/tests/Android.Tests.ps1
images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json

Remove old android SDK versions from ubuntu 20.04 and ubuntu 22.04 images
- #8952

[Ubuntu] Remove old android SDK versions

---

images/windows/scripts/docs-gen/SoftwareReport.Android.psm1
images/windows/scripts/tests/Android.Tests.ps1
images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json

Remove old android SDK versions from Windows 2019 and Windows 2022 images.
- #8952

[Windows] Remove old android SDK versions

---

images/macos/toolsets/toolset-11.json
images/macos/toolsets/toolset-12.json

Remove old android SDK versions from macOS 11 and macOS 12 images.
- #8952

[macOS] Remove old android SDK versions

---

images/macos/scripts/build/Install-Xcode.ps1
images/macos/scripts/docs-gen/SoftwareReport.Common.psm1
images/macos/scripts/helpers/Xcode.Installer.psm1

This PR refactors PowerShell scripts used for macOS Software Report:
- Almost all functions used to get application version were changed to the "Run-Command" function.
- Scripts were aligned with code style guide.
- https://github.com/actions/runner-images-internal/issues/5621

[macOS] Update SoftwareReport scripts

---

images/ubuntu/scripts/helpers/install.sh
images/ubuntu/templates/ubuntu-20.04.pkr.hcl
images/ubuntu/templates/ubuntu-22.04.pkr.hcl

As pointed out by @luka5 in https://github.com/actions/runner-images/pull/9114, ubuntu build script contains statically defined path. This PR adds `INSTALLER_SCRIPT_FOLDER` variable usage instead.

[ubuntu] Fix static path in install.sh

---

images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json

In scope of this pull request, we replace Xcode 15.2 beta with the stable one

[macOS] Add Xcode 15.2

---

images/windows/scripts/build/Install-WindowsUpdates.ps1

Exclude KB5034439 from windows updates.
The known issue - https://support.microsoft.com/en-au/topic/kb5034439-windows-recovery-environment-update-for-azure-stack-hci-version-22h2-and-windows-server-2022-january-9-2024-6f9d26e6-784c-4503-a3c6-0beedda443ca
Since Azure VMs do not use WinRE, and it is disabled by default we are going to skip the KB5034439.
- https://github.com/actions/runner-images/issues/9148

[Windows] Exclude KB5034439 from windows updates

---

images/ubuntu/scripts/tests/System.Tests.ps1

The `$env:AGENT_NAME` and `$env:RUNNER_NAME` are predefined variables for the ADO pipelines and for the GitHub actions respectively.
If the variables is not empty, it means the test is running on the ADO pipeline or on the GitHub actions, and should be skipped.

[Ubuntu] Add predefined variable to skip test in the pipeline

---

helpers/CreateAzureVMFromPackerTemplate.ps1
helpers/GenerateResourcesAndImage.ps1
images.CI/linux-and-win/azure-pipelines/image-generation.yml

This PR cleans up `json` formatted packer template references and code blocks, since all template files were converted `.hcl`

Cleanup json formatted packer template references

---

images/windows/scripts/build/Install-Docker.ps1
images/windows/scripts/build/Install-DockerCompose.ps1
images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json

There are number of bugs provided in Moby repo for the Docker v25. Let's avoid install it until patch is ready.

[Windows] Pin Docker 24.0.7 to avoid bugs

---

images/ubuntu/scripts/build/install-docker.sh
images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json

There are number of bugs provided in Moby repo for the Docker v25. Let's avoid install it until patch is ready.

[Ubuntu] Pin Docker 24.0.7 to avoid bugs

---

images/macos/scripts/build/configure-preimagedata.sh

This PR fixes installed software and release related links in preimage data for arm64 images.

[macos] Fix links in preimage data

---

images.CI/macos/azure-pipelines/image-generation.yml
images.CI/macos/azure-pipelines/secondary-macos11.yml
images.CI/macos/azure-pipelines/secondary-macos12.yml

This PR adds additional macos11 and macos12 CI pipelines for build on secondary agents

Add secondary MacOs image generation pipelines

---

images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
images/macos/scripts/tests/BasicTools.Tests.ps1
images/macos/toolsets/toolset-11.json

Remove `imagemagick` package from MacOS-11.

[macos11] Remove imagemagick package

---

images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
images/macos/scripts/tests/PHP.Tests.ps1
images/macos/templates/macOS-11.pkr.hcl
images/macos/toolsets/toolset-11.json

Remove `php` package from MacOS-11.

[macos11] Remove php package

---

images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1

Remove Composer version from macOS 11 doc due to previous tool removal

[macOS] Remove Composer version from macOS 11 doc

---

.github/workflows/create_sbom_report.yml

This PR pins `syft` used for SBOM generation to `v0.100.0` since latest version of `syft` is pushing workflow run times above 6h.

Pin syft for SBOM report to v0.100.0

---

images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json

Update docker patch version from 24.0.7 to 24.0.8
https://github.com/actions/runner-images/issues/9349

[Ubuntu] update docker version

---

images/macos/toolsets/toolset-14.json

Add libsodium to the macOS-14
https://github.com/actions/runner-images/issues/9341

[macOS] Add libsodium to the macOS-14

---

README.md

We should encourage customers to always use main as builds are not idempotent.

README: recommend always using main for custom images

---

images/windows/scripts/build/Install-MysqlCli.ps1

MySQL 5.7.44 is the final release of the MySQL 5.7 series. 
This packet was removed from the download page - https://dev.mysql.com/downloads/mysql/5.7.html.
Now it is located in the archive page - https://downloads.mysql.com/archives/community/
https://github.com/actions/runner-images-internal/issues/5820

[Windows] Update downloadsPageUrl for mysql

---

images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json

The actual fix is in that patch version

[Ubuntu] update docker components to be >=24.0.9

---

images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json

Remove Ruby and Go old versions
- https://github.com/actions/runner-images/issues/9326
- https://github.com/actions/runner-images/issues/9327

[Windows] Remove Ruby, Go old versions

---

images/macos/templates/macOS-12.anka.pkr.hcl
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/templates/macOS-14.anka.pkr.hcl
images/macos/templates/macOS-14.arm64.anka.pkr.hcl

This PR adds ability to run Anka-based MacOS templates using `null` Packer builder. With null builder VM is expected to be pre-created and Packer would only deploy packages to it leaving VM management to the caller.
By default template uses Anka source (as it is today). Passing `-var builder_type=null` to the Packer switches to using null `builder`. VM host/ip and credentials have to be provided as well.
```
packer build \
-var builder_type=null \
-var source_vm_name=192.168.1.15 \
-var vm_username=USERNAME \
-var vm_password=PASSWORD \
<rest of arguments>
```
This change also allows running Packer against the localhost, but with one caveat - template will fail once it reaches the reboot step. For the non-localhost scenario reboot is handled properly.

Support null builder for MacOS templates

---

images/ubuntu/scripts/build/install-sqlpackage.sh

Install libssl1.1 for jammy using apt instead, so that no upstream versioning bump would fail the build again.
It has been resolved in #9428, which updated the new version string and hash.

[Ubuntu] 22.04: install libssl1.1 via apt

---

images/macos/scripts/tests/WebServers.Tests.ps1

This PR change pester for web servers from string parse to .json

[MacOS] Update webservers pester test

---

images/ubuntu/scripts/build/install-kotlin.sh

Kotlin developers changed method of publishing hashes for installer archive. 
- https://github.com/actions/runner-images/issues/9466

[Ubuntu] Update Kotlin installer hash check

---

images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
images/macos/scripts/tests/Common.Tests.ps1
images/macos/templates/macOS-14.anka.pkr.hcl

This PR will remove `vcpkg` tool from macOS-14 image. We are not going to continue maintain this tool.

[macOS] Remove VCPKG from macOS-14

---

images/windows/toolsets/toolset-2022.json

Fixing signature for Visual Studio Enterprise 2022.17 in toolset 2022.
#9188

Updating signature for Visual Studio Enterprise 2022.17.

---

helpers/software-report-base/SoftwareReport.BaseNodes.psm1
images.CI/macos/anka/Anka.Helpers.psm1
images.CI/macos/anka/CreateCleanAnkaTemplate.ps1
images.CI/macos/anka/Service.Helpers.psm1
images/macos/scripts/build/install-android-sdk.sh
images/macos/scripts/build/install-openssl.sh
images/macos/scripts/build/install-xcode-clt.sh
images/ubuntu/scripts/build/configure-dpkg.sh
images/ubuntu/scripts/build/configure-environment.sh
images/ubuntu/scripts/build/configure-system.sh
images/ubuntu/scripts/build/install-android-sdk.sh
images/ubuntu/scripts/build/install-dotnetcore-sdk.sh
images/ubuntu/scripts/build/install-firefox.sh
images/ubuntu/scripts/build/install-haskell.sh
images/ubuntu/scripts/build/install-homebrew.sh
images/ubuntu/scripts/build/install-java-tools.sh
images/ubuntu/scripts/build/install-rust.sh
images/ubuntu/scripts/build/install-selenium.sh
images/ubuntu/scripts/build/install-swift.sh
images/windows/scripts/build/Install-Selenium.ps1

Fixed some typos in the source code. Note that I also touched some files in `macos` folders. I understand that that may be off limits. I could revert those changes.

Fixed typos

---

images/ubuntu/scripts/build/configure-environment.sh

Getting the number decreased to bypass ASL problem when compiling with LLVM and ASAN turned on.

[Ubuntu] Decrease vm.mmap_rnd_bit to prevent ASLR ASAN issues

---

images/macos/toolsets/toolset-13.json

XCode 15.3 requires macos-14+ according to [documentation](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_3-release-notes). This PR removes XCode 15.3 from macos-13

[macos13] Remove Xcode 15.3

---

images/windows/scripts/build/Install-Wix.ps1
images/windows/scripts/tests/Wix.Tests.ps1

Adding `WIX` binaries folder to the `PATH` environment variable. 
https://github.com/actions/runner-images/issues/9551

[Windows] Add WIX binaries folder to the PATH

---

images/ubuntu/scripts/build/Install-Toolset.ps1

This PR adds `arch` filter when running Install-Toolset.ps1

[ubuntu] Fix arch in Install-Toolset.ps1

---

images/macos/templates/macOS-12.anka.pkr.hcl
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/templates/macOS-14.anka.pkr.hcl
images/macos/templates/macOS-14.arm64.anka.pkr.hcl

This PR adds an option to specify SSH port for the `null` builder (defaults to `22`).
It also switches `null` builder to using public key authentication with password representing a path to the private key file. There is a downside of overloading `vm_password` parameter but it also keeps amount of parameters small.
That being said I'm open for adding a new parameter specifically for the private key file.

Configurable SSH port

---

images/ubuntu/scripts/build/install-swift.sh

Use key-server instead of key-file when installing Swift.
https://github.com/actions/runner-images/issues/9664

[Ubuntu] Fix Swift installer

---

images/windows/scripts/build/Configure-System.ps1

The `Configure-System.ps1` script displayed the wrong filename.

Small filename fix.

---

images.CI/linux-and-win/azure-pipelines/image-generation.yml

Update test pipelines to use OIDC
[#5919](https://github.com/actions/runner-images-internal/issues/5919)

Update Windows/Ubuntu image generation pipeline to use OIDC

---

images/macos/scripts/build/configure-windows.sh

In scope of this PR, we add a fix for the issue related to open windows

[macOS] Fix the issue related to open windows

---

images/ubuntu/scripts/build/install-packer.sh

It has the conflicting LICENSE.txt file.

[Ubuntu] fix overwrite packer files on unpack

---

images.CI/linux-and-win/azure-pipelines/ubuntu2404.yml
images/ubuntu/scripts/build/configure-apt.sh
images/ubuntu/scripts/build/install-container-tools.sh
images/ubuntu/scripts/build/install-docker.sh
images/ubuntu/scripts/build/install-gcc-compilers.sh
images/ubuntu/scripts/build/install-gfortran.sh
images/ubuntu/scripts/build/install-java-tools.sh
images/ubuntu/scripts/build/install-php.sh
images/ubuntu/scripts/build/install-powershell.sh
images/ubuntu/scripts/build/install-python.sh
images/ubuntu/scripts/build/install-rust.sh
images/ubuntu/scripts/build/install-swift.sh
images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
images/ubuntu/scripts/docs-gen/SoftwareReport.Common.psm1
images/ubuntu/scripts/helpers/os.sh
images/ubuntu/scripts/tests/Browsers.Tests.ps1
images/ubuntu/scripts/tests/CLI.Tools.Tests.ps1
images/ubuntu/scripts/tests/Common.Tests.ps1
images/ubuntu/scripts/tests/Databases.Tests.ps1
images/ubuntu/scripts/tests/Java.Tests.ps1
images/ubuntu/scripts/tests/Tools.Tests.ps1
images/ubuntu/scripts/tests/Toolset.Tests.ps1
images/ubuntu/templates/ubuntu-24.04.pkr.hcl
images/ubuntu/toolsets/toolset-2404.json

Due to release of the new Ubuntu Noble Numbat we are going to release related runner image.
https://github.com/actions/runner-images/issues/9691

[Ubuntu] Add Ubuntu-24.04 base image

---

images/ubuntu/scripts/build/install-gcc-compilers.sh
images/ubuntu/scripts/build/install-gfortran.sh
images/ubuntu/toolsets/toolset-2204.json

As described in the announcement

[Ubuntu] remove toolchain test repo

---

images/ubuntu/scripts/tests/Tools.Tests.ps1

[Ubuntu] fix pester tests to include ubuntu22 back

---

images/macos/scripts/build/install-python.sh

Change PIPX_HOME for arm64 for avoiding whitespaces 
https://github.com/actions/runner-images/issues/9703

[MacOS] Change PIPX_HOME for arm64

---

images/ubuntu/scripts/build/install-java-tools.sh
images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
images/ubuntu/scripts/tests/Java.Tests.ps1
images/ubuntu/toolsets/toolset-2404.json

Add Adoptium JDKs to the Ubuntu 24.04 image.

[Ubuntu] Add missing Java SDKs to Ubuntu 24.04

---

images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
images/ubuntu/toolsets/toolset-2404.json

Python available for the latest Ubuntu-24.04 in the external repo. Adding it to the toolcache.

[Ubuntu] Add Python to the Ubuntu 24.04 toolcache

---

images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1
images/ubuntu/scripts/tests/Tools.Tests.ps1
images/ubuntu/templates/ubuntu-24.04.pkr.hcl

Add podman, buildah, skopeo to the Ubuntu 24.04 image.

[Ubuntu] Revert Podman, buildah and skopeo for Ubuntu-24.04

---

images/ubuntu/scripts/build/Install-PowerShellAzModules.ps1
images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json
images/ubuntu/toolsets/toolset-2404.json

Removed zip versions redundant code from PowerShellAZ module script and removed the properties from toolsets.json.

[Ubuntu] Remove zip versions from Azuremodules

---

images/windows/toolsets/toolset-2022.json

In order to unblock deployment since:
```
azure-arm.image: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
azure-arm.image: Package downloaded in 0.64 seconds
azure-arm.image: Signature thumbprint do not match expected.
```

[Windows] Update VS2022 code signature

---

images/macos/toolsets/toolset-14.json

Replace Xcode 15.4 RC with a release version of tool for macOS-14 based images.
https://github.com/actions/runner-images/issues/9840

[macOS] Add Xcode 15.4 Release

---

images/ubuntu/scripts/build/install-azure-cli.sh

Install from `.deb` while package is not available in repo for `Noble Numbat`.

[Ubuntu] Patch azure-cli installer for Ubuntu 24.04

---

images/ubuntu/scripts/build/install-kubernetes-tools.sh

New v3.15.0 version somehow returns an incorrect version when executing `helm version`.
https://github.com/actions/runner-images/issues/9865

[Ubuntu] Pin Helm 3.14.4 due to unusual release of 3.15.0

---

images/windows/scripts/helpers/VisualStudioHelpers.ps1

The bug that prompted enabling 8.3 filename creation was fixed 5 years ago, see https://github.com/xamarin/xamarin-android/issues/3407:
> Fix included in Xamarin.Android 10.1.0.30.
>
> Fix included on Windows in Visual Studio 2019 version 16.4.
We're on VS 2019 16.11: https://github.com/actions/runner-images/blob/98150396188d19c21a7d7c596cf4a4d7609bb12a/images/windows/Windows2019-Readme.md?plain=1#L233
8.3 filename creation is known to hurt file creation performance, especially when there are a large number of similarly named files in the same folder:
* …

VisualStudioHelpers.ps1: stop enabling 8.3 filename creation

---

images/macos/scripts/build/configure-preimagedata.sh

This PR fixes readme and release URLs in case of macos-12

[macos] Fix URLs in configure-preimagedata.sh

---

images/macos/scripts/build/install-swiftlint.sh

[macOS] Pin Swiftlint on macOS-12 due to Xcode 15.3 requirements

---

images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1

Latest release signed with the new signature

[Windows] Update signature for Azure CosmosDb Emulator

---

images/ubuntu/scripts/build/install-docker.sh
images/ubuntu/scripts/tests/Tools.Tests.ps1

Fix, made in process of Ubuntu-24.04 addition works fine. Tests could be added in order to unlock `latest` tag for Docker installation.

[Ubuntu] Revert previously removed Docker tests

---

images/windows/scripts/build/Install-AndroidSDK.ps1

Update script to install emulator separately.
The latest [diff ](https://github.com/actions/runner-images/pull/9945/files)exposed that Android emulator is missed in the system.

[Windows] Update script to install emulator separately

---

images/ubuntu/templates/ubuntu-20.04.pkr.hcl
images/ubuntu/templates/ubuntu-22.04.pkr.hcl
images/ubuntu/templates/ubuntu-minimal.pkr.hcl

We need to source helper scripts earlier as we now source `os.sh` in `apt-configure.sh`

[Ubuntu] move source scripts earlier

---

images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1

As we fixed apt-fast's installation condition on Ubuntu 24.04, it is no longer being installed so we do not need it in the software report / it does not work there.

[Ubuntu] exclude apt-fast from sw report on 24

---

images/ubuntu/scripts/build/configure-system.sh

Apply to 24.04 for now as it is the only impacted version, but later can be backported or exposed further as needed.

[Ubuntu] do not restart provisioner on 24.04 automatically

---

images/ubuntu/scripts/build/configure-apt.sh

The file has moved to the new path since 24

[Ubuntu] Display APT sources on 24 properly

---

images/windows/scripts/build/Install-PostgreSQL.ps1
images/windows/scripts/tests/Databases.Tests.ps1
images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json

This PR:
1. temporarily pins PostgreSQL version to `14.12.1` on Windows.
2. Update LLVM to 18* on Windows

[windows] Pin PostgreSQL and Update LLVM

---

images/ubuntu/templates/ubuntu-minimal.pkr.hcl

During the investigation for an issue, there was an update to be made in the ubuntu minimal image packer file for the environment variable from var to local.
[#10028](https://github.com/actions/runner-images/issues/10028)

[Ubuntu] Update Ubuntu minimal packer file

---

images/macos/toolsets/toolset-14.json

Xcode 16 runtimes conflicting with other installations on macOS-14 Intel-based image

[macOS] Install Xcode 16 on macOS-14 Intel-based image without runtimes

---

images/ubuntu/scripts/build/configure-environment.sh
images/ubuntu/scripts/tests/System.Tests.ps1

Strictly speaking we do not need any means of 3rd party hardening on runners (selinux/apparmor) so lets just disable it so it does not change system's behaviour.

[Ubuntu] disable apparmor

---

images/windows/toolsets/toolset-2019.json

This PR:
1. Temporarily removes `Microsoft.VisualStudio.Component.Azure.Storage.AzCopy` Visual Studio 2019 workload. There is an ongoing issue about package being unavailable https://developercommunity.visualstudio.com/t/PackageId:MicrosoftAzureStorageAzCopy/10679936
2. Updates Visual Studio `16.11.37` signature

[windows] Remove Visual Studio 2019 AzCopy component and fix signature

---

images/ubuntu/scripts/build/install-ruby.sh

This PR pins `public_suffix` gem version to 5.1.1 for ubuntu-20.04

[Ubuntu20] Pin public_suffix gem to 5.1.1

---

images/windows/scripts/build/Install-CloudFoundryCli.ps1

Build Failed because of Cloud-Foundry Signature  :  [Windows-2019](https://github.visualstudio.com/runner-images/_build/results?buildId=136231&view=results)
This PR Updates Cloud-Foundry signature for successful build.

[windows] Fix Cloud-Foundry signature for windows

---

images/macos/toolsets/toolset-14.json

Update `Xcode 16.0 Beta 1` to `Xcode 16.0 Beta 2` on `macOS-14` images. iOS simulator runtimes continue to conflict when installed in a single thread on `amd64`.

[macOS] Update Xcode 16.0 to Beta 2 for macOS-14

---

images/ubuntu/scripts/build/install-oc-cli.sh
images/ubuntu/toolsets/toolset-2004.json

Ubuntu 20 build failed due to OC CLI version not compatible with GLIBC 2.32 version .
This PR will pin OC CLI tool version on ubuntu 20 for successful build.
[10148](https://github.com/actions/runner-images/issues/10148)

[Ubuntu] Fix Openshift CLI version for ubuntu 20

---

images/windows/toolsets/toolset-2022.json

1.  Image generation failed due to visual studio cli signature, this PR will update the new Signature.
2.  Windows 2022 image generations will be successful.
https://github.com/actions/runner-images/issues/10201

[Windows] Fix visual studio cli signature error for windows 2022

---

images/macos/toolsets/toolset-13.json

Update default Xcode to 15.2 on macOS 13 Ventura
[10120](https://github.com/actions/runner-images/issues/10120)

[macOS] Update Xcode default to 15.2 for macos13

---

images/macos/templates/macOS-12.anka.pkr.hcl
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/templates/macOS-14.anka.pkr.hcl
images/macos/templates/macOS-14.arm64.anka.pkr.hcl

We encountered some issues with the SSH RSA key auth.  After VM is rebooted Packer fails to reconnect to it. Password auth works just fine.
We decided to not spend much time troubleshooting it because Packer scripts still require VM admin password in some places so we have to provide it anyway. Once we get rid of those places we can switch back to the RSA key auth.

Switch null builder to the SSH password auth

---

images/macos/toolsets/toolset-14.json

Update default Xcode to 15.4 on macOS 14 Sonoma
[ #10121 ](https://github.com/actions/runner-images/issues/10121)

[macOS] Update Xcode default to 15.4 for macos-14

---

images/macos/scripts/build/install-powershell.sh
images/macos/toolsets/toolset-14.json

This PR updates `link` property for Xcode 16 beta to reflect Apple download links. This help with automating XCode download. We use `symlinks` property to keep files available under `16.0` location

[macOS] Fix Xcode-16 naming on macOS-14

---

images/macos/toolsets/toolset-14.json

Xcode 16.0 Beta 3 compatible with macOS 14 released.
[#10242 ](https://github.com/actions/runner-images/issues/10242)

[macOS] Add Xcode 16.0 Beta 3 for macOS14

---

images/macos/toolsets/toolset-14.json

Xcode 16.0 Beta 4 compatible with macOS 14 released.
[#10242 ](https://github.com/actions/runner-images/issues/10242)

[macOS] Add Xcode 16.0 Beta 4 for macOS14

---

images/windows/toolsets/toolset-2022.json

1) Image generation failed due to visual studio cli signature, this PR will update the new Signature.
2) Windows 2022 image generations will be successful.
[10350](https://github.com/actions/runner-images/issues/10350)

 Fix Visual Studio signature issue for windows 2022

---

images/ubuntu/scripts/build/install-azure-cli.sh

This PR ensures that Azure CLI ('az') is installed and operational by attempting to retrieve its help information. If the command fails, it provides an error message and exits with a non-zero status, signaling a failure in Azure CLI availability.
[10110](https://github.com/actions/runner-images/issues/10110)

[Ubuntu] Update Shell Script to Verify Azure CLI Availability

---

images/windows/toolsets/toolset-2019.json

This PR will be the Temporary fix for gitversion build failure of windows 2019 by pin the previous version 5.12.0.
[10331](https://github.com/actions/runner-images/issues/10331)
- [] Changes are tested and related VM images are successfully generated

[Windows] Pin the version of gitversion package for Windows 2019 image

---

images/windows/toolsets/toolset-2019.json

This PR will pin the SqlServer version to 22.2.0 and it will fix the windows build failure 
[10216](https://github.com/actions/runner-images/issues/10216)

[Windows] Pin SqlServer version for windows -19

---

images/ubuntu/scripts/docs-gen/SoftwareReport.Common.psm1

`Tools.Tests.ps1` checks the version of `brew` with `--version` argument.
```powershell
Describe "Homebrew" {
It "homebrew" {
"/home/linuxbrew/.linuxbrew/bin/brew --version" | Should -ReturnZeroExitCode
}
}
```
`SoftwareReport.Common.psm1` checks it with `-v` argument.
```powershell
function Get-HomebrewVersion {
$result = Get-CommandResult "/home/linuxbrew/.linuxbrew/bin/brew -v"
$result.Output -match "Homebrew (?<version>\d+\.\d+\.\d+)" | Out-Null
return $Matches.version
}
```
Generally, `--version` and `-v` are equivalent. But a recent bug in `brew` makes `-v` returns the output of `brew help`.
https://github.com/Homebrew/brew/pull/17903
It's best to maintain consistency in version checks and explicitly use `--version` in both places.

[Ubuntu] Make brew version check consistent

---

images/windows/scripts/build/Install-AzureCli.ps1
images/windows/scripts/build/Install-Firefox.ps1

Image generation failed due to Azcli and geckodriver signature, this PR will update the new Signature.
https://github.com/actions/runner-images/issues/10403

Updating thumbprint for both Azcli and geckodriver

---

images/macos/scripts/build/install-nvm.sh
images/macos/scripts/build/install-rust.sh
images/macos/toolsets/toolset-12.json

It was firstly introduced here: https://github.com/rustsec/rustsec/issues/1217. Still blocks our image generation process.
UPD: This PR also includes a workaround for the issue with the NVM shell script.

[macOS] Unlock Cargo crate dependencies due to a bug

---

images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1
images/windows/toolsets/toolset-2019.json

Image generation failed due to checksum issues with Azure Cosmos DB and problems with the m2repository in the Android SDK. This PR addresses the checksum issue and removes the m2repository from the Android SDK after the image generation passes successfully.

[Windows] Updating AzurecosmoDB checksum and Removing m2repositry in AndriodSDK

---

images/windows/toolsets/toolset-2019.json

This PR will be the fix for gitversion build failure of windows 2019 with latest version of gitversion.portable.
[10331](https://github.com/actions/runner-images/issues/10331)

[Windows] fix gitversion.portable version issue for Windows 2019 image

---

images/macos/scripts/build/configure-system.sh
images/macos/scripts/build/install-common-utils.sh
images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
images/macos/scripts/helpers/confirm-identified-developers-macos13.scpt
images/macos/scripts/helpers/confirm-identified-developers-macos14.scpt
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-14.anka.pkr.hcl
images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json

Add Parallels Desktop extension:
1. Install Parallels
2. Approve the Parallels Kernel Extension
3. Reboot
4. Uninstall Parallels
**Related issue:**
[ #10143 ](https://github.com/actions/runner-images/issues/10143)

[macOS] Add parallels desktop extension to macOS13 and macOS14 intel machines

---

images/macos/templates/macOS-12.anka.pkr.hcl
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/templates/macOS-14.anka.pkr.hcl
images/macos/templates/macOS-14.arm64.anka.pkr.hcl

This PR changes `github_api_pat` Packer variable to be treated as `sensitive`. This is to prevent the value from being displayed in the logs.

[macOS] Treat `github-api-pat` as sensitive variable

---

images/macos/scripts/build/install-actions-cache.sh

Pass API PAT to make authenticated calls to GitHub APIs with the hope to resolve `403` error which is likely to be caused by throttling.

Use API PAT for downloading actions/cache

---

images/windows/toolsets/toolset-2022.json

This PR will fix the WDK image generation failure for win-22. The issue was caused by the missing Visual Studio Component for WDK. This PR adds the Visual Studio Component  to the image, which will fix the WDK image generation failure for win-22.
[10444](https://github.com/actions/runner-images/issues/10444)

[Windows] Fix WDK image generation failure for win-22

---

images/macos/toolsets/toolset-14.json

Adding Xcode 16.0 Beta 5 to macOS 14 so that we can keep track of both Xcode 16.1 and 16.0 beta 5 versions.
https://github.com/actions/runner-images/issues/10464

[macOS] Adding  Xcode 16.0 Beta 5 for macOS-14 back to the repository

---

images/macos/scripts/build/install-chrome.sh

This PR fixes an old issue with `install-chrome` Bash script. It freezes the VM causing a simple installation taking over an hour on Intel (less on ARM, just because it's more powerful). I observed 99% CPU with over 400GB of virtual RAM (with tons of page faults) which explains why VM was freezing

[macOS] Fix Chrome installer script which freezes VM

---

images/macos/toolsets/toolset-14.json

Updating changes:
Update Xcode 16.0 Beta 5 to Xcode 16.0 Beta 6 compatible with macOS 14 released.

[macOS]Add Xcode 16.0 Beta 6 for macOS-14

---

images/windows/toolsets/toolset-2022.json

1.Image generation failed due to visual studio cli signature, this PR will update the new Signature.
2.Windows 2022 image generations will be successful.
https://github.com/actions/runner-images/issues/10505

[Windows] Fix Visual Studio signature issue for windows 2022

---

images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1

1.Image generation failed due to AzureCosmosDbEmulator signature, this PR will update the new Signature.
2.Windows 2019 and  2022 image generations will be successful.
https://github.com/actions/runner-images/issues/10524

[Windows] Fix AzureCosmosDbEmulator signature issue for windows 2019 and 2022

---

images/windows/scripts/build/Install-AzureCli.ps1

Windows -19 and 2022 image generation failed due to AzureCli signature, this PR will update the new Signature.
Windows-19 and Windows 2022 image generations will be successful
https://github.com/actions/runner-images/issues/10547

[Windows] updated azure cli signature 

---

helpers/software-report-base/SoftwareReport.Nodes.psm1
images/macos/scripts/docs-gen/SoftwareReport.Xcode.psm1
images/macos/toolsets/toolset-14.json

- `Simulator - Xcode` link was redundant
- `visionOS` simulator won't work on Intel-based runners which was triggering issues in the `software report` module

[macOS] Remove redundant info from SR, fix bug with empty runtimes for Xcode

---

images/macos/toolsets/toolset-14.json

Xcode 16.0 RC1 released. It should replace Xcode 16.0 Beta 6. This PR targeted to macOS-14 only.
#10583

[macOS] Update Xcode 16.0 to RC1 on macOS-14

---

images.CI/macos/anka/CreateCleanAnkaTemplate.ps1

- Add 25 GB to the base images
- Remove disk_size from the template name
https://github.com/actions/runner-images/issues/10511

[macOS] Increase base disk size by 25 GB

---

images/macos/scripts/build/configure-system.sh

Clean up Homebrew downloads folder to save disk space on macOS-14 runners.

[macOS] Clean up Homebrew downloads folder

---

images/macos/scripts/tests/Xcode.Tests.ps1
images/macos/toolsets/toolset-15.json

- Replace Xcode 16.0_beta_6 with Xcode 16.0 Release Candidate
- Update test case to run with all composite versions of Xcode
Note: It will work while version separated by underline, will not work with `12Preview` or `34.5-beta`

[macOS] Update Xcode 16.0 to RC1 on macOS-15

---

images/macos/scripts/tests/Xamarin.Tests.ps1

Pester tests discovering process ignores `-Skip` which leads to an error.

[macOS] Workaround issue with Xamarin Pester tests discovery

---

images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Replace Xcode 16 Release candidate with Xcode 16.0 on macOS-14 and macOS-15
#10629

[macOS] Replace Xcode 16 RC with Xcode 16.0 on macOS-14 and macOS-15

---

images/ubuntu/scripts/build/install-swift.sh

Ubuntu-20.04 image generation is failing due to the swift failure. This PR fixes the issue by updating the swift version signature for the latest version.

[ubuntu] Add new Swift GPG key to unlock Ubuntu builds

---

.github/workflows/ubuntu2004.yml
.github/workflows/ubuntu2204.yml
.github/workflows/ubuntu2404.yml
.github/workflows/windows2019.yml
.github/workflows/windows2022.yml

This PR updates job conditions for GitHub CI workflows from using `github.event.pull_request.labels.*.name` context to `github.event.label.name`.
This allows to avoid workflows executing till completion twice in certain labeling scenarios.

Update job conditions for GitHub CI workflows

---

images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Replacing Xcode 16.1 Beta with recently released Xcode 16.1 Beta 2. 🎉

[macOS] Update Xcode 16.1 to Beta 2 on macOS-14 and macOS-15

---

images/macos/scripts/build/configure-shell.sh

`brew shellenv` started to return unpredicted result which block users from updating PATH.  Temporary workaround while fix is in progress in the upstream.
#10624

[macOS] Fix for Homebrew shellenv bug to unlock PATH

---

images/macos/toolsets/toolset-14.json

Temporary solution to free up disk space. Full description in linked issue.
#10559

[macOS] visionOS platform tools temporary removed from macOS-14

---

README.md

Updating ubuntu24.04 image as ubuntu-latest 
https://github.com/actions/runner-images/issues/10636

[doc] Updating ubuntu-24.04 image as ubuntu-latest

---

images/macos/scripts/build/install-compilable-brew-packages.sh
images/macos/scripts/tests/BasicTools.Tests.ps1
images/macos/scripts/tests/Common.Tests.ps1
images/macos/templates/macOS-12.anka.pkr.hcl
images/macos/toolsets/toolset-12.json

Since Homebrew no longer supports macOS 12 for Ant, Kotlin, and SBT, we are installing all three after Xcode installation.

[macOS] Install ant, kotlin and sbt after XCode installation

---

images/macos/scripts/build/configure-shell.sh

Changes to implement after additional discussion under this PR:
https://github.com/Homebrew/brew/pull/18366
https://github.com/actions/runner-images/issues/10624

[macOS] Recommended version of `brew shellenv` usage

---

images/macos/scripts/build/install-bicep.sh

Removing temporary functionality designed to compensate for incompatibility with the previous version of Xcode CLT
https://github.com/actions/runner-images/issues/10686

[macOS] Disable removing default Xcode CLT for macOS-15

---

images/macos/scripts/build/install-common-utils.sh

Packer is deprecated from Homebrew `Warning: packer has been deprecated! It will be disabled on 2024-09-27.`
Hence we are installing packer using `hashicorp/tap/packer`.

[macOS] Install packer using tap

---

images/macos/macos-15-arm64-Readme.md

[macOS] [doc] Update macos-15-arm64 readme to the current version

---

images/macos/scripts/build/configure-autologin.sh
images/macos/scripts/build/configure-machine.sh
images/macos/scripts/build/configure-system.sh
images/macos/templates/macOS-13.anka.pkr.hcl
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/templates/macOS-14.anka.pkr.hcl
images/macos/templates/macOS-14.arm64.anka.pkr.hcl
images/macos/templates/macOS-15.anka.pkr.hcl
images/macos/templates/macOS-15.arm64.anka.pkr.hcl

Details of the two changes done below:
1. Replace 'osascript' with 'expect' for enabling automationmodetool. osascript was not working as expected with macOS 14.7. Hence replacing for all images.
2. Include `configure-autologin.sh` script for all images and set `autoLoginUserScreenLocked` value to 'false'.

[macOS] Fix automationmodetool for macOS14.7

---

README.md

macOS-12 deprecation process is on track
https://github.com/actions/runner-images/issues/10721

[doc] Mark macOS-12 as deprecated

---

images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json

Setup-actions team currently use Tcl/Tk in macOS12 to generate artifacts for python. Since macOS12 is deprecated adding Tcl/Tk to macOS13.

[macOS] Add tcl-tk to macOS13

---

images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Update Xcode 16.1 to Beta 3 for macOS 14 and macOS 15.

[macOS] Add Xcode 16.1 Beta 3 to macOS14 and macOS15

---

images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json

This PR contains
Added Go 1.23 version to Ubuntu20 and 22 image 
Making 1.23 version as a default in ubuntu20 and 22 image.
https://github.com/actions/runner-images/issues/10436

[Ubuntu 20 and 22] Go version 1.23 added

---

images/ubuntu/scripts/build/configure-environment.sh
images/windows/scripts/build/Configure-SystemEnvironment.ps1

Add the `RUNNER_TOOL_CACHE` environment variable for Ubuntu and Windows images.
https://github.com/actions/runner-images-internal/issues/6459

[Ubuntu, Windows] Add RUNNER_TOOL_CACHE environment variable

---

images/ubuntu/scripts/build/install-python.sh

This is a temporary workaround put in place to allow users of ubuntu-24.04 runner images use pip install in the default environment.
[runner-images/issues#10781](https://github.com/actions/runner-images/issues/10781)
[c2c-actions-support/issues#4413](https://github.com/github/c2c-actions-support/issues/4413)
VM image is successfully [generated](https://github.com/actions/runner-images-ci/actions/runs/11354988709).
VM image is successfully [deployed](https://github.com/actions/runner-images-ci/actions/runs/11355755511).

[Ubuntu 2404] Allow pip to install packages in default environment

---

images/ubuntu/toolsets/toolset-2404.json

This PR will remove the Node.js version 16*
VM image is successfully [generated](https://github.com/actions/runner-images-ci/actions/runs/11385073691)

[ Ubuntu 2024 ] Removing Node.js version 16*

---

.github/workflows/create_sbom_report.yml

- Unpin SYFT-tool version for the macOS and Ubuntu jobs
- Use ReleaseBranchName variable as a part of `run-name` to simplify identity run

[actions] Use latest SYFT on macOS/Ubuntu; provide useful run-name

---

images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json
images/ubuntu/toolsets/toolset-2404.json

This PR adding latest Node.js version 22 in Ubuntu

[Ubuntu] Adding latest Node.js version 22* .

---

images/macos/scripts/tests/System.Tests.ps1

Minimum required 14 GB might be not enough for many projects unfortunately

[macOS] Update disk space Pester test: current target - 30 GB

---

images/macos/toolsets/toolset-14.json

- Removed Xcode 14 and 16 from macOS 14 as per new support policy.
- Added visionOS.
- https://github.com/actions/runner-images/issues/10703

[macOS] macOS-14-updated support policy changes

---

images/macos/toolsets/toolset-15.json

The command line tools for android SDK were updated.
https://github.com/actions/runner-images/issues/10814

[macOS] Update android commandlinetools for macOS 15

---

images/macos/toolsets/toolset-14.json

We are adding Xcode16 back to macOS14 images (without visionOS).

[macOS] Add Xcode16 back to macOS14 images

---

images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Updating Cmake 3.22.1 to 3.31.0
Related issue [Link](https://github.com/actions/runner-images/issues/10933)

[MacOS]Upgrade cmake to 3.31.0

---

images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Pin version for Az powershell module to `Az: 12.4.0` for all macOS images.

[macOS] Pin version for Az powershell module

---

images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Replace `Xcode 16.2_beta_2` with `Xcode 16.2_beta_3` on macOS15

[macOS] Update Xcode 16.2 Beta on macOS15

---

images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

[MacOS]Update php-8.3 to php-8.4

---

images/windows/scripts/tests/Tools.Tests.ps1

Quick fix to update the Kotlin pester test for Windows.
In the latest release of Kotlin was removed deprecated JS `DCE` class, so `kotlin-dce-js.bat` was also removed. Instead, `kotlinc-js` was added to the test.
References:
- [Delete the org.jetbrains.kotlin.cli.js.dce.K2JSDce class](https://github.com/JetBrains/kotlin/releases/tag/v2.1.0)
- https://youtrack.jetbrains.com/issue/KT-70231

[Windows] Update Kotlin pester test

---

images/windows/scripts/build/Configure-System.ps1
images/windows/scripts/build/Install-BizTalkBuildComponent.ps1
images/windows/scripts/build/Install-Docker.ps1
images/windows/scripts/build/Install-Toolset.ps1
images/windows/scripts/build/Invoke-Cleanup.ps1
images/windows/scripts/helpers/InstallHelpers.ps1
images/windows/scripts/helpers/VisualStudioHelpers.ps1
images/windows/scripts/tests/Tools.Tests.ps1
images/windows/templates/windows-2019.pkr.hcl
images/windows/templates/windows-2022.pkr.hcl

This PR changes the temporary files directory from `C:\Users\<user>\AppData\Local\Temp`  to `D:\temp`, where `D:` drive is an temporary disk propagated with selected VM size. 
Also, all cleanup actions have been moved from `Configure-System.ps1` script to `Invoke-Cleanup.ps1`

[Windows] Reorganize temporary file storage and separate cleanup activities

---

.github/workflows/windows2025.yml

Add trigger to run Windows 2025 CI

Add trigger to run Windows 2025 CI

---

images/windows/scripts/build/Configure-ImageDataFile.ps1
images/windows/scripts/build/Configure-System.ps1
images/windows/scripts/build/Configure-User.ps1
images/windows/scripts/build/Install-Docker.ps1
images/windows/scripts/build/Install-Haskell.ps1
images/windows/scripts/build/Install-Mingw64.ps1
images/windows/scripts/build/Install-MongoDB.ps1
images/windows/scripts/build/Install-Rust.ps1
images/windows/scripts/build/Install-VisualStudio.ps1
images/windows/scripts/build/Invoke-Cleanup.ps1
images/windows/scripts/docs-gen/Generate-SoftwareReport.ps1
images/windows/scripts/docs-gen/SoftwareReport.Databases.psm1
images/windows/scripts/docs-gen/SoftwareReport.Tools.psm1
images/windows/scripts/helpers/ImageHelpers.psm1
images/windows/scripts/helpers/InstallHelpers.ps1
images/windows/scripts/tests/CLI.Tools.Tests.ps1
images/windows/scripts/tests/ChocoPackages.Tests.ps1
images/windows/scripts/tests/Databases.Tests.ps1
images/windows/scripts/tests/Docker.Tests.ps1
images/windows/scripts/tests/Haskell.Tests.ps1
images/windows/scripts/tests/Rust.Tests.ps1
images/windows/scripts/tests/Tools.Tests.ps1
images/windows/scripts/tests/VisualStudio.Tests.ps1
images/windows/scripts/tests/WDK.Tests.ps1
images/windows/templates/windows-2025.pkr.hcl
images/windows/toolsets/toolset-2025.json

This PR adds the Windows 2025 image to the repository.
Release notes:
- Updated software:
- `mingw` was updated to 14.2.0
- `Azure Service Fabric` runtime was updated to 10.1.2493.9590
- `Azure Service Fabric` SDK was updated to 7.0.2712
- `strawberryperl` was updated to 5.40.0.1
- `maven` was updated to 3.9
- `LLVM` was updated to 19
- `PostgreSQL` was updated to 17
- `openssl` was updated to 3.4.0
- `MongoDB` was updated to 7.0
- Removed software/Items:
- InnoSetup
- Mercurial
- NSIS
- Alibaba Cloud CLI
- bindgen 
- cbindgen 
- cargo-audit 
- cargo-outdated
- AzureRM PowerShell module
- Azure PowerShell module
- .Net v6.0 and v7.0
- TortoiseSVN
- Docker images:
- mcr.microsoft.com/windows/servercore:ltsc2022
- mcr.microsoft.com/windows/nanoserver:ltsc2022
- …

[Windows] Add windows 2025 image

---

images/windows/scripts/helpers/InstallHelpers.ps1

Sorting by semantic version in PowerShell does not always give predictable results in more complex cases. 😞  Example: "v2.47.0.windows.2"
At the same time not all the repos use `latest` tag for the current release in production, so we need to sort using more complex logic. 🤷‍♂️

[Windows] Update Get-GithubReleasesByVersion function sorting

---

images/windows/scripts/build/Invoke-Cleanup.ps1

This PR will fix an issue with MSI installers that requires the `C:\Windows\Installer` directory to exist.

[Windows] Exclude "installer" directory from deletion in Windows 2025

---

images/macos/scripts/tests/BasicTools.Tests.ps1

Quick fix to update the Kotlin test for macOS
In the latest release of Kotlin was removed deprecated JS DCE class, so kotlin-dce-js.bat was also removed. Instead, kotlinc-js was added to the test.
References:
[Delete the org.jetbrains.kotlin.cli.js.dce.K2JSDce class](https://github.com/JetBrains/kotlin/releases/tag/v2.1.0)
https://youtrack.jetbrains.com/issue/KT-70231

[macOS] Update Kotlin to BasicTools.test file

---

images/macos/toolsets/toolset-15.json

The platform is too used to not be added.
- https://github.com/actions/runner-images/issues/10814

[macOS] Add Android SDK 34 to macOS-15 images

---

images/macos/toolsets/toolset-15.json

Update Xcode 16.2 Beta 3 to Xcode 16.2 RC on macOS-15.

[macOS]  Add Xcode 16.2 Release Candidate to macOS15

---

images/ubuntu/scripts/tests/Apt.Tests.ps1
images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json
images/ubuntu/toolsets/toolset-2404.json

Add systemd-coredump utility to all Ubuntu images.
https://github.com/actions/runner-images/issues/10480

[Ubuntu] Add systemd-coredump

---

images/windows/scripts/build/Configure-User.ps1

This change is tweak registry to accept by default "Send Diagnostic data to Microsoft" consent for windows-2025 image.
Example:

[Windows] Accept by default "Send Diagnostic data to Microsoft" consent for windows-2025 image

---

images/windows/scripts/build/Invoke-Cleanup.ps1

This PR removes `$env:SystemRoot\Installer\*` folder cleanup for Windows Server 2019 and 2022.

[windows] Remove Windows\Installer\* folder cleanup

---

images/windows/toolsets/toolset-2025.json

This pull request moves `Strawberry Perl` down in the list of packages that are installed via chocolatey.
The updated version of `Strawberry Perl` comes with `CMake` with an older version than the one we install directly from chocolatey. To keep the correct version of `CMake`, we need to move `Strawberry Perl` down.

[Windows] Install "strawberryperl" right after "cmake" in windows-2025 image

---

images/windows/scripts/docs-gen/SoftwareReport.VisualStudio.psm1

This PR contains following Visual Studio related software report adjustments for windows images:
1. `Windows Driver Kit` is not installed standalone on windows-2025, so removed from the report.
2. `$ssdtPackages` is an orphaned variable, so removed from the report.

[windows] Update Visual Studio Software Report

---

images/windows/toolsets/toolset-2022.json

Add .NET 4.7.2 SDK to the windows-2022 image to maintain app development capability
https://github.com/actions/runner-images/issues/10942

[Windows] Add Microsoft.Net.Component.4.7.2.SDK to Windows toolset 2022

---

images/windows/scripts/build/Invoke-Cleanup.ps1

Remove `C:\Windows\Installer\*` folder cleanup for windows 2025 image

[Windows] Remove Windows\Installer\* folder cleanup for windows 2025 image

---

images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Update  Xcode 16.2 RC to Xcode 16.2 Release on macOS-14 and macOS-15.

[macOS] Add Xcode 16.2 Release to macOS14 and macOS15

---

images/windows/scripts/build/Install-MongoDB.ps1
images/windows/scripts/tests/Databases.Tests.ps1

This PR:
1. Installs `mongosh` for ALLUSERS on windows-2025
2. Enables Pester Test

[windows-2025] Install mongosh for ALLUSERS and enable test

---

images/windows/scripts/build/Configure-System.ps1
images/windows/scripts/build/Install-WSL2.ps1
images/windows/scripts/docs-gen/Generate-SoftwareReport.ps1
images/windows/scripts/docs-gen/SoftwareReport.Tools.psm1
images/windows/scripts/tests/WindowsFeatures.Tests.ps1
images/windows/templates/windows-2025.pkr.hcl

This PR adds WSL v2 support to Windows-2025 image.
>[!! IMPORTANT] WSL v2 does not have a default distribution installed.
https://github.com/actions/runner-images/issues/10563
https://github.com/actions/runner-images/issues/11228

[Windows] Add WSL2 to Windows-2025 image

---

images/windows/toolsets/toolset-2025.json

This PR adds Android 34 SDK and Tools to `windows-2025`

[windows] Add Android SDK and Tools 34 to windows-2025

---

images/windows/scripts/tests/WindowsFeatures.Tests.ps1

This PR skips the WSL2 pester test for `windows-2019` and `windows-2022`.

[windows] Fix WSL2 pester test

---

images/macos/toolsets/toolset-14.json

Update Xcode 16.0 to Xcode 16.2 Release on macOS-14.

[macOS] Add Xcode 16.2 Release to macOS14

---

images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json

This PR will remove the .Net version 7.0 
Related Announcement: https://github.com/actions/runner-images/issues/10894

[Ubuntu 20 and 22] Removing .Net version 7.0 

---

images/ubuntu/scripts/build/install-zstd.sh

Speeds up my builds from 93s to 37s (four core) for the install-zstd.sh step
None

Use all processors when installing zstd

---

images/ubuntu/scripts/build/cleanup.sh
images/ubuntu/scripts/build/install-azure-cli.sh
images/ubuntu/scripts/build/install-azure-devops-cli.sh

This PR fixes #10110.
- Config + cli-extensions directory is placed in /opt but not in installation dir at /opt/az/ as this is bad practice.
- Removed cli-extensions directory setup from devops extension as this setting belongs in az-cli setup
- Added cleanup for telemetry / logs in config directory
#10110

Implement az-cli warmup on ubuntu

---

images/ubuntu/toolsets/toolset-2404.json

This PR will add the `libsqlite3-dev` package to the Ubuntu 24 image .
https://github.com/actions/runner-images/issues/11279

[Ubuntu-24] Add libsqlite3-dev package to ubuntu 24

---

README.md

Fixes #10636
Update the `README.md` to reflect the change in the `ubuntu-latest` label to Ubuntu 24.04.
* Change the `ubuntu-latest` label to point to Ubuntu 24.04.
* Remove the beta tag from the Ubuntu 24.04 image.
* Update the rollout status of the Ubuntu 24.04 image to reflect the latest changes.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/actions/runner-images/pull/11332?shareId=eb29b820-6b75-4f3d-9d7d-e615fa05e301).

Update ubuntu-latest to Ubuntu 24.04

---

README.md
docs/dotnet-ubuntu.md

This adds a short document detailing the changes .NET Core team have made related to Ubuntu.
It provides a brief overview of the implications and how to resolve issues caused by this change.
Docs only.

[ubuntu] Add documentation on .NET core changes for 2404

---

images/windows/scripts/helpers/InstallHelpers.ps1

This PR updates the `Get-WindowsUpdateStates` function to skip the update failed event if the update has already been successfully installed

[windows] Update Get-WindowsUpdateStates function

---

images/macos/toolsets/toolset-14.json

1. Replace install_runtimes with runtimes for Fix iOS18.2 Simulator for Xcode 16.2 on macOS 14
2. [Issue-11335](https://github.com/actions/runner-images/issues/11335)

[macOS] Fix iOS18.2 Simulator for Xcode 16.2 on macOS 14

---

images/ubuntu/toolsets/toolset-2004.json
images/ubuntu/toolsets/toolset-2204.json

This PR adding latest Dotnet version 9.0 in Ubuntu-20 and Ubuntu-22.
https://github.com/actions/runner-images/issues/10964

[Ubuntu 20 & Ubuntu 22] Adding Dotnet latest version 9.0

---

images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json
images/windows/toolsets/toolset-2025.json

This PR will update the latest version of PHP 8.4* to the windows 2019, 2022 and 2025.
https://github.com/actions/runner-images/issues/11187

[Windows] Updated to PHP version 8.4.

---

.github/workflows/codeql-analysis.yml

After applying https://github.com/actions/runner-images/pull/11473, we no longer use Ruby in our sources. Required for unlock: https://github.com/actions/runner-images/pull/11473
https://github.com/actions/runner-images/pull/11473

[Actions] Remove Ruby check for CodeQL test as not used

---

images/ubuntu/scripts/build/install-android-sdk.sh
images/ubuntu/scripts/tests/Android.Tests.ps1

This pull request adds the Android SDK Platform-Tools to the Ubuntu image.
The platform tools take up about 18 MB of disk space, but this should not be an obstacle to adding them.
https://github.com/actions/runner-images/issues/10495

[Ubuntu] add Android SDK Platform-Tools

---

images/ubuntu/scripts/build/configure-dpkg.sh

This PR adds the `libicu` package version 70 to the Ubuntu 24 image.

[Ubuntu24] adding libicu package version 70

---

images/ubuntu/scripts/build/install-ruby.sh

Improvement: Don't install rdoc/ri (ruby information) documentation in the runner image.
Just something I randomly noticed in the output of building an image, and it's not needed since the documentation isn't for programmatic access.
Changed worked locally for me, and sped up the ruby install step from ~135 seconds to ~60 seconds (55% speed up).

[ubuntu] Don't install documentation for ruby gems

---

images/windows/scripts/build/Install-DotnetSDK.ps1

Visual Studio 2022 installation contains `Microsoft.NetCore.Component.SDK` component, which creates `C:\Program Files\dotnet\sdk-manifests\8.0.100` folder with `microsoft.net.sdk.aspire 8.2.2` workload manifest.
Later during any dotnet/sdk 8.0 installation using [dotnet-install](https://dot.net/v1/dotnet-install.ps1) script, `8.0.100` folder's existence prevents manifest files from being copied. This causes [issues](https://github.com/dotnet/sdk/issues/45931) with `dotnet` cli command
This PR introduces following workaround logic on `windows-2022` and `windows-2025` images:
1. Manifests created by Visual Studio are copied to the temporary location for the duration of `dotnet-sdk` install
2. Visual Studio related manifests are copied back to the original location after `dotnet-sdk` install

[windows] Fix .Net 8 SDK installation

---

images/windows/scripts/build/Install-DotnetSDK.ps1

This PR fixes condition handling in `Install-DotnetSDK.ps1` script in case of `windows-2025`

[windows-2025] Fix .Net 8 SDK installation

---

images/windows/scripts/build/Install-EdgeDriver.ps1
images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json
images/windows/toolsets/toolset-2025.json

This PR will update the Edge-Driver  , vcRedis Signature for Windows 2019 and 2022 images and Openssl version 3.4.1 is updated in Windows-2025 image.

[Windows] Updated the EdgeDriver, vcRedis signature and Openssl version to 3.4.1 in Windows 25

---

helpers/GenerateResourcesAndImage.ps1
images.CI/linux-and-win/build-image.ps1
images/ubuntu/templates/ubuntu-20.04.pkr.hcl
images/ubuntu/templates/ubuntu-22.04.pkr.hcl
images/ubuntu/templates/ubuntu-24.04.pkr.hcl
images/ubuntu/templates/ubuntu-minimal.pkr.hcl
images/windows/templates/windows-2019.pkr.hcl
images/windows/templates/windows-2022.pkr.hcl
images/windows/templates/windows-2025.pkr.hcl

This pull request removes the `packer` block from the related templates. 
Also, a new parameter `PluginVersion` is introduced for the scripts `GenerateResourcesAndImage.ps1` and `build-image.ps1`. It will allow the version of the Packer Azure plugin to be specified."
To install the Packer Azure plugin, the command `packer init` was changed to `packer plugins install`. 
https://github.com/actions/runner-images/issues/10560

Add the ability to specify Packer Azure plugin version

---

images.CI/linux-and-win/build-image.ps1
images.CI/linux-and-win/cleanup.ps1

This PR removes unnecessary authentication methods from the "cleanup" script, since the image generation workflow uses OIDC authentication.
Also, this PR make the `ClientSecret` parameter optional for the `build-image.ps1` script.
https://github.com/actions/runner-images-internal/issues/6776

Remove authentication method from "cleanup" script

---

images/windows/scripts/build/Install-Git.ps1

This PR will pin the git version to 2.47.1 on Windows.

[Windows] Pin the git version to 2.47.1

---

images/macos/scripts/build/install-git.sh

update git version to 2.48.1 to all macOS images.

[macOS] update git version to 2.48.1

---

images/macos/toolsets/toolset-15.json

Removing beta due to compatibility issues with other Xcode 16.x simruntimes

[macOS] Remove Xcode 16.3 Beta 1 due to compatibility issues

---

images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json
images/windows/toolsets/toolset-2025.json

This PR updates the docker engine version to 27 and compose to 2.32.2

[Windows] Updating Docker-Engine version to 27

---

images/macos/scripts/build/configure-machine.sh
images/macos/scripts/tests/Common.Tests.ps1

This PR enables passwordless sudo for users in the admin group, and also fixes the permissions of the sudoers daemon files (they turned out to be corrupted).
Plus a couple of tests are added to check the validity of the above parameters.
- https://github.com/actions/runner-images/issues/10484

[macOS] Enable NOPASSWD `sudo` for `admin` group

---

images/macos/scripts/helpers/Xcode.Installer.psm1
images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Temporary fix for the Saturday rollback reason. `xcodebuild -downloadAllPlatforms` is not so reliable as we thought.
https://github.com/actions/runner-images/issues/11683

[macOS] Force Xcode 16.2 to install correct runtimes for iOS/visionOS

---

images/macos/scripts/docs-gen/Generate-SoftwareReport.ps1
images/macos/scripts/docs-gen/SoftwareReport.Common.psm1
images/macos/scripts/tests/BasicTools.Tests.ps1
images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Add Ninja to macOS images
https://github.com/actions/runner-images/issues/11391
https://github.com/actions/runner-images/issues/11235

[macOS] Add Ninja

---

images/ubuntu/scripts/build/install-ruby.sh

This PR will includes the installation of the google-cloud-errors gem (version 1.4.0) for Ubuntu 20 environments.

[Ubuntu] Add Installation of google-cloud-errors Gem for Ubuntu 20

---

docs/create-image-and-azure-resources.md
helpers/GenerateResourcesAndImage.ps1

This PR:
1. Removes `Force` and `ReuseResourceGroup` parameters from [GenerateResourcesAndImage](https://github.com/actions/runner-images/blob/main/helpers/GenerateResourcesAndImage.ps1) helper. The resource group to store final artifact will be reused when it already exists and an error will be thrown when it doesn't
2. Updates documentation to reflect the changes

Remove deprecated parameters from GenerateResourcesAndImage helper

---

images/macos/scripts/build/install-runner-package.sh

Without using PAT, the method quickly exhausts access attempts due to unauthorised access limits.

[macOS] Update Runner installer script to use API PAT

---

images/macos/toolsets/toolset-15.json

Xcode 16.3 beta 2 version added along with the simulators.

[macOS] Xcode 16.3 beta 2 version update 

---

images/ubuntu/scripts/docs-gen/SoftwareReport.Common.psm1

The output of the sbt --version command has been updated to display the `sbt runner version` instead of the `sbt script version`, which will resolve the issue.
https://github.com/actions/runner-images/issues/11813

[Ubuntu] Updating SBT version regex pattern.

---

images/ubuntu/scripts/build/install-kotlin.sh

This PR will resolve the Kotlin test failure on v2.1.20 by pinning the previous version 2.1.10.
https://github.com/actions/runner-images/issues/11844

[Ubuntu] Pinning Kotlin previous version 2.1.10

---

images/macos/toolsets/toolset-15.json

Updated xcode to 16.3 beta 3  for macOS15 and  macOS15arm

[macOS] Updated xcode to 16.3 beta 3  for macOS15 macOS15arm

---

images/macos/scripts/build/install-common-utils.sh
images/macos/scripts/build/install-homebrew.sh

- Homebrew team deprecated bundle tap - deprecate it as available via `brew bundle` by default
- Kotlin 2.1.20 release blocks our tests - temporary pin previous release; issue [link](https://youtrack.jetbrains.com/issue/KT-76169/kotlinc-js-version-and-kapt-version-returning-non-zero-status-code-on-v2.1.20)
- Modify `install-common-utils.sh` to work with `case` instead of `if` blocks

[macOS] Deprecate brew/bundle tap, pin Kotlin to 2.1.10

---

images/macos/scripts/build/Install-Xcode.ps1
images/macos/scripts/helpers/Xcode.Installer.psm1
images/macos/toolsets/Readme.md
images/macos/toolsets/toolset-13.json
images/macos/toolsets/toolset-14.json
images/macos/toolsets/toolset-15.json

Modification of the Xcode runtime installer function. Added the ability to install multiple versions for one platform, improved the mechanism for working with the toolset, added validation of options. Additionally, the formatting of the toolset section has been updated to be more readable, and the documentation has been updated accordingly. The set of runtimes remains unchanged.

[macOS] Update Xcode runtimes installer helper and toolset format

---

images/windows/scripts/build/Configure-ImageDataFile.ps1

This PR is to change the encoding of ImageDatafile to use UTF-8 without BOM.
Some system is facing issues in reading the content of this file.

[Windows] Change file encoding to utf8 with no BOM

---

images/windows/scripts/docs-gen/SoftwareReport.Common.psm1
images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json
images/windows/toolsets/toolset-2025.json

This PR will resolve SBT version mismatch issue and Kotlin test failure on v2.1.20 by pinning the previous version 2.1.10 in the Windows image
https://github.com/actions/runner-images/issues/11844

[Windows] Fix SBT version issue and Pinning Kotlin version

---

images/macos/scripts/helpers/Xcode.Installer.psm1

We don't really need sudo there. It might have negative impact.

[macOS] Remove `sudo` from simulators installer script

---

images/macos/scripts/build/configure-system.sh
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/templates/macOS-14.arm64.anka.pkr.hcl
images/macos/templates/macOS-15.arm64.anka.pkr.hcl

- Set solid color wallpaper
- Disable Handoff and Continuity
- Disable some graphic effects in System
- Disable analytics daemon
- Disable notification center agent
- Disable Time Machine and it's daemon
- Disable Apple Push Notification Service daemon
- Disable MDS and Spotlight (macOS-14 and higher)
Apply script to arm64 based machines.
- [#6865](https://github.com/actions/runner-images-internal/issues/6865)

[macOS] Disable rarely used services, use optimised configs

---

images/ubuntu/toolsets/toolset-2204.json
images/ubuntu/toolsets/toolset-2404.json

This PR removes the MongoDB from the toolset in Ubuntu 22.04 and 24.04.
`Mongo Db` is not part of Ubuntu 22.04 and 24.04

[Ubuntu] Removing mongo db from  toolset in Ubuntu 22.04 and 24.04

---

images/macos/toolsets/toolset-15.json

Updated xcode to 16.3 Release Candidate 2 to macOS15 images.

[macOS] Updated xcode to 16.3 Release Candidate 2 to macOS15 images.

---

images/macos/scripts/build/install-codeql-bundle.sh

Bug fix — the default version of the CodeQL version was using the `https://raw.githubusercontent.com/github/codeql-action/v2/src/defaults.json` file to retrieve the latest CLI version, but we have deprecated v2 of the CodeQL Action and the file no longer populates the latest CLI versions. This change updates to v3.

[macOS] Update default CodeQL major version to v3

---

images/windows/scripts/build/Install-CodeQLBundle.ps1

Bug fix — the default version of the CodeQL version was using the `https://raw.githubusercontent.com/github/codeql-action/v2/src/defaults.json` file to retrieve the latest CLI version, but we have deprecated v2 of the CodeQL Action and the file no longer populates the latest CLI versions. This change updates to v3.

[Windows] Update default CodeQL major version to v3

---

images/ubuntu/scripts/build/install-codeql-bundle.sh

Bug fix — the default version of the CodeQL version was using the `https://raw.githubusercontent.com/github/codeql-action/v2/src/defaults.json` file to retrieve the latest CLI version, but we have deprecated v2 of the CodeQL Action and the file no longer populates the latest CLI versions. This change updates to v3.

[Ubuntu] Update default CodeQL major version to v3

---

images/macos/scripts/build/install-common-utils.sh

Users report major degradation in the new version, which prevents many projects from compiling using it. Temporarily pinning the latest stable version until the circumstances are clarified.
- https://github.com/actions/runner-images/issues/11926

[macOS] Pin Cmake to 3.31.6 due to a backward compatibility issue in 4.0

---

images/macos/toolsets/toolset-15.json

Update Xcode to 16.3 release to macOS 15 images.

[macOS]Update Xcode to 16.3 release to macOS15 images.

---

images/windows/scripts/build/Install-Rust.ps1

This PR fixes the Rust issue on Windows 19 and Windows 22.
https://github.com/actions/runner-images/issues/11941

[Windows 19 & Windows 22] Fix Rust issue.

---

images/windows/scripts/build/Install-ChocolateyPackages.ps1
images/windows/scripts/helpers/ChocoHelpers.ps1
images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json
images/windows/toolsets/toolset-2025.json

This PR will pin the cmake version to 3.31.6 on windows image to resolve compatibility issues .

[windows] Pin the cmake version to 3.31.6

---

images/macos/scripts/build/configure-system.sh

Turn back on indexing for macOS-14 and macOS-15.
- https://github.com/actions/runner-images/issues/11921

[macOS] Enable index for macOS-14 and macOS-15

---

README.md

This PR changes the status of Windows-2025 from beta to GA.

[doc] Change Windows-2025 status: beta -> GA

---

images/windows/scripts/docs-gen/SoftwareReport.Tools.psm1
images/windows/scripts/tests/Tools.Tests.ps1
images/windows/toolsets/toolset-2022.json
images/windows/toolsets/toolset-2025.json

This PR updates the DacFx package path for Windows and updates the mysql-cli signature for Windows 22 and 25.
https://github.com/actions/runner-images/issues/12054

[windows] Update DacFx package Path & Mysql cli signature thumbprint

---

images/ubuntu/scripts/build/install-container-tools.sh

This PR fixes an issue with Podman on Ubuntu 22, where it was failing due to a problem with the CNI version. The solution is to install containernetworking-plugins version 1.1.1, which resolves the issue and makes Podman work correctly.

[Ubuntu-22] Fix Podman CNI version issue on Ubuntu 22 by installing containernetworking-plugins 1.1.1

---

images/windows/scripts/build/Install-CodeQLBundle.ps1

Instead of hardcoding the CodeQL Action major version, we now always use the latest major version of CodeQL Action. 

[Windows] Always use the latest major version of CodeQL Action

---

images/ubuntu/scripts/build/configure-apt-sources.sh

Restore search part of search and replace to enable application of `mirror+file:` protocol.
- https://github.com/actions/runner-images/pull/11997#discussion_r2047325056

Fix `mirror+file:` for `ubuntu.sources`

---

images/macos/scripts/build/install-vcpkg.sh

We don't need that workaround at the moment.
#12085

[macOS] Remove stale VCPKG workaround

---

images/macos/scripts/build/install-codeql-bundle.sh

Instead of hardcoding the CodeQL Action major version, we now always use the latest major version of CodeQL Action. 

[macOS] Always use the latest major version of CodeQL Action

---

images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1

Bug fixing
SHA256SUM changed to the value of azure-cosmosdb-emulator-2.14.22-5aad492b.msi downloaded today.

[Windows] Update Install-AzureCosmosDbEmulator.ps1 SHA256Sum

---

images/ubuntu/templates/ubuntu-22.04.pkr.hcl
images/ubuntu/templates/ubuntu-24.04.pkr.hcl
images/windows/templates/windows-2019.pkr.hcl
images/windows/templates/windows-2022.pkr.hcl
images/windows/templates/windows-2025.pkr.hcl

This PR prepare Packer templates that will allow a new image version to be published to an existing shared image gallery.
Also new authentication methods are added.
https://github.com/github/hosted-runners-images/issues/92

Update packer templates with new features

---

images/ubuntu/scripts/build/configure-environment.sh
images/ubuntu/scripts/tests/System.Tests.ps1

We're running on VMs in Azure and the fwupd package is not needed.
Leaving it enable means periodic refreshes show in network traffic and firewall logs.
The current check has a bug, meaning the timer isn't masked. 
In the current `fwupd` version there isn't a `daemon.conf` file present so the `if` condition doesn't run and doesn't mask the systemd unit. 
```
❯ cat /etc/fwupd/daemon.conf                                                                                                                                                             
[bat error]: '/etc/fwupd/daemon.conf': No such file or directory (os error 2)
```
- https://github.com/github/hosted-runners/issues/1377

Bug: Mask `fwupd` timer on ubuntu images

---

images/ubuntu/templates/ubuntu-22.04.pkr.hcl
images/ubuntu/templates/ubuntu-24.04.pkr.hcl
images/windows/templates/windows-2019.pkr.hcl
images/windows/templates/windows-2022.pkr.hcl
images/windows/templates/windows-2025.pkr.hcl

This pull request introduces changes to the `os_disk_size_gb` and `os_type` parameters across multiple Packer template files for both Ubuntu and Windows images. These changes improve flexibility by allowing these values to be configured via variables instead of being hardcoded.

Variabilize several elements in Packer templates

---

images/macos/scripts/tests/Browsers.Tests.ps1
images/macos/templates/macOS-13.arm64.anka.pkr.hcl
images/macos/templates/macOS-14.arm64.anka.pkr.hcl
images/macos/templates/macOS-15.arm64.anka.pkr.hcl

1.Add Mozila Firfox to macOS 13,14 and 15 arm64 images.
2. User raised public [issue 12049](https://github.com/actions/runner-images/issues/12049)

[macOS]Add Mozila Firfox to macOS 13,14 and 15 arm64 images.

---

images/macos/toolsets/toolset-15.json

Removing Xcode15.4 from macOS15 images.
Announcement ticket issue - https://github.com/actions/runner-images/issues/12195

[macOS] Removing Xcode15.4 from macOS15 images

---

images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json

A recent PR, removes VCRedist 17 as a part of PostgreSQL Installation.
Still mention into toolsets for Windows Server 2019 and 2022.
[Windows] Update AzureCosmosDbEmulator signature and Removing VSredist 17 installation in Postgresql #12247
#12265
- [!] Tests are written (if applicable)
- [!] Documentation is updated (if applicable)

[Windows] Update Toolsets for Windows Server 2019 and 2022 after PR merged #12247

---

images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json

This PR removes Ruby 3.0 and sets Ruby 3.3 as the default version.
https://github.com/actions/runner-images/issues/12033

[Windows 19 & Windows 22]Removing Ruby 3.0 and making 3.3 as a default version.

---

images/ubuntu/toolsets/toolset-2204.json

This PR updates the default Node.js version to 20 for Ubuntu 22.
https://github.com/actions/runner-images/issues/12143

[Ubuntu 22] Update Node.js version 20 as the default.

---

images/windows/toolsets/toolset-2022.json

This PR updates the default Node.js version to 20 for Windows 22.
https://github.com/actions/runner-images/issues/12034

[Windows 22] Update Node.js version 20 as the default.

---

.github/workflows/create_sbom_report.yml

Bug fixing
Downgraded Syft to version v1.24.0 for macOS platforms  in the SBOM generation workflow to avoid indefinite hangs caused by privilege prompts in newer versions (e.g., v1.26.0).
The downgrade is scoped only to runner.os == 'macOS', and Windows/Linux runners will continue using the latest available Syft version.No other workflow logic is changed.

SBOM Issue: SYFT downgraded to 1.24.0

---

images/ubuntu/toolsets/toolset-2204.json
images/ubuntu/toolsets/toolset-2404.json

This PR updates the Maven version from 3.9.9 to 3.9.10. Maven 3.9.9 is no longer available in the official Maven repository and results in a 404 error during builds. Upgrading to 3.9.10 resolves this issue and Image generation issue.
https://github.com/actions/runner-images/issues/12334

[Ubuntu] Update Maven to 3.9.10 to fix 404 error.

---

.github/workflows/windows2025.yml

The job name for `windows-2025` CI incorrectly says `Windows_2022`, which is corrected by this PR.

[Windows-2025] Correct job name

---

images/ubuntu/toolsets/toolset-2204.json
images/ubuntu/toolsets/toolset-2404.json

This PR updates the docker-compose version to 2.36.2 in Ubuntu 22.04 and 24.04

[Ubuntu] Updated docker-compose to 2.36.2

---

images/macos/toolsets/toolset-15.json

Adding new Xcode 26.0 Beta 1 to macOS-15 arm64-based aka `macos-15` in GitHub Actions
- https://github.com/actions/runner-images/issues/12355

[macOS] Add Xcode 26 beta 1 without runtimes on macOS-15-arm64 image

---

images/windows/scripts/build/Install-AzureCosmosDbEmulator.ps1
images/windows/scripts/build/Install-WSL2.ps1
images/windows/scripts/helpers/InstallHelpers.ps1

This Pr will 
1. Set $ProgressPreference = 'SilentlyContinue' in helper script to clean up console output
2. Removed checksum verification for WSL2 and Azure CosmosDB emulator setups to simplify installation

[windows] Suppress Progress Output and Disable Checksum Verification

---

images/ubuntu/scripts/helpers/Common.Helpers.psm1

This PR replaces usage of the `WebClient` class with PowerShell’s native `Invoke-WebRequest` cmdlet.
https://learn.microsoft.com/en-us/dotnet/api/system.net.webclient?view=net-9.0#remarks

[Ubuntu] Replace WebClient with Invoke-WebRequest

---

images/windows/scripts/build/Install-Git.ps1

Remove extraneous spaces between key types to fetch. The Windows image has only the RSA key for github[.]com in file "C:\Program Files\Git\etc\ssh\ssh_known_hosts". This PR removes spaces in the list of key types so that neither ecdsa nor ed25519 are interpreted as hostnames

[windows] Fix syntax of ssh-keyscan

---

images/windows/scripts/build/Configure-System.ps1

This pull request enables inheritance for the entire `C: drive in the Windows-2025 image.
https://github.com/github/c2c-actions-support/issues/4894

[Windows-2025] Enable permission inheritance for the C: drive

---

images/windows/scripts/build/Install-AWSTools.ps1
images/windows/scripts/build/Install-AzureCli.ps1
images/windows/scripts/build/Install-BizTalkBuildComponent.ps1
images/windows/scripts/build/Install-Chocolatey.ps1
images/windows/scripts/build/Install-Chrome.ps1
images/windows/scripts/build/Install-CloudFoundryCli.ps1
images/windows/scripts/build/Install-DACFx.ps1
images/windows/scripts/build/Install-EdgeDriver.ps1
images/windows/scripts/build/Install-Firefox.ps1
images/windows/scripts/build/Install-GoogleCloudCLI.ps1
images/windows/scripts/build/Install-MongoDB.ps1
images/windows/scripts/build/Install-MysqlCli.ps1
images/windows/scripts/build/Install-PostgreSQL.ps1
images/windows/scripts/build/Install-SQLOLEDBDriver.ps1
images/windows/scripts/build/Install-SQLPowerShellTools.ps1
images/windows/scripts/build/Install-VisualStudio.ps1
images/windows/scripts/build/Install-WDK.ps1
images/windows/scripts/build/Install-WebPlatformInstaller.ps1
images/windows/scripts/build/Install-WinAppDriver.ps1
images/windows/scripts/helpers/ImageHelpers.psm1
images/windows/scripts/helpers/InstallHelpers.ps1
images/windows/scripts/helpers/VisualStudioHelpers.ps1
images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json
images/windows/toolsets/toolset-2025.json

This PR switches verification of authenticode signature to use the certificate subject instead of the thumbprint. This prevents  occasional verification failures caused by certficate renewal.

Validate authenticode signature using the certificate Subject

---

images/windows/toolsets/toolset-2022.json

>Strawberry Perl is a perl environment for MS Windows containing all you need to run and develop perl applications. It is designed to be as close as possible to perl environment on UNIX systems.
* Update `strawberryperl` from `5.32.1.1` -> `5.40.2.2`
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases

[Windows 2022] Update `strawberryperl` to `5.40.2.2`

---

images/ubuntu/scripts/tests/Tools.Tests.ps1

Current Ninja pester tests implementation might fail when run sequentially from elevated and non-elevated prompts.
This PR adds test cleanup

[ubuntu] Update Ninja pester test

---

README.md
images/windows/Windows2019-Readme.md

Reverts actions/runner-images#12519, fix link
Let's keep doc available for customers until decommission. 
ADO deprecation date: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=windows-images%2Cyaml#windows-server-2019-hosted-image-deprecation-schedule

Revert "Remove W19 readme"

---

images/ubuntu/scripts/build/install-git.sh

- Install git version `2.50.1`
- Install it from ppa candidate repo

chore: Add ppa candidate repo to install 2.50.1 version of git

---

images/ubuntu/scripts/build/install-kubernetes-tools.sh

This PR will enhances the installation process by:
1. Adding retry logic to curl commands for better reliability
2. Ensuring /etc/apt/keyrings directory exists before storing GPG keys

[Ubuntu] Improve kubectl installation script with retry logic and keyring checks

---

images/ubuntu/scripts/build/install-microsoft-edge.sh
images/ubuntu/toolsets/toolset-2204.json
images/ubuntu/toolsets/toolset-2404.json
images/windows/scripts/build/Install-EdgeDriver.ps1

- This PR will updates the url of edgedriver from msedgedriver.azureedge.net to msedgedriver.microsoft.com  in both ubuntu and Windows images.
- Maven version to 3.9.11 in Ubuntu images
https://github.com/actions/runner-images/issues/12597

[Ubuntu, Windows] Update edgedriver URL and maven version on ubuntu

---

images/macos/scripts/build/install-edge.sh

1. Update Microsoft Edge WebDriver URL for intel macOS images.

[macOS] Update edgedriver URL for intel macOS images.

---

images/ubuntu/scripts/build/install-kotlin.sh
images/ubuntu/scripts/tests/Tools.Tests.ps1

This PR will update Kotlin to latest for Ubuntu 
Running `kotlinc-js -help` confirms that the Kotlin/JS CLI tool is installed and accessible.

[Ubuntu] Upgrade Kotlin to latest

---

images/windows/scripts/tests/Tools.Tests.ps1
images/windows/toolsets/toolset-2022.json
images/windows/toolsets/toolset-2025.json

This PR will update Kotlin to latest for windows images 
Running `kotlinc-js -help` confirms that the Kotlin/JS CLI tool is installed and accessible.

[Windows] Update Kotlin to latest

---

images/macos/scripts/build/install-common-utils.sh
images/macos/scripts/tests/BasicTools.Tests.ps1

1. Pin kotlin to latest version(2.2.0)
2. Replaced -version with -help in a test case due to disabled version output for the compiler without a compilable target.

[macOS] Pin kotlin to latest version(2.2.0)

---

images/ubuntu/toolsets/toolset-2204.json
images/ubuntu/toolsets/toolset-2404.json

Fix regression from introducing a breaking change causing stalled docker compose builds with bake used by default.
No version in v2.37 branch is usable.
The issue seems to be fixed in v2.38.0 proper.
I've picked v2.38.2 as the most conservative version having the most fixes added, while not upgrading past v2.39 for new functionality at the same time.
Tested on stalled CI by upgrading with setup action to confirm resolving the regression. See issue for details, STR, logs and upstream tickets.

[Ubuntu] Upgrade docker-compose to fix build regression

---

images/macos/toolsets/toolset-15.json

Adding a variable "filename" to toolset-15.json file as Xcode26 beta 5 on "VendorOS workflow" is causing the vendor-toolset workflow to fail.

[macOS] Adding a variable "filename" to toolset-15.json file

---

images/macos/toolsets/toolset-15.json

Sumulator runtimes and devices are available again for Xcode 26 beta on Intel-based macOS-15. 🎉

[macOS] Directly install Xcode 26 beta simruntimes

---

images/ubuntu/templates/build.ubuntu-22_04.pkr.hcl
images/ubuntu/templates/build.ubuntu-24_04.pkr.hcl

This pull request makes a minor adjustment to the build process for Ubuntu images by increasing the pause before executing a shell provisioner script. This change gives the system more time to stabilize before running cleanup operations.

[ubuntu] Adjust provisioner pause after reboot

---

images/windows/scripts/build/Install-MongoDB.ps1

Mongo documentation structure has changed for `v5.0*` and `v6.0*`.
This PR updates Uri used for parsing latest patch version

[windows] Update uri for mongo releases

---

images/macos/toolsets/toolset-15.json
images/macos/toolsets/toolset-26.json

New Xcode was released. Delivering with runtimes.
https://github.com/actions/runner-images/issues/12991

[macOS] Update Xcode 26 to 26.0 Release

---

images/macos/scripts/build/install-rust.sh
images/ubuntu/scripts/build/install-rust.sh
images/windows/scripts/build/Install-Rust.ps1

Initially reported issue highlights upcoming breaking change. Let's pin current version until some information on that behaviour provided in the developers repo: https://github.com/rust-lang/rust/issues/145936
https://github.com/actions/runner-images/issues/13041

[all OSs] Pin Rust to 1.89.0 due to a 1.90.0 breaking change

---

images/ubuntu/scripts/build/install-ruby.sh

This PR updates Ruby installation script for ubuntu images according to the release management changes in https://github.com/ruby/ruby-builder

[ubuntu] Update Ruby installer

---

images/macos/scripts/build/install-rust.sh
images/ubuntu/scripts/build/install-rust.sh
images/windows/scripts/build/Install-Rust.ps1

Reverts actions/runner-images#13044

Revert "[all OSs] Pin Rust to 1.89.0 due to a 1.90.0 breaking change"

---

images/windows/scripts/docs-gen/Generate-SoftwareReport.ps1
images/windows/scripts/tests/ChocoPackages.Tests.ps1
images/windows/toolsets/toolset-2025.json

This PR adds InnoSetup to windows 2025 image.
https://github.com/actions/runner-images/issues/12947

[Windows 2025] Add InnoSetup.

---

images/windows/toolsets/toolset-2019.json
images/windows/toolsets/toolset-2022.json
images/windows/toolsets/toolset-2025.json

- Push MinGW version to 14.* for Windows 2022
- Push MinGW version to 15.* for Windows 2025
- Disable Kotlin pinning notification for Windows 2019
https://github.com/actions/runner-images/issues/13097

[Windows] Update MinGW on 2022 and 2025, disable alert for 2019

---

images/ubuntu/templates/source.ubuntu.pkr.hcl
images/ubuntu/templates/variable.ubuntu.pkr.hcl

This pull request introduces a new configuration option to the Ubuntu image build process, allowing control over whether SSH authorized keys are cleared during image creation.

[Ubuntu] Add ssh_clear_authorized_keys to Packer template
