actions/runner-images

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/tool-request.md
README.md

https://github.blog/changelog/2019-11-06-github-actions-macos-virtual-environment-updated-to-catalina

Update macOS 10.14 to 10.15

---

images/win/scripts/Installers/Windows2019/Install-VS2019.ps1

Visual Studio 2019 moves the merge modules to an individual component.  They are deprecated in this release, but are still required to build MSI installers for applications built using Visual C or C++.
[Appveyor had a similar issue and fixed it about a month ago; see https://github.com/appveyor/ci/issues/3175]

Add Visual Studio 2019 VC redist merge modules

---

images/win/Windows2019-Azure.json

Validate-SQLPowerShellTools was missing from VS2019 on WS2019 template, original from @ryanspletzer

Add Validate-SQLPowerShellTools to VS2019 on WS2019 template

---

images/linux/scripts/installers/java-tools.sh

Because https://github.com/actions/virtual-environments/commit/1dcd276b1e42aaa2ee3c45707fca988e902263db removed the changes from https://github.com/actions/virtual-environments/pull/133

Update Maven to 3.6.3 (again)

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/tool-request.md
.github/workflows/issue-triager.yml
triage-rules.yml

This is a first pass at adding an issue triager. It relies on the person filing the issue to provide an area and type (e.g. bug, question, feature). It will then apply area and type labels and try to assign it to the correct owner.

Add a triager and update issue templates

---

images/linux/scripts/installers/1604/php.sh
images/linux/scripts/installers/1804/php.sh

As originally submitted by @ropnop in #152 (I'm just cherry-picking his change into a clean branch):
This addresses #146
The SHA384 hash of the composer-setup.php script is hardcoded in the build script for the Ubuntu images. This means that whenever the install script is updated, the entire packer build fails and errors out on that step.
According to this page from Composer, the better way is to fetch the latest signature dynamically and compare it against the downloaded installer file.
I modified the php steps slightly to compare the hash against the latest official one from https://composer.github.io/installer.sig
Let me know if you think this is the best approach. The other approach would be to pin the installer to a specific hash and then downloading it by reference like …

compare php composer against latest signature

---

images/win/scripts/Installers/Windows2019/Install-WDK.ps1
images/win/scripts/Installers/Windows2019/Validate-WDK.ps1

As described by @christopherco in original PR:
When building Windows Drivers in the pipeline, SDK and WDK versions must match. The VS2019 updates the SDK to 1903, so WDK needs to also update to 1903 (10.0.18362.0 version)
Fixes #157

Update to WDK 1903 in VS2019 image

---

images/linux/scripts/installers/google-chrome.sh
images/linux/scripts/installers/java-tools.sh

In this PR we've extended `images/linux/scripts/installers/google-chrome.sh` script in order to install Chromedriver compatible with installed Google Chrome version and latest stable selenium-server-standalone version

Install Google Chrome, Chromedriver and Selenium

---

images/linux/scripts/installers/1804/basic.sh

It's duplicate on https://github.com/actions/virtual-environments/blob/fef47980696fd0fa4f0d013c18618544d27c4e38/images/linux/scripts/installers/1804/basic.sh#L13-L14

Remove duplicate install curl on linux 18.04

---

helpers/GenerateResourcesAndImage.ps1
images/linux/Ubuntu1604-README.md
images/linux/Ubuntu1804-README.md
images/linux/config/ubuntu1604.conf
images/linux/config/ubuntu1804.conf
images/linux/scripts/installers/1604/preparemetadata.sh
images/linux/scripts/installers/1804/preparemetadata.sh
images/win/Windows2016-Readme.md
images/win/Windows2019-Readme.md
images/win/scripts/Installers/Windows2016/Initialize-VM.ps1
images/win/scripts/Installers/Windows2019/Initialize-VM.ps1

Found a few "hosted" usages that were ambiguous in the current context so I decided to remove them for clarity. Also cleaned up one usage of the previous repo name that could cause confusion.

Fix usage of ambiguous hosted term in readmes and scripts.

---

images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/win/Windows2016-Azure.json

Added sensitive-variables spec to ubuntu16, ubuntu18, and Windows 2016 to make sure those don't get ouptut to logs inadvertently.

Add secret variables to sensitive-variables array.

---

images/macos/macos-10.15-Readme.md

macOS Catalina **10.15.2 (19C57)**
- Xcode 11.3(11C29)
- Python 3.7.6
- Node.js v12.14.0
- NPM 6.13.4
- Git: git version 2.24.1
- Git LFS: git-lfs/2.9.2 (GitHub; darwin amd64; go 1.13.5)
- Homebrew 2.2.2
- CMake 3.16.2
- xctool 0.3.7
- Bundler version 2.1.3
- App Center CLI 2.3.3
- fastlane 2.139.0
- Yarn 1.21.1
- azure-cli 2.0.78
- Go 1.13.5
- NVM - Installed node versions:
- v8.17.0 
- v10.18.0 
- v12.14.0 
- v13.5.0 
- GNU parallel 20191222
- Google Chrome 79.0.3945.88 
- ChromeDriver 79.0.3945.36
- Android Emulator 29.3.2
Xamarin:
- Visual Studio for Mac: 8.3.11.1

macOS 10.15 software updates week2

---

images/win/scripts/Installers/Install-DotnetSDK.ps1

Adding it as otherwise this will be a sudden break for customers. The plan is eventually remove if after a grace period.

Explicitly adding back 2.2 eol channel for .net core

---

README.md

This reverts commit 3ac3a7dd44921a04a724b3996120c7b03c1b1daa so that readme links from badges are loaded from release branches instead of pointing to master.

Revert "Update badges to point to README's in master for now"

---

images/linux/scripts/installers/google-chrome.sh
images/win/scripts/Installers/Install-Selenium.ps1

This PR related to the #242 issue.
We have removed selenium jar from the `CLASSPATH` and declared new environment variable `SELENIUM_JAR_PATH` in order to give the client an ability to specify selenium in `-classpath` parameter of `java` command in order to run selenium tests

Remove selenium from the CLASSPATH env variable

---

images/win/scripts/Installers/Install-Git.ps1

Especially the mingw folder conflicts with other mingw installs. I don't think installing git should put a compiler on the PATH, especially since the Windows virtual environment by default already has a separate chocolatey mingw installed (at least according to the documentation).
I'm not sure why the \bin and \usr\bin paths are put on the PATH manually since that should already be done by chocolatey so I removed those as well. Any pointers on how I can actually test these changes would be appreciated (the link to setting up an azure in the contributing docs gives a 404).

Don't bloat the PATH when installing git

---

images/linux/scripts/installers/1804/basic.sh

In #204, a duplication curl install call was removed. Since then, the builds are failing unable to find curl during verification. Switching to the end to make sure it's there.

Move installation of curl in ubuntu18 to last

---

images/linux/Ubuntu1604-README.md
images/linux/Ubuntu1804-README.md
images/linux/scripts/installers/clang.sh

Issue:
https://github.com/actions/virtual-environments/issues/260
Fix:
Escape ~

Fix incorrect display Clang 6.0 version in Ubuntu-README.md

---

images/linux/scripts/installers/google-chrome.sh

In scope of this Pull Request we've fixed [this bug](https://github.com/actions/virtual-environments/issues/262)

Add ChromeWebDriver env variable on Ubuntu

---

images/macos/macos-10.15-Readme.md

Software updates:
- Node.js v12.14.1
- NVM v8.17.0 *,v10.18.0 *,v12.14.0
- .NET SDK  3.1.100 3.1.101
- Go 1.13.6
- Bundler version 2.1.4
- Curl 7.68.0
- Git: 2.25.0
- gpg (GnuPG) 2.2.19
- Fastlane 2.140.0
- Azure CLI 2.0.80
- Google Chrome 79.0.3945.117 
- ChromeDriver 79.0.3945.36
- macOS toolcache Python 2.7.17 3.5.9 3.6.10 3.7.6 3.8.1
- macOS toolcache Ruby 2.4.9 2.5.7 2.6.5
- Android Emulator 29.3.4  
Xamarin:
- Visual Studio for Mac 8.4.0.2657
- Mono 6.6.0.155
- Xamarin.iOS 13.8.3.0
- Xamarin.Mac 6.8.3.0
- Xamarin.Android 10.1.1

macOS 10.15 software updates week 3

---

images/win/scripts/Installers/Install-Git.ps1

In #211  the `C:\Program Files\Git\bin` was removed from the `PATH`. This folder contains a lot of bash tools such as `find` and its removing makes all these tools unreachable from `bash`(#263 ). 
Despite the assumption that `choco` must add this folder t the `PATH` while installing `git` - it was not done automatically so we have to add this folder to `PATH` manually.

Put necessary directories to the PATH

---

images/macos/macos-10.15-Readme.md

- Java 1.7: (Zulu 7.36.0.5-CA-macosx) (build 1.7.0_252-b10)
- Java 1.8: (Zulu 8.44.0.9-CA-macosx) (build 1.8.0_242-b20) (default)
- Java 11: Zulu11.37+17-CA (build 11.0.6+10-LTS)
- Java 13: Zulu13.29+9-CA (build 13.0.2+6-MTS)
- Rust 1.40.0
- Homebrew 2.2.4
- Rustup 1.21.1
- RubyGems 3.1.2
- Gradle 6.1
- Git: 2.25.0
- gpg (GnuPG) 2.2.19
- Azure CLI 2.0.80
- Google Chrome 79.0.3945.130 
- 8.4.1.4
- 13.10.0.17
- 6.10.0.17
- 10.1.3
| Version                        | Build                          | Path                           |
| ------------------------------ | ------------------------------ | ------------------------------ |
| 11.3.1                         | 11C505                         | /Applications/Xcode_11.3.1.app |
- Nomad CLI 3.1.2

macOS 10.15 software updates week 4

---

README.md
help/CreateImageAndAzureResources.md
helpers/GenerateResourcesAndImage.ps1

- add docs page for image generation
- help page was moved from [here](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/help/CreateImageAndAzureResources.md) (I think that the file was lost after migration to virtual environments, that is why I returned it back).
- pass GitHub access token to script `helpers/GenerateResourcesAndImage.ps1`

Update docs and pass GitHub token

---

images/win/Windows2019-Azure.json

The Windows Server 2019 has less than 10GB left in C: after the current rollout, we need to increase the disk size.

Upsize Win19 to 256 GB

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/Windows2019-Readme.md
images/win/scripts/Installers/Download-ToolCache.ps1
images/win/scripts/Installers/Validate-Boost.ps1
images/win/scripts/Installers/Validate-ToolCache.ps1
images/win/toolcache-2016.json
images/win/toolcache-2019.json

This PR switch Windows2016, Windows2019 toolcache provisioner to use Github Actions NPM registry. 
**Additional:**
- Issue https://github.com/actions/virtual-environments/issues/74 was fixed
- Toolcache provisioner for windows was improved
- Windows Toolcache tests are improved
- Boost 1.72 - msvc 14.1 added to Win2016
- Boost 1.72 - msvc 14.2 added to Win2019

Switch Windows hostedtoolcache provisioner to GitHub Actions NPM registry

---

images/win/scripts/Installers/Validate-AzureModules.ps1

```
==> vhd: Provisioning with powershell script: C:\agent1\_work\225\s\images\win/scripts/Installers/Validate-AzureModules.ps1
==> vhd: At C:\Windows\Temp\script-5e1dc318-9b9d-d017-fea0-68186c6d47f4.ps1:70 char:5
==> vhd: +     }
==> vhd: +     ~
==> vhd: Unexpected token '}' in expression or statement.
==> vhd: At C:\Windows\Temp\script-5e1dc318-9b9d-d017-fea0-68186c6d47f4.ps1:71 char:1
==> vhd: + }
==> vhd: + ~
==> vhd: Unexpected token '}' in expression or statement.
==> vhd:     + CategoryInfo          : ParserError: (:) [], ParseException
==> vhd:     + FullyQualifiedErrorId : UnexpectedToken
```

fix(Validate-AzureModules): additional line in description fixes terminator character issues

---

images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

According to https://github.com/actions/virtual-environments/issues/268, we have modified Ubuntu 16/18 images for adding the [DefaultLimitNOFILE=50000] setting to /etc/systemd/system.conf.
This setting will be used in non-interactive sessions for increasing the max open files limit

Increase max number of open files

---

images/linux/scripts/installers/mysql.sh

We have several complaints about libmysqlclient-dev installation on Ubuntu images. 
https://github.com/actions/virtual-environments/issues/337
https://github.com/microsoft/azure-pipelines-image-generation/issues/1410
This happens when MySQL version is superseded in ubuntu repositories, but we still have an older one on the deployed VM and it requires the same outdated libmysqlclient-dev version, which is no longer available via apt-get.
The solution is to install libmysqlclient-dev during image generation to have the same versions of packages at the end of the build. 
Changes:
- Add libmysqlclient-dev installation to MySQL Client installation script

Add libmysqlclient-dev installation on Ubuntu

---

images/win/scripts/Installers/Install-SeleniumWebDrivers.ps1

Fixes #351, related to #338.
Here is a fix for some doubled `\` in `Install-SeleniumWebDrivers.ps1` that make `Validate-SeleniumWebDrivers.ps1` to fail.

Fix SeleniumWebDrivers error

---

images/win/scripts/Installers/Windows2016/Initialize-VM.ps1
images/win/scripts/Installers/Windows2019/Initialize-VM.ps1

Issue:
Unable to install chocolatey - The request was aborted: Could not create SSL/TLS secure channel.
Fix:
Enable Tls1.2.

Fixing chocolatey installation

---

images/linux/scripts/installers/haskell.sh

Fixes https://github.com/actions/setup-haskell/issues/6 by adding [GHC 8.8.2](https://www.haskell.org/ghc/blog/20200116-ghc-8.8.2-released.html) to the virtual environment so that https://github.com/actions/setup-haskell can select this version.

Include ghc version 8.8.2

---

images/linux/scripts/installers/dpkg-config.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

Issue:
[apt-get install may ask questions and hang](https://github.com/actions/virtual-environments/issues/122)
As example `splapd` requests by default from the user during installation and block pipeline:
Fix:
1. Suppress requests for information during package configuration
Debian packages can request information from the user during installation in order to generate customised configuration files. The preferred method for doing this is through the configuration management protocol provided by DebConf. One of the benefits of DebConf is that it provides a central point of control over how and whether any questions are asked.
The required effect in this instance can be obtained by setting the environment variable DEBIAN_FRONTEND to the value noninteractive
`export …

Fix unattended installation some packages

---

images/macos/macos-10.15-Readme.md

- System Version: macOS 10.15.3 (19D76)
- Kernel Version: Darwin 19.3.0
- Java 1.8: (Zulu 8.44.0.11-CA-macosx) (build 1.8.0_242-b20) (default)
- Rust 1.41.0
- NVM - Cached node versions: v6.17.1 v8.17.0 v10.18.1 v12.14.1 v13.7.0
- PowerShell 6.2.4
- Go 1.13.7
- Gradle 6.1.1
- Git LFS: 2.10.0
- GNU parallel 20200122
- Fastlane 2.141.0
- Cmake 3.16.3
- Microsoft Edge 79.0.309.71 
- MSEdgeDriver 79.0.309.71
- 2.7.17
- 8.4.3.12
- Android SDK Build-Tools, Revision 29.0.3

macOS 10.15 software updates week 6

---

images/linux/scripts/installers/1604/dotnetcore-sdk.sh
images/linux/ubuntu1604.json

According to https://github.com/actions/virtual-environments/issues/353, dotnetcore-sdk.sh has been modified.
Addition of extra repository 'microsoft-ubuntu-bionic-prod' has been removed from this script (right microsoft package already is added through repos.sh script), because it impacted to PowerShell Core installation and build has been broken
After this modification Ubuntu16 build is successful.

Ubuntu16 build has been fixed

---

images/linux/scripts/installers/1804/dotnetcore-sdk.sh

Issue:
[Segmentation fault (core dumped) - NetCore 3.0 ](https://github.com/dotnet/core/issues/3620) - Segmentation fault    (core dumped) dotnet new [Ubuntu 18.04]
Fix:
Set DOTNET_CLI_TELEMETRY_OPTOUT=1 before installing

Disable telemetry before dotnet installation to prevent Segmentation fault

---

images/linux/scripts/installers/1604/php.sh
images/linux/scripts/installers/1804/php.sh

Composer's path to global executable modules: `~/.config/composer/vendor/bin` 
Adding this path to $PATH variable allow to invoke these modules without full path.
Issue: [#118](https://github.com/actions/virtual-environments/issues/118)

Added path to installed global modules of composer to $PATH

---

images/macos/macos-10.15-Readme.md

Software updates:
- Clang/LLVM 9.0.1
- gcc-8 (Homebrew GCC 8.3.0_2) 8.3.0
- gcc-9 (Homebrew GCC 9.2.0_3) 9.2.0
- GNU Fortran (Homebrew GCC 8.3.0_2) 8.3.0
- GNU Fortran (Homebrew GCC 9.2.0_3) 9.2.0
- Node.js v12.15.0
- NVM - Cached node versions: v6.17.1 v8.17.0 v10.19.0 v12.15.0 v13.8.0
- PHP 7.4.2
- Homebrew 2.2.5
- Yarn 1.22.0
- psql (PostgreSQL) 12.1
- aria2 1.35.0
- azcopy 10.3.4
- Azure CLI 2.0.81
- Google Chrome 80.0.3987.87 
- ChromeDriver 80.0.3987.16
- Microsoft Edge 80.0.361.48 
- MSEdgeDriver 80.0.361.48
- Visual Studio for Mac 8.4.4.91
- Xcode 11.4 beta(11N111s)

macos 10.15 software updates week 7

---

images/linux/scripts/installers/1604/basic.sh
images/linux/scripts/installers/1804/basic.sh

According to https://github.com/actions/virtual-environments/issues/275, tk library installation has been added to Ubuntu 16/18.
This library is used for correct tkniter work in Ubuntu.

tk installation has been added to Ubuntu 16/18 basic.sh

---

images/win/scripts/Installers/Install-Git.ps1

This is a quick fix for issue https://github.com/actions/virtual-environments/issues/282
In [#211](https://github.com/actions/virtual-environments/pull/211) C:\Program Files\Git\usr\bin was removed from the PATH caused to using [Windows tar](https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/)(C:\Windows\System32\tar.exe) instead of the tar comes along with Git. Windows doesn't have xz support by default, tries to use mingw xz utility and hangs.
Changes:
- Restore `"C:\Program Files\Git\usr\bin"` in the PATH, until MSYS2 is added(https://github.com/actions/virtual-environments/issues/30)

Restore Git bash utilities to the PATH

---

images/win/Windows2019-Azure.json
images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Windows2019/Install-WDK.ps1
images/win/scripts/Installers/Windows2019/Validate-WDK.ps1
images/win/scripts/Installers/Windows2019/Validate-Wix.ps1

We have several issues related to WDK:
https://github.com/actions/virtual-environments/issues/259
https://github.com/actions/virtual-environments/issues/428
The root cause is an incorrect installation order - WDK is supposed to be installed after VS19, not before so that the extension can be added to VS.
Changes:
- Installation order changed
- Try-catch on package installation added in order to break the build if the package is not installed
- Validate-WDK script works properly now, previously it's just put hardcoded value to the softwarelist(the same can be done for windows16 if needed)
- Get-VS19ExtensionVersion function created to use it in both Validate-WDK and Validate-Wix scripts

WDK installation fix for win19

---

images/win/scripts/Installers/Windows2016/Install-VS2017.ps1
images/win/scripts/Installers/Windows2019/Install-VS2019.ps1

This PR fixes issue https://github.com/actions/virtual-environments/issues/363 and it adds .NET framework 4.7.2 SDK, Targeting Pack and Developer tools as visual studio components to VS17 and VS19

Add dotnet 4.7.2 developer tools

---

images/macos/macos-10.15-Readme.md

- Node.js v12.16.0
- NVM - Cached node versions: v6.17.1 v8.17.0 v10.19.0 v12.16.0 v13.8.0
- Ruby 2.7.0p0
- Go 1.13.8
- Homebrew 2.2.6
- Gradle 6.2
- Cmake 3.16.4
- Google Chrome 80.0.3987.106 
- ChromeDriver 80.0.3987.106
- Microsoft Edge 80.0.361.54 
- MSEdgeDriver 80.0.361.54
- Mozilla Firefox 73.0
- geckodriver 0.26.0
- 8.4.5.19

macOS sofware updates week 8

---

images/win/scripts/Installers/Install-NodeLts.ps1

For feedback ticket: https://developercommunity.visualstudio.com/content/problem/815166/cannot-find-module-node-sass-on-npm-build.html

Install node-sass module since it doesn't come with Node anymore

---

images/linux/scripts/installers/1804/powershellcore.sh

libicu64, which comes with php-intl module, has powershell breaking issue:https://github.com/PowerShell/PowerShell/issues/9746
As a workaround, this library was removed, but php-intl modules were also removed. The following issue has been received as a result.
https://github.com/actions/virtual-environments/issues/432
Changes:
- Install new libicu version 6.5 where the breaking issue is fixed

Restore ubuntu 18 php-intl installation

---

images/win/scripts/Installers/Validate-DACFx.ps1

There is [a complaint](https://github.com/actions/virtual-environments/issues/413) that Microsoft SQL Server Express is not mentioned in the readme.
This PR simply adds SqlLocalDb path to the SoftwareMd file.

Add SqlLocalDb to windows19 readme file

---

images/linux/scripts/installers/azure-cli.sh
images/linux/scripts/installers/azure-devops-cli.sh

Issue:
Once an extension is installed, it's found under the value of the `$AZURE_EXTENSION_DIR` shell variable. If this variable is unset, by default the value is `$HOME/.azure/cliextensions` on Linux and macOS. After image build is successfully finished, user profile is deleted with `.azure/cliextensions ` and we don't have any azure-cli extensions on an image.
Fix:
Define `AZURE_EXTENSION_DIR` set up to `/opt/az/azcliextensions` (default azure-cli folder) as global for all users
```
~$ az -v
azure-cli                          2.1.0
command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4
Extensions:
azure-devops                      0.17.0
Python location '/opt/az/bin/python3' …
```

Fix Azure CLI DevOps installation on Ubuntu images

---

images/win/scripts/Installers/Install-JavaTools.ps1

Updating Maven from 3.6.2 to 3.6.3 to resolve a bug with detecting maven extensions.  Related to #132.

Updated maven from 3.6.2 to 3.6.3

---

images/win/scripts/Installers/Install-DotnetSDK.ps1

Addition to https://github.com/actions/virtual-environments/pull/444
Remove 3.1.102 from the releases list.

[Windows] Disable .net SDK 3.1.102 installation part 2

---

images.CI/azure-pipelines/image-generation.yml
images.CI/azure-pipelines/ubuntu1604.yml
images.CI/azure-pipelines/ubuntu1804.yml
images.CI/azure-pipelines/windows2016.yml
images.CI/azure-pipelines/windows2019.yml
images.CI/create-release.ps1
images/win/Windows2016-Readme.md

This PR adds `images.CI` folder in the root of repository. This folder contains set of scripts and yml files to run image generation builds in Azure DevOps CI.
Builds will be run on `https://dev.azure.com/github/virtual-environments`

Add Images.CI for Windows and Ubuntu images (Azure DevOps)

---

images/macos/macos-10.15-Readme.md

- Node.js v12.16.1
- NVM - Cached node versions: v6.17.1 v8.17.0 v10.19.0 v12.16.1 v13.9.0
- .NET SDK 2.0.0 3.0.100 3.0.101 3.0.102 3.0.103 3.1.100 3.1.101
- PHP 7.4.3
- GNU parallel 20200222
- psql (PostgreSQL) 12.2
- Fastlane 2.142.0
- Azure CLI 2.1.0
- Google Chrome 80.0.3987.122 
- Microsoft Edge 80.0.361.57 
- MSEdgeDriver 80.0.361.57
- Mozilla Firefox 73.0.1
- geckodriver 0.26.0
- 8.4.6.36
| Version                           | Build                             | Path                              |
| --------------------------------- | --------------------------------- | --------------------------------- |
| 11.4 (beta 2)                       | 11N123k                           | /Applications/Xcode_11.4_beta.app |
| Package Name                                | Description …

macOS Catalina 10.15.3  sofware updates week 9

---

images/win/scripts/Installers/Install-AzureModules.ps1
images/win/scripts/Installers/Validate-AzureModules.ps1

Add Az 3.5.0 Modules to Windows Server 2016/2019 images. Customer request -  https://github.com/actions/virtual-environments/issues/440
1. Can we remove old versions?
No. This can break existing customers who has written there scripts based on the old AzurePS commands and using that specific version in the task.
2. Can we change default versions?
There are breaking changes between V2.1.0 and V5.13.0, V6.13.1. There are many third party custom tasks that may have taken dependency on V2.1.0 which will break if we change the default version.

Add Az 3.5.0 PowerShell module to Windows Server 2016/2019

---

images/linux/scripts/installers/rust.sh
images/linux/scripts/installers/updatepath.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

Customers requested to add  .dotnet and php composer default folders to the PATH to eliminate manual update `PATH` environment variable to the workflows.
Fix add updatepath.sh  script to update all paths at the single place:
1. `/home/runner/.dotnet/tools` - customer request https://github.com/actions/virtual-environments/issues/213
2. `/home/runner/.config/composer/vendor/bin` -  customer request https://github.com/actions/virtual-environments/issues/118
3. move ${CARGO_HOME} from `rust.sh` to `updatepath.sh`
PS. `/home/runner` - is the $HOME folder for `runner` user under that user all builds run.

Update PATH environment variable to add .dotnet and php composer default folder

---

images/linux/scripts/installers/haskell.sh

Fixes [actions/setup-haskell#8](https://github.com/actions/setup-haskell/issues/8) by adding [GHC 8.8.3](https://mail.haskell.org/pipermail/ghc-devs/2020-February/018643.html) to the virtual environment so that https://github.com/actions/setup-haskell can select this version.

Supported GHC 8.8.3

---

images/win/scripts/Installers/Validate-Packer.ps1

Issue:
`"_Version:_ $PackerVersion.Item(1)"` output will contain not only packer version, but additional   `.Item(1)`  element, for example: `_Version:_ Packer v1.5.4.Item(1)`
Fix:
We don't need using split statement, because `packer --version` = `1.3.4` command displays only version: `_Version:_ 1.3.4` compare to the command `packer version` = `Packer v1.3.4`

Fixing packer version description for Windows

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json

The Windows runners have two versions of Perl installed. Strawberry Perl should be first in the default path ahead of git-bash Perl because it handles Windows newlines better.
https://github.com/actions/virtual-environments/issues/123
**Changes:**
- Moved Perl installation before Git-Install to change directories order in the Path

Change default Perl on Windows Images

---

images/win/scripts/Installers/Windows2019/Install-VS2019.ps1

After WDK installation was fixed in https://github.com/actions/virtual-environments/pull/431 Spectre mitigation flag is enabled by default - [related thread on Developer Community.](https://developercommunity.visualstudio.com/content/problem/348985/installing-wdk-1809-enabled-spectre-mitigation-fla.html)
That causes build failures for some users because Spectre-mitigated libraries for MSVC v141 are not installed  - https://github.com/actions/virtual-environments/issues/488
**Changes:**
- Add Spectre-mitigated components for MSVC v141 in Visual Studio 2019

Add Spectre-mitigated libraries for MSVC v141 in Visual Studion 2019

---

images/win/scripts/Installers/Validate-VSWhere.ps1

Issue:
VsWhere version description contains a lot of noise in the output - https://github.com/actions/virtual-environments/blob/releases/win19/20200301/images/win/Windows2019-Readme.md
Fix:
Get ProductVersion in format: `2.8.4+ff0de50053 - shim 0.8.1`

Fix vswhere version in the output file

---

images/linux/scripts/installers/mysql.sh

Issue:
https://github.com/actions/virtual-environments/issues/348 and announce https://github.com/actions/virtual-environments/issues/375
Fix:
Disable autostart mysql.service.  We don't want to mask service: `This will prevent the MySQL service from being started, automatically or manually, for as long as it is masked.`

Disable mysql.service by default on Ubuntu images

---

images/win/Windows2019-Azure.json
images/win/scripts/Installers/Validate-Zstd.ps1

In this PR zstd was added to win16 only, however, it's supposed to be presented on all images
https://github.com/actions/virtual-environments/pull/414
Related issue
https://github.com/actions/virtual-environments/issues/89
Changes:
- Add zstd to win19
- Minor version output fix to get rid of 'v' before the version number

Add zstd to win19 image

---

images/win/Windows2019-Azure.json
images/win/scripts/Installers/Windows2019/Install-AnalysisExtenstion.ps1
images/win/scripts/Installers/Windows2019/Validate-AnalysisExtenstion.ps1

Analysis Services Project extension is included in a standalone SSDT installer for VS17, but there is no such installer for VS19. With Visual Studio 2019, the required functionality to enable Analysis Services, Integration Services, and Reporting Services projects has moved into the respective Visual Studio (VSIX) extensions only. It blocks migration to VS19 for some customers https://github.com/actions/virtual-environments/issues/510
Changes:
- Add Install-AnalysisExtenstion script for VS19

Add Microsoft Analysis Services Projects extension for VS19

---

images/linux/scripts/installers/clang.sh

https://github.com/actions/virtual-environments/issues/104#issuecomment-589962007

Install clang-format

---

images/linux/scripts/installers/1604/basic.sh

PR for Issue #72 
Added `libc++-dev` and `libc++abi-dev` installation for Ubuntu 16.04

Add installation of libs for default Clang on Ubuntu 16.04

---

images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Windows2019/Install-AnalysisExtenstion.ps1
images/win/scripts/Installers/Windows2019/Install-Wix.ps1

The last 2 days VS extension marketplace returns Error 429, which breaks image building.
```
==> vhd: Provisioning with powershell script: C:\agent\_work\2\s\images\win/scripts/Installers/Windows2019/Install-AnalysisExtenstion.ps1
vhd: Downloading Microsoft.DataTools.AnalysisServices.vsix extension
vhd: Installing Microsoft.DataTools.AnalysisServices.vsix extension
vhd: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (429)."
```
This PR adds retry logic for extension download process.
Changes:
- Add Install-VsixExtension function
- Change Install-Wix and Install-AnalysisExtenstion scripts to use the helper function

Add retry logic for VS19 extensions installation

---

images/macos/macos-10.15-Readme.md

- NVM - Cached node versions: v6.17.1 v8.17.0 v10.19.0 v12.16.1 v13.10.1
- PowerShell 7.0.0
- julia 1.3.1
- Vcpkg 2020.02.04
- Homebrew 2.2.9
- Yarn 1.22.1
- Gradle 6.2.2
- Curl 7.69.0
- Git: 2.25.1
- Packer 1.5.4
- bazel 2.2.0
- bazelisk v1.3.0
- Fastlane 2.143.0
- Cmake 3.16.5
- Google Chrome 80.0.3987.132 
- Microsoft Edge 80.0.361.66 
- MSEdgeDriver 80.0.361.66
- 8.4.8.2
| Version          | Build   | Path                              |
| ---------------- | ------- | --------------------------------- |
| 11.4 (beta)      | 11N132i | /Applications/Xcode_11.4_beta.app |

macOS Catalina 10.15.3 sofware updates week 11

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json

Issue:
We have faced with the `Failed to install Visual Studio. Check the logs for details in` exception in the Install-VS2017.ps1 script while building Windows Server 2016 image .  We already have got the `Update-DotnetTLS.ps1` script  which allow to enable TLS1.2 to whole system via updating `SchUseStrongCrypto=1` registry key, but we apply at the end of build generation process.
Failed build - https://github.visualstudio.com/virtual-environments/_build/results?buildId=62133&view=logs&j=50448a2f-9550-51a0-b6c4-5ec64224dd81&t=301ee57f-1f15-5a1f-450b-d1d367782be4
Fix:
Move the `Update-DotnetTLS.ps1` script at the top of packer config.

Move the Update-DotnetTLS.ps1 script to the top

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json

As a result of PR https://github.com/actions/virtual-environments/pull/494 OpenSSL from Perl bin directory became the default. However that OpenSSL isn't fully functional - issue https://github.com/actions/virtual-environments/issues/547
Changes:
- Moved OpenSSL installation before Perl to change directories order in the Path

Change default Openssl on Windows Images

---

images.CI/azure-pipelines/windows2019.yml

There is an error in  PR https://github.com/actions/virtual-environments/pull/536 Windows 2019 contains readme for Windows 2016.

Fix windows 2019 readme name

---

images.CI/build-image.ps1
images/win/scripts/Installers/Windows2016/Initialize-VM.ps1
images/win/scripts/Installers/Windows2019/Initialize-VM.ps1

With this pull request the following errors will be solved when running the Initialize-VM.ps1:
Error 1: 
``` 
Stop-Process : Cannot find a process with the name "Explorer". Verify the process name and call the cmdlet again.
Stop-Process -Name Explorer -Force -ErrorAction Continue
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Explorer:String) [Stop-Process], ProcessCommandException
+ FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.StopProcessCommand
```
Error 2: 
```
+ Set-ExecutionPolicy Unrestricted
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
+ FullyQualifiedErrorId : …
```

Fix errors in Initialize-VM.ps1

---

images/linux/scripts/installers/1604/android.sh
images/linux/scripts/installers/1804/android.sh
images/win/scripts/Installers/Update-AndroidSDK.ps1

Android SDK gradle plugin supports fixed versions of cmake, which are
either 3.6.4111459 or 3.10.2. 4988404, and on Github Actions our apps
fail to build if their build.gradle specify cmake 3.10.2 because
Android Gradle Plugin tries to download and install it if it's missing
(and causes file write access violation, at least on Ubuntu).

Add Android SDK cmake 3.10.2 component to ubuntu16.04, 18.04 and windows.

---

images/linux/scripts/installers/boost.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

Request: [Environment variable BOOST_ROOT will be deprecated in 2 month.](https://github.com/actions/virtual-environments/issues/319)
Updates:
1. Remove BOOST_ROOT environment variable
2. Update documentation to add all missing boost versions based on `toolcache.json` file (missing entry Boost C++ Libraries 1.72.0)
3. Update missing BOOST_ROOT_VERSION environment variables based on `toolcache.json` file( BOOST_ROOT_1_72_0 is currently missing)
Example output:
- Boost C++ Libraries 1.69.0
- Boost C++ Libraries 1.72.0

Deprecate BOOST_ROOT environment variable on Ubuntu 16.04/18.04

---

images/linux/scripts/installers/1604/android.sh
images/linux/scripts/installers/1804/android.sh

Issue: [#60](https://github.com/actions/virtual-environments/issues/60)
It fixes installation process to install sdkmanager to the correct directory. It changes directory for sdk manager from `/usr/local/lib/android` to `/usr/local/lib/android/sdk` ($ANDROID_HOME).
Builds:
[Ubuntu 1604](https://dev.azure.com/github/virtual-environments/_build/results?buildId=62040)
[Ubuntu 1804](https://dev.azure.com/github/virtual-environments/_build/results?buildId=62041)

Fix android sdkmanager installation path

---

images/win/scripts/Installers/Install-PHP.ps1
images/win/scripts/Installers/Validate-PHP.ps1

1. Install Composer from Chocolatey. PHP needs its dependency manager.
2. Enable php_openssl.dll - believe this is necessary in the case someone wants to update Composer. 
**Reference**
https://chocolatey.org/packages/composer
https://github.com/actions/virtual-environments/issues/587
https://superuser.com/questions/1010080/the-openssl-extension-is-missing-on-windows-while-installing-composer

Update Install-PHP.ps1 to include Composer

---

images/win/scripts/Installers/Validate-NSIS.ps1

Looks like NSIS version was missed in docs. Add it back.
Fix for #597

Add NSIS to the docs for Windows images

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/Installers/Install-Boost.ps1
images/win/scripts/Installers/Validate-Boost.ps1

Request: [Environment variable BOOST_ROOT will be deprecated in 2 month.](https://github.com/actions/virtual-environments/issues/319)
Updates:
To be in consistence with Ubuntu images and related with deprecation the `BOOT_ROOT` environment variable. We decided to:
- Remove default boost version directory with binaries(b2.exe, bootstrap) from path on Windows Server 2016 and Windows Server 2019

Remove default boost version directory with binaries from path on Windows Server 2016/2019

---

images/win/Windows2019-Azure.json

the boost_default variable has been removed from the boos installation. The 2019 json file still got the reference to is
- [X ] Related issue / work item is attached
https://github.com/actions/virtual-environments/issues/618

Removeboostenv

---

images/linux/scripts/installers/clang.sh

Ubuntu 16.04/18.04 image generation failed while installing clang-8. We use the `llvm.sh` script to install clang-8 version that script  stopped to  support installation clang-8(only 9,10,11 versions are supported).
```
==> azure-arm: Installing clang-8...
==> azure-arm: + LLVM_VERSION=9
==> azure-arm: + '[' 1 -eq 1 ']'
==> azure-arm: + LLVM_VERSION=8
==> azure-arm: ++ lsb_release -is
==> azure-arm: + DISTRO=Ubuntu
==> azure-arm: ++ lsb_release -sr
==> azure-arm: + VERSION=18.04
==> azure-arm: + DIST_VERSION=Ubuntu_18.04
==> azure-arm: + [[ 0 -ne 0 ]]
==> azure-arm: This script does not support LLVM version 8
```
https://github.com/actions/virtual-environments/issues/623
Use standard Ubuntu repositories to install clang-8

Ubuntu 16.04/18.04 image generation failed while installing clang-8

---

images/macos/macos-10.15-Readme.md

- Java 14: Zulu14.27+1-CA (build 14+36)
- Rust 1.42.0
- gcc-8 (Homebrew GCC 8.4.0) 8.4.0
- gcc-9 (Homebrew GCC 9.3.0) 9.3.0
- GNU Fortran (Homebrew GCC 8.4.0) 8.4.0
- GNU Fortran (Homebrew GCC 9.3.0) 9.3.0
- NVM - Cached node versions: v13.11.0
- Python 3.7.7
- .NET SDK 3.1.200
- PHP 7.4.3
- julia 1.3.1
- CocoaPods 1.9.1
- Homebrew 2.2.10
- Yarn 1.22.4
- Pip 20.0.2 (python 3.7)
- Miniconda 4.8.2
- Curl 7.69.1
- Git: 2.25.2
- Hub CLI: 2.14.2
- helm v3.1.2+gd878d4d
- Docker 19.03.8
- docker-machine 0.16.2
- docker-compose 1.25.4
- App Center CLI 2.3.4
- Azure CLI 2.2.0
- Google Chrome 80.0.3987.149
- Microsoft Edge 80.0.361.69
- Mozilla Firefox 74.0

mac OS 10.15 software updates week  13

---

images/win/scripts/Installers/Windows2016/Install-SSDT.ps1

In scope of this pull request we added the following changes:
- updated the download link for SSDT 15.9.4 for vs2017-win2016 image in `images/win/scripts/Installers/Windows2016/Install-SSDT.ps1` file.

Update the download link for SSDT for win2016

---

images/linux/scripts/installers/haskell.sh

GHC 8.10.1 was [released](https://mail.haskell.org/pipermail/ghc-devs/2020-March/018729.html). This PR adds this version of GHC to the virtual environments.

Supported GHC 8.8.10

---

.github/workflows/issue-triager.yml
triage-rules.yml

Current rules for triage bot doesn't satisfy our triaging process. The purpose of this PR is improving it a bit.
- Put `needs triage` label on all issues (even area path is determined successfully). We should add `needs triage` always to make sure that issue will be triaged properly by DRI.
Unfortunately, it is impossible to put needs triage tag always via `damccorm/tag-ur-it` action so I just changed condition for `actions/github-script` to run always and put this tag.
- Fix parameters of `actions/github-script` step because it looks like it has never worked due to invalid parameters
- Remove unused steps at the end of pipeline. Not sure why we need them, tested on my fork and everything works as expected without it.
- Disable assigning to particular people, Not sure that we really need …

Improve automated triage process

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/Installers/Install-ServiceFabricSDK.ps1

Match the same ExecutioPolicy as in the Install-ServiceFabricSDK
This will solve the following error: 
==> vhd: Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
==> vhd: a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
==> vhd: execution policy of Bypass. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
==> vhd: information please see "Get-Help Set-ExecutionPolicy".
==> vhd: At C:\Windows\Temp\script-5e7b1f2e-71af-55d1-e9f9-b46c8a1fb26d.ps1:11 char:1
==> vhd: + Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
==> vhd: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : …

Set the execution policy in Packer to RemoteSigned

---

images/win/Windows2019-Azure.json
images/win/scripts/Installers/Install-RootCA.ps1

On the windows-2019, not all root CA certificates are installed. Some are missing (for example Quo Vadis). This leads for some tools to the following error: X509: CERTIFICATE SIGNED BY UNKNOWN AUTHORITY when calling a API vis SSL.
**New tool, Bug fixing, Improvement?**  
CertUtil [Options] -generateSSTFromWU SSTFile 
SSTFile is the name of the .sst file that is created. The generated .sst file contains the third-party root certificates that are downloaded from Windows Update.
Installation time: ~1min
Total size: ~ 2mb
https://github.com/actions/virtual-environments/issues/628
https://github.com/actions/virtual-environments/issues/577

Install missing root certificates on windows-2019

---

images/win/scripts/Installers/Install-DotnetSDK.ps1

Environment variable Path has a space as the last character in a folder name. Windows will not accept a  name with a trailing space character.
`Caused by: java.nio.file.InvalidPathException: Trailing char < > at index 36: C:\Program Files (x86)\Microsoft SQL `
The root cause of the issue is in the `setx` command limitation: `WARNING: The data being saved is truncated to 1024 characters.` In the script `Install-DotnetSDK.ps1` we are trying to update PATH variable using `setx` after truncation there is a chance to  have names with a trailing space at the end.
PowerShell  `[System.Environment]::SetEnvironmentVariable` static method doesn't have this limitation and support 32767 characters.
https://github.com/actions/virtual-environments/issues/635

Fix user environment  PATH variable

---

images/win/scripts/Installers/Validate-Cmake.ps1

Bug fixing.  
According to https://github.com/actions/virtual-environments/issues/641 "Cmake" has been changed to "CMake" in Validate-Cmake.ps1.

[Cmake] has been changed to [CMake]

---

images/macos/macos-10.15-Readme.md

- System Version: macOS 10.15.4 (19E266)
- Kernel Version: Darwin 19.4.0
- NVM - Cached node versions: v6.17.1 v8.17.0 v10.19.0 v12.16.1 v13.12.0
- .NET SDK 2.0.0 3.0.100 3.0.101 3.0.102 3.0.103 3.1.100 3.1.101 3.1.200 3.1.201
- Go 1.14.1
- Homebrew 2.2.11
- NuGet 5.5.0.6382
- Gradle 6.3
- Git: 2.26.0
- Packer 1.5.5
- GNU parallel 20200322
- gpg (GnuPG) 2.2.20
- Fastlane 2.144.0
- Cmake 3.17.0
- App Center CLI 2.3.5
- AWS CLI 2.0.5
- MSEdgeDriver 80.0.361.69
- 8.5.0.3183
- 6.8.0.123
- 13.14.1.39
- 6.14.1.39
- 10.2.0
| Version          | Build   | Path                           |
| ---------------- | ------- | ------------------------------ |
| 11.4             | 11E146  | /Applications/Xcode_11.4.app   |
| Package Name     | Version      |
| ---------------- | ------------ |
| Android …

macOS software updates week 14

---

images/win/scripts/Installers/Windows2016/Initialize-VM.ps1
images/win/scripts/Installers/Windows2019/Initialize-VM.ps1

There are two cpack.exe in PATH
1. The alias of choco pack for Chocolatey
2. The pack module of the CMake suite
The first one (placed in `%ChocolateyInstall%\bin\`) is in front of the second one (`%ProgramFiles%\CMake\bin\`), so when use cpack, it will call the `%ChocolateyInstall%\bin\cpack.exe` . But actually, the `%ChocolateyInstall%\bin\cpack.exe` is just an alias, while `%ProgramFiles%\CMake\bin\cpack.exe` is an important program, and the second one is more important the the first one.
https://github.com/chocolatey/choco/commit/e9dcb0cc12d49791511e8456b6e94438b81c369c
```
NOTE: `cpack` has been deprecated as it has a name collision with CMake. Please 
use `choco pack` instead. The shortcut will be removed in v1.
```
https://github.com/actions/virtual-environments/issues/649 …

Remove choco alias cpack.exe that conflicts with CMake cpack

---

images/linux/scripts/installers/haskell.sh

`cabal-install 3.2.0.0` was [released](https://hackage.haskell.org/package/cabal-install-3.2.0.0). This PR adds this version of `cabal-install` to the virtual environments.

Added cabal-install 3.2.0.0.

---

images/win/Windows2019-Azure.json
images/win/scripts/ImageHelpers/InstallHelpers.ps1

1. Change Azure VM Size Standard_DS4_v2  to Standard_D4_v2 to decrease packer winrm timeout with Windows Server 2019 - https://github.com/hashicorp/packer/issues/8658
One of packer contributor provide - https://github.com/hashicorp/packer/issues/8658#issuecomment-605376740
My findings are as follows:
1. v1.5.5 using Standard_D2_v2 resulted in a successful build every time.
2. v1.5.5 patched to use <machinename>.<location>.cloudapp.azure.com using Standard_D2_v2 resulted in a succesful build every time.
3. v1.5.5 using Standard_DS2_v2 timed out 60% of the time.
4. v1.5.5 patched to use <machinename>.<location>.cloudapp.azure.com using Standard_DS2_v2 timed out 80% of the time (seems like a lot, so maybe be something else going on; will retest)
As we can see there is no any difference …

Fix vsix installation

---

images/linux/scripts/installers/firefox.sh

Time to time we have errors  with incorrect parsing geckodriver url during ubuntu image generation process.  For example, last build failed with incorrect `https://github.com/vladikoff` url instead of something like `https://github-production-release-asset-2e65be.s3.amazonaws.com.`
https://github.visualstudio.com/virtual-environments/_build/results?buildId=64162&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=486c0909-f67d-5748-80b3-bb1d531e7b43
```
azure-arm: Downloading geckodriver https://github.com/vladikoff...
azure-arm: --2020-04-03 02:14:54--  https://github.com/vladikoff
azure-arm: Resolving github.com (github.com)... 192.30.255.112
azure-arm: Connecting to github.com (github.com)|192.30.255.112|:443... connected.
azure-arm: HTTP request sent, awaiting response... 200 OK …
```

Fix geckodriver url parse

---

images/win/scripts/Installers/Windows2016/Initialize-VM.ps1

Microsoft deprecated support SSL/old TLS to compliant version 1.2. In that case we should manually set `Tls12` before nuget installation to fix Windows Server 2016  image generation process.
https://github.com/actions/virtual-environments-internal/issues/338

Fix nuget installation on Windows Server 2016

---

images/linux/scripts/installers/rndgenerator.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

The build hangs forever with a [cryptographic library](https://github.com/uio-bmi/crypt4gh) , because the library can’t generate encryption keys due to the issue [GPG does not have enough entropy](https://serverfault.com/questions/214605/gpg-does-not-have-enough-entropy)
> We need to generate a lot of random bytes. It is a good idea to perform
> some other action (type on the keyboard, move the mouse, utilize the
> disks) during the prime generation; this gives the random number
> generator a better chance to gain enough entropy.
> Not enough random bytes available.  Please do some other work to give
> the OS a chance to collect more entropy!
Haveged - 200kb (~10 seconds) …

Add haveged random generator tool on Ubuntu images

---

images/linux/scripts/installers/firefox.sh

<h1>Description</h1>
Firefox on ubuntu has different locales compared with other browsers, en_GB instead of en_US
- mv .mozilla to skel
- add user.js profile with its changes
<h4>Related issue:</h4>
https://github.com/actions/virtual-environments/issues/614
<h4>Link image</h4>
https://github.visualstudio.com/virtual-environments/_build/results?buildId=64369&view=results
<h2>Check list</h2>

Change default locale for Firefox on Ubuntu

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json

After installation MS SQL Server 2019 Express we have faced with  incorrect dynamic-link library search order: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order due to conflict with `instapi150.dll`.
Without SQL:
If SafeDllSearchMode is enabled, the search order is as follows:
1. The directory from which the application loaded. 
2. The system directory. Use the GetSystemDirectory function to get the path of this directory.
3. The 16-bit system directory. There is no function that obtains the path of this directory, but it is searched.
4. The Windows directory. Use the GetWindowsDirectory function to get the path of this directory.
5. The current directory.
6. The directories that are listed in the PATH environment variable. Note that this does not …

Disable MS SQL Server 2019 Express  installation

---

images/linux/scripts/helpers/etc-environment.sh
images/linux/scripts/installers/1604/php.sh
images/linux/scripts/installers/1804/php.sh
images/linux/scripts/installers/dotnetcore-sdk.sh
images/linux/scripts/installers/homebrew.sh
images/linux/scripts/installers/rust.sh
images/linux/scripts/installers/updatepath.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

Improvement
Use functions from `helpers/etc-environment.sh` in order to
* modify `/etc/environment` from install scripts:
- installers/rust.sh
- installers/1604/php.sh
- installers/1604/php.sh
- installers/dotnetcore-sdk.sh
* remove legacy `updatepath.sh` used to modify `/etc/environment` 
* rename the helpers functions for better readability
https://github.com/actions/virtual-environments-internal/issues/334 
- [x ] Related issue / work item is attached
- [x ] Changes are tested and related VM images are successfully generated

Migrate /etc/environment modifications to helpers

---

images/win/scripts/Installers/Install-Git.ps1

I'm updating the Git install script for Windows images to use the release from the official GitHub for Windows repo. The main reason for this is to be able to move the version without being attached to what chocolatey provides.

Fix Git installer to download directly from release

---

images/win/scripts/Installers/Install-Julia.ps1
images/win/scripts/Installers/Validate-Julia.ps1

Julia 1.3.1 was packed using NSIS  installer with parameter /D to overrides destination folder. After updating Julia to version Julia 1.4.0  installer was updated to use Inno Setup with a new parameter /DIR:
```
/DIR="x:\dirname"
Overrides the default directory name displayed on the Select Destination Location wizard page. A fully qualified pathname must be specified. May include an "expand:" prefix which instructs Setup to expand any constants in the name. For example: '/DIR=expand:{autopf}\My Program'.
```

Fix Julia destination folder

---

images/linux/scripts/installers/vcpkg.sh

Vcpkg bootstrap failed with `2020/04/15 08:34:22 ui error: ==> azure-arm: CMake Error: The source directory "/home/packer/toolsrc" does not exist.`after this PR https://github.com/microsoft/vcpkg/pull/10834 
Changed vcpkg installation to the previous commit to unblock image generation.

[Ubuntu] Workaround for vcpkg installation

---

images/linux/scripts/installers/vcpkg.sh

Fix for pr https://github.com/actions/virtual-environments/pull/724
`git checkout` is supposed to be invoked from the downloaded repo directory

[Ubuntu] Fix workaround for vcpkg

---

images/linux/scripts/installers/aws-sam-cli.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

Install AWS SAM CLI on Ubuntu images
New Tool.
Adds _sam_ utility according to the installation instructions https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html
This PR does not include adding the AWS SAM docker container.
**Total size (including related brew tap) 650Kb. Installation time: between 5 and 10 minutes**
https://github.com/actions/virtual-environments/issues/94

Install AWS SAM CLI

---

images/linux/scripts/installers/1604/basic.sh
images/linux/scripts/installers/1804/basic.sh

The new version of puppeteer(Node library which provides a high-level API to control Chrome or Chromium) requires libgbm library, which is not installed on the images.
Related issues: 
https://github.com/actions/virtual-environments/issues/732
https://github.com/puppeteer/puppeteer/issues/5661
**Library size:** 100 Kb
**Installation time:** less that a minute

[Ubuntu] Add libgbm to resolve puppeteer issue

---

images/linux/scripts/installers/vcpkg.sh

Don't need this workaround anymore – issue fixed in https://github.com/microsoft/vcpkg/pull/10846

[Ubuntu] Remove workaround for vcpkg

---

images/win/scripts/Installers/Download-ToolCache.ps1

This PR fix issue with gem update of system default ruby in `Download-Toolcache.ps1`.
Previously, `gem update --system` was executed before changes in system path were applied.
```
vhd: Use Ruby 2.5 as a system Ruby
...
==> vhd: gem : The term 'gem' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
==> vhd: spelling of the name, or if a path was included, verify that the path is correct and try again.
==> vhd: At C:\Windows\Temp\script-5e981db6-c29e-5a7e-58ae-d3139d037aec.ps1:75 char:5
==> vhd: +     gem update --system
==> vhd: +     ~~~
==> vhd:     + CategoryInfo          : ObjectNotFound: (gem:String) [], CommandNotFoundException
==> vhd:     + FullyQualifiedErrorId : CommandNotFoundException
```
This fix update environment before get …

Fix gem update for system default Ruby

---

images/linux/scripts/installers/1604/android.sh
images/linux/scripts/installers/1804/android.sh

Bug fixing
Installed Android SDK binaries can be executed only by root, due to lack of permissions.
https://github.com/actions/virtual-environments/issues/738
It seems it's really minor change, and nothing is changed in image build workflow.

Android SDK binaries insufficient permissions.

---

images/linux/scripts/installers/1604/android.sh
images/linux/scripts/installers/1804/android.sh

Reverts actions/virtual-environments#711
This PR will help us to get ~3.8 gb disk space back to resolve
https://github.com/actions/virtual-environments/issues/709

Revert "Pre-install Android NDK 20 on Ubuntu"

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/Installers/Install-AWS-SAM.ps1
images/win/scripts/Installers/Validate-AWS-SAM.ps1

New tool
Install AWS SAM CLI according to the instruction https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-windows.html
There's no official choco package so MSI installation used. It is confirmed the Machine Environment is updated by MSI installer.
**Total size:** 132Mb
**Installation time.** 1min

Install AWS SAM CLI on Windows images

---

images/linux/scripts/installers/cleanup.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

At the end of image generation we should cleanup the apt package cache (apt-get clean). There's no use for it on deployed images. Doing this would free up multiple GB of disk space.
https://github.com/actions/virtual-environments/issues/751

Clean up apt package cache

---

images/win/scripts/Installers/Install-AWS-SAM.ps1

Bug fixing 
Catch up with the most recent master changes: Install-MSI replaced with Install-Binary
https://github.com/actions/virtual-environments-internal/issues/418

Use Install-Binary instead of Install-MSI

---

images/win/scripts/Installers/Install-DotnetSDK.ps1

It is not most recent now and it not selected by defaultg
Improvement?  
[Buggy](https://github.com/dotnet/aspnetcore/issues/19133) Dotnet SDK 3.1.102 has been exclude for a while to avoid it became default. Since 3.1.201 release we can return it back to the images

Return back dotnent 3.1.102

---

images/win/scripts/Installers/Install-RootCA.ps1

Signing validation for .Net Core projects started raising a red flag about a DLL signed with a certificate that was revoked. This issue only happens in the hosted agents (only tested with 'windows-2019') and it started happening about a day ago. Apparently the hosted agents got the certificate revoked.
https://github.com/dotnet/arcade/issues/5328

Clear CERT_NOT_BEFORE_FILETIME_PROP_ID property

---

images/linux/scripts/helpers/etc-environment.sh

Improvement
Don't leave the backup file after `sed` execution

Don't create backup sed file

---

README.md

I adde few new items to tool installation guide:
- If tool license is not MIT, Apache or GNU, the tool cannot be installed on image.
- Big tools can be pre-installed after our evaluation of the image space usage.
- If a tool requires the support of more than one version, we will consider the cost of this maintenance, how often new versions bring dangerous updates.
- Please, before creating a PR with tool installation, wait for confirmation that this tool can be installed on image.

Updated README with new rules of tool installation.

---

images/linux/scripts/installers/validate-disk-space.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/Installers/Validate-DiskSpace.ps1

Сheck of free disk space on Windows and Ubuntu was added after image generation was completed.
Issue: #752

Fail fast in image generation if not enough disk space for customers

---

images/win/scripts/Installers/Windows2016/Initialize-VM.ps1
images/win/scripts/Installers/Windows2019/Initialize-VM.ps1

The `FS-iSCSITarget-Server`  feature allows for putting temp directory in a RAMdisk and reduces installation step on 30 seconds. 
https://github.com/actions/virtual-environments/issues/708

Add FS-iSCSITarget-Server

---

images/macos/macos-10.15-Readme.md

- Rust 1.43.0
- NVM - Cached node versions: v6.17.1 v8.17.0 v10.20.1 v12.16.2 v13.13.0
- Git: 2.26.2
- GNU parallel 20200422
- azcopy 10.4.1
- bazel 3.1.0
- helm v3.2.0+ge11b7ce
- Fastlane 2.146.1
- App Center CLI 2.5.0
- Azure CLI 2.4.0
- AWS CLI 2.0.9
- Aliyun CLI 3.0.39
- Google Chrome 81.0.4044.122 
- Microsoft Edge 81.0.416.64 
- MSEdgeDriver 81.0.416.64
- 8.5.4.12
| Version          | Build   | Path                           |
| ---------------- | ------- | ------------------------------ |
| 10.3             | 10G8    | /Applications/Xcode_10.3.app   |
| Package Name   | Description                                 |
| -------------- | ------------------------------------------- |
| platform-tools | Android SDK Platform-Tools, Revision 30.0.0 |
| Package Name     | Version      |
| …

macOS software updates week18

---

images/win/scripts/Installers/Install-JavaTools.ps1
images/win/scripts/Installers/Validate-JavaTools.ps1

Download and Install Java 13 to VM.
**Total size**: 199880KB
**Installation time**: Not quite sure. Please let me know how I can get the time.
https://github.com/Azure/azure-sdk-for-java/issues/10465

Added java 13 package in VM

---

images/linux/scripts/installers/1604/php.sh
images/linux/scripts/installers/1804/php.sh

Bug fixing
Php composer set permission for `.composer` folder like for `/usr/bin/composer` which causes lack of permissions issue in attempt to use compose in agents.
https://github.com/actions/virtual-environments/issues/824

Create .composer folder to preserve permissions

---

images/linux/scripts/installers/1804/basic.sh

Bug fixing
Sometimes, stub DNS for systemd-resolve does not work properly, and it is not possible to determine what exactly is happening. It looks like a bug in systemd-resolve service.
https://github.com/actions/virtual-environments/issues/798

Systemd-resolve workaround for Ubuntu 18.

---

images/win/scripts/Installers/Install-CloudFoundryCli.ps1
images/win/scripts/Installers/Install-Go.ps1
images/win/scripts/Installers/Install-Kind.ps1
images/win/scripts/Installers/Install-MysqlCli.ps1
images/win/scripts/Installers/Install-Rust.ps1
images/win/scripts/Installers/Install-SQLPowerShellTools.ps1
images/win/scripts/Installers/Update-AndroidSDK.ps1

This PR improves stability for following Windows provisioners:
1. Install-CloudFoundryCli.ps1
1. Install-Go.ps1
1. Install-Kind.ps1
1. Install-MysqlCli.ps1
1. Install-Rust.ps1
1. Install-SQLPowerShellTools.ps1
1. Update-AndroidSDK.ps1
Most of default `Invoke-WebRequest` occurrences was replace with custom `Start-DownloadWithRetry` function that support retries logic. Also several improvements in syntax was made.
**How it was tested:**
Validation image was generated - [Windows2019](https://dev.azure.com/github/virtual-environments/_build/results?buildId=65363&view=results).
Issue: https://github.com/actions/virtual-environments-internal/issues/384

Improve Windows provisioners stability

---

images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Install-DotnetSDK.ps1
images/win/scripts/Installers/Windows2016/Install-VS2017.ps1
images/win/scripts/Installers/Windows2019/Install-VS2019.ps1

This PR improves stability for following Windows provisioners:
1. Install-DotnetSDK
1. Install-VS2017
1. Install-VS2019
Most of default `Invoke-WebRequest` occurrences was replace with custom `Start-DownloadWithRetry` function that support retries logic. Also several improvements in syntax was made.
**How it was tested:**
Windows 2016 - https://github.visualstudio.com/virtual-environments/_build/results?buildId=65825&view=results
Windows 2019 - https://github.visualstudio.com/virtual-environments/_build/results?buildId=65826&view=results
Issue: https://github.com/actions/virtual-environments-internal/issues/384

Improve Windows Visual Studio provisioners

---

images/win/scripts/Installers/Install-Chrome.ps1
images/win/scripts/Installers/Install-Edge.ps1
images/win/scripts/Installers/Install-Firefox.ps1

This PR improves Windows browsers provisioners (`Install-Edge`, `Install-Chrome`, `Install-Firefox`). 
Default `Install-Exe` functions in provisioners was changed to custom `Install-Binary`, `Invoke-WebRequest` methods was also changed to cusetom `Start-DownloadWithRetry` to avoid possible image-generation failures, caused by connectivity issues. PR also includes several minor improvements in provisioners syntax.
**How it was tested:**
Validation image was generated - [Windows2019](https://dev.azure.com/github/virtual-environments/_build/results?buildId=65239&view=results).
Issue: https://github.com/actions/virtual-environments-internal/issues/384

Improve Windows browsers provisioners stability

---

images/win/scripts/Installers/Install-JavaTools.ps1

During setting maven's environment variables we have error, when we try to get `M2_HOME` value from registry:
```
$m2_home = (Get-ItemProperty -Path $userEnvironmentKey -Name M2_HOME) ...
Get-ItemProperty : Property M2_HOME does not exist at path
CategoryInfo          : InvalidArgument: (M2_HOME:String) [Get-ItemProperty], PSArgumentException
```
and as a result of this we have incorrect value `M2` env variable: `M2=\bin` on Windows images.
This can be fixed by replacing the registry key for getting value `M2_HOME` env variable from registry.
Test build: [Windows-2019](https://github.visualstudio.com/virtual-environments/_build/results?buildId=67169)

Fix setting Maven's environment variables

---

images/linux/scripts/installers/dpkg-config.sh
images/macos/macos-10.15-Readme.md

We suppress output about obsolete packages to delete. The `apt-get` doesn't have indicator whether you're using the packages or not, but it knows that they were installed automatically and nothing depends on them any more. In that case we can break some customers who use these packages if we run `apt-get autoremove`.
```
The following packages will be REMOVED:
bc dns-root-data dnsmasq-base ebtables grub-pc-bin landscape-common
liblldb-6.0 liblldb-8 liblxc-common liblxc1 libuv1 linux-headers-4.15.0-99
lxcfs lxd lxd-client python3-attr python3-automat python3-click
python3-colorama python3-constantly python3-hyperlink python3-incremental
python3-pam python3-pyasn1 python3-pyasn1-modules python3-service-identity
python3-twisted python3-twisted-bin python3-zope.interface xdelta3
0 upgraded, 0 …
```

Hide packages that are no longer required

---

images/win/scripts/Installers/Windows2019/Install-VS2019.ps1

Improvment
SSDT tools now should be installed as workload for Visual Studio 2019. More information can be obtained here: https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-ver15#ssdt-for-vs-2017-standalone-installer
Size: 500 Mb
https://github.com/actions/virtual-environments/issues/702

Add SSDT Workload to Visual Studio 2019

---

images/linux/scripts/installers/go.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

Internal issue: [#489](https://github.com/actions/virtual-environments-internal/issues/489)
Moved Go location from `/usr/local` to `/opt/hostedtoolcache/go` directory to work with `setup-go` action.
Example of path:
```
/opt/hostedtoolcache/go/1.14.2/x64
```

Install Go to hostedtoolcache directory on Ubuntu image

---

images/win/scripts/Installers/Install-Go.ps1
images/win/scripts/Installers/Validate-Go.ps1

Internal issue: [#488](https://github.com/actions/virtual-environments-internal/issues/488)
Moved Go location from `C:` to `C:\hostedtoolcache\go` directory to work with `setup-go` action.
Example of path:
```
C:\hostedtoolcache\go\1.14.2\x64
```
Also it uses `7z` tool instead `Expand-Archive` to decrease expand archive time (about 20 min with `Expand-Archive` and 3 min with `7z`).

Install Go to hostedtoolcache directory on Windows image

---

images/win/scripts/Installers/Windows2019/Install-VS2019.ps1

Windows 10 SDK (10.0.14393.795) VS19 workload was deprecated quite a long time ago https://github.com/MicrosoftDocs/visualstudio-docs/commit/37e6886087e40f8576eaa82dfd5e87e524c2319f#diff-757fef660bf40737850ce059881acf40L387 so we have to use a standalone installer.
https://github.com/actions/virtual-environments/issues/858
- [N/a] Tests are written (if applicable)

Install Windows 10 SDK (10.0.14393.795) via standalone installer

---

images.CI/azure-pipelines/image-generation.yml
images.CI/cleanup.ps1

The result is not returned to the variable because of the output redirect
Bug fixing  
The cleanup script does not work anymore.It does not get the result in the variable $groupExists due to output redirect.

Fix the cleanup script.

---

images/linux/scripts/installers/azcopy.sh

Add Azcopy10 to the image and preserve Azcopy 7 because the functionality between these versions differs(AzCopy 7 uses Shared Keys while version 10 uses SAS)
Azcopy10 size ~20Mb
https://github.com/actions/virtual-environments/issues/868

[Ubuntu] Add Azcopy10

---

images/macos/macos-10.15-Readme.md

- Rust 1.43.1
- NVM 0.35.3
- NVM - Cached node versions: v6.17.1 v8.17.0 v10.20.1 v12.16.3 v13.14.0 v14.2.0
- Homebrew 2.2.15
- RubyGems 3.1.3
- Gradle 6.4
- Packer 1.5.6
- azcopy 10.4.3
- Vagrant 2.2.8
- App Center CLI 2.5.1
- Google Chrome 81.0.4044.138 
- ChromeDriver 81.0.4044.138
- Mozilla Firefox 76.0
- 8.5.5.7
| Version          | Build   | Path                              |
| ---------------- | ------- | --------------------------------- |
| 11.5 (beta)      | 11N605f | /Applications/Xcode_11.5_beta.app |
- Nomad CLI 3.1.3
| Package Name   | Description                                 |
| -------------- | ------------------------------------------- |
| platform-tools | Android SDK Platform-Tools, Revision 30.0.1 |
| Package Name           | Description …

macOS software updates week20

---

images/linux/scripts/installers/cleanup.sh
images/linux/scripts/installers/validate-disk-space.sh

We check disk free space when some garbage files are in /tmp, yet these files do not exist on the final VM. Need to clean them up before the checking. The limit is also lowered because we have a bit more space after provisioning now.
https://github.com/actions/virtual-environments/issues/709

[Ubuntu] Add /tmp cleanup

---

images/linux/scripts/installers/1804/basic.sh

Bug fixing
- [This is Github issue](https://github.com/systemd/systemd/issues/10298), with exactly the same problem, which was not fixed, only workaround was provided as solution.
- Root cause is unclear.
- I'm not sure that we can remove systemd-resolve without effects. but we can disable it by default. However, in this case, it is required to add manually nameserver record to `/etc/resolv.conf `file.
- In the [official documentation](https://wiki.archlinux.org/index.php/Systemd-resolved), I didn't find misconfigurations.
So, the workaround helps us to resolve the issue with default systemd-resolve.
However, during the last try, we faced the issue with docker agents. I have verified that current workaround works as expected.
$ docker exec -it ubuntu:18 /bin/bash
**Reproduced:**
```
/# ln …
```

[Ubuntu 18] systemd-resolve workaround

---

images/win/scripts/Installers/Install-JavaTools.ps1
images/win/scripts/Installers/Validate-JavaTools.ps1

Java 13 is installed instead of Java 11 due to broken comparison.
https://github.com/actions/virtual-environments/issues/885

[Windows] Fix java 11 installation

---

images/win/scripts/Installers/Install-Msys2.ps1

Packer fails while building the MSYS2  due to missing  ZST archives. 
https://github.com/actions/virtual-environments/issues/898
https://github.com/msys2/MSYS2-packages/issues/1960

Update pacman package to install msys2

---

images/win/scripts/Installers/Validate-Msys2.ps1

Added a note that MSYS2 is pre-installed but not added to PATH.

Add a note about MSYS2 installation

---

images/win/Windows2016-Azure.json

vswhere is designed to be a redistributable, single-file executable that can be used in build or deployment scripts to find where Visual Studio - or other products in the Visual Studio family - is located. vswhere simplifies process of the generation markdown documentation related with Visual Studio. We already have the same util on Windows Server 2019.

Add vswhere app on  Windows Server 2016

---

images.CI/azure-pipelines/image-generation.yml
images.CI/build-image.ps1
images/linux/scripts/installers/validate-disk-space.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json

This flag allows to skip disk space validation step during the build process. Default value of the flag is set `false`. 
https://github.com/actions/virtual-environments-internal/issues/580

Add flag validation diskspace and set false(skip) step by default

---

images/win/scripts/Installers/Install-Msys2.ps1

1. Use 20200517 release from GitHub (https) instead of older 20190524 release (http)
2. Git tar  - change paths to full nix style
3. Git tar - requires exe's from Git/mingw64/bin, set ENV
2 & 3 may not be needed, but if anything changes...
Script will run locally assuming one has Git for Windows installed.  Since the base install is much newer, it requires fewer updates to be installed.

WIndows - update Install-Msys2.ps1

---

images/linux/scripts/installers/validate-disk-space.sh

Change minimum free space limit from 17800mb to 16000mb for Ubuntu 16.04/18.04

Change minimum free space limit to 16000mb for Ubuntu 16.04/18.04

---

images/macos/macos-10.15-Readme.md

- PowerShell 7.0.1  
- .NET SDK 3.1.202
- Go 1.14.3
- PHP 7.4.6
- Homebrew 2.2.17  
- Gradle 6.4.1  
- Git LFS: 2.11.0
- GitHub CLI: 0.8.0
- psql (PostgreSQL) 12.3  
- PostgreSQL 12.3  
- helm v3.2.1+gfe51cd1
- virtualbox 6.1.8r137981
- mongo v4.2.6
- mongod v4.2.6
- Vagrant 2.2.9 
- Fastlane 2.148.1
- App Center CLI 2.5.2
- AWS SAM CLI 0.49.0
- Aliyun CLI 3.0.42 
- Google Chrome 81.0.4044.138 
- Microsoft Edge 81.0.416.72 
- MSEdgeDriver 81.0.416.72
- Mozilla Firefox 76.0.1
- 3.8.3
| Version          | Build   | Path                           |
| ---------------- | ------- | ------------------------------ |
| 11.5             | 11E608c | /Applications/Xcode_11.5.app   |  
| Version      | Path                                       |
| ------------ | …

macOS 10.15 software updates week22

---

images/win/scripts/Installers/Install-Msys2.ps1

New tool, Bug fixing, or Improvement?  Bug
Due to conflicts with two installed versions
See https://github.com/actions/virtual-environments/issues/905

[Bug] Windows - Install-Msys2.ps1 - remove msys2 p7zip / 7z package

---

images/linux/scripts/installers/pypy.sh

The pypy.sh script failed due to unable to get PyPy version from downloads.python.org related to network issue.
```
==> azure-arm: Provisioning with shell script: C:\agent\_work\2\s\images\linux/scripts/installers/pypy.sh
==> azure-arm: gzip: stdin: not in gzip format
azure-arm: Failed to get PyPy version '2.7'
```
Changes :
- Add curl parameter -4 to use IPv4 only
- Max attempts 20

Add retries to get PyPy version

---

images/win/scripts/Installers/Update-AndroidSDK.ps1

Improvement
We have only Android NDK installed with Visual Studio, but version is too old(16.1.4479499). Need to install the latest one.
Also, by unknown reason we missed Android SDK 29.0.1 in our installation steps. So, added it.
NDK installation time is about 4-5 minutes.
https://github.com/actions/virtual-environments/issues/344

Add Android SDK 29.0.1 and NDK 21

---

images/linux/scripts/installers/basic.sh

Bug fixing.
Due to issues after systemd-resolve fix, described in[ github issue 929](https://github.com/actions/virtual-environments/issues/929#issuecomment-634148495), it is required to revert it back.
https://github.com/actions/virtual-environments/issues/929#issuecomment-634148495

Revert systemd-resolve workaround.

---

images/linux/ubuntu2004.json

Azure-cli package for Ubuntu20 has been released recently
https://github.com/Azure/azure-cli/issues/13081
N\A
- [N\A] Related issue / work item is attached

[Ubuntu20] Add azure-cli and azure-devops extension

---

images/win/scripts/Installers/Install-IEWebDriver.ps1

Windows images build fails due to unable to download Selenium Web Driver for IE:
`C:\Windows\Temp\script-5ecd16ad-74f7-86b7-1e84-501f9e9dfe1f.ps1 : [!] Failed to download SeleniumWebDrivers.zip`
Previous installation source is unavailable - https://seleniumwebdrivers.blob.core.windows.net/seleniumwebdrivers/SeleniumWebDrivers.zip .
https://github.com/actions/virtual-environments/issues/940

Update IEDriverServer url

---

images/linux/scripts/installers/haskell.sh

Recently, [actions/setup-haskell v.1.1](https://github.com/actions/setup-haskell/releases/tag/v1.1.0) was released. This version started to support the installation of Haskel, Cabal, Stack on-demand. Considering this fact, we are planning to deprecate old versions of ghc and cabal from the image to release free space for new software.
In the future, we are planning to pre-cache 3 latest ghc releases (currently, 8.10.1, 8.8.3, 8.6.5) and 1 latest cabal release (currently, 3.2) on the image. Any other versions can be installed in runtime using [actions/setup-haskell](https://github.com/actions/setup-haskell) action.
https://github.com/actions/virtual-environments/issues/852

[Ubuntu] Install 3 latest Haskell version and latest Cabal version

---

images/linux/scripts/installers/azure-cli.sh
images/win/scripts/Installers/Install-AzureCli.ps1

Azure-cli 2.6.0 has [a bug](https://github.com/Azure/azure-cli/issues/13706), which is supposed to be fixed in 2.7.0. 
Hardcode version 2.5.1 in the install scripts until then to unblock image rollout.
https://github.com/actions/virtual-environments/issues/948

Temporary downgrade Azure-Cli to 2.5.1

---

images/win/scripts/Installers/Install-WDK.ps1
images/win/scripts/Installers/Windows2019/Install-VS2019.ps1

Need newer Windows SDK to compile against GraphicsCaptureSession.IsCursorCaptureEnabled property. I personally don't care about WDK, but it seems like they need to be updated as a set.
Verified correct version of SDK, WDK, and WDK VS extension were all installed to generated VM. My application compiles successfully.
Didn't touch Windows2019-Readme.md because it looks auto-generated.
Should I create an issue?

Update Windows2019 image to use 2004 SDK & WDK

---

.vscode/settings.json
README.md

Documentation fix
[Public virtual environments project](https://github.com/actions/virtual-environments/projects/1) was removed recently and we need to fix link that points to it.
Also I have updated docs to mention tags that we use.
Also updated annoying vscode settings that don't allow to edit markdown files at all.
https://github.com/actions/virtual-environments/issues/962

Fix broken link in readme file

---

images/linux/scripts/installers/dotnetcore-sdk.sh

It is not most recent now and it not selected by defaultg
Improvement
[Buggy](https://github.com/dotnet/aspnetcore/issues/19133) Dotnet SDK 3.1.102 has been exclude for a while to avoid it became default. Since 3.1.201 release we can return it back to the images

Return back dotnent 3.1.102 on Ubuntu images

---

images/win/scripts/Installers/Install-Msys2.ps1

New tool, Bug fixing, or Improvement?  **Improvement**
1. MSYS2 - add small changes to make MSYS2 installation/update via script more stable.
2. Update logging code for both install/update and final package listing.
Tested both locally and with GHA

Windows - Install-Msys2.ps1 - minor reliability, taskkill, logging

---

images/win/scripts/Installers/Install-AzureCli.ps1

Azure-cli 2.7.0 [has been released](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.7.0) and the bug with `azdevops login` is supposed to be fixed.
https://github.com/actions/virtual-environments/issues/948
- [N\A ] Documentation is updated (if applicable)

[Windows] rollback azure-cli hardcode and install the latest version

---

images/linux/scripts/installers/azure-cli.sh

Azure-cli 2.7.0 [has been released](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.7.0) and the bug with `azdevops login` is supposed to be fixed.
https://github.com/actions/virtual-environments/issues/948
- [N\A ] Documentation is updated (if applicable)

[Ubuntu] rollback azure-cli hardcode and install the latest version

---

images/win/scripts/Installers/Install-MongoDB.ps1
images/win/scripts/Installers/Install-PostgreSQL.ps1
images/win/scripts/Installers/Validate-MongoDB.ps1
images/win/scripts/Installers/Validate-PostgreSQL.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Databases.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

We have merged PRs for [PostgreSQL](https://github.com/actions/virtual-environments/pull/636) and [MongoDB](https://github.com/actions/virtual-environments/pull/680) on Windows, but they use the old way of docs generation. We should update it in the scope of this ticket.
| Version | UserName | Password | Path                           | ServiceName       | ServiceStatus | ServiceStartType |
| ------- | -------- | -------- | ------------------------------ | ----------------- | ------------- | ---------------- |
| 12.3    | postgres | root     | C:\Program Files\PostgreSQL\12 | postgresql-x64-12 | Stopped       | Disabled         |
| Version | ServiceName | ServiceStatus | ServiceStartType |
| ------- | ----------- | ------------- | ---------------- |
| 4.2.7.0 | MongoDB     | Running …

Update MongoDB and PostgreSQL documentation

---

images/linux/scripts/installers/php.sh

PHP is missing  from Ubuntu 16.04/18.04/20.04 images.
https://github.com/actions/virtual-environments/issues/981

Fix regression with PHP installation

---

images/linux/toolcache-2004.json
images/linux/toolset-2004.json
images/linux/ubuntu2004.json

Add toolcache:
- Ruby    [2.5, 2.6, 2.7]
- Python [2.7, 3.5, 3.6, 3.7, 3.8]
- Pypy     [2.7, 3.6]
- Node    [8, 10, 12, 14]
https://github.com/actions/virtual-environments-internal/issues/629

[Ubuntu 20] Add toolcache(Ruby,Python,PyPy,Node)

---

images/win/scripts/Installers/Finalize-VM.ps1

New tool, Bug fixing, or Improvement?  Improvement!
Suppresses output from `takeown` during `Finalize-VM.ps1`, which reduces Packer overall log size by ~80% (8.87MB -> 1.80MB in a local run of mine).  I didn't observe any speed-up (still took a minute before and after), but I think the log size reduction still makes this worthwhile, and I hope you'll agree!
#1005

Suppress output from takeown during Windows's Finalize-VM.ps1

---

images/win/scripts/Installers/Windows2016/Install-VS2017.ps1
images/win/scripts/Installers/Windows2019/Install-VS2019.ps1

Add new Visual Studio workloads:
Visual Studio Tools for Office (VSTO) build tools
Office/SharePoint development build tools
Windows Workflow Foundation Build Tools
The installed workloads contain components for the development of Office, SharePoint and Workflow foundation application with Visual Studio
**total size.**
200Mb
**installation time**
less than 30sec

AddVisualStudio BuildTools

---

images/win/scripts/Installers/Windows2019/Install-VS2019.ps1

New tool and fixing  
Microsoft.VisualStudio.Component.VC.v141.ATL is needed to build the VC++ projects which are not upgraded to 142 toolkit.
Installation size: **10mb**

Add C++ ATL for v141 build tools (x86 & x64)

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/Installers/Install-Nuget.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

The macOS 10.15 image includes nuget.exe (using Mono) but our Windows images doesn’t. This is unfortunate because publishing NuGet packages doesn’t work consistently with dotnet nuget. Users need to figure out a way to download nuget.exe manually if they want to use it,NuGet.exe is required to consistently install packages to GitHub Packages.
https://github.com/actions/virtual-environments/issues/1039

Add NuGet.exe on Windows Server 2016/2019

---

images/linux/scripts/installers/1604/android.sh
images/linux/scripts/installers/1804/android.sh
images/linux/scripts/installers/2004/android.sh
images/win/scripts/Installers/Update-AndroidSDK.ps1

Based on https://github.com/actions/virtual-environments/pull/1030
This PR add Android 11 platform and build-tools to SDK on linux and windows.

Adding Android 11 (android-30) into SDK installation

---

images/linux/scripts/base/apt.sh
images/linux/scripts/base/limits.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

I propose a slight improvement: Each stanza, like a paragraph or a function, should cover one topic.  Move the apt commands and ulimit adjustments into separate scripts and invoke them separately.
See https://github.com/actions/virtual-environments/issues/1061

Paragraphs (or stanzas) should cover 1 topic only.

---

images/win/scripts/Installers/Install-DotnetSDK.ps1

We are going to remove .NET Core 2.2 on 19 June due to this version has reached end of life.
https://github.com/actions/virtual-environments/issues/975

[Windows] Remove .NET Core 2.2

---

images/linux/scripts/helpers/install.sh

Use `curl` in download retry helper function instead `wget`, because wget can return gzip content.
#1066

Use curl in download retry helper

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/Installers/Install-WindowsUpdates.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1

This addresses the issues raised in #1070, with Windows Updates not being applied to the machine.  To address the two main issues as called out in the bug:
1. I've added `elevated_user`/`elevated_password` properties to the `Install-WindowsUpdates.ps1` PowerShell provisioner, so that updates can actually be properly installed.
2. I've relocated the provisioner to be right before the SoftwareReport is generated.  We want WU to be run as late as possible (even `Install-WindowsUpdates.ps1` included comments about this 😇), so this is a better location for it.  I've also added a reboot task, so that the updates can be properly applied.
Additionally, I've removed one of the `Get-WUInstall` calls to speed up a bit; there shouldn't be a need to run `-WindowsUpdate` prior to `-MicrosoftUpdate`, …

Fixes for Install-WindowsUpdates.ps1 to install updates correctly

---

images/linux/scripts/installers/nvm.sh

Bug fixing
Default Node.JS version is not set for NVM. It causes unexpected behavior of NVM.
Repro steps:
1) `echo "10.20.1" > .nvmrc`
2) `source $HOME/.bash_profile`
3) Fails with non-zero exit code and error that Node.js 10.20.1 is not installed yet.

Setup default NVM Node version properly

---

images/win/scripts/Installers/Install-JavaTools.ps1
images/win/scripts/Installers/Validate-JavaTools.ps1

Improvement: #1057 
Internal issue https://github.com/actions/virtual-environments-internal/issues/683

Switch Java installation to AdoptOpenJDK on Windows

---

images/linux/scripts/installers/java-tools.sh

Improvement
Description: https://github.com/actions/virtual-environments/issues/1057
https://github.com/actions/virtual-environments-internal/issues/685
- [+] Documentation is updated (if applicable)

Add Adopt Open JDK for Ubuntu.

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/Installers/Install-GoogleCloudSDK.ps1
images/win/scripts/Installers/Validate-GoogleCloudSDK.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

Google Cloud SDK is a set of tools that you can use to manage resources and applications hosted on Google Cloud Platform. These include the gcloud, gsutil, and bq command line tools. Google Cloud SDK is already available on the Mac and Ubuntu environments.
Google Cloud SDK:
- Size ~800mb
- Installation time ~ 3 -5 minutes
https://github.com/actions/virtual-environments/issues/206

Add Google Cloud SDK for Windows

---

images/win/scripts/Installers/Install-PostgreSQL.ps1
images/win/scripts/Installers/Validate-PostgreSQL.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Databases.psm1

Bug fixing.
When compiling C++ code using the MinGW install already on the machine, #include <pthread.h> finds a header located in Postgress's install directory
I have verified that the fix works as expected.
https://github.com/actions/virtual-environments/issues/1089
- [-] Changes are tested and related VM images are successfully generated

PostgreSQL: Remove from PATH/Add environment variables.

---

images/linux/scripts/installers/configure-environment.sh

Cannot resolve localhost to an IPv6 address on ubuntu-latest due to missing localhost alias ::1.
Current behavior:
```
ubuntu:~$ java -classpath . Test localhost
localhost/127.0.0.1
```
Expected:
```
ubuntu:~$ java -classpath . Test localhost
localhost/127.0.0.1
localhost/0:0:0:0:0:0:0:1
```
https://github.com/actions/virtual-environments/issues/929

[Ubuntu] Add localhost alias ::1 IPv6

---

images/linux/scripts/installers/docker-moby.sh

After the new version of Docker-Moby was released for Ubuntu 16.04 the image generation process is failing with the error:
```
azure-arm: Server:
azure-arm: ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
```
https://github.com/actions/virtual-environments-internal/issues/748

[Ubuntu] Start and enable docker.service if not running or enabled

---

images/linux/scripts/installers/aws-sam-cli.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

Aws-sam-cli is supposed to be installed via homebrew yet that approach leads to install separate python3, which overrides system one and causes issues for some customers. The workaround was implemented here https://github.com/actions/virtual-environments/pull/789 but it turned out that brew functionality is partly broken after the changes.
The solution is to get-rid of brew aws-sam cli installation and use `setup.py` script that comes along with aws-sam sources. After these changes, another PR will be made to move homebrew to the beginning of the PATH as it was initially.
Changes:
- Aws-sam-cli installation switched to build from sources via setup.py script
- Installation script moved to the end of the template in order to run after toolset installation …

[Ubuntu] Install aws-sam-cli without brew

---

images/linux/scripts/installers/aws.sh

Bug fixing  
In scope of this PR we are updating AWS CLI V1 to V2 on Ubuntu 20.04 image to fix issue that occurs with AWS CLI V1 ('ascii' codec can't decode byte 0xc3 in position 66: ordinal not in range(128)). 
We are planning to merge this PR on 7/6/2020. Related announcement: [**#1108**](https://github.com/actions/virtual-environments/issues/1108)

Update AWS CLI V1 to V2 on Ubuntu 20.04 Image

---

images/linux/scripts/installers/aws-sam-cli.sh
images/linux/scripts/installers/homebrew-validate.sh
images/linux/scripts/installers/homebrew.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

This is the second PR to resolve the initial issue. We don't use brew to install tools anymore after https://github.com/actions/virtual-environments/pull/1160 so brew executables can be safely placed at the beginning of the `PATH` in order to install tools via brew **in runtime** correctly
`/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin` -> `/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/l …

[Ubuntu] Prepend brew directories to the PATH

---

images/win/scripts/Installers/Install-Git.ps1

Bug fix: enable symlink support of Git for Windows
@al-cheb reached out privately to ask whether it would be a good idea to enable Git's symbolic link support, and I think it makes sense.

Install Git for Windows with symbolic links enabled

---

images/linux/scripts/installers/aliyun-cli.sh
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

It has a version sub command, and --version is used to specify product api version,
not to get version of aliyun-cli.
Improvement of getting version of aliyun-cli.

Fix getting version of aliyun cli.

---

images/linux/scripts/helpers/document.sh
images/linux/scripts/installers/php.sh

Bug fixing.
ppa:ondrej/php repository is used to install PHP and the modules. Currently it contains libzip-dev package corresponding to libzip4 shared libraries. Ubuntu 20.04 does not contain libzip4 so, instead it has libzip5 libraries. As a result the binaries built with pipelines are linked against to libzip4 and crash on the real life Ubuntu 20.04 
As a solution in this PR i removed the ppa:ondrej/php right after PHP has been installed.

Remove  ppa:ondrej/php from the list of apt repositories

---

images/win/scripts/ImageHelpers/TestsHelpers.ps1

Issue:
PowerShell Desktop can't import ImageHelpers module with unicode char:
```
PS > Import-Module C:\Users\testAdm2\Desktop\virtual-environments\images\win\scripts\ImageHelpers\ImageHelpers.psm1
At .\virtual-environments\images\win\scripts\ImageHelpers\TestsHelpers.ps1:83 char:11
+         $ÑommandOutputIndent = " " * 4
+           ~~~~~~~~~~~~~~~~~~~
Unexpected token 'ommandOutputIndent' in expression or statement.
+ CategoryInfo          : ParserError: (:) [], ParseException
+ FullyQualifiedErrorId : UnexpectedToken
```

Fix unicode char c=1089 to c=99 in TestsHelpers.ps1

---

images/linux/scripts/installers/rust.sh

`rm -rf` with quotes doesn't do the job
https://github.com/actions/virtual-environments/issues/895

[Ubuntu] Fix Cleanup Cargo registry data folders

---

images/win/scripts/Installers/Install-Toolset.ps1

Since, we are working on adding support for unstable versions of Python, `versions-manifest.json` will include versions in format `3.9.0-beta.2` and etc.
`[System.Version]` type doesn't support such format and will fail even we don't cache such versions on image. Just on parsing of `versions-manifest.json`.
This PR removes sorting of versions because it is redundant. `versions-manifest.json` is sorted by default and we don't need to sort it one more time

Toolset support for Semver notation

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

WSL was added to Windows 2019 only in the scope of this PR, but it seems we forget to add a condition in the software report generator.
https://github.com/actions/virtual-environments/issues/50

[Windows] Remove WSL from software output on Windows 2016

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json

Recently, Windows 2016 builds started to fail on reboot step after update installation: https://github.visualstudio.com/virtual-environments/_build/results?buildId=75637&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=486c0909-f67d-5748-80b3-bb1d531e7b43 due to ` vhd: Timeout waiting for machine to restart`.
https://github.com/actions/virtual-environments-internal/issues/839

[Windows] Increase windows update restart timeout to 30 min

---

images/win/scripts/SoftwareReport/SoftwareReport.Android.psm1

Bug fixing: this flag has broken software report generation.

Remove verbose flag from android helper

---

images/linux/scripts/installers/swig.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

This PR adds on all Ubuntu images new tool - Swig. 
`apt-get` was used for installation.
#1203

Add swig support

---

triage-rules.yml

We don't want to mark issues as bugs before investigation and confirmation that it is a real bug

Disable auto triage rules for type of issue

---

images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1

Version numbers for the Wix Toolset and Wix Visual Studio Extension in documentation are flipped. In scope of this PR we are fixing it.
https://github.com/actions/virtual-environments/issues/1299

[Windows] Fix Wix Toolset version numbers in documentation

---

CONTRIBUTING.md
images/win/scripts/ImageHelpers/VisualStudioHelpers.ps1
images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1

Currently, VS Extensions are being displayed in documentation without its versions. This issue came with [this ](https://github.com/actions/virtual-environments/pull/1251)PR. In scope of this PR we are adding versions of VS Components back to documentation.

[Windows] Add back to documentation versions of Visual Studio Components

---

images/linux/scripts/installers/php.sh

Provide documentation about installed openssl and libssl-dev package versions for Ubuntu images.
ubuntu 16.04:
```
- OpenSSL 1.1.0h  27 Mar 2018 (Library: OpenSSL 1.1.1g  21 Apr 2020)
- Libssl 1.1.1g-1+ubuntu16.04.1+deb.sury.org+1
```
ubuntu 18.04:
```
- OpenSSL 1.1.1g  21 Apr 2020
- Libssl 1.1.1g-1+ubuntu18.04.1+deb.sury.org+1
```
ubuntu 20.04:
```
- OpenSSL 1.1.1f  31 Mar 2020
- Libssl 1.1.1f-1ubuntu2
```
https://github.com/actions/virtual-environments/issues/1307

[Ubuntu] Provide documentation about installed openssl and libssl-dev package versions

---

images/win/Windows2019-Azure.json
images/win/scripts/Installers/Run-NGen.ps1

https://support.microsoft.com/en-us/help/2570538/installing-updates-for-the-microsoft-net-framework-4-can-take-longer-t - When you install an update for the Microsoft .NET Framework 4, the Native Image Generator (NGen.exe) uses a high percentage of the CPU cycles on the computer for a long time. This time varies with how many Native Images are installed on the computer.
https://github.com/actions/virtual-environments/issues/1269

[Windows] .NET Framework  Performance Issue

---

images/linux/scripts/installers/firefox.sh

Ubuntu image generation is broken due to incorrect download link for geckodriver.
```
azure-arm: Downloading geckodriver https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
azure-arm: https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc
==> azure-arm: --2020-07-30 01:44:44--  https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz%0Ahttps://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc
==> azure-arm: Resolving github.com (github.com)... 192.30.255.112
==> azure-arm: Connecting to github.com (github.com)|192.30.255.112|:443... connected.
==> azure-arm: HTTP request sent, awaiting response... 404 Not …
```

[Ubuntu] Fix incorrect parsing download url for geckodriver

---

images/linux/scripts/installers/basic.sh

Add brotli to linux images
Approximate size: 730.0 kB (Installed size in Ubuntu 20.04: https://packages.ubuntu.com/focal/brotli)
Tests should already be included: https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/basic.sh#L94-L101

Add brotli to linux images

---

images/win/Windows2016-Azure.json
images/win/scripts/Installers/Install-AliyunCli.ps1

Alibaba-cli chocolatey package is outdated, it was updated in 2019 last time
https://chocolatey.org/packages/aliyun-cli
Switch to download the latest release from GitHub since the installation is pretty simple — the archive contains only 1 exe file.
https://github.com/actions/virtual-environments/issues/1350

[Windows] Change Alibaba Cloud CLI installation to direct download

---

images/linux/scripts/installers/basic.sh

Modifies the existing script to add libc++ and libc++abi to all Ubuntu images, rather than just 16.04.

Add libc++ and libc++abi for all Ubuntu images

---

images/linux/scripts/installers/docker-moby.sh

This is to add buster image as part of the cache
#1358

add buster layer to github runner's cache

---

images/win/scripts/Installers/Install-NSIS.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

Bug fixing
It is temporary workaround to fix the issued with non-working NSIS download link https://astuteinternet.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe used by choco 
Use https://jztkft.dl.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe -Name nsis-3.05-setup.exe instead
- [x ] Changes are tested and related VM images are successfully generated

Install NSIS from Source Forge

---

images/linux/scripts/installers/cleanup.sh

Truncate log files in /var/log folder to save disk space and decrease content for debugging purpose.
https://github.com/actions/virtual-environments-internal/issues/943

[Ubuntu] Truncate log files at the end of the image generation

---

images/linux/scripts/installers/mongodb.sh
images/linux/ubuntu2004.json

Mongodb 4.2 doesn't support Ubuntu 20.04, that's why we decided to update mongodb from v4.2 to v4.4 version that supports Ubuntu 20.04. In that case we will use the same mongodb v4.4 version for all Ubuntu 16.04/18.04/20.04 images and thus avoiding to support separate branches 4.2/4.4.  
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/#platform-support
```
MongoDB 4.4 Community Edition supports the following 64-bit Ubuntu LTS (long-term support) releases on x86_64 architecture:
20.04 LTS (“Focal”)
18.04 LTS (“Bionic”)
16.04 LTS (“Xenial”)
```
https://github.com/actions/virtual-environments-internal/issues/947

[Ubuntu] Update mongodb 4.2 -> 4.4 lts

---

images/win/scripts/Installers/Install-MongoDB.ps1

The MongoDB v4.4.0 package in chocolatey repository is currently broken. The root cause is a msi package doesn't contain components what previous version has:
` ["C:\windows\System32\msiexec.exe" /i "C:\Users\packer\AppData\Local\Temp\chocolatey\mongodb.install\4.4.0\mongodb-windows-x86_64-4.4.0-signed.msi" ADDLOCAL="Server,ServerService,Router,Client,MonitoringTools,ImportExportTools,MiscellaneousTools" /qn /norestart MONGO_DATA_PATH="C:\ProgramData\MongoDB\data\db"  MONGO_LOG_PATH="C:\ProgramData\MongoDB\log"  ] .`
As a temporary fix is to hard-coded previous MongoDB v4.2.8 version.
v4.4.0:
`ADDLOCAL=ServerService,Server,ProductFeature,Client,Router,MiscellaneousTools`
v4.2.8:
`ADDLOCAL="Server,ServerService,Router,Client,MonitoringTools,ImportExportTools,MiscellaneousTools"` …

[Windows] Hard-coded MongoDB v4.2.8

---

helpers/CreateAzureVMFromPackerTemplate.ps1

I ran into problems using CreateAzureVMFromPackerTemplate.ps1 because the subscription ID I passed in was not the default subscription in my account. Some of the Azure CLI commands failed even though the script passes in the `-r` and `--subscription` arguments. There might be a deeper problem in the Azure CLI, but I changed the script to pass in full resource IDs and the problem went away. I decided to submit a PR in case my changes are of value to anyone else.
I also cleaned up the output to make it more consistent. Each Azure CLI command now prints the JSON for the created/updated resource to the console (before, some commands did and others didn't).

Use full resource IDs and clean up output

---

images/linux/scripts/installers/dotnetcore-sdk.sh
images/win/scripts/Installers/Install-DotnetSDK.ps1

Improvement
Looks like DOTNET_MULTILEVEL_LOOKUP that is enabled by default causes big delays in customers' builds that use DOTNET. We got request from .NET Core team to set environment variable DOTNET_MULTILEVEL_LOOKUP=0 for all runners (macOS, Ubuntu, Windows) images.
https://github.com/actions/virtual-environments-internal/issues/944
- [ -] Changes are tested and related VM images are successfully generated

Add DOTNET_MULTILEVEL_LOOKUP variable.

---

images/win/scripts/Installers/Install-MongoDB.ps1

Chocolatey MongoDB v4.4.0 package installation was fixed - https://github.com/mkevenaar/chocolatey-packages/pull/63. We don't need to hard-code mongodb version.

[Windows] Revert mongodb fix

---

images/win/scripts/Installers/Initialize-VM.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

msvcr100.dll - is missing for Windows Server 2019. We should install `Microsoft Visual C++ 2010 Redistributable Package` to fix missing dll for Windows Server 2019. 
Example output:
| Name                                         | Architecture | Version     |
| -------------------------------------------- | ------------ | ----------- |
| Microsoft Visual C++ 2010 Redistributable    | x64          | 10.0.30319  |
| Microsoft Visual C++ 2010 Redistributable    | x86          | 10.0.40219  |
| Microsoft Visual C++ 2012 Additional Runtime | x64          | 11.0.61030  |
| Microsoft Visual C++ 2012 Minimum Runtime    | x64          | 11.0.61030  |
| Microsoft Visual C++ 2013 Additional Runtime | x64          | 12.0.40660  |
| Microsoft Visual C++ 2013 Minimum Runtime    | x64          | …

[Windows 2019] Fix missing msvcr100.dll

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/Installers/Configure-DynamicPort.ps1
images/win/scripts/Tests/WindowsFeatures.Tests.ps1

After installing VS via script https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-VS.ps1 the dynamic port range is changed to:
```
Protocol tcp Dynamic Port Range
vhd: ---------------------------------
vhd: Start Port      : 1024
vhd: Number of Ports : 64511
```
Example https://github.visualstudio.com/virtual-environments/_build/results?buildId=78654&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=486c0909-f67d-5748-80b3-bb1d531e7b43 : 
Before Visual Studio installation [703]:
```
==> vhd: Provisioning with powershell script: C:\agent\_work\9\s\images\win/scripts/Installers/Install-VS.ps1
vhd: Display ports
vhd:
vhd: Protocol tcp Dynamic Port Range
vhd: ---------------------------------
vhd: Start Port      : 49152
vhd: Number of Ports : …
```

[Windows] Set the dynamic port range to start at port 49152 and to end at the 65536 (16384 ports)

---

images/linux/scripts/installers/aws-sam-cli.sh

Aws-sam-cli url changed from https://github.com/awslabs/aws-sam-cli to https://github.com/aws/aws-sam-cli and that breaks image generation.
n\a

[Ubuntu] Fix aws-sam-cli repository url

---

images/linux/scripts/installers/java-tools.sh

24 June 2020 we merged our pull request with migration from Java Zulu to AdopOpenJdk. We got an issue that on ubuntu16 java and javac versions are different. On all other images they have same java and javac versions. With this pull request we want to manually setup javac version for ubuntu 16.04.
Ubuntu 16.04:
- java -version: 
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```
- javac -version: 
```
javac 1.7.0_272
```
Java config for Ubuntu 16.04:
```
Selection    Path                                                  Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/zulu-7-azure-amd64/bin/javac …
```

Set javac version 1.8 on Ubuntu 16.04

---

images/linux/scripts/installers/mono.sh

This installs NuGet, a package manager widely used in Mono applications alongside Mono itself. A relatively up-to-date version of the NuGet package is available in the same repository as Mono itself (`download.mono-project.com`).
The total size of the package is 1.3MB and it takes approximately 2.5 seconds to install.

Install NuGet when installing Mono.

---

images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

Current documentation displays Github CLI version as
GitHub CLI gh version 0.11.1 (2020-07-28) https://github.com/cli/cli/releases/tag/v0.11.1
but should display as
GitHub CLI 0.11.1

the Github CLI version fix for short version number

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/Installers/Install-Pulumi.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/win/scripts/Tests/Tools.Tests.ps1

This installs Pulumi on Windows images, the latest available version will be installed.
The total size of the package is 57MB and it takes approximately 10 seconds to install.

Add Pulumi to Windows images

---

.github/workflows/create_pull_request.yml
.github/workflows/merge_pull_request.yml

Sometimes, merge-pull-request workflow fails because of conflicts in PR. It happens when current deployment was started earlier then previous one was finished.
Changes:
- Added step to create special branch for pull request
- Added step to resolve PR's conflicts in this branch before merging to main
- Added step to delete this additional branch
Internal issue: [#908](https://github.com/actions/virtual-environments-internal/issues/908)

Resolve possible conflicts in software update PR

---

images/linux/scripts/installers/android.sh

FIx the issue with android permissions. The following command `/usr/local/lib/android/sdk/tools/bin/sdkmanager "add-ons;addon-google_apis-google-19"` threw an error if it run without sudo permissions. It was fixed by adding permissions after creation all directories.

Fix android permissions

---

images/linux/scripts/helpers/install.sh
images/linux/scripts/installers/git.sh

New tool, Bug fixing, or Improvement?  Improvement
Snap is no more the recommended way to install `hub`, as stated on the [official project](https://github.com/github/hub#installation).

Install hub without snap

---

images/win/scripts/ImageHelpers/ImageHelpers.psm1
images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/ImageHelpers/VisualStudioHelpers.ps1
images/win/scripts/Installers/Install-VS.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.VisualStudio.psm1
images/win/scripts/Tests/SSDTExtensions.Tests.ps1
images/win/scripts/Tests/VisualStudio.Tests.ps1
images/win/scripts/Tests/WDK.Tests.ps1
images/win/scripts/Tests/Wix.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

Added Visual Studio build tools installation for Windows 2016/2019 images with vs_buildtools.exe installer. Minor changes for current VS installation, testing and documentation.
This functionality creates an opportunity to install workloads corresponding to Visual Studio build tools.
Seems that vs_enterprise.exe can't install properly the Microsoft.VisualStudio.Workload.WebBuildTools workload, the installation process ends without errors, but the workload components are not installed. The vs_buildtools.exe looks like the proper way of installation for build tools workloads (as said in documentation, [Microsoft docs link](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019)), Microsoft.VisualStudio.Workload.WebBuildTools in this case. …

Add VS build tools installation

---

images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

It seems multi-line announcements can't be properly parsed when using `sh -c`, the error in the log is:
```
2020-09-08T20:18:48.0470937Z  mmsprodwcus0    2020/09/08 20:15:01 packer.exe: 2020/09/08 20:15:01 [DEBUG] starting remote command: sudo sh -c 'ANNOUNCEMENTS='| Announcements |
2020-09-08T20:18:48.0471878Z  mmsprodwcus0    2020/09/08 20:15:01 packer.exe: |-|
2020-09-08T20:18:48.0472816Z  mmsprodwcus0    2020/09/08 20:15:01 packer.exe: | [Clang/LLVM 10 will be set as a default one and Clang/LLVM 6 will be deprecated  for Ubuntu 20.04 on September, 16](https://github.com/actions/virtual-environments/issues/1536) |' HELPER_SCRIPTS='/imagegeneration/helpers' IMAGE_VERSION='20200908.1' METADATA_FILE='/imagegeneration/metadatafile' PACKER_BUILDER_TYPE='azure-arm' …
```

[Ubuntu] Fix announcements rendering

---

images/win/scripts/Installers/Install-NodeLts.ps1

New tool, Bug fixing, or Improvement?   Bug
Some tools like Yarn will spawn nodeJS via CreateProcess and pass an environment block that contains duplicated environment variables, e.g:
Windows doesn't do any checking of environment variables being duplicated in CreateProcess so the node.exe process gets created with the two names. Then in our case, MSBuild gets launched from within node.exe, which later launches CL.exe and other build tools.
The Azure DevOps CI pipeline sets NPM_CONFIG_CACHE (all caps), while yarn will add the lowercase npm_config_cache to the environment block when a process is launched via child_process.exec()
As a result of this, we are hitting an error in our CI because MultiTaskTool is probably putting variables in a case-insensitive dictionary and doesn't expect to …

MSBuild/CL.exe fails to launch when called from a nodeJS script via Yarn 

---

images/win/scripts/Installers/Install-DotnetSDK.ps1
images/win/scripts/Tests/DotnetSDK.Tests.ps1

- fix for falling tests with dot net on windows images, because we download rc version.

Fix dot net test issue with 5.0 version

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md

Since our MacOS CI doesn't support external contributions, we would like to update contribution guide to prevent customers about contributing to MacOS source.

Update contribution guide for MacOS image to prevent customers contributing to MacOS source

---

images/win/scripts/Installers/Install-PyPy.ps1

It turned out the filter for PyPy versions doesn't avoid rc versions.
n\a

[Windows] Fix PyPy versions filter to avoid release candidates

---

images/win/scripts/Installers/Install-Edge.ps1

Webdriver win64 for version 85.0.564.60 doesn't exist thus all windows builds are broken. Temporary hardcode 85.0.564.51 installation.
n\a

[Windows] Workaround for missing Edge webriver

---

images/linux/scripts/installers/post-deployment.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

Add 777(rwx) permissions for `/opt` directory during image generation.
https://github.com/actions/virtual-environments-internal/issues/1177

[Ubuntu] Set chmod -R 777 /opt

---

images/macos/provision/configuration/configure-machine.sh
images/macos/tests/Common.Tests.ps1

Enterprise iOS Distribution Certificates generated between February 7 and September 1st, 2020 will expire on February 7, 2023. Rotate the certificate before expiration to ensure your apps are installed and signed with an active certificate.
Enterprise iOS Distribution Certificates generated after September 2, 2020 require the new intermediate certificate installed on any machines that will be code signing. Xcode 11.4.1 or later automatically downloads the new Apple Worldwide Developer Relations Intermediate Certificate, and it is also available directly from the Certificate Authority page. Confirm that the correct intermediate certificate is installed by verifying the expiration date is set to 2030.
https://github.com/actions/virtual-environments/issues/1620

[macOS] Apple Worldwide Developer Relations Intermediate Certificate Expiration

---

images.CI/macos/azure-pipelines/image-generation.yml

For now we can't rerun failed build, because it fails due to new virtual machine has the same name as previous VM. Adding attempt counter we create new virtual machine name on rerun failed build.

Add attempt count to macOS VM name

---

images/macos/provision/core/commonutils.sh
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/Common.Tests.ps1

1. R - postflight script for R  contains incorrect regex conditions due to that there are no symlinks in /usr/local/bin
```
if uname -r | grep '^1[5-9]' >/dev/null; then
if [ ! -e /usr/local/bin ]; then
mkdir -p /usr/local/bin
fi
cd /usr/local/bin
fi
```
2. virtualbox - currently doesn't support macOS Big Sur[[Big Sur Host Issues]( https://forums.virtualbox.org/viewtopic.php?f=39&t=98763) ] and unable to start vm
3. vagrant - tied to VirtualBox
https://github.com/actions/virtual-environments-internal/issues/1176

[macOS] Remove R and virtualbox packages for macOS Big Sur

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/installers/gcc.sh

In scope of this PR we add GCC 10 for Ubuntu 18.04/20.04 and fix output version order in markdown.
Gcc-10 is not available for Ubuntu 16.04.
https://github.com/actions/virtual-environments/issues/1604

[Ubuntu] Add GCC 10

---

helpers/GenerateResourcesAndImage.ps1

Bug: `New-AzADServicePrincipal` cmdlet is invoked with incorrect argument name and argument type: `Password` instead `PasswordCredential` and `<SecureString>` type instead `<PSADPasswordCredential[]>`. It throws the following error:
```
GenerateResourcesAndImage : Cannot bind parameter 'PasswordCredential'. Cannot convert the
"System.Security.SecureString" value of type "System.Security.SecureString" to type
"Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential".
```
Az module doc about `New-AzADServicePrincipal`: [link](https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadserviceprincipal?view=azps-4.7.0)
These changes were tested locally and it works.
#1664

Fix credentials in GenerateResourcesAndImage.ps1

---

images/linux/scripts/installers/clang.sh

In scope of this PR we decided to install clang from from official repository for  Ubuntu 18.04/20.04 and use llvm.sh for clang-9 on Ubuntu-16.04 only(missing in the official repository). In that way, we don't need to add llvm repository manually when we need to install additional packages(e.g.: apt-get install clang-tidy-10).
https://github.com/actions/virtual-environments/issues/1536

[Ubuntu] Use official repository to install clang

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

The line contains incorrect statement that cause the errors:
https://github.com/actions/virtual-environments/blob/b0f3f989abd744ea6bfcaf62fc5decf19f8853b6/images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1#L37
```
char:36
+     $CodeQLVersion = $($CodeQLPath version --quiet)
+                                    ~~~~~~~
Unexpected token 'version' in expression or statement.
Import-Module : The specified module
'..\virtual-environments\images\win\scripts\SoftwareReport\SoftwareReport.Tools.psm1' was
not loaded because no valid module file was found in any module directory.
At line:1 char:1
```
https://github.com/actions/virtual-environments-internal/issues/1213

[Windows] Fix Get-CodeQLBundleVersion output

---

images/macos/provision/configuration/configure-machine.sh

It turned out we have a few CPU-consuming processes on the base image after the generation. These mdworker processes belong to spotlight search indexing, and it looks like we don't use spotlight at all so the indexing can be safely turned off.
https://github.com/actions/virtual-environments-internal/issues/1212

[macOS] Disable spotlight indexing

---

images/macos/provision/core/pypy.sh

The recently released PyPy 7.3.2 for High Sierra is broken and is already fixed in the main PyPy branch but not yet released https://foss.heptapod.net/pypy/pypy/-/issues/3311
To avoid build failures 7.3.1 can be installed for HS.
As an additional change — workaround for 7.3.1 removed from 10.14 & 10.15 PyPy installations.
https://github.com/actions/virtual-environments-internal/issues/1217

[macOS] Hardcode PyPy 7.3.1 for macOS-10.13

---

images/win/scripts/Installers/Update-DockerImages.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

In scope of this [work item](https://github.com/actions/virtual-environments-internal/issues/1215) we have moved the list of Docker images to toolset on Windows and updated the Update-DockerImages.ps1 script

Move the list of Docker images to toolset on Windows

---

images/linux/scripts/installers/python.sh
images/linux/toolsets/toolset-2004.json

Currently, Python 2.7 is set by default on Ubuntu 20.04. Python 2 was sunsetted on Jan 1 2020 and this version is not supported anymore. In scope of this PR we set the default Python to 3.8 on Ubuntu 20.04.
Alias:
```
/usr/bin/python -> /usr/bin/python3 ->  /usr/bin/python3.8
/usr/bin/pip -> /usr/bin/pip3
```
https://github.com/actions/virtual-environments/issues/1591

[Ubuntu] Default Python will be switched to 3.8 on Ubuntu 20.04

---

images/macos/provision/core/audiodevice.sh
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

Xamarin iOS 14 requires Xcode 12, so we can't set it by default along with Xcode 11.7.
The default Xcode will be switched to 12 in 2-3 weeks.
As an addition permissions for audio devices were moved to the base image since they are not functional during the image generation because of enabled SIP.
https://github.com/actions/virtual-environments/issues/1712

[macOS] Set 6_12_0 as default Xamarin bundle

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1

Currently `- CodeQL Action Bundle ` version is missing due to incorrect  directory case name. 
```
2020-09-30T17:25:09.6741308Z ==> azure-arm: [91mGet-ChildItem: [0m/imagegeneration/SoftwareReport/SoftwareReport.Tools.psm1:33
2020-09-30T17:25:09.6749043Z ==> azure-arm: [96m  33 | [0m â€¦    $CodeQLVersionPath = [96mGet-ChildItem $CodeQLVersionsWildcard[0m | Selec â€¦
2020-09-30T17:25:09.6761964Z ==> azure-arm: [91m[96m     | [91mCannot find path '/opt/hostedtoolcache/codeql' because it does
2020-09-30T17:25:09.6884852Z ==> azure-arm: [91mJoin-Path: [0m/imagegeneration/SoftwareReport/SoftwareReport.Tools.psm1:34
2020-09-30T17:25:09.6889840Z ==> azure-arm: [96mLine |
2020-09-30T17:25:09.6899425Z ==> azure-arm: [96m  34 | [0m     $CodeQLPath = Join-Path …
```

[Ubuntu] Fix CodeQL version output in markdown file

---

images/win/Windows2016-Azure.json
images/win/Windows2019-Azure.json
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Currently, Update-DockerImages.ps1 doesn't work properly due to missing TOOLSET_JSON_PATH.
Changes:
- Add TOOLSET_JSON_PATH
- Return "Cached Docker images"
https://github.com/actions/virtual-environments-internal/issues/1244

[Windows] Fix Update-DockerImages.ps1 installation

---

images/macos/software-report/SoftwareReport.Generator.ps1

After installing Xcode 12 xcrun simctl list --json doesn't provide full list of devices and runtimes after first lunch. The second attempt works as expected.
```
==> vsphere-clone: MethodInvocationException: /Users/runner/image-generation/software-report/SoftwareReport.Xcode.psm1:206
==> vsphere-clone: Line |
==> vsphere-clone:  206 |          return [PSCustomObject] @{
==> vsphere-clone:      |                 ~~~~~~~~~~~~~~~~~~~
==> vsphere-clone:      | Exception calling "Join" with "2" argument(s): "Value cannot
==> vsphere-clone:      | be null. (Parameter 'values')"
==> vsphere-clone: 
==> vsphere-clone: MethodInvocationException: /Users/runner/image-generation/software-report/SoftwareReport.Xcode.psm1:206
==> vsphere-clone: Line |
==> vsphere-clone:  206 |          return …
```

[macOS] Fix Xcode simulators section

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

Currently, Erlang version is missing in the markdown documentation due to incorrect regex pattern(current version 11.1).  Fix: use eval to  get system_info(version).
https://github.com/actions/virtual-environments-internal/issues/1246

[Ubuntu] Fix erlang version output

---

images/macos/provision/core/commonutils.sh

This PR updates the `gh` tool's homebrew formula name to use the updated formula name. The new formula can be seen [here](https://github.com/Homebrew/homebrew-core/blob/38d4781f10b61240c109ad08c4824e1c01f7ca82/Formula/gh.rb).
cc https://github.com/actions/virtual-environments/issues/1734

[macOS] Update gh homebrew formula name

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/SoftwareReport/SoftwareReport.Helpers.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1

Currently, The utils: Helm, Yarn, Buildah, Podman, GitHub CLI don't provide version output in the markdown documentation due to lack of permissions. Fix: restore files owner in user profile.
https://github.com/actions/virtual-environments-internal/issues/1247

[Ubuntu] Fix output Helm, Yarn, Buildah, Podman, GitHub CLI

---

images/linux/scripts/installers/nvm.sh
images/macos/provision/core/nvm.sh

~New tool~, ~Bug fixing~, or Improvement?
Current nvm installer scripts, both on Linux and macOS, are requiring manual updates on every new nvm release. This change is to make it more automated, and to keep up with the latest releases of nvm. It also fixes a small redirect problem in macOS script. URL was pointing to the old repository, and now it's the correct one. I understand you don't accept any external contributions to macOS images, if you prefer, I can split the changes and create a PR for Linux, and an issue for macOS.

[Linux, macOS] Improve nvm installer

---

images/macos/provision/core/haskell.sh

Ghcup output has changed recently and awk doesn't work for us anymore, it returns the wrong data either in $3 or $4
The solution is switching to grep usage and search the version by pattern.
https://github.com/actions/virtual-environments-internal/issues/1261

[macOS] Fix haskell installation

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/macos/software-report/SoftwareReport.Generator.ps1

In scope of this PR  we set `$ErrorActionPreference = "Stop"`  to prevent the image generation process if errors occur.

[macOS] Set $ErrorActionPreference = "Stop" in SoftwareReport.Generator.ps1

---

.github/workflows/issue-triager.yml

Updated triage bot to avoid setting of "needs triage" to announcements
- [ n/a] Related issue / work item is attached
- [n/a ] Tests are written (if applicable)
- [n/a ] Documentation is updated (if applicable)
- [n/a ] Changes are tested and related VM images are successfully generated

Do not set "needs triage" to Annoucements

---

images.CI/macos/azure-pipelines/image-generation.yml
images.CI/macos/destroy-vm.ps1

Currently, we don't delete any macOS VMs on build canceling.
https://github.com/actions/virtual-environments-internal/issues/1248

[images.CI] Delete macOS VMs on build canceling

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1

In scope of this PR we set $ErrorActionPreference = "Stop" to prevent the image generation process if errors occur.
Changes:
- Add $ErrorActionPreference = "Stop"
- Replace 2>&1 to Get-CommandResult

[Ubuntu] Replace 2>&1 to Get-CommandResult

---

images/linux/scripts/installers/docker-moby.sh

Docker-moby packages for Ubuntu 20 were pushed to the prod channel so we can switch to it and get rid of OS condition.
n\a

[Ubuntu 20] Switch docker-moby installation to prod channel

---

images/macos/provision/core/edge.sh

Microsoft Edge webdriver is broken since version 86 with the following error:
```
Command 'msedgedriver --version' has finished with exit code
dyld: Library not loaded: @rpath/libc++.dylib   Referenced from: /usr/local/bin/msedgedriver   Reason: image not found
```
This PR hardcodes version 85 until we've found the root cause.
n\a

[macOS] Add workaround to install edge 85 instead of the latest one

---

images/win/scripts/Installers/Install-Haskell.ps1

Currently, our version query for haskell doesn't take care of broken packages so 8.10.2.1 package, which is currently broken, marked as the latest one.
To avoid this situation we need one more condition to filter unapproved versions.
n\a

[Windows] Install approved haskell versions only

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

Due to $ErrorActionPreference = "Stop" in the software report generator we need to acquire pipx version via Get-CommandResult to avoid build failures.
Without Get-Command:
With Get-Command
n\a

[Ubuntu] Fix pipx output in the software report generator

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

`pipx --version` command writes some symbols to stderr:

[Ubuntu] Fix pipx version on software report

---

images/linux/scripts/installers/android.sh
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json

Currently, we are installing a bunch of Android build-tools packages that are marked as obsolete. We are going to stop installing them on images starting of October, 20.
Changes:
- remove parameter --include_obsolete
- set build_tools_min_version": "19.1.0"
https://github.com/actions/virtual-environments/issues/1743

[Ubuntu] Do not install obsolete Android build-tools packages

---

images/macos/provision/core/node.sh
images/macos/tests/Common.Tests.ps1

We've run into an issue with the `mobile-center-cli` package during the image generation. We've noticed that the `mobile-center-cli` package is no longer supported. In scope of this PR we removed installation of the `mobile-center-cli` from all MacOS images.

Remove mobile-center-cli package from MacOS images

---

images/win/windows2016.json
images/win/windows2019.json

Improvement
According to the [packer documentation ](https://www.packer.io/docs/provisioners/file#directory-uploads), it is required to copy folder into directy itself without trailing slash, or using trailing slash right after directory. Currently, we have nested folder inside C:\post-generation folder.
https://github.com/actions/virtual-environments-internal/issues/1191

Remove nested post-generation folder.

---

images.CI/macos/azure-pipelines/image-generation.yml

Currently, the name of VM is not equal to BuildNumber. It brings some issues and it is not clear how to find specific VM.
We need to update BuildNumber accordingly.

Update BuildNumber to include retry number

---

images/macos/provision/core/rubygem.sh

Freeze `xcodeproj` (dependency of cocoapods) on 1.18.0 since 1.9.0 contains breaking changes.
Related issue: https://github.com/CocoaPods/CocoaPods/issues/10153

Freeze xcodeproj 1.18.0

---

images/macos/tests/Python.Tests.ps1

There was a bug recently when pip3 was linked to the python3 version differing from the default one. We'd missed that during image generation and received a few issues.
This PR adds a test for such a case.
https://github.com/actions/virtual-environments/issues/1819
https://github.com/actions/virtual-environments/issues/1818

[macOS] Add pester test for pip3 path

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

Current `(?<version>\d+\.\d+\.\d+)` regex doesn't suitable to match new Gradle 6.7 version.
https://github.com/actions/virtual-environments-internal/issues/1325

[Ubuntu] Fix gradle version

---

images/macos/provision/core/aws.sh

Recently we've faced some unpredictable dependencies coming from brew aws-cli formula. According [to the docs ](https://docs.aws.amazon.com/cli/latest/userguide/install-macos.html) the recommended installation method is via a package. Furthermore, package installation consumes less space than the brew one and contains all required dependencies.
**Package**:
```
du -sh /usr/local/aws-cli
87M	/usr/local/aws-cli
```
**Brew** with python 3.9 preinstalled separately:
```
du -sh /usr/local/Cellar/awscli/2.0.57
114M	/usr/local/Cellar/awscli/2.0.57
```
https://github.com/actions/virtual-environments/issues/1819

[macOS] switch aws-cli installation to the pkg

---

images/win/scripts/Installers/Install-Haskell.ps1
images/win/scripts/Tests/Haskell.Tests.ps1

Haskell versions with revisions(7.10.2.**1**, 8.10.2.**1**, etc) installed in the directory with a different pattern — not `C:\ProgramData\chocolatey\lib\ghc.8.10.2.1\tools\ghc-8.10.2.1` but `C:\ProgramData\chocolatey\lib\ghc.8.10.2.1\tools\ghc-8.10.2\bin`
This PR adds the capability to set such a version as a default one and also fixes all related Haskell tests to be compatible with these "revision" versions.
https://github.com/actions/virtual-environments-internal/issues/1331

[windows] Fix Haskell revision version installation and related tests

---

images/win/scripts/ImageHelpers/VisualStudioHelpers.ps1

We don't log any errors during Visual Studio installation process except `exitCode` . Fix: display log `"$env:TEMP\dd_setup_*_errors.log"` output to the console.
https://github.com/actions/virtual-environments-internal/issues/1336

[Windows] Provide Visual Studio setup error logs

---

images/linux/scripts/installers/swift.sh

There is a need to have a swiftc symlink point to swift binary for some tools (such as bazel's swift rules)

added a swiftc symlink

---

images/macos/provision/utils/xcode-utils.sh

Improvement
"Open" tool sometimes fails on unpacking xip archives while extracting Xcode (extracted files are harmed), "xip" utility is much more stable in both single and multi-thread unpacking without any performance degradation.

Change "open" tool to "xip" on XCode archive extraction

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1

We don't have apt-fast version in the readme even though some customers would like to see it.
There is no `apt-fast --version` or something similar, so the simplest way to get the version is `apt-get list -installed`
https://github.com/actions/virtual-environments/issues/1841

[Ubuntu] Add apt-fast version to readme

---

images/macos/provision/core/openssl.sh

It turned out we need openssl 1.0.2t for pre-cached python.
https://github.com/actions/virtual-environments/issues/1745
https://github.com/actions/virtual-environments-internal/issues/1327

[macOS] Fix openssl on Big Sur

---

images/macos/macos-11.0-Readme.md

| Announcements |
|-|
| [[macOS] Built-in Python 2.7 will be used on macOS instead of Homebrew formula on November, 3rd.](https://github.com/actions/virtual-environments/issues/1848) |
| [macOS 11.0 (Big Sur) is available as a preview 🚀](https://github.com/actions/virtual-environments/issues/1814) |
| [[macOS] Default Ruby version will be changed to 2.7 on October, 26](https://github.com/actions/virtual-environments/issues/1775) |
| [Default Xcode will be changed to Xcode 12.0.1 on October, 20](https://github.com/actions/virtual-environments/issues/1712) |
| [Xcode 11.0, 11.1, 11.4.0 will be deprecated on November, 5](https://github.com/actions/virtual-environments/issues/1688) |
***
- System Version: macOS 11.0 (20A5395g)
- Image Version: 20201020.1
- Clang/LLVM 11.0.0
- Node.js v12.19.0 …

macOS 11.0 (20201020 update)

---

images/macos/provision/utils/utils.sh

Xamarin downloads sometimes fail with error 404, but rerun doesn't face with it.
This PR adds HTTP code 404 to available wget retry codes.
n\a

[macOS] Add http code 404 to download with retry function

---

helpers/GenerateResourcesAndImage.ps1

A bunch of improvements for `GenerateResourcesAndImage.ps1`. Mostly, they are needed to run this script on MacOS / Ubuntu.
Changes:
- Fix template paths
- Fix `Get-LatestCommit` to make sure that it doesn't block build
- Add proper error if packer doesn't exist + remove .exe extension
- Set default value for `$ImageGenerationRepositoryRoot`

Improve GenerateResourcesAndImage.ps1 - Adapt for Unix

---

images/macos/provision/core/xcode-clt.sh

Xcode command-line tools 12.1 are unsupported in Big Sur, but being installed by default. This PR adds a condition to install compatible 12.2_beta command-line tools instead.
n\a

[macOS] Install Xcode tools 12.2_beta for Big Sur

---

images.CI/macos/move-vm.ps1
images/macos/provision/core/xcode-clt.sh

Improvement - move-vm.ps1 will stop  and rename unstable VMs in case of failure before moving.
Test failure: https://github.visualstudio.com/virtual-environments/_build/results?buildId=85939&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=027aaa20-7755-5366-f0d4-a9dbdf9aa415
https://github.com/actions/virtual-environments-internal/issues/1335

Implement additional feature for stopping and renaming the unstable VMs in case of failure

---

images/macos/provision/core/rubygem.sh

The issue has been fixed in cocoapods 1.10.0 https://github.com/CocoaPods/CocoaPods/issues/10153 so we don't need this workaround anymore.
https://github.com/actions/virtual-environments/issues/1804

[macOS] Revert "Freeze xcodeproj 1.18.0"

---

images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

Xamarin iOS 14 required for Xcode 12 so along with changing default Xcode we have to change the default xamarin bundle too.
Xcode 12.1 removed from macOS 11 since it's not supported on Big Sur.
https://github.com/actions/virtual-environments/issues/1712

[macOS] Switch Xamarin bundle to the latest one for 10.15

---

images/macos/provision/utils/utils.sh

Replaced wget to curl in retry helper and added explicit cycle for retrying (similarly retry helper in Linux).
Internal issue [#1031](https://github.com/actions/virtual-environments-internal/issues/1031)

[macOS] Rework retry helper function

---

images.CI/macos/azure-pipelines/image-generation.yml
images.CI/macos/move-vm.ps1
images.CI/macos/select-datastore.ps1

We have had a situation when 3 out of 4 scheduled builds were placed on the same datastore probably because there is some delay between datastore selections and VM files creation.
In this PR we implement the following logic:
- Build set the tag on datastore after selection
- Wait for 1 minute
- Only the first two tags will be able to book the datastore
- The third and all the other tags will be deleted and the build will go through all the process again up to 5 times
- Tag is deleted on the move-vm stage
https://github.com/actions/virtual-environments-internal/issues/1360

[macOS] Improve select datastore script

---

images/linux/scripts/installers/homebrew.sh

We don't need to `chmod` brew directory and make it "dirty" after this script https://github.com/actions/virtual-environments/blob/main/images/linux/post-generation/homebrew-permissions.sh
https://github.com/actions/virtual-environments/issues/1568

[Ubuntu] Remove chmod for homebrew directory

---

images/macos/provision/core/edge.sh

Edge webdriver 86.0.622.51 has been fixed recently. We don't need this workaround anymore.
https://github.com/actions/virtual-environments-internal/issues/1290

[macOS] Remove workaround for MS edge webdriver

---

images/macos/provision/core/xamarin.sh

Xamarin app builds started to fail with Xcode 12 as default. We've added `/Applications/Xcode_12.app` string to the `/Library/Preferences/Xamarin/Settings.plist` to avoid errors related to Xcode 12 symlink.

Fix Xamarin issue with Xcode symlink

---

images/win/scripts/Installers/Initialize-VM.ps1
images/win/windows2019.json

Currently, we use a temp disk to store a  diskpart script which can cause an issue on a system without disk `'D'`.
Changes:
- Use powershell cmdlets to expand disk size
- Remove the temporary diskpart script
- Set vm size for Windows Server 2019 to `Standard_DS4_v2` 
https://github.com/actions/virtual-environments/issues/1842

[Windows] Resize disk using powershell and don't use disk D for a diskpart script

---

images/linux/post-generation/homebrew-permissions.sh
images/linux/post-generation/rust-permissions.sh

Fixed post-deployment scripts on Linux. 
Scripts are executed via sudo and $USER environment variable value is "root", but these script should set permissions according to actual user, the $SUDO_USER variable is an appropriate option.

fix user on rust and brew scripts

---

images/win/scripts/Installers/Configure-Shell.ps1
images/win/scripts/Installers/Install-Msys2.ps1
images/win/scripts/Tests/Shell.Tests.ps1

In scope of the https://github.com/actions/virtual-environments/pull/1648 PR we removed Git internal tools from PATH. In the migration process we found an issue related to how to correct prepare environment before running commands in the bash shell.
Issue:
If we try to invoke a find command, it runs the default `C:\Windows\System32\find.exe` Windows program instead of  `C:\msys64\usr\bin\find.exe` and  `PATH` order is incorrect( `/mingw64/bin:/usr/bin` in the PATH should be before C:\Windows\System32):
```
PS > bash -c 'echo $PATH'
/c/shells:/c/Program Files/MongoDB/Server/4.4/bin:/c/aliyun-cli:/c/ProgramData/kind:/c/vcpkg:/c/cf-cli:
PS >bash -c 'where find'
C:\Windows\System32\find.exe
C:\msys64\usr\bin\find.exe
PS > bash -c 'find'
FIND: Parameter format not correct
```
We should …

[Windows] Add bash wrapper from git

---

images/macos/provision/core/powershell.sh
images/macos/toolsets/toolset-10.13.json
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

Az PowerShell version 5 contains a lot of breaking changes, we should stay at 4.8 for a few more weeks until these issues are resolved.
n\a

[macOS] Explicitly set Az powershell version 4.8

---

images/macos/provision/core/edge.sh

There is a unique URL for the macOS edge webdriver now.
n\a

[macOS] Change edge webdrivder url

---

images/linux/scripts/installers/powershellcore.sh

After updating Az.Accounts module to the latest 2.1.2 version, snap powershell  unexpectedly raises a segfault when we invoke Import-Module Az.Accounts statement. As a fix we change installation approach to use `dotnet tool` util.

[Ubuntu] Install pwsh using dotnet tool

---

images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

Related announcements:
- https://github.com/actions/virtual-environments/issues/1847

Deprecate Boost 1.69.0 from Windows images

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/macos/provision/core/pipx-packages.sh

Improvement
Add too docker information listed in Software report the docker digest and age.

Print more informantion about cached Docker images linux

---

images/macos/provision/core/rust.sh

Make installed Rust components the same as for Ubuntu. See also: 
https://github.com/actions/virtual-environments/blob/f38833acec5cc1c3239474f8135b23c17cb72351/images/linux/scripts/installers/rust.sh
See: https://github.com/actions/virtual-environments/issues/1916
Fixes: #1916 
@maxim-lobanov

OSX: Rust tools: install 'rustfmt' and 'clippy'

---

images/linux/scripts/base/apt.sh
images/linux/scripts/base/repos.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

The following error appeared during Ubuntu20 image generation on mmsprodwcus0.
Need to collect additional information and ask for help from Canonical.
```
2020-11-05T03:12:39.6168065Z  mmsprodwcus0    2020/11/05 03:08:37 ui error: ==> azure-arm: E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.15.0-1build1_amd64.deb  Temporary failure resolving 'azure.archive.ubuntu.com'
2020-11-05T03:12:39.6168997Z  mmsprodwcus0    2020/11/05 03:08:37 ui error: ==> azure-arm: E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/libs/libssh2/libssh2-1_1.8.0-2.1build1_amd64.deb  Temporary failure resolving 'azure.archive.ubuntu.com'
2020-11-05T03:12:39.6169949Z  mmsprodwcus0    2020/11/05 03:08:37 ui error: ==> azure-arm: E: Failed to fetch …
```

[Ubuntu] Fix image generation for Ubuntu20

---

images/linux/scripts/base/apt.sh
images/linux/scripts/base/repos.sh
images/linux/scripts/installers/azpowershell.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

PowerShell Core 7,on Ubuntu20, was causing segmentation faults (segfaults) after powershell modules were updating to Az 5.0 and Az.Accounts 2.1.2. 
Fix: use hardcoded version Az=4.8.0 and Az.Accounts=1.9.5.

[Ubuntu] Freeze Az.Accounts module for Ubuntu 20

---

images/linux/post-generation/homebrew-permissions.sh

Homebrew version reported as dirty due to the fact that /home directory permissions recursively changed to 777 during VM provision. This PR resets brew directory permission to the default ones.
https://github.com/actions/virtual-environments/issues/1568

[Ubuntu] Reset homebrew git repository to restore file permissions

---

images/macos/provision/utils/xcode-utils.sh
images/macos/tests/Xcode.Tests.ps1

RC versions of Xcode should be excluded from XCODE_DEVELOPER_DIR variables

[MacOS] Exclude release candidates from XCODE_DEVELOPER_DIR variables

---

images/linux/scripts/installers/php.sh

- New tool
- Added `php-dev` for each supported PHP version and `php-pear`. It fixes #1944
- Should take around 500kb for `php-dev` for each PHP version and around `280kb` for php-pear. 
- Time taken will not change much, as time taken to install `php-pear` will be offset by time taken to remove `php-dev`.

[Ubuntu] Add php-dev and php-pear

---

images/win/scripts/Installers/Install-PowershellCore.ps1

While the update check happens during the first session in a given 24-hour period, for performance reasons, the notification will only be shown on the start of subsequent sessions. Also for performance reasons, the check will not start until at least 3 seconds after the session begins.
https://github.com/actions/virtual-environments-internal/issues/1435

[Windows] PWSH - turns off the update notification feature

---

images/linux/scripts/base/apt-mock.sh

Bug fixing
The PR replaces the retry logic based on fuser (see https://github.com/actions/virtual-environments/pull/1883) with 
the more robust check of apt stderr

Workaround for apt db locked by WALinuxAgent v2

---

images/macos/provision/core/gcc.sh

Bug fixing
Currently, due to changed brew link logic, gcc-8 is unlinking during gcc-9 installation. I have created [an issue](https://github.com/Homebrew/brew/issues/9100) to brew repository to clarify is it a bug or not.
1448

macOS: gcc workaround

---

images/linux/scripts/base/apt.sh

Sometimes build process fails on apt-get/dpkg locks, unattended-upgrades can be one of the reasons of these failures.

Remove unattended upgrades

---

images/macos/provision/configuration/preimagedata.sh

Recently, macos tag name was changed from `macos-10.15` to `macOS-10.15`. need to fix the content of image file accordingly. 
Also put the same file to MacOS 10.13, MacOS 10.14 because now we have all readme files in virtual-environments repository

Fix image link in initialize job step

---

images/linux/scripts/installers/dotnetcore-sdk.sh
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

In scope of this PR we are we moving the list of .Net Core versions to toolset to simplify maintenance.

[Ubuntu] Move list of .Net Core versions to install to toolset

---

images/linux/scripts/installers/azpowershell.sh
images/linux/scripts/installers/powershellcore.sh

On Ubuntu-20.04 PowerShell is installed from snap due to the lack of official support. It causes error in logs: mkrdir: cannot create directory /run/user/1001 : Permission denied that causes pipelines to fail if Fail on Standard Error checkbox is checked.
Powershell 7.1 has been recently released with native Ubuntu 20 support
https://github.com/PowerShell/powershell/releases
https://github.com/actions/virtual-environments-internal/issues/1449

[Ubuntu20] Swap Ubuntu-20.04 powershell installation from snap to official package

---

images.CI/macos/select-datastore.ps1

There is a chance, we can face with the logical bug on condition that `$buildDatastore` value is not changed, but we already have had two or more tags , in that case we will never pick up a datastore.

[Image.CI] Pick up a random datastore by condition

---

images.CI/linux-and-win/azure-pipelines/image-generation.yml

We should provide readme output before `Create release for VM deployment` step and not depend on the it if an error occurs - https://github.visualstudio.com/virtual-environments/_build/results?buildId=88861&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

[Image.CI] Move up the readme output stage

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json
images/win/announcements.md
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/windows2016.json
images/win/windows2019.json

Announcements table is removed from generation process to avoid appearing it in PR description. Announcements will be added to the readme files later, when the commit is creating.
internal issue [#1462](https://github.com/actions/virtual-environments-internal/issues/1462)

[Ubuntu][Windows] Remove announcements from generation process

---

images/macos/provision/core/gcc.sh

Improvement.
Bug with gcc versions were fixed in the homebrew version 2.5.11. So, we just need to remove it.
- [-] Related issue / work item is attached

Homebrew: Remove gcc workaround

---

images/linux/scripts/base/apt.sh

Some base images of the ubuntu on AWS contains an outdated cache. So, when tries to installs the package we receive an error `unable to locate package`. To install the package, added the line `apt-get update`  to update the cache.

Cache Update

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Currently, "BizTalk Server" split MSYS section to two parts. Need to move it lower in documentation

Move BizTalk Server lower in documentation

---

images/linux/scripts/base/apt-mock-remove.sh
images/linux/scripts/base/apt-mock.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

Improvement
The `apt-get update` sporadically fails with the error output like 
```
==> azure-arm: E: Could not open file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_focal-backports_universe_i18n_Translation-en - open (2: No such file or directory)
==> azure-arm: E: Could not open file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_focal-backports_universe_binary-amd64_Packages - open (2: No such file or directory)
==> azure-arm: E: Could not open file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_focal-
``` 
As a workaround the apt is mocked with the script to check the output for the specific error and rerun the command after a delay
The `apt get` sporadically fails with the error output like 
```
gpg: can't connect to the agent: IPC connect call failed
```
Currently it …

fix sporadic build fails

---

images/linux/scripts/installers/cmake.sh

Update CMake from 3.17.0 to 3.19.1 on the Linux/Ubuntu images. Release notes: CMake [3.18](https://cmake.org/cmake/help/latest/release/3.18.html), [3,19](https://cmake.org/cmake/help/latest/release/3.19.html).
Windows and macOS images are updated automatically.

[Ubuntu] Update CMake to 3.19.1

---

.vscode/settings.json
images.CI/linux-and-win/azure-pipelines/image-generation.yml
images.CI/linux-and-win/build-image.ps1
images.CI/macos/azure-pipelines/image-generation.yml
images.CI/measure-provisioners-duration.ps1

This PR adds script `measure-provisioners-duration.ps1` to repo. This script parses packer diagnostic logs and determine the duration of every step. As a result, it prints the following output:
- The whole build timeline 
- The Top 25 longest provisioners
All changes:
- Move logic to find template to the separate step on Windows / Linux to reuse it later and avoid code duplication
- Set `PACKER_LOG: 1`. image generation logs will still contain only short log. But diagnostic logs will be saved to separate file.
Build examples:
- https://dev.azure.com/github/virtual-environments/_build/results?buildId=90048&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=8b69240d-5eca-52e7-db53-21813d4d30a5
- https://dev.azure.com/github/virtual-environments/_build/results?buildId=90047&view=logs&j=80d866 …

Implement script to parse provisioners duration from packer diagnostic logs

---

images/macos/provision/core/rust.sh

Recently, Rustup was updated to 1.23.0. After this change `$CARGO_HOME/env` file is not presented anymore.
Removing invocation of this file, since brew adds `$CARGO_HOME/bin` to PATH without it

Fix Rustup installation after update on 1.23.0

---

images/linux/scripts/installers/dotnetcore-sdk.sh

Dotnet SDKs installation process include "curl" that needs to be replaced by "download_with_retry" function to make installation process less flaky due to network errors/timeouts.

Improve dotnet SDKs installation

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1
images/win/scripts/Installers/Install-PHP.ps1

Currently, during image generation process we install the latest version of PHP. At time of writing the current version of PHP is 8.0. One of the dependencies of PHP 8.0 is the `visualstudio2019buildtools` package which causes another issue  https://github.com/actions/virtual-environments/issues/1470.
```
2020-11-30T14:08:31.7820834Z     vhd: By installing you accept licenses for the packages.
2020-11-30T14:08:33.2822538Z     vhd: Progress: Downloading visualstudio2019buildtools 16.8.2.0... 100%
2020-11-30T14:08:34.1117278Z     vhd: Progress: Downloading chocolatey-visualstudio.extension 1.8.1... 100%
2020-11-30T14:08:35.4864619Z     vhd: Progress: Downloading dotnetfx 4.8.0.20190930... 100%
2020-11-30T14:08:37.0665171Z     vhd: Progress: Downloading chocolatey-dotnetfx.extension 1.0.1... …
```

[Windows] Set PHP-7.4 as default

---

images/linux/scripts/base/apt-mock.sh

Bug fixing and Improvement
Аdd fix for build error
```
==> azure-arm: Provisioning with shell script: C:\agent\_work\9\s\images\linux/scripts/base/apt.sh
==> azure-arm: sudo: unable to resolve host pkrvmjd4gkmsxeh: Temporary failure in name resolution
==> azure-arm: Removed /etc/systemd/system/timers.target.wants/apt-daily.timer.
==> azure-arm: Removed /etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer.
==> azure-arm: sudo: unable to resolve host pkrvmjd4gkmsxeh: Temporary failure in name resolution
```
Handle the case error has happened in the child process by removing the check for exit code and always 
grep err log
Handle the case the err log has not been created at all

Handle DNS error and errors in the child processes

---

images/linux/scripts/installers/containers.sh

Improvement
Currently, there are no checks in containers.sh file
https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/containers.sh
Thus we have to wait for 3 hours for these tools to be checked.
https://github.com/actions/virtual-environments-internal/issues/1539

[Ubuntu] Additional verification for container's tools

---

images/linux/scripts/installers/oc.sh

Recent Ubuntu builds are failing due to invalid openshift-client download link. [[Link](https://github.visualstudio.com/virtual-environments/_build/results?buildId=90789&view=results) to the build example]. In scope of this PR we are fixing the download  link and adding download with retries logic.

[Ubuntu] Fix Openshift-client installation

---

images/linux/ubuntu2004.json

Improvement
Some of our build fails due to unexpected issue with apt.sh script, which most probably caused by reboot step.
https://github.com/actions/virtual-environments-internal/issues/1508

[Ubuntu20] remove reboot from packer json.

---

images/linux/scripts/installers/php.sh

- This PR adds `PHP 8.0` to the Ubuntu environments.
- PHP extension `xmlrpc` has been dropped from `PHP 8.0`, so installing it only on `PHP 7.4` and lower. 
Reference: https://wiki.php.net/rfc/unbundle_xmlprc
- PHP extension `json` is now always enabled and does not have to be installed separately, hence has no package for PHP 8.0.
Reference: https://wiki.php.net/rfc/always_enable_json
- Bumped PHPUnit version to PHPUnit 8.

[Ubuntu] Add PHP 8.0

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

This adds the `MediaInfo` package as suggested in https://github.com/actions/virtual-environments/issues/2185
> command-line utility for reading information from audio/video files
- https://github.com/actions/virtual-environments/issues/2185

[Ubuntu] Add MediaInfo package

---

images/macos/software-report/SoftwareReport.Common.psm1

The output of the `rustup --version` command was changed and this caused problems with the macOS software documentation. In scope of this PR we fixed it.

[macOS] Fix Rustup version in the software documentation

---

images/macos/software-report/SoftwareReport.Common.psm1

Currently only the brew installation of clang is documented. This PR adds the clang version from Xcode installation to the appropriate docs section.

[macOS] Clarify clang versions

---

images/win/scripts/Installers/Update-AndroidSDK.ps1

Bug fixing
C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd
contains a line
```
%~dp0\build\ndk-build.cmd %*
```
and %~dp0 expands to a string with a spaces and causes the "Item not found" error
The PR adds the double quotes in order to make the command to work

Fix spaces in ndk-build.cmd path

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Perl is currently installed in all major Linux distributions, but it was not detected. This adds detection, guided by #2204. It fixes #2203 
#2203 #2204

Adds Perl version detection

---

images/linux/scripts/installers/containers.sh

Currently, apt-mock.sh incorrectly parses `<`. Use the `add key` command without `>`  is resolved the issue.
```
==> azure-arm: Provisioning with shell script: C:\agent\_work\7\s\images\linux/scripts/installers/containers.sh
==> azure-arm: 2020-12-02 17:17:31 URL:https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key [1093/1093] -> "Release.key" [1]
==> azure-arm: Warning: apt-key output should not be parsed (stdout is not a terminal)
==> azure-arm: gpg: can't connect to the agent: IPC connect call failed
azure-arm: ...retry 1
```
https://github.com/actions/virtual-environments-internal/issues/1554

[Ubuntu] Fix add key in containers.sh script

---

images/macos/provision/core/python.sh

Due to maintenance concerns, we are going to stop installing Python 2.7 from the Homebrew formula, which was deprecated at the beginning of 2020, and instead, use the official macOS pkg installer available by the following link
https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg
This package installs pip along with the python, but the version is outdated so the update required. Also, the GUI installation process requires to run the install certificates command after successful installation:
The corresponding step added to the installation script.
https://github.com/actions/virtual-environments-internal/issues/1543

[macOS] Install Python2 from pkg installer

---

images/linux/scripts/SoftwareReport/SoftwareReport.Android.psm1
images/macos/software-report/SoftwareReport.Android.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Android.psm1

Improvement
Recently, we had an incident related to version of Android Emulator. We should add version of emulator to software report to avoid such issues in future

Add Android Emulator to software report for all images

---

images.CI/macos/destroy-vm.ps1
images.CI/macos/helpers.psm1
images.CI/macos/move-vm.ps1
images.CI/macos/select-datastore.ps1

Connect-VCServer is broken with the new version of azdo powershell task. We need to pass parameters explicitly to fix the issue.
n\a

[macOS CI] Explicitly pass parameters for Connect-VCServer function

---

images/macos/provision/core/powershell.sh

Stop adding backward compatibility of Az and AzureRM by Enable-AzureRmAlias cmdlet.
https://github.com/actions/virtual-environments/issues/2090

[macOS] Disable AzureRM aliases

---

images.CI/linux-and-win/build-image.ps1

Currently `$Image` variable is empty, this PR fixes it.
n\a

[ImageBuild] Fix templatepath and image variables

---

images/macos/provision/core/openssl.sh
images/macos/tests/Common.Tests.ps1

The Openssl 1.0.2 brew formula was deprecated a long time ago and that's painful to keep it on the image at the moment.
We decided to switch to 1.1 as the default and also install the latest version (it's the same 1.1 at the moment).
https://github.com/actions/virtual-environments/issues/2089

[macOS] Deprecate openssl 1.0.2 and set 1.1 as the default one

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Adding bash version output.
OS|Bash Version
---|--------------
Windows Server 2016 |Bash 4.4.23(1)-release
Windows Server 2019 |Bash 4.4.23(1)-release
https://github.com/actions/virtual-environments/issues/2232

[Windows] bash version output

---

images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1

Adding bash version output.
OS|Bash Version
---|--------------
macOS 10.15 |3.2.57(1)-release
macOS 11.0 |3.2.57(1)-release
https://github.com/actions/virtual-environments/issues/2232

[macOS] bash version output

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Adding bash version output. 
OS|Bash Version
---|--------------
Ubuntu 16.04 |Bash 4.3.48(1)-release
Ubuntu 18.04 |Bash 4.4.20(1)-release
Ubuntu 20.04 |Bash 5.0.17(1)-release
https://github.com/actions/virtual-environments/issues/2232

[Ubuntu] bash version output

---

images/macos/tests/Android.Tests.ps1

Android NDK test started to fail because of updated NDK:
```
vsphere-clone:  Context Legacy NDK versions
vsphere-clone:    [-] Android NDK version is 21 50ms (45ms|4ms)
vsphere-clone:     Expected case sensitive like wildcard '*Revision = 21.*' to match 'Pkg.Desc = Android NDK
vsphere-clone:     Pkg.Revision = 22.0.7026061
vsphere-clone:     ', but it did not match.
vsphere-clone:     at $rawContent | Should -BeLikeExactly "*Revision = 21.*", /Users/runner/image-generation/tests/Android.Tests.ps1:75
vsphere-clone:     at <ScriptBlock>, /Users/runner/image-generation/tests/Android.Tests.ps1:75
```
As we decided to install the latest version every time, we don't need this test anymore.
https://github.com/actions/virtual-environments-internal/issues/1615

[macOS] Get rid of NDK version check test

---

images/macos/provision/core/commonutils.sh
images/macos/provision/core/swiftlint.sh
images/macos/templates/macOS-10.13.json
images/macos/templates/macOS-10.14.json
images/macos/templates/macOS-10.15.json
images/macos/templates/macOS-11.0.json

[Swiftlint brew formulae](https://formulae.brew.sh/formula/swiftlint) requires Xcode >= 11.4 to build the package yet the latest one we have on Mojave is 11.3.1.
This PR adds swiftlint installation from the latest release from https://github.com/realm/SwiftLint/releases for all macOS except High Sierra since it's not supported.
As an addition, xcode-clt installation script reverted to invoke before homebrew.
https://github.com/actions/virtual-environments-internal/issues/1620

[macOS] install swiftlint from pkg

---

images/linux/scripts/base/apt-mock.sh

Improvement
There was error during Ubuntu built:
`==> azure-arm: dpkg: error: dpkg frontend is locked by another process`
I've added the error to apt.mock to retry in case of re-occurance.
---
- [-] Related issue / work item is attached
- [-] Tests are written (if applicable)

[Ubuntu] update apt.mock with additional lock error.

---

images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

We've investigated image generation using different VM sizes and the results are quite promising with Standard_D4s_v4 VM size (4cpu, 16Gb Ram, no temporary storage)  — build time decreased from 3.40-3.50 to 3 hours for Ubuntu 18.
The price shouldn't increase much:
Standard_D4s_v4 for 3h — $1.22
Standard_DS2_v2 for 4h — $1.01
https://github.com/actions/virtual-environments-internal/issues/1595

[Ubuntu] Switch image generation to Standard_D4s_v4 VM size

---

images/linux/scripts/installers/pypy.sh
images/macos/provision/core/pypy.sh
images/win/scripts/Installers/Install-PyPy.ps1

In scope of this pull request we add new `PYPY_VERSION` file for all images. File will contain the version of PyPy. This changes are related to pull request with adding support for `setup-python` to install pypy.

Add PYPY_VERSION file to the images

---

images/win/windows2016.json
images/win/windows2019.json

It makes sense to change VM specs to cheaper Standard_D8s_v4 (0.816$\h vs 1.008$\h) because we don't need temporary storage for the image generation.
https://github.com/actions/virtual-environments-internal/issues/1627

[Windows] Change vm spec to Standard_D8s_v4

---

images/linux/scripts/helpers/invoke-tests.sh
images/linux/scripts/installers/aliyun-cli.sh
images/linux/scripts/installers/aws-sam-cli.sh
images/linux/scripts/installers/aws.sh
images/linux/scripts/installers/azure-cli.sh
images/linux/scripts/installers/azure-devops-cli.sh
images/linux/scripts/installers/github-cli.sh
images/linux/scripts/installers/google-cloud-sdk.sh
images/linux/scripts/installers/oc.sh
images/linux/scripts/installers/oras-cli.sh
images/linux/scripts/installers/vercel.sh
images/linux/scripts/tests/CLI.Tools.Tests.ps1

In scope of this PR we are migrating tests for CLI tools to Pester (see list of tools in related issue).

[Ubuntu] Migrate tests for CLI tools to Pester

---

images/win/scripts/Installers/Install-PHP.ps1

One of the dependencies of PHP 8.0 was the `visualstudio2019buildtools` package which caused  issue #1470. Now it has been fixed and depends on `vcredist140`  - https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1591
To preserve consistence with macOS and Ubuntu, PHP 8.0 will be pre-installed on Windows too.
https://github.com/actions/virtual-environments-internal/issues/1534

[Windows] Install PHP 8.0

---

images/macos/provision/core/audiodevice.sh
images/macos/provision/core/aws.sh
images/macos/provision/core/chrome.sh
images/macos/provision/core/commonutils.sh
images/macos/provision/core/edge.sh
images/macos/provision/core/firefox.sh
images/macos/provision/core/homebrew.sh
images/macos/provision/core/openjdk.sh
images/macos/provision/core/powershell.sh
images/macos/provision/utils/utils.sh

Improvement
Brew changed cask installation to the following mode:
`brew install --cask`
in the build logs, it can be observed:
`Error: Calling brew cask install is disabled! Use brew install [--cask] instead.`
1629

[macOS] brew --cask option fix.

---

images/linux/ubuntu2004.json

Remove stale `go_default` and `go_versions` params in a packer config.

[Ubuntu] Remove stale go_default and go_versions params

---

images/macos/software-report/SoftwareReport.Common.psm1

Clang MacOS  report string contains `$(brew --prefix llvm)/bin/clang` string that was not escaped

Added escaping on clang report

---

images/linux/scripts/installers/dotnetcore-sdk.sh

Minor change of dotnet core sdk unpacking stage. Now all unpacking jobs will start at the same time. Help command is unnecessary because the sdk version is mentioned in build output.

Dotnet core sdk unpacking stage changes

---

images/linux/scripts/installers/aws.sh

Improvement?  
We have apt mocks to retry in case of  errors, but there's no one for dpkg utility.

Replace dpkg with apt

---

images/win/scripts/SoftwareReport/SoftwareReport.Android.psm1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

New tool 
size:  100Mb
time: 30 secs
Virtual environments currently installs Android "SDK Tools", which is deprecated: https://developer.android.com/studio/releases/sdk-tools
Google suggests using the new "cmdline-tools" package instead:
https://developer.android.com/studio/command-line

Install Android Command Line tools on Windows images

---

images/linux/scripts/installers/dotnetcore-sdk.sh

Reverted [dotnet sdk exctraction in parallel](https://github.com/actions/virtual-environments/commit/ba0809214be7bd66a26465734c9f77a951e73db8)

Reverted dotnet sdk extraction in parallel

---

images/macos/provision/core/android-toolsets.sh
images/macos/software-report/SoftwareReport.Android.psm1
images/macos/tests/Android.Tests.ps1
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

New tool 
size:  100Mb
time: 30 secs
Virtual environments currently installs Android "SDK Tools", which is deprecated: https://developer.android.com/studio/releases/sdk-tools
Google suggests using the new "cmdline-tools" package instead:
https://developer.android.com/studio/command-line

Add Android Command Line tools for MacOS images

---

images/linux/scripts/SoftwareReport/SoftwareReport.Android.psm1
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

New tool 
size:  100Mb
time: 30 secs
Virtual environments currently installs Android "SDK Tools", which is deprecated: https://developer.android.com/studio/releases/sdk-tools
Google suggests using the new "cmdline-tools" package instead:
https://developer.android.com/studio/command-line

Add Android Command Line tools to Linux images

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Install `libgsl-dev` from Ubuntu APT repository. `libgsl23` is a dependency (binary package) so no need to install separately.

[Ubuntu] Preload `libgsl-dev` from APT repo

---

images/linux/scripts/installers/mysql.sh
images/linux/scripts/tests/Databases.Tests.ps1

Currently, password for user `root` is not set during mysql 8 installation on Ubuntu 20.04:
```
select host,user,authentication_string,plugin from mysql.user
--------------
+-----------+------------------+------------------------------------------------------------------------+-----------------------+
| host      | user             | authentication_string                                                  | plugin                |
+-----------+------------------+------------------------------------------------------------------------+-----------------------+
| localhost | mysql.infoschema | $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED | caching_sha2_password |
| localhost | mysql.session    | $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED | …
```

[Ubuntu] Fix empty password for mysql-server

---

images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1

Improvement
Here is a list with missed Rust tools in the documentation:
rustdoc
cargo
rustfmt
clippy

Add missed Rust tools to the documentation for macOS

---

images/win/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Improvement
Here is a list with missed Rust tools in the documentation:
rustdoc
cargo
rustfmt
clippy

Add missed Rust tools to the documentation for Win

---

images/linux/scripts/helpers/etc-environment.sh
images/linux/scripts/installers/python.sh

Function `setEtcEnvironmentVariable` adds new variable value with quotes. It cause incorrect installation for new packages via pipx on Ubuntu.
Example of installation a new package: https://buildcanary.visualstudio.com/PipelineCanary/_build/results?buildId=1314837&view=logs&j=2666b424-a65e-5d07-a841-d60507eedf54&t=30f8b51d-c83a-54b4-a539-070a66f8e560
Also, `pipx list` command not shows already installed packages.

[Ubuntu] Fix `setEtcEnvironmentVariable` function

---

images/win/scripts/Installers/Install-Git.ps1

In scope of this PR we are adding `--ignore-dependencies` option during the installation of hub, because Git for Windows is installed twice in current approach: once explicitly using the binary installer, and again using Chocolatey as a dependency of hub.

[Windows] Fix hub installation

---

images/win/scripts/Installers/Update-AndroidSDK.ps1

Improvement
Create a hardlink `C:\Android\android-sdk` pointing to `C:\Program Files (x86)\Android\android-sdk` and set `ANDROID_SDK_ROOT` to `C:\Android\android-sdk`
Problem to solve:
ANDROID_NDK_PATH / HOME should not contain spaces. Otherwise, the script C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd gives an error
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
changing just ndk-build.cmd is not (nearly) enough. We depend on all the compiler wrapper scripts in ./toolchains/llvm/prebuilt/windows-x86_64/bin/<architecture>-clang*.cmd being capable of handling spaces, and have not gone beyond checking what else might break.

Change Android SDK root

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

- deprecate Node.js 8.*
**It is not a breaking changes. Official setup tasks will still be able to install all these versions on-flight. This PR removes pre-caching these versions from images.**
https://github.com/actions/virtual-environments-internal/issues/1690

[Ubuntu] Deprecate node.js 8

---

images/win/scripts/Installers/Install-NodeLts.ps1

This commit change the way to set npm cache path from env to config file on Windows runners.
The `npm_config_cache` env, if set, will have highest priority, and harder to change.
One way to un-set this is add a global workflow env, like:
```
env:
npm_config_cache: ''
```
This commit change the cache config to use `npm config set cache $CachePath --global`,
which should save the path under the global npmrc at: `C:\npm\prefix\etc\npmrc`,
and allow easier later reset with user/repo level `.npmrc` files.
For the record, my usage is to unify all platform's npm cache to `~/.npm/`,
then use the same cache action config on all platform to cache the folder.

[Windows] use `npm config` instead of `npm_config_cache`

---

images/win/scripts/Installers/Install-PHP.ps1

Openssl extension installation on Windows do not use correct string replacements. 
Currently no string that contains "php_openssl.dll" can be found at php.ini and also documentation says that 
> "The syntax used in previous PHP versions ('extension=<ext>.so' and 'extension='php_<ext>.dll') is supported for legacy reasons and may be deprecated in a future PHP major version. So, when it is possible, please move to the new ('extension=<ext>) syntax"
so `extension=openssl` should be used instead.

openssl php extension fix

---

images.CI/macos/move-vm.ps1

Current output contains unnecessary info:
```
Name                 PowerState Num CPUs MemoryGB
----                 ---------- -------- --------
macOS-10.15_2021011… PoweredOff 10       24.000
macOS-10.15_2021011… PoweredOff 10       24.000
VM has been successfully powered off and renamed to [macOS-10.15_20210114.10_unstable.1_failed]
macOS-10.15_2021011… PoweredOff 10       24.000
VM has been moved successfully to target datastore 'ds-image'
Change CPU count to 3, cores count to 3, amount of RAM to 14336
macOS-10.15_2021011… PoweredOff 3        14.000
```

[Image.CI] Suppress output from Set/Stop/Move-VM cmdlets

---

images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/Common.Tests.ps1
images/macos/toolsets/toolset-10.13.json
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

Previously, we updated a perl package as a dependency of the subversion package. The new version of the subversion doesn't depend on on the perl package that's why the perl package was downgraded.
`Installing dependencies for subversion: apr, apr-util, lz4, perl and utf8proc`
macOS 10.15 Version: 20201212.1
`Perl 5.32.0`
macOS 10.15 Version: 20210110.1
`Perl 5.18.4`
https://github.com/actions/virtual-environments/issues/2477

[macOS] Update default Perl

---

images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Add back missing Cbindgen version output in README back that was accidentally removed in scope of [this](https://github.com/actions/virtual-environments/pull/2422/files#diff-0f0deef55edf9ac41fe9db1cd386e44aac4536569e49e147e8fdc52457ca8dedL127) PR.

[Windows] Add missing Cbindgen version output in README

---

images/linux/scripts/installers/android.sh
images/macos/provision/configuration/environment/bashrc
images/win/scripts/Installers/Update-AndroidSDK.ps1

Added ANDROID_NDK_HOME and ANDROID_NDK_ROOT to the all images
#2426

ANDROID_NDK_ROOT and ANDROID_NDK_HOME environment variables should be preset

---

images/linux/scripts/installers/homebrew.sh

Improvement
Since update and cleanup are invoked in the CI environment each time, the installation process using brew is very slow. However, these are generally not needed in CI environments and we can disable them using the following environment variables:
* HOMEBREW_NO_AUTO_UPDATE
* HOMEBREW_NO_INSTALL_CLEANUP

Set HOMEBREW_NO_AUTO_UPDATE and HOMEBREW_NO_INSTALL_CLEANUP

---

README.md

Updated README to indicate macOS 11.0 is in private preview.

Update README with new macOS 11.0 status

---

images/macos/provision/core/android-toolsets.sh

In scope of this pull request we add logic to switch latest ndk-bundle to the 21 due to the issue with android-xamarin.

[macOS] Switch to android ndk 21 from the latest one (22.0.7026061)

---

images/win/scripts/Installers/Update-AndroidSDK.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

In scope of this pull request we add logic to switch latest ndk-bundle to the 21 due to the issue with android-xamarin.

[Windows] Switch to android ndk 21 from the latest one (22.0.7026061)

---

images/linux/scripts/installers/android.sh
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

In scope of this pull request we add logic to switch latest ndk-bundle to the 21 due to the issue with android-xamarin.

[Ubuntu] Switch to android ndk 21 from the latest one (22.0.7026061)

---

images/win/scripts/ImageHelpers/InstallHelpers.ps1

Previously it was hardwired to "Enterprise".
Bug fixing.
The VS version is specified in the toolset.json instead of hardwiring it to "Enterprise".

Use the value from toolset visualStudio.edition when locating VSIXInstaller

---

images/linux/scripts/installers/docker-compose.sh
images/linux/scripts/installers/oras-cli.sh

Install docker-compose 1.27.4 on ubuntu16/18 until the issue is resolved - https://github.com/docker/compose/issues/8048
https://github.com/actions/virtual-environments-internal/issues/1711

[Ubuntu] Install 1.27.4 on ubuntu16/18

---

images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

Default Xcode is changed to 12.3, and default Xamarin bundle is changed to 6_12_5 which includes:
- Xamarin.iOS 14.8 
- Xamarin.Android 11.1
- Xamarin.Mac 7.2
- Mono 6.12
https://github.com/actions/virtual-environments/issues/2440

[macOS] Default Xcode is set to Xcode 12.3 and default Xamarin bundle is changed to 6_12_5

---

images/macos/provision/core/rust.sh

It turned out that `cargo install` ignores the `Cargo.lock` file by default, which leads to unpredictable installation failures due to broken dependencies. The recent one affected us as well https://github.com/rust-lang/cargo/issues/9101
To avoid such surprises `--locked` flag can be used.
PS: A huge related thread for reference https://github.com/rust-lang/cargo/issues/7169
https://github.com/actions/virtual-environments-internal/issues/1737

[macOS] Add locked flag to cargo install

---

images/linux/scripts/installers/rust.sh

It turned out that `cargo install` ignores the `Cargo.lock` file by default, which leads to unpredictable installation failures due to broken dependencies. The recent one affected us as well https://github.com/rust-lang/cargo/issues/9101
To avoid such surprises `--locked` flag can be used.
PS: A huge related thread for reference https://github.com/rust-lang/cargo/issues/7169
https://github.com/actions/virtual-environments-internal/issues/1737

[Ubuntu] Add locked flag to cargo install

---

images/win/scripts/Installers/Install-Rust.ps1

It turned out that `cargo install` ignores the `Cargo.lock` file by default, which leads to unpredictable installation failures due to broken dependencies. The recent one affected us as well https://github.com/rust-lang/cargo/issues/9101
To avoid such surprises `--locked` flag can be used.
PS: A huge related thread for reference https://github.com/rust-lang/cargo/issues/7169
https://github.com/actions/virtual-environments-internal/issues/1737

[Windows] Add locked flag to cargo install

---

images/macos/provision/core/apache.sh
images/macos/provision/core/nginx.sh
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/software-report/SoftwareReport.WebServers.psm1
images/macos/templates/macOS-10.15.json
images/macos/templates/macOS-11.0.json
images/macos/tests/WebServers.Tests.ps1

| Name  | Version  | ConfigFile                      | ServiceStatus | ListenPort |
| ----- | -------- | ------------------------------- | ------------- | ---------- |
| httpd | 2.4.46_2 | /usr/local/etc/httpd/httpd.conf | stopped       | 80         |
| nginx | 1.19.6   | /usr/local/etc/nginx/nginx.conf | stopped       | 80         |
```
1. Start the service formula immediately
brew services start $service
2. List all managed services
brew services list | grep $service
3. Port 80 availability check
sudo lsof -i :80 | grep LISTEN
4. Stop the service formula immediately
brew services stop "$service"
```
https://github.com/actions/virtual-environments-internal/issues/1713

[macOS] Add apache and nginx

---

images/macos/provision/core/firefox.sh

Geckodriver brew formula has a build-time only dependency "rust", which can't be built on High Sierra at the moment. Moreover, building rust takes about 1.5h instead of a few seconds to download and untar the binary.
https://github.com/actions/virtual-environments-internal/issues/1740

[macOS] install geckodriver from binaries for 10.13

---

images/macos/tests/WebServers.Tests.ps1

Exclude WebServer tests for macOS less than Catalina

[macOS] Exclude WebServer tests for macOS less than Catalina

---

images/linux/scripts/installers/docker-moby.sh
images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

Ubuntu builds, by default, pull images anonymously from the
official DockerHub. DockerHub rate limits requests from
anonymous and unpaid accounts:
- https://docs.docker.com/docker-hub/download-rate-limit/
When those rate limits are reached the Packer build will
fail with an error indicated the rate limit has been
reached.
Add support for providing credentials for a paid
account that can be used by the Docker setup steps to
authenticate when pulling images from DockerHub, thereby
avoiding the rate limit.
Related to #2094

feat(docker): authenticate using DockerHub credentials

---

images/linux/scripts/installers/docker-compose.sh

The https://github.com/docker/compose/issues/8048 bug has been fixed in 1.28.2 version [Revert to Python 3.7 bump for Linux static builds - https://github.com/docker/compose/releases/tag/1.28.2]. Remove hardcoded 1.27.4 version.

[Ubuntu] Revert hardcoded docker-compose version

---

images/win/scripts/Installers/Install-Apache.ps1
images/win/scripts/Installers/Install-Nginx.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/win/scripts/SoftwareReport/SoftwareReport.WebServers.psm1
images/win/scripts/Tests/Apache.Tests.ps1
images/win/scripts/Tests/Nginx.Tests.ps1
images/win/windows2016.json
images/win/windows2019.json

New Tool
This PR adds `Apache` and `Nginx` to the Windows images.
| Name   | Version | ConfigFile                            | ServiceName | ServiceStatus | ListenPort |
| ------ | ------- | ------------------------------------- | ----------- | ------------- | ---------- |
| Apache | 2.4.46  | C:\tools\Apache24\conf\httpd.conf       | Apache      | Stopped       | 80         |
| Nginx  | 1.19.6  | C:\tools\nginx-1.19.6\conf\nginx.conf | nginx       | Stopped       | 80         |

[Windows] Add Apache and Nginx

---

images/linux/scripts/SoftwareReport/SoftwareReport.Android.psm1

There is no ndk section in the readme due to the latest changes (switching from ndk-bundle to separate ndk installation)
https://github.com/actions/virtual-environments-internal/issues/1765

[Ubuntu] Get back Android NDK to the readme 

---

images/macos/toolsets/toolset-11.0.json

Xcode 12.5 has been released and it requires macOS Big Sur 😩
https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-beta-release-notes
n\a

[macOS] Add Xcode 12.5 to Big Sur

---

images/macos/software-report/SoftwareReport.Android.psm1

Due to the wrong condition, NDK versions are not included in the Readme file.
https://github.com/actions/virtual-environments-internal/issues/1764

[macOS] Fix ndk output in readme for Big Sur

---

images/win/scripts/Installers/Update-DockerImages.ps1

We've faced intermittent docker images download failures from mcr.microsoft.com docker registry in west us2 azure region — after several retries the whole process ended with unexpected EOF:
```
2021-01-30T00:24:08.4376780Z     vhd: bd091f41e44c: Retrying in 7 seconds
2021-01-30T00:24:09.5598137Z     vhd: bd091f41e44c: Retrying in 6 seconds
2021-01-30T00:24:10.5462171Z     vhd: bd091f41e44c: Retrying in 5 seconds
2021-01-30T00:24:11.5227268Z     vhd: bd091f41e44c: Retrying in 4 seconds
2021-01-30T00:24:14.9258966Z     vhd: bd091f41e44c: Retrying in 3 seconds
2021-01-30T00:24:14.9261333Z     vhd: bd091f41e44c: Retrying in 2 seconds
2021-01-30T00:24:14.9267194Z     vhd: bd091f41e44c: Retrying in 1 second
2021-01-30T00:24:25.2014841Z     vhd: unexpected EOF
2021-01-30T00:24:25.2019153Z …
```

[Windows] Add workaround to download docker images from another endpoint

---

images/macos/provision/core/xcode.ps1

Enable SPACESHIP_SKIP_2FA_UPGRADE flag for xcversion.
See details in https://github.com/fastlane/fastlane/pull/18116

Enable SPACESHIP_SKIP_2FA_UPGRADE flag for xcversion

---

images/linux/scripts/helpers/Tests.Helpers.psm1
images/linux/scripts/installers/basic.sh

Looks like we missed the test in the previous PR https://github.com/actions/virtual-environments/pull/2463 The test should be executed after the installation as well as at the end of the build.
This PR also fixes the case when all tests are skipped because conditions were not met.
n\a

[Ubuntu] Invoke chromium test after installation

---

images/macos/helpers/SoftwareReport.Helpers.psm1
images/macos/software-report/SoftwareReport.Android.psm1
images/macos/software-report/SoftwareReport.Browsers.psm1
images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1

Improvement
the following environment variables that are mentioned in documentation:
All platforms:
ANDROID_HOME
ANDROID_SDK_ROOT
ANDROID_NDK_HOME
CHROMEWEBDRIVER
EDGEWEBDRIVER
GECKOWEBDRIVER
VCPKG_INSTALLATION_ROOT
CONDA
ANT_HOME
GRADLE_HOME

Document environment variables of MacOS images

---

images/linux/scripts/installers/nodejs.sh

We should avoid explicit npm installation and stick to the version which comes along with node js.
https://github.com/actions/virtual-environments-internal/issues/1789

[Ubuntu] Remove explicit npm installation

---

images/linux/scripts/installers/java-tools.sh

Improvement
Since Maven 3.5.0, environment variable M2_HOME is not used/supported anymore:
https://maven.apache.org/docs/3.5.0/release-notes.html#overview-about-the-changes

Remove M2_HOME from linux images

---

images/linux/scripts/installers/haskell.sh
images/linux/scripts/tests/Haskell.Tests.ps1

Сurrently, we install the latest 3 versions of GHC on Ubuntu images. We need to change installation policy and install only two versions due to lack of free space.

[Ubuntu] Install the latest two versions of GHC

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Package management environmental variables should be at the end of the section, not at the beginning as it's now.
No newline required in the browsers section.
The current output [can be found here](https://github.com/actions/virtual-environments/pull/2709/commits/35d3142b20038903355f723345c0b64a309e21bc)
https://github.com/actions/virtual-environments-internal/issues/1833

[Ubuntu] Tiny fix for the environmental variables section in the docs

---

images/linux/scripts/installers/cmake.sh

Currently, we install the latest published version instead of the latest  release. To exclude rc versions from the output use a filter `.prerelease==false`
https://github.com/actions/virtual-environments-internal/issues/1834

[Ubuntu] Install the latest version of cmake

---

images/win/scripts/Installers/Install-JavaTools.ps1

Improvement
Since Maven 3.5.0, environment variable M2_HOME is not used/supported anymore:
https://maven.apache.org/docs/3.5.0/release-notes.html#overview-about-the-changes

remove M2_HOME from windows images

---

images/macos/provision/core/nvm.sh
images/macos/tests/Node.Tests.ps1

In scope of this pull request we deprecate some old node versions from nvm and remove nvm node aliases.

[macOS] Remove nvm aliases and old node versions.

---

images/linux/ubuntu1604.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json
images/win/windows2016.json
images/win/windows2019.json

There is an issue in Azure — we can't create any generation VMs except V2 at the moment.
https://github.com/actions/virtual-environments-internal/issues/1845

[Windows, Ubuntu] Temporarily switch VM size to V2

---

images/linux/scripts/installers/cmake.sh

This change fixes to install cmake.
https://github.com/actions/virtual-environments/pull/2714 has added an install script for [Kitware/CMake](https://github.com/Kitware/CMake).
But this script failed in installing process.
Because Kitware/CMake changed the name of assets after 3.20.0-rc that is the latest release (not pre-release).
e.g) `cmake-3.19.5-Linux-x86_64.sh` to `cmake-3.20.0-rc1-linux-x86_64.sh`
So, this Pull Request changes the pattern of assets. 
- not applicable
- not applicable

[Ubuntu] Updating release file pattern for Kitware/CMake

---

images/linux/scripts/installers/containers.sh
images/linux/scripts/tests/PowerShellModules.Tests.ps1

After installing `dbus-user-session` package on Ubuntu 18.04 ,` Import-Module Az.Accounts` has returned `** Message: 17:43:58.624: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service` files which has broken our CI due to writing to the stderr.
https://github.com/actions/virtual-environments-internal/issues/1831

[Ubuntu] Do not import Az.Account module on Ubuntu 18.04

---

images.CI/macos/azure-pipelines/macos1013.yml

Turning off macOS 10.13 scheduled build because we stop deploying it on regular basis, only per request.
HS is out of support for a lot of tools and its update is almost always a bit of pain, so given its usage, we are stopping its regular updates.
- [n\a ] Related issue / work item is attached
- [n\a ] Tests are written (if applicable)
- [n\a ] Changes are tested and related VM images are successfully generated

Turn off macOS 10.13 scheduled daily builds

---

images/linux/scripts/tests/Android.Tests.ps1
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json

1. There is a new Android platform called **S** that breaks our test script since we rely on numbers only:
`System.Management.Automation.PSInvalidCastException: Cannot convert value "S" to type "System.Int32"`
Also, we don't install the RC version of build tools, yet we didn't make an exclusion in tests for that case either.
2. Cmake 3.6 is not available through SDK manager anymore, we need to switch to 3.10
https://github.com/actions/virtual-environments-internal/issues/1858

[Ubuntu] Fix Android tests to work with platform version S and remove Cmake 3.6

---

images/macos/provision/core/android-toolsets.sh
images/macos/provision/core/dotnet.sh
images/macos/tests/Android.Tests.ps1
images/macos/toolsets/toolset-10.13.json
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

1. There is a new Android platform called **S** that breaks our test script since we rely on numbers only:
`System.Management.Automation.PSInvalidCastException: Cannot convert value "S" to type "System.Int32"`
Also, we don't install the RC version of build tools, yet we didn't make an exclusion in tests for that case either.
2. Cmake 3.6 is not available through SDK manager anymore, we need to switch to 3.10
https://github.com/actions/virtual-environments-internal/issues/1858

[macOS] Fix Android tests to work with platform version S and remove Cmake 3.6

---

images/win/scripts/Installers/Update-AndroidSDK.ps1
images/win/scripts/Tests/Android.Tests.ps1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

There is a new Android platform called S that breaks our test script since we rely on numbers only:
`System.Management.Automation.PSInvalidCastException: Cannot convert value "S" to type "System.Int32"`
https://github.com/actions/virtual-environments-internal/issues/1858

[Windows] Fix Android tests to work with platform version S and remove Cmake 3.6

---

images/win/scripts/Installers/Install-PyPy.ps1

Currently, our images contains hack - symlink for PyPy on Windows: https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-PyPy.ps1#L77
Some time ago we have modified actions/setup-python and UsePython and we don't need this hack anymore. It can be safety removed from images

Remove PyPy symlink workaround from Windows images

---

images/linux/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1

PyPy based on python 3.7.9 is still in beta state so the version output is `PyPy 7.3.3-beta0`, which is currently not acceptable by regex pattern and thus we've got the wrong version in the docs.
https://github.com/actions/virtual-environments-internal/issues/1859

[Ubuntu] Fix PyPy version pattern to pick up beta versions

---

images.CI/macos/select-datastore.ps1

It seems that currently, select-datastore script doesn't work properly because sometimes 2 simultaneous builds run on the same host even though all the other hosts are free. We changed the logic a bit to follow "last in first out" approach, it should help us in this case.
https://github.com/actions/virtual-environments-internal/issues/1864

[macOS] Improve select-datastore script

---

images/linux/scripts/installers/Configure-Toolset.ps1

Improvement
The GOROOT environment variable is mostly deprecated, and no setup requires it. 
The problem with hardcoding a GOROOT is that if any other go tool is in use (for example, because one compiled Go tip), the environment variable will override its autodetected GOROOT.

Remove GOROOT on linux images

---

images/win/scripts/Installers/Configure-Toolset.ps1

Improvement
The GOROOT environment variable is mostly deprecated, and no setup requires it.
The problem with hardcoding a GOROOT is that if any other go tool is in use (for example, because one compiled Go tip), the environment variable will override its autodetected GOROOT.

Remove GOROOT on Windows images

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json

We are going to deprecate old Android SDK Platforms and Build-tools due to a lack of free space on Ubuntu images.
Build tools version 23.0.0 marked as obsolete so the first available version will be 23.0.1
https://github.com/actions/virtual-environments/issues/2673

[Ubuntu] Remove Android SDK Platforms and Build-tools that are less than version 23

---

images/win/scripts/Installers/Configure-GDIProcessHandleQuota.ps1
images/win/scripts/Tests/WindowsFeatures.Tests.ps1
images/win/windows2016.json
images/win/windows2019.json

Increase `GDIProcessHandleQuota` value to 20000:
```
PS > testlimit64.exe -g
Testlimit v5.24 - test Windows limits
Copyright (C) 2012-2015 Mark Russinovich
Sysinternals - www.sysinternals.com
Process ID: 6648
Creating GDI objects...
Created 20000 GDI objects totalling 19 KB. Lasterror: 0
PS C> & "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\ResGen.exe" icons.resx icons.resources
Read in 4001 resources from "icons.resx"
Writing resource file...  Done.
```
https://github.com/actions/virtual-environments/issues/2740

[Windows] Increase GDIProcessHandleQuota value to 20000

---

images/macos/provision/configuration/environment/bashrc
images/macos/provision/core/commonutils.sh
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

Go 1.16 contains a lot of breaking changes, we should avoid setting it as the default one at least for a few next weeks.
it also turned out that we don't need to export `/usr/local/go/bin` directory as brew's go installed by another path.
https://github.com/actions/virtual-environments-internal/issues/1882

[macOS] Stick to go 1.15

---

images/macos/provision/core/commonutils.sh

Brew formula for the latest go adds all the binaries from Go's bin directory (go and gofmt), we need to do the same for 1.15
https://github.com/actions/virtual-environments-internal/issues/1882

[macOS] Add all Go symlinks for version 1.15

---

images/win/scripts/Installers/Update-DockerImages.ps1

The issue is resolved from the MCR side, we can get rid of the workaround.

Revert "[Windows] Add workaround to download docker images from another endpoint"

---

images/linux/scripts/installers/configure-environment.sh
images/linux/scripts/installers/dotnetcore-sdk.sh
images/linux/scripts/installers/nvm.sh
images/linux/scripts/installers/php.sh
images/linux/scripts/installers/python.sh

We have different OS users for AzDO and GitHub actions (vsts and runner) thus we should have different PATH and env variables, which contain `$HOME` directory. Variable expansion does not work in `/etc/environment` so we need another solution. This solution is creating a file in `/etc/profile.d/` that contains all user-related vars and PATH. To source the file in non-interactive sessions (this is our case) `BASH_ENV` variable should be defined as well.
https://github.com/actions/virtual-environments-internal/issues/1883

[Ubuntu] Add a file with global user-related variables and point BASH_ENV variable to it

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/tests/Apt.Tests.ps1
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Install net-tools on Ubuntu 20.04
https://github.com/actions/virtual-environments/issues/2837

[Ubuntu] Add net-tools

---

images/linux/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1
images/linux/scripts/helpers/SoftwareReport.Helpers.psm1
images/linux/scripts/installers/Configure-Toolset.ps1
images/linux/scripts/installers/Install-Toolset.ps1
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json

We are going to deprecate Boost due to lack of free space on images, maintenance concerns and low popularity.
https://github.com/actions/virtual-environments/issues/2667

[Ubuntu] Remove boost from the images

---

images/win/scripts/Installers/Configure-Toolset.ps1
images/win/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1
images/win/scripts/SoftwareReport/SoftwareReport.Helpers.psm1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

We are going to deprecate Boost due to lack of free space on images, maintenance concerns and low popularity.
https://github.com/actions/virtual-environments/issues/2667

[Windows] Remove boost from the images

---

images/win/scripts/Installers/Initialize-VM.ps1
images/win/scripts/Installers/Install-Haskell.ps1
images/win/scripts/Tests/Haskell.Tests.ps1

Starting from version 9 Haskell installation directory is `$env:ChocolateyToolsLocation` instead of `$env:ChocolateyInstall\lib`. By default `$env:ChocolateyToolsLocation` is not initialized and any choco script using it fall back to the `C:\Tools` directory, however, we can explicitly set this variable to the same`C:\Tools` path by calling the `Get-ToolsLocation` function: https://github.com/chocolatey/choco/blob/b6f49599536f77a204a1009d31185218fc8aee7c/src/chocolatey.resources/helpers/functions/Get-ToolsLocation.ps1#L87
This enables us to use the variable in all further build steps.
https://github.com/actions/virtual-environments-internal/issues/1904

[Windows] Fix haskell tests for version 9

---

images/linux/toolsets/toolset-2004.json

related to #2819
I don't know how to build the image locally to check the correctness. But using fresh new ubuntu-20.04 with these packages are enough for my project to be built with clang-11.

[Ubuntu] add clang-11

---

images/macos/provision/configuration/max-files.sh

Issue: `Error: ENFILE: file table overflow, open`
Changes:  Increase kern.maxfilesperproc to 65536
https://github.com/actions/virtual-environments/issues/2842

[macOS] Increase kern.maxfilesperproc to 65536

---

images/linux/scripts/installers/configure-environment.sh

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15
Environment variable | Description
-- | --
ACCEPT_EULA | Set the ACCEPT_EULA variable to any value to confirm your acceptance of the End-User Licensing Agreement. Required setting for the SQL Server image.
https://github.com/actions/virtual-environments/issues/2904

[Ubuntu] Add ACCEPT_EULA=Y env var

---

images/win/scripts/Installers/Install-Zstd.ps1

The new archive of zstd was repacked without parent folder - https://github.com/facebook/zstd/issues/2532
https://github.com/actions/virtual-environments/issues/2858

[Windows] Zstd add support archive with the parent folder

---

images/linux/scripts/installers/validate-disk-space.sh

The GitHub-hosted runners  should have at least 14GB of disk space available: change minimumFreeSpaceMB 16000 -> 15000

[Ubuntu] Change minimumFreeSpaceMB 16000 -> 15000

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Add lerna to Ubuntu 20.04 docs.
https://github.com/actions/virtual-environments-internal/issues/1920

[Ubuntu] Add lerna to Ubuntu 20.04 docs

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

We are reconsidering the space usage policy on Ubuntu images and are going to deprecate these docker images due to a lack of free space.
https://github.com/actions/virtual-environments/issues/2958

[Ubuntu] Remove jekyll/builder and node8-typescript docker images

---

images/macos/provision/core/vsmac.sh

There is a json file available by http://aka.ms/manifest/stable that contains the data about stable VS4mac and xamarin versions. We can use it to get the latest vs4mac version instead of greping brew formula, which is not updated regularly
https://github.com/actions/virtual-environments-internal/issues/1907

[macOS] Get vs4mac version from stable manifest json

---

images/linux/scripts/installers/preimagedata.sh

The variable name is wrong — should be `image_version` instead of `imageVersion`.
Thanks @jsoref for noticing it.
https://github.com/actions/virtual-environments/pull/2783

[Ubuntu] Fix variable name in releaseUrl

---

README.md

The `ubuntu-latest` tag was updated to point to `ubuntu-20.04` when a new runner is spun up. This PR updates the README to reflect that change.
Fixes #2854

Update the ubuntu-latest tag to point to 20.04

---

images/linux/scripts/installers/configure-environment.sh
images/linux/scripts/installers/dotnetcore-sdk.sh
images/linux/scripts/installers/nvm.sh
images/linux/scripts/installers/php.sh
images/linux/scripts/installers/python.sh

It turned out that $BASH_ENV causes some issues since updated PATH is not propagated to other shells like pwsh.
Reverts https://github.com/actions/virtual-environments/pull/2826
https://github.com/actions/virtual-environments/issues/2978

[Ubuntu] Revert $BASH_ENV variable

---

images/linux/scripts/tests/Apt.Tests.ps1
images/linux/toolsets/toolset-2004.json

There is no pre-installed the acl package by default on Ubuntu 20.04 which we use during installation provisioner stage.

[Ubuntu] Add acl package on Ubuntu 20.04

---

images/linux/scripts/installers/ansible.sh
images/linux/scripts/tests/Common.Tests.ps1
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json
images/linux/ubuntu1804.json
images/linux/ubuntu2004.json

- use pipx to install ansible on Ubuntu 18.04/20.04
- remove ppa:ansible/ansible on Ubuntu 18.04
https://github.com/actions/virtual-environments/issues/3001

[Ubuntu] use pipx to install ansible

---

.github/workflows/linter.yml

Improvement
Linter started to fail recently with
```
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
git pull <remote> <branch>
```
The fix is borrowed from https://github.com/github/super-linter/issues/1397#issuecomment-805249812

Fix linter fails

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Change list to table and print package version corresponding to the tool.
This will allow to see which versions of `apt` tools are installed in current image.

feat: Return `apt` packages with their installed versions

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

We are going to deprecate these versions of the listed tools due to the lack of free space on Ubuntu images
https://github.com/actions/virtual-environments/issues/2950#

[Ubuntu] Remove Clang, GCC and Gfortran versions less than 9.x

---

images/linux/scripts/installers/julia.sh

Sometimes the latest release of julia from github is not available to download from `https://julialang-s3.julialang.org` site.  Use official repo `https://julialang-s3.julialang.org/bin/versions.json` json to parse the latest available julia archive.
https://github.com/actions/virtual-environments-internal/issues/1957

[Ubuntu] get julia version from julialang.org

---

images/win/scripts/Installers/Install-AzureCli.ps1

Use a msi package to install the latest Azure Cli release from github source
[Windows] Fix Azure Cli installation #1974

[Windows] use github release for Azure Cli

---

images/win/scripts/Installers/Install-JavaTools.ps1
images/win/scripts/SoftwareReport/SoftwareReport.Java.psm1

It turned out that the java path shouldn't contain the '+' sign, Android builds can't find such paths.
https://github.com/actions/virtual-environments/issues/3014

[Windows] Replace '+' to '-' in java path

---

images/linux/scripts/installers/google-chrome.sh
images/linux/toolsets/toolset-2004.json

Currently, Chrome isn't able to render emojis properly. It's annoying when using browser testing tools taking screenshots of the changes such as [Symfony Panther](https://github.com/symfony/panther) (maintainer here), or [Cypress](https://docs.cypress.io/guides/guides/screenshots-and-videos.html).
Adding the `fonts-noto-color-emoji` font fixes the problem.

fix: emoji support in Chrome on Ubuntu

---

images/linux/scripts/installers/swift.sh

We shouldn't keep wget's downloading progress in a packer log and use the download_with_retries helper function .
e.g
https://github.visualstudio.com/virtual-environments/_build/results?buildId=103242&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043
lines: 19747 - 11700 = 8047

[Ubuntu] suppress wget's progress bar in swift.sh script

---

images/linux/scripts/installers/nodejs.sh
images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

In scope of this pull request we switch installation of yarn from `apt` to `npm install -g yarn`.

[Ubuntu] Install yarn from npm

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/tests/Tools.Tests.ps1

SoftwareReport collects wrong version for Erlang, it reports Eshell version rather than Erlang itself.
reference: https://stackoverflow.com/questions/9560815/how-to-get-erlangs-release-version-number-from-a-shell
2nd answer
`erl` doesn't have `-v` flag, only `-version`
`erlc` `-v` flag is for verbose output
`rebar3` reports it's version with flag `-v`
Reverting back the erlang test logic to test it via `command -v` as it breaks during packer build.
reference: http://erlang.org/doc/man/erl.html

fix: Report correct Erlang version, fix Erlang tests

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1

Az **PowerShell** modules should be in the PowerShell Tools section of the docs.
n\a

[Ubuntu] Move Az modules to the PowerShell Tools section

---

images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1

Removed tool versions from `tools` section in Ubuntu readme for tools have installed as apt package. Section `Installed apt packages` contains these tool versions.
- 7zip
- zstd
- zip
- unzip
- wget
- swig
- net-tools
- curl
- binutils
- coreutils
- m4
- pass
- yamllint (Ubuntu 16 only)

Remove duplicates from Ubuntu documentation

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json

Previously the package was installed during the ansible tool installation, but we've changed the way for ansible installation and this package does not exist on Ubuntu 18 anymore. 
This PR explicitly adds the package by specifying it in the toolset file for Ubuntu 16 & 18 since the package is for python2, which is not presented on Ubuntu 20 image.
https://github.com/actions/virtual-environments/issues/3069

[Ubuntu] Add python-setuptools package to Ubuntu 16 & 18 toolset files

---

images/linux/scripts/installers/dotnetcore-sdk.sh

We have investigated and found out that installation of .NET is hugest bottleneck in image-generation of  Ubuntu. The Ubuntu `dotnetcore-sdk.sh` installation script takes 1h20m (the total time of image-generation is 3h30m). 
There are two reasons for it:
1. We install a lot of .NET versions: 2.1, 3.1, 5.0 on Ubuntu
2. We run a huge validation after installation that takes the most of the time
On Ubuntu, we run the following code for every version:
```
dotnet new globaljson --sdk-version "$sdk"
dotnet new "$sample"
dotnet restore
dotnet build
```
In scope of the investigation ([Speed up .NET installation process](https://github.com/actions/virtual-environments/discussions/2367)) we decided to remove warmup stage  , since there are no performance benefits at all. 
Platform | Downloading and …

[Ubuntu] Disabled .NET warmup 

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1

We install clang-format along with the clang but don't mention it in the readme.
https://github.com/actions/virtual-environments/issues/3053

[Ubuntu] Add clang-format to the readme

---

images/win/scripts/Installers/Configure-Shell.ps1

Set the default encoding for C:\shells\msys2bash.cmd is ascii.
https://github.com/actions/virtual-environments/issues/3085

[Windows] set ascii encoding - C:\shells\msys2bash.cmd

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1

Packer 1.7.1 has a bug and outputs version to stderr instead of stdout https://github.com/hashicorp/packer/issues/10855
This PR changes `Get-PackerVersion` function to retrieve the version regardless of the output stream. 
https://github.com/actions/virtual-environments-internal/issues/2013

[Ubuntu] Fix packer output for version 1.7.1

---

images/macos/software-report/SoftwareReport.Common.psm1

Packer 1.7.1 has a bug and outputs version to stderr instead of stdout https://github.com/hashicorp/packer/issues/10855
This PR changes `Get-PackerVersion` function to retrieve only the version regex match. 
https://github.com/actions/virtual-environments-internal/issues/2013

[macOS] Fix packer output for version 1.7.1

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

After reworked ansible(https://github.com/actions/virtual-environments/pull/3015) installation we stop pre-install `sshpass` pkg.  We should revert this pkg.
https://github.com/actions/virtual-environments/issues/3102

[Ubuntu] Add sshpass package

---

images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

Packer 1.7.1 has a bug and outputs version to stderr instead of stdout https://github.com/hashicorp/packer/issues/10855
This PR changes the `Get-PackerVersion` function to retrieve the version regardless of the output stream. 
https://github.com/actions/virtual-environments-internal/issues/2013

[Windows] Fix packer output for version 1.7.1

---

help/CreateImageAndAzureResources.md

Improvement
There is no documentation for post-deployment scripts in our repository. Let's add some description for them.
https://github.com/actions/virtual-environments-internal/issues/1975
- [+] Documentation is updated (if applicable)

Update documentation for post-deployment scripts.

---

images/linux/scripts/installers/java-tools.sh

In scope of this pull request we add permission java distributors located in /usr/lib/jvm to be able execute some command without sudo.

[Ubuntu] Change permissions for /usr/lib/jvm

---

images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/software-report/SoftwareReport.Xamarin.psm1

We've improved the documentation for Xamarin by adding the table containing Xamarin bundles and associated symlinks.
[Add information about default Xamarin / Mono to MacOS image documentation #1929](https://github.com/actions/virtual-environments-internal/issues/1929)

[macOS] Rework Xamarin documentation

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/installers/containers.sh

In scope of this PR we are simplifying `podman`, `buildah `and `skopeo` installation on `ubuntu20`. As for `ubuntu16` and `ubuntu18` we have to use current installation approach.

[Ubuntu] Remove apt source for podman, buildah and skopeo

---

images/linux/scripts/installers/pypy.sh

Starting from PyPy 7.3.4 symlinks for python3 and python3 are already included in the package — there is no need to create them.
https://github.com/actions/virtual-environments-internal/issues/2033

[Ubuntu] Don't create symlinks for PyPy 7.3.4

---

images/macos/toolsets/toolset-10.13.json
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

Az modules is updated from 4.8.0 to 5.7.0
https://github.com/actions/virtual-environments/issues/3129

[macOS] Upgrade az powershell module from 4.8.0 to 5.7.0

---

images/macos/provision/core/pypy.sh

Starting from PyPy 7.3.4 symlinks for python3 and python3 are already included in the package — there is no need to create them.
https://github.com/actions/virtual-environments-internal/issues/2033

[macOS] Don't create symlinks for PyPy 7.3.4

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Improvement
Some cached OS images have reached EOL and need to be updates
Required size: 50Mb

Update the cached Docker images

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/installers/git.sh

In scope of this PR we are reworking `git` and `git-lfs` to avoid using apt repo.

[Ubuntu] Rework Git installation to avoid using apt repo

---

images.CI/linux-and-win/azure-pipelines/image-generation.yml
images.CI/linux-and-win/cleanup.ps1

Currently, our cleanup script only deletes the temporary resource group and VM created by the packer, however, it doesn't touch os disk, thus the vhd file remains in the storage account.
https://github.com/actions/virtual-environments-internal/issues/1908

Add cleanup logic for the packer os disk

---

images/win/post-generation/Dotnet.ps1

This PR should mitigate the issue when packages from NuGet.org are not resolved due to the empty user-wide nuget.config.
https://github.com/actions/virtual-environments/issues/3038

[Windows] Remove user-wide dotnet config

---

images/win/scripts/Installers/Install-RootCA.ps1

added retry behaviour to certutil.exe -generateSSTFromWU
Improves the generateSSTFromWU task in Install-RootCA with a retry behaviour. It happend multiple times that Install-RootCA.ps1 exited with the following eror
```
=> vhd: Provisioning with powershell script: C:\virtual-environments\images\win/scripts/Installers/Install-RootCA.ps1
vhd: Certificates without CERT_NOT_BEFORE_FILETIME_PROP_ID property
vhd: Subject: CN=Microsoft Root Certificate Authority, DC=microsoft, DC=com
vhd: Subject: CN=Thawte Timestamping CA, OU=Thawte Certification, O=Thawte, L=Durbanville, S=Western Cape, C=ZA
vhd: Subject: CN=Microsoft Root Authority, OU=Microsoft Corporation, OU=Copyright (c) 1997 Microsoft Corp.
vhd: Subject: CN=Symantec Enterprise Mobile Root for Microsoft, O=Symantec Corporation, C=US
vhd: …
```

Add retry to Install-RootCA.ps1 generateSSTFromWU

---

images/linux/scripts/installers/bazel.sh

Improvement
bazel can be installed from git, it is one of recommend method https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu

Rework bazel installation to avoid using apt repos

---

images/macos/tests/Java.Tests.ps1

Remove Gradle test for init.d plugins because executing Gradle tasks as part of an undefined build is not supported since Gradle 7.0

[macOS] Remove gradle test for init.d plugins

---

images/linux/scripts/tests/Common.Tests.ps1

Currently the output doesn't contain list of pipx packages in the PipxPackages test.
```
azure-arm: Describing PipxPackages
azure-arm:   [+]  63ms (59ms|3ms)
azure-arm:   [+]  172ms (171ms|1ms)
azure-arm:   [+]  324ms (322ms|2ms)
```

[Ubuntu] Fix package name output in Pipx test

---

images/linux/toolsets/toolset-1604.json
images/linux/toolsets/toolset-1804.json
images/linux/toolsets/toolset-2004.json

Node 14 is an LTS version and pretty popular nowadays. It could justify having it cached to speed up a lot of GitHub action run.
https://github.com/actions/virtual-environments/issues/3159

[Ubuntu] Add node14 & node14-alpine docker images

---

images/macos/toolsets/toolset-10.13.json

Go 1.16 contains a lot of breaking changes, we should avoid setting it as the default one. We have previously done it for all macOS versions except HS here https://github.com/actions/virtual-environments/pull/2795
https://github.com/actions/virtual-environments-internal/issues/2046

[macOS] Change go in the HS toolset to 1.15

---

images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/BasicTools.Tests.ps1
images/macos/toolsets/toolset-10.14.json
images/macos/toolsets/toolset-10.15.json
images/macos/toolsets/toolset-11.0.json

SwiftFormat goes above and beyond what you might expect from a code formatter. In addition to adjusting white space it can insert or remove implicit self, remove redundant parentheses, and correct many other deviations from the standard Swift idioms.
https://github.com/actions/virtual-environments/issues/3166

[macOS] Add SwiftFormat for all macOS versions except HS

---

images/macos/provision/configuration/environment/bashrc
images/macos/provision/configuration/finalize-vm.sh

Added VM_ASSETS environment variable to point to the folder with vm_assets scripts, so that we can use this variable in official documentation without exposing `/usr/local/opt/runner/scripts`

[macOS] Create VM_ASSETS environment variable

---

images/linux/scripts/SoftwareReport/SoftwareReport.Tools.psm1
images/linux/scripts/installers/google-cloud-sdk.sh

- Remove packages.cloud.google.com/apt (Google Cloud SDK)
https://github.com/actions/virtual-environments-internal/issues/2073

[Ubuntu] Remove google-cloud-sdk repo

---

images/win/scripts/Installers/Install-PyPy.ps1
images/win/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1
images/win/toolsets/toolset-2016.json
images/win/toolsets/toolset-2019.json

Starting PyPy 7.3.4, the format of versions was changed:
- platform: `win32` -> `win64`
- arch: `x86` -> `x64`
We need to fix it. We will download versions with win64 platform but will continue to install it to the `x86` folder. Otherwise, we will break tasks: UsePython (ADO), setup-python (GA)

Update PyPy to 7.3.4 on Windows (change platform format)

---

images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
images/linux/scripts/tests/Tools.Tests.ps1

We don't provide information about the MSBuild version even though it comes along with Mono.
Sample output:
https://github.com/actions/virtual-environments/issues/3148

[Ubuntu] Add MSBuild to software report

---

images/macos/provision/core/edge.sh

set -o pipefail This setting prevents errors in a pipeline from being masked. If any command in a pipeline fails, that return code will be used as the return code of the whole pipeline. By default, the pipeline's return code is that of the last command - even if it succeeds.
E.g:
```
$ ps -ef | grep [M]icrosoft | awk '{print $2}' | sudo xargs kill -9 || echo "ExitCode: $?"
ExitCode: 1
```
https://github.com/actions/virtual-environments-internal/issues/2077

[macOS] suppress pipefail pgrep exit code

---

images/macos/software-report/SoftwareReport.Common.psm1
images/macos/software-report/SoftwareReport.Generator.ps1
images/macos/tests/Xamarin.Tests.ps1

We don't provide information about the MSBuild version even though it comes along with Mono.
https://github.com/actions/virtual-environments/issues/3148

[macOS] Add MSBuild to software report 

---

images/win/scripts/Installers/Initialize-VM.ps1

`Choco-Install -PackageName vcredist2010` started to fail because the links to vcredist2010 in `chocolateyInstall.ps1` are not valid anymore. We need this package since it provides msvcr100.dll — https://github.com/actions/virtual-environments/pull/1427
This PR adds vcredist2010 installation from the direct links, which were taken from https://www.microsoft.com/en-us/download/details.aspx?id=26999
https://github.com/actions/virtual-environments-internal/issues/2098

[Windows] Install vcredist 2010 using direct links
